### ISSUE TITLE
Omega beta2 next widget issues

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.horizon.2#1003]
### Skin section

Home Widgets

### Current Behavior

Currently theres a folder icon and next to it off the screen, theres a blinking icon. 

### Expected Behavior

A next page icon and no blinking icon

### Steps To Reproduce

scroll to the end of a limited widget and it should show

### Screenshots and Additional Info

![Screen Recording 2023-12-12 at 8](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/43726430/8dfd3b7a-b2df-4232-9d32-cbed600661dd)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
Turn off the Show more Widget in settings, this has been previously spoken about.

**Comment by Liquidrag** [comment]
@adamosborne83 sorry I searched but could not find it before opening a new issue. Thank you so much!

**Comment by adamosborne83** [comment]
No worries, glad ots sorted 😀
