### ISSUE TITLE
Omega beta2 highlight widget issues

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.horizon.2#1004]
### Skin section

Home Widgets

### Current Behavior

The widget highlight is very hard to see in omega

### Expected Behavior

A more solid outline like in Nexus

### Steps To Reproduce

Focus an item in a widget

### Screenshots and Additional Info

![Screen Recording 2023-12-12 at 8](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/43726430/fea3a89c-5db1-4561-9a15-d7a1cd0cc7ba)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by ChocOranger** [comment]
Windows beta 2 with most recent skin works as expected with the highlight ie same as Nexus.

What platform and skin version are you running? Does it happen on a clean install (use a portable install to test)

**Comment by Liquidrag** [comment]
> Windows beta 2 with most recent skin works as expected with the highlight ie same as Nexus.
> 
> What platform and skin version are you running? Does it happen on a clean install (use a portable install to test)

macOS 11 (Big Sur) on beta 2. I migrated from my nexus build. I’ll have to backup and try a fresh install and get back to you. Thanks.

**Comment by Liquidrag** [comment]
Fixed: unchecking "Limited widgets have 'more items' object" did the trick.
