### ISSUE TITLE
ArcticFlix won'tinstall

### ISSUE THREAD

**Issue by Freemz1** [jurialmunkey/skin.arctic.horizon.2#1008]
### Skin section

Other

### Current Behavior

Hi, I'm trying to install Arctic Horizon 2 on Fire TV Cube and I keep getting ArcticFlix wrror, it won't install, can you advise what to do please?

### Expected Behavior

Any link to download it separately?

### Steps To Reproduce

.

### Screenshots and Additional Info

![17054713967291505045340300050245](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/156881924/6bf333d3-e0ea-42af-b967-f31aa14ac9f8)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Nothing to do with me. Sounds like you've installed some crap 3rd party repo that is attempting to override addons. Good luck!

**Comment by Freemz1** [comment]
No repos except yours, it's a fresh install on new device.
