### ISSUE TITLE
[Issue] Landscape Combined - No context menu on episodes

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.horizon.2#101]
In standard views you can bring up the context menu on episodes for the extra info (and to mark an episode as watched if you watched it on another device)

![screenshot00031](https://user-images.githubusercontent.com/25871666/172502220-6ff4b76b-40b6-4017-9694-2afc81402e48.png)

In landscape combined view there seems to be no way to bring up the context menu

![screenshot00032](https://user-images.githubusercontent.com/25871666/172502261-78e199bb-6a95-4dda-94d1-18a1f0a79332.png)

Workaround: click on the season number to enter a regular view, from there you can access context menu for the episode

**Comment by jurialmunkey** [comment]
Same issue was in AH1. Not fixable. 

It's due to a kodi bug with library widget containers that aren't the main view (the seasons are the view but the episodes above are a widget). I believe the bug is fixed in nexus.
