### ISSUE TITLE
[Feature] [Recommendations Dialog] Youtube videos

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/skin.arctic.horizon.2#102]
Hi @jurialmunkey, would you please add a YouTube video section for movie/tv show/actor/album/song/artist, etc., so we can get more related information (alternative trailers for movie/tv show, actor interviews, music videos for album/song/artist, etc.) for an item? It would be better if there is option to turn on/off this option.

**Comment by jurialmunkey** [comment]
Linking #265 for music info.

**Comment by jurialmunkey** [comment]
Added in 0.2.4 for video info

Will be added when for music info when #265 feature is completed
