### ISSUE TITLE
[bug] strange delay when select "play" + splash animation

### ISSUE THREAD

**Issue by georgew21** [jurialmunkey/skin.arctic.horizon.2#105]
*congrats for the awesome skin.

For some reason suddney , when I select to play an item, there is a huge delay _(while before with your skin, it was pretty quick_). 

I see an splash animation [tmdb] for some reason and then there is again delay.

I send the video link to understand the splash animation: https://imgur.com/a/a9CTQb1

Is this bug or some change? Before when selectin play the process was  4-5 seconds and now approximately 20 seconds

**Comment by krzysztofwinnik** [comment]
@georgew21 try changing TMDB helper settings
SETTINGS > EXPERT > LIMiT FAKE RESOLVEDURL METHOD TO DB - check that field

**Comment by jurialmunkey** [comment]
Not a skin issue
