### ISSUE TITLE
[Feature] Restore debug functionality

### ISSUE THREAD

**Issue by RagnarLothbrok-Odin** [jurialmunkey/skin.arctic.horizon.2#106]
On previous skin, Arctic Horizon, for example, you could run the following to get the view IDs
`Skin.ToggleSetting(debuginfo)`

I use AutoWidget, and this view ID was helpful to set custom widget labels.
However, on Arctic Horizon 2, the command brings up the plot of the media selected, and not the ID

Would it be possible to restore the original functionality of this command?

**Comment by rizreflects** [comment]
FYI you can do the same thing in autowidget directly. Go into autowidget settings and you'll find an option to toggle skin debugging.
