### ISSUE TITLE
[Bug] [Fonts] Arabic font baseline issues

### ISSUE THREAD

**Issue by zombiB** [jurialmunkey/skin.arctic.horizon.2#108]
Hello jurial congrats on this amazing skin and thanks for sharing it
Is it possible to add a font compatible with arabic characters?
I tried to add one myself to the skin but i didn't succeed the skin ended up showing only arabic characters and not english ones

**Comment by jurialmunkey** [comment]
Could you try 0.1.26? Specifically using the "NotoRoboto - Arabic" fontset.
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.26

I've merged Noto Arabic Condensed with Roboto Condensed using fontforge. It isn't perfect (there's some baseline upwards shift) but in general it looks very acceptable. However, I'm not an Arabic speaker so I have no idea if it is suitable!

Also note that there's some Kodi rendering issues with RTL and auto sizing buttons, so there will be an issue with Arabic text going over the edge of some buttons. But that happens even when I use Kodi's builtin Arial font so I believe it is a more general Kodi issue with rendering RTL than it is with the font itself that I've made.

**Comment by zombiB** [comment]
thank you for working on it so fast 
the font work great 
1-some characters don't show fully as u mentioned hope we find a solution to it 
![screenshot00000](https://user-images.githubusercontent.com/6505870/173038191-63e4dcc6-e741-436e-ae10-d856d5029fb6.png)

2-I am aware about the RTL problem actually  this issue was fixed on an old skin phenomenal
https://forum.kodi.tv/showthread.php?tid=307361
https://github.com/tomer953/skin.phenomenal
i know this is not a priority but if the fixe is easy hope u consider it 
thxx

**Comment by jurialmunkey** [comment]
For the title font, could you try using Light font under appearance settings and see if that helps?

**Comment by jurialmunkey** [comment]
Please try v0.2.24 as that should fix the baseline font issue for Arabic
