### ISSUE TITLE
[Feature] for OSD Screen

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#109]
Would it be possible to add a setting to disable this window pop up on the OSD screen ,, I'm noticing sometimes the episodes display ![image](https://user-images.githubusercontent.com/49699869/172677793-07803f8d-315f-4b4d-a226-ca75556b0ce0.jpeg)but sometimes it's just blank not sure if certain plug-ins need something to make this work all the time but it would be nice to have a disable or enable option

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/172678109-ecd2fa61-c19e-463f-a34c-13c7943d992f.jpeg)

**Comment by jurialmunkey** [comment]
If there is a playlist queued it will display the playlist. Otherwise it tries to grab the episodes from library, then TMDbHelper.

I just forgot to add a condition to hide it if there's no items.
