### ISSUE TITLE
Blank screen when selecting Music Videos

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#112]
When selecting "Music Videos" within the Music Library using Arctic Horizon 2, a blank screen is displayed. When using Arctic Horizon, the music video thumbnails are displayed ok, as in the attached screenshots. Many thanks.

![AH2](https://user-images.githubusercontent.com/67786207/172702826-bd6de6d0-e8c0-4718-a31c-7cccb14e1215.png)

![AH](https://user-images.githubusercontent.com/67786207/172702848-f5d15bd4-b8d8-4a67-a0dd-08a6a9648bfa.png)

**Comment by jurialmunkey** [comment]
Is this via Videos library or Music library? (iirc music videos can be opened in either).

**Comment by berkhornet** [comment]
Hi there. This was via the Music Library. I can run a test via the Video Library in a couple of hours. Thanks.

Mick
________________________________

**Comment by berkhornet** [comment]
@jurialmunkey  - your commit fixed the issue. Many thanks.
