### ISSUE TITLE
Can access dependencies

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#113]
When you try to click on dependencies it flashes for a quick second and then it goes to add on browsers Is this by default if not it would be great if we can be able to access our dependencies

**Comment by dm2912** [comment]
can confirm.

Settings > system > addons > Manage dependencies is borked and just goes to add on browser.

**Comment by xyzfre** [comment]
Sorry for commenting back on this close issue but I Notice yesterday The same thing was happening with the feature running add-ons ,flashes for one second and then it takes you to the add-on browser ,really appreciate all the hard work that's going into AH2 so far it is an AMAZING skin
