### ISSUE TITLE
[Bug] [Mouse] Mouse usage issues

### ISSUE THREAD

**Issue by jsmdy** [jurialmunkey/skin.arctic.horizon.2#116]
I noticed some mouse usage troubles (it's certainly secondary now but?):
-can't select the search area in top menu
-can't reach the management of extension, once the mouse move the window disappear, setting icon and "manage" button
-during a research, the setting menu don't react

Something not working with all selections technic:s
-no hover on settings icon top right
-we can't re-selecting the settings icon in the settings menu (to go to extensions for example)

This seems to be the ultimate skin of Kodi :)

**Comment by jurialmunkey** [comment]
Mouse and touch are not currently supported. They might work in some places but the skin is primarily designed for remotes.

**Comment by jsmdy** [comment]
I was supposing it ;), but as it is almost fully working with mouse cursor I was not sure, so just pay attention on this two lines:
-no hover on settings icon top right
-re-selecting the settings icon in the settings menu (to go to extensions for example)
