### ISSUE TITLE
[BUG] [Player Process Dialog] Keyboard Command "O" not working

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#117]
The Kodi keyboard command "O" for Player Process info does not display anything. Alt-O and Ctrl-Shift-O do work ok. Many thanks.

**Comment by berkhornet** [comment]
Hi

Thanks for your response.

I think the issue is that Arctic Horizon 2 isn’t responding to the “O” keyboard command. The mapping in Kodi must be ok because this command works fine with Arctic Horizon and other skins.

Mick
________________________________

**Comment by berkhornet** [comment]
@jurialmunkey - many thanks for response. I will close the issue

**Comment by jurialmunkey** [comment]
I think leave it open because it is a missing feature. I still need to add it and it will be a good reminder! 

Plus less likely other people will re-report it if there is already an existing issue.
