### ISSUE TITLE
[Feature] [Viewtype Select] Preview images for viewtypes

### ISSUE THREAD

**Issue by francis-robert** [jurialmunkey/skin.arctic.horizon.2#118]
Could we get previews of the view types/layouts before selecting them? These could be static images with fixed content, for example purposes.

A great example of this is from the Titan Bingie skin

![image](https://user-images.githubusercontent.com/87673558/172913978-2d5d2b27-cb68-4722-8954-08a8d3464bf1.png)

This would be really helpful when setting up widgets and customizing the skin!

Thanks

**Comment by jurialmunkey** [comment]
Yes, this is definitely planned. Just haven't quite got to generating a suitable set of screenshots yet.
