### ISSUE TITLE
[Issue] Trailers requesting install of addon "tubed"

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.horizon.2#120]
I don't know if this is a skin issue (or a something up with my setup system), but since the latest update whenever i try to watch a trailer via widgets etc its trying to make me install "tubed"

TMDB helper is working as normal using the youtube addon which i already have installed. 

I'm a bit confused though, just did a grep on AH2's code and "tubed" isnt mentioned anywhere so i dont know why its requiring this?.

![screenshot00034](https://user-images.githubusercontent.com/25871666/172933527-5cba1457-fedb-4d88-8c32-336752c58dee.png)

**Comment by dm2912** [comment]
fwiw, it went ahead and installed "tubed" and logged into my youtube account

And it just throws out constant errors in the log when trying to do something

```
2022-06-09 21:07:02.419 T:4064    ERROR <general>: [plugin.video.tubed][api][decorators] API request failed:
                                                     {'error': {'code': 403, 'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'errors': [{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]}}
```

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/172951796-069f989d-de51-446e-8173-621a65ff785b.MOV

**Comment by dm2912** [comment]
Well this is very very strange.

From TMDB helper its using youtube app with no issues.

But anything from library widgets in AH2 is insisting I install Tubed

Ok.. 

I completely uninstalled Youtube. Then reinstalled Youtube again from Kodi repo. And now AH2 is using proper youtube app.

I cannot fathom why it was telling me to install that add on. Maybe because my youtube was installed from its repo and not kodi repo?

Weird. But solved..

**Comment by dm2912** [comment]
Nope, after reboot, its asking me to download tubed again

**Comment by jurialmunkey** [comment]
Yeah I can confirm. I saw this the other day - seems to be only tvshows in library as far as I can tell. 

I think it might be a tvshow scraper issue as the skin definitely doesnt have any reference to the tubed plugin.

**Comment by dm2912** [comment]
yeh, i cant work it out. 

neither scraper, be it the old xml tmdb one, or the new python scraper have any mention of tubed anywhere in their coding. 

bizarre.
