### ISSUE TITLE
Hide top lines and then wall view with 3 cover lines? 

### ISSUE THREAD

**Issue by Hallo951** [jurialmunkey/skin.arctic.horizon.2#122]
Hello,

Is it possible to include an option in the video view with which the top lines (heading, date,...) can be completely hidden, so that 3 cover lines can be displayed in the wall view instead of 2 cover lines?

Another question about the trailers. Is there a possibility to start the trailers automatically after a defined time in a small window (for example in the upper right corner) which overlays the normal view?

**Comment by jurialmunkey** [comment]
No sorry. The skin has strict design guides, one of which is side padding rules and always visible top bar.

The problem with auto playing trailers is that when you finish watching a video Kodi will refresh all containers so it will cause your widgets to reload - I had tried it previously but the reloading was really annoying. Basically - maybe a possibility for library but definitely not for home.
