### ISSUE TITLE
subtitles not downloading

### ISSUE THREAD

**Issue by timiman1996** [jurialmunkey/skin.arctic.horizon.2#13]
download subtitles button. It pauses the movie for second, nothing happens and movie continues.

**Comment by dm2912** [comment]
Works OK for me using sources from Netflix addon  (where subs are hard coded into the source)

Works OK for me using sources from "other" online media (where subs are hard coded into the source)

Not yet tried from a source that doesnt have subs hard coded

(the subtitles intregration/selection is stunning)

**Comment by timiman1996** [comment]
this is doesn't works for me

(Not yet tried from a source that doesnt have subs hard coded)

**Comment by dm2912** [comment]
What addon are you using for subs?

**Comment by timiman1996** [comment]
opensubtitles and a4ksubtitles

**Comment by jurialmunkey** [comment]
Yeah I forgot about the download subs dialog so it doesn't exist at the moment! I'm so used to having hardcoded (eg Netflix) or local subs (eg library) that I forgot that there was a download subs dialog. 

I should have this fixed soon!

**Comment by jurialmunkey** [comment]
Fixed in 0.1.1
