### ISSUE TITLE
Home Screen overlay not fully covering widgets

### ISSUE THREAD

**Issue by Mycale11** [jurialmunkey/skin.arctic.horizon.2#130]
There is a bright band on the top and bottom of my tv when scrolling through widgets. Seems like the dimming overlay doesn’t stretch far enough. 

![7C4C01D8-9E63-42B6-B011-B07D7CC21805](https://user-images.githubusercontent.com/107252205/173049220-b1898934-7517-4a02-aa08-e50bebeca7cf.jpeg)

I had the same issue in an earlier version, but when I changed the resolution in kodi (just flipped back and forth through them), that fixed the issue until the add on was updated again. I also don’t like to use overscan on the tv, so I’m wondering can you stretch out the overlay? 

Thanks!

**Comment by Mycale11** [comment]
Update: it seems to only happen when the refresh rate in kodi is changed from 59.94 to 60. 
No trouble to set it to 59.94, but then my tv changes back to 60 and flickers when I exit kodi. Not sure if it’s a skin issue or just my tv. 
Thanks!

**Comment by jurialmunkey** [comment]
It looks like screen calibration for that refresh rate has slight underscan. The overlay is aligned to 0,0 pixel coordinators so it isn't the skin.

You can correct over/underscan in screen calibration (you'll need v0.1.32 or higher)
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.32
`Settings > System > Display > Video calibration ...`

Check that both corners have 0,0 coordinates. If they don't, you are probably adjusting for an overscan setting on your tv. When I very first set up my TV with Kodi, I had to find a setting on my TV to disable overscan and then set my screen calibration in Kodi to 0,0 coordinators for the corners.
