### ISSUE TITLE
[BUG] Download subtitles with KORE remote control not working

### ISSUE THREAD

**Issue by vermope** [jurialmunkey/skin.arctic.horizon.2#131]
Hi, 

Love the skin, certainly the revamped addon section is a bliss now! 
One little annoyance I've noticed is working with the KORE Android remote control, when no subtitles are available, the menu item "download subtitle" does not open the subtitle download menu.

**Comment by jurialmunkey** [comment]
What version of the skin are you using? I'm pretty sure I already fixed the subtitles dialog.
