### ISSUE TITLE
[BUG] [Info Dialog] Original language in some addon lists unlikely AH1

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/skin.arctic.horizon.2#134]
Though tmdbhelper and all information providers are set to Russian, titles of Tvshows in widgets are in English. Though plots and artwork are displayed in Russian as supposed to.
Movie widgets are ok, titles and plots are in system locale.
The issue is skin-related, as other skins (incl. AH1) with the same settings display tvshow widgets language correctly.
![upload_2022_06_10_21_10_43_829](https://user-images.githubusercontent.com/85682547/173125838-274e536c-9c8c-40c3-af60-03e2d85141ad.jpg)
![upload_2022_06_10_21_11_21_973](https://user-images.githubusercontent.com/85682547/173125900-9b8dc073-5251-496c-a224-49b86d9c51e7.jpg)

**Comment by jurialmunkey** [comment]
Are you sure your TMDbHelper settings are set to Russian? 

The skin doesn't control the language of a trailer. It is whatever the add-on provides.

**Comment by patkino** [comment]
Of course I'm sure. 2 screenshots illustrate the bug. All the same settings, but the ski  is switched from ah2 to ah1

**Comment by jurialmunkey** [comment]
Do you have an example of a movie or show where playing the trailer in AH1 is in Russian but playing the trailer in AH2 is not?

**Comment by patkino** [comment]
Well, my bad. It's the addon, who messes things up (elementum - trakt trending). Tmdbhelper is ok.
Still it doesn't happen in AH1..🤷‍♂️
Anyway I'm closing the issue. 
Sorry for inconvenience

**Comment by patkino** [comment]
Still some addon lists (e.g. Elementum-tvshows-trakt trending), which were in system language in AH1, are displayed by AH2 in English. 
It's not a "classical" issue of the skin or a bug, but unwanted skin behavior, which might be solved due to AH1 correct lists processing

**Comment by patkino** [comment]
So finally as far as managed to discover, the skin takes titles in video info dialog somewhere else than AH1. That's the possible reason why AH1 displays the title from tmdbhelper (tmdb database), though AH2 displays titles from an addon
