### ISSUE TITLE
[Bug?]Widget list title and CLEARART

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.arctic.horizon.2#137]
I have only seen this a few times and doesn't really bother me but will report to try and help if you need to fix. 

![image](https://user-images.githubusercontent.com/63697905/173176535-e19e9c0b-0b23-4750-b18c-606eb834106d.jpeg)

**Comment by jurialmunkey** [comment]
Could you try 0.1.31? I think it should fix it
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.31

**Comment by derrgoo** [comment]
Much better👍
