### ISSUE TITLE
[BUG] There is no exit button from the series Only in movies

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#140]
There is no exit button from the series
Only in movies

**Comment by jurialmunkey** [comment]
What is an "exit" button? I don't know what this means.

**Comment by koby455** [comment]
![image](https://user-images.githubusercontent.com/102416233/173182476-5a5ffa4b-44bf-4c33-ad71-d93e9f77cb29.png)
If I'm not interested in watching the series
I do not have a button to exit the home screen

**Comment by jurialmunkey** [comment]
There's and option in skin setting to always show the stop button.
