### ISSUE TITLE
[BUG] Once there is no poster, do not list the name of the movie on the side

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#141]
Once there is no poster, do not list the name of the movie on the side

**Comment by jurialmunkey** [comment]
Sorry I don't know what you mean. Screenshots would help.

**Comment by koby455** [comment]
![image](https://user-images.githubusercontent.com/102416233/173182396-798b040a-7791-44ab-9bf1-838d6a3665ba.png)
If there is no poster
I can not know what it is

**Comment by jurialmunkey** [comment]
You'll have to use a different widget style then. Landscape and square both show text.

**Comment by koby455** [comment]
> You'll have to use a different widget style then. Landscape and square both show text.

in skin arctic horizon 1 the text was there in all styles
