### ISSUE TITLE
[BUG] To get to the "Install from Zip" screen

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#142]
To get to the "Install from Zip" screen
Need to double click search and exit
It does not appear without it
![image](https://user-images.githubusercontent.com/102416233/173182764-d474bce6-501d-43aa-b6bb-7d839f37ba2e.png)

**Comment by derrgoo** [comment]
Install from zip keep clicking to right a window opens.

**Comment by koby455** [comment]
> My add-ons - click right until window opens.
yes its works on right click .. its need to be upside

**Comment by jurialmunkey** [comment]
Or you can press left from the left side. Or you can press m on keyboard.
