### ISSUE TITLE
[Feature] [Subtitles] Adding subtitle background button

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#143]
Adding the subtitle background darkening button
There are movies that have subtitles built in
I would love to have a button that allows you to make a black background, while playing other subtitles

**Comment by jurialmunkey** [comment]
I don't know what this is? Is it in Estuary?

**Comment by koby455** [comment]
> I don't know what this is? Is it in Estuary?

There's it in Estuary but only in settings
From version 19 it exists, and you can add a button in the player itself
In case someone wants to blacken the background


![image](https://user-images.githubusercontent.com/102416233/173189926-16a7ae02-b0b4-4761-bc7b-15449e9bc35b.png)

**Comment by jurialmunkey** [comment]
No builtin function to change this setting. Not possible.
https://kodi.wiki/view/List_of_built-in_functions
