### ISSUE TITLE
[Bug] [Music OSD] Playlist button not working

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#145]
In the Music OSD, clicking the playlist button displays a blank screen. Thanks

**Comment by Blackysbd** [comment]
Had same issue when I first played a file, then tried again and a vertical menu appeared.

**Comment by dm2912** [comment]
music osd / playlists still on the todo list

https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/14
