### ISSUE TITLE
[Feature] [Fonts] Thai language

### ISSUE THREAD

**Issue by showkubii** [jurialmunkey/skin.arctic.horizon.2#148]
Because skin doesn't support Thai language.

https://github.com/jurialmunkey/skin.arctic.horizon.2/pull/149

RSU-Bold.ttf
RSU-Light.ttf
RSU-Regular.ttf

You can add fonts rusfont.
https://www2.rsu.ac.th/files/rsufont.zip

**Comment by jurialmunkey** [comment]
Thanks but the skin uses Roboto family fonts. Only fonts with the Roboto style will be accepted.

**Comment by showkubii** [comment]
> Roboto family fonts

doesn't support Thai language.
