### ISSUE TITLE
[Feature] [EPG] Long press up/down should scroll up/down and stop on first/last channel 

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#151]
**Is your feature request related to a problem? Please describe.**
When I long press up or down in EPG view channel list is scrolling infinitely. Because of this it is difficult to easily scroll to the top of the list.

**Describe the solution you'd like**
Long press up/down should scroll up/down **and stop on first/last channel**. Same way as it is designed for OSD Channnel List or Channels view.

**Describe alternatives you've considered**
Surely I can always press channel number or move to the top of the list via context menu (navigation -> top).
However long press solution seems to be far better and consistent with other views.

**Additional context**
n/a

**Comment by jurialmunkey** [comment]
Unfortunately the skin doesn't have any control over this behaviour. The only way to stop it would be to prevent the loop entirely which I suspect would be worse for usability if you couldnt move from top to bottom.

**Comment by krzysztofwinnik** [comment]
I see. Let's leave it the way it is then.
