### ISSUE TITLE
[Feature] [Skin Section] subtitle settings

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon.2#154]
will subtitle settings. be implemented soon. currently, I have to change skin(AH) to download subtitles, or am I missing something?

AH2 
<img width="1438" alt="Screenshot 2022-06-12 at 18 06 23" src="https://user-images.githubusercontent.com/2873112/173245054-2ac364ee-ed78-44f1-87da-fe87b127924c.png">

AH
<img width="1438" alt="Screenshot 2022-06-12 at 17 59 09" src="https://user-images.githubusercontent.com/2873112/173245063-09dc9e07-a09b-4ab4-85cb-d130f3b4a90c.png">

Thanks

**Comment by drinfernoo** [comment]
The button to the left, with the "speech balloon" icon, is for Subtitle Settings.

**Comment by Blurayx** [comment]
> The button to the left, with the "speech balloon" icon, is for Subtitle Settings.

Ah, I didn't realise I had to press the"speech balloon" twice for the settings.

Thanks
