### ISSUE TITLE
[BUG] [Skin Section] Short Description Resume progress points no longer show percentage

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#157]
Just try the latest version of AH2 0.1.35 TMDB H 4.8.11 and on the resume progress points the percentage doesn't show up anymore but on the previous version they did not sure if it's an issue or a change just wanted to keep you posted thank you

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/173261003-f955f173-7732-4cac-a050-fc2130c05555.jpeg) previous version resume point has percentage

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/173261088-85cc5bd1-28bd-49fd-aa43-ff4ea374d881.jpeg) V 0.1.35

**Comment by derrgoo** [comment]
I think it turned them into just the clock icon to see progress.

**Comment by jurialmunkey** [comment]
I can't reproduce. It is working fine for me.

![Honeyview_screenshot00113](https://user-images.githubusercontent.com/4618719/173272964-a3c292db-6224-4e37-bad4-8605452a0c53.jpg)

**Comment by xyzfre** [comment]
Just install TMDB H ,V4.8.12 and now it is fixed but for some reason on .11 it didn't ,,thank you working perfect now ,so far Skin is AMAZING great work

**Comment by derrgoo** [comment]
Yea same here. After updating skin working 👍

**Comment by jurialmunkey** [comment]
> Just installed TMDB H ,V4.8.12 and now it is fixed but for some reason on .11 it didn't ,,thank you working perfect now ,so far Skin is AMAZING great work

Interesting. Can you have a look in In-Progress **Shows** in TMDbH and check you get progress indicator there?

![Honeyview_screenshot00115](https://user-images.githubusercontent.com/4618719/173276397-d30782e6-3df5-4989-abad-7925ab86d57c.jpg)

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/173276952-8da87928-aeb5-44ba-8d70-7d1f773cd25e.jpeg)

**Comment by xyzfre** [comment]
I didn't even know about these I barely go into my in progress TV Shows I'm always checking my in progress episodes lol, WOO these look GREAT ,Good work @jurialmunkey ✊🏼

**Comment by derrgoo** [comment]
Mine worked too. 

On this subject if I am on Your In Progress Episodes and it is half watched I should be able to click on context menu and 'reset resume position'. Should this reset to none watched? If so, doesn't seem to reset for me or there may be a big delay when that happens.

**Comment by jurialmunkey** [comment]
> I didn't even know about these I barely go into my in progress TV Shows I'm always checking my in progress episodes lol, WOO these look GREAT ,Good work @jurialmunkey ✊🏼

Excellent. I'm setting a custom property with that value to display in the skin. Only thing I changed between 4.8.11 and .12 in TMDbH was that I removed the custom property for movies/episodes because it was stopping the skin from getting the "true" resume value stored in Kodi. 

Since that solved the issue for you, I was worried that the property wasn't working at all even for tvshows - but clearly it is, so that's excellent! No idea why it caused an issue for movies/episodes but better it isn't added to those anyway.


> Mine worked too.
> 
> On this subject if I am on Your In Progress Episodes and it is half watched I should be able to click on context menu and 'reset resume position'. Should this reset to none watched? If so, doesn't seem to reset for me or there may be a big delay when that happens.

Not if you enable the setting to update resume points from Trakt.

That context menu item only resets the resume point from Kodi, so it effectively does nothing with that setting. What actually happens is that when you reset the Kodi resume point it causes the TMDbH container to refresh and so TMDbH sets Kodi's resume point back to match Trakt as per your settings.

Can't currently override these context menu items - it's the same issue with the Mark as Watched. I think there's options coming in Nexus to give plugins more control over which default context options display so these type of things which essentially do nothing can be disabled.

**Comment by derrgoo** [comment]
Okay that makes sense. Cool was just wondering for a few days 😂 

The other question is is there a time set when to add the progress icon. Sometimes I notice mine the next day. Not as soon as I push stop?

**Comment by derrgoo** [comment]
> Just installed TMDB H ,V4.8.12 and now it is fixed but for some reason on .11 it didn't ,,thank you working perfect now ,so far Skin is AMAZING great work 

I only see v4.8.11. Where is .12?

**Comment by jurialmunkey** [comment]
> Okay that makes sense. Cool was just wondering for a few days 😂
> 
> The other question is is there a time set when to add the progress icon. Sometimes I notice mine the next day. Not as soon as I push stop?

TMDbH will sync the data when the container loads if Trakt says that there's new data available. 

However, it really depends on whatever is scrobbling resume data to Trakt as TMDBH doesn't do that. If the addon doing the scrobbling doesn't sync with Trakt before the container reloads then obviously the data will be old but it should update on the next container reload.

**Comment by derrgoo** [comment]
I know your busy with so many things so it is not a big deal really. On my MacBook both your next episodes and your progress tv shows work and show progress indicators. 

My shield pro 2019 only will show your in progress tv shows. I have tested by playing and stopping still don't show. The other guy mentioned TMDB v4.8.12. I only see .11 in your git. 😅

**Comment by derrgoo** [comment]
> 4.8.12 you have to manually install the zip from GH,, till he updates to the repo if you want to try it
> 

I always goto git but what I see is 

![image](https://user-images.githubusercontent.com/63697905/173341228-26329fe9-4155-4e7b-8aa6-ee8646334c35.jpeg)

**Comment by xyzfre** [comment]
If you click on Commit you'll see it's .12 he probably hasn't had a chance to adjusted he's been like a machine Jurial super busy

**Comment by derrgoo** [comment]
> If you click on Commit you'll see it's .12 he probably hasn't had a chance to adjusted he's been like a machine Jurial super busy 

Okay slowly learning this lol. I found this pic but not sure how to pull the file?

![image](https://user-images.githubusercontent.com/63697905/173346085-51b9c794-c201-42f8-a8c4-26a7e51024db.jpeg)
