### ISSUE TITLE
[BUG] Watched status for YouTube addon widget

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/skin.arctic.horizon.2#159]
I added several YouTube addon widgets, but the Watched statuses of the items in these widgets are not marked. Is this expected behavior, or a bug?

**Comment by jurialmunkey** [comment]
Does it work in other skins?

**Comment by Hawkedon** [comment]
Hi @jurialmunkey, seems it doesn't work for other skins either (checked Embuary skin). Is this a Kodi limitation or skinshortcuts limitation? Never noticed this as I basically only use local library for widgets.

**Comment by jurialmunkey** [comment]
Watched status definitely works in widgets for other addons, so I'd say it's an issue with the youtube addon itself rather than kodi.
