### ISSUE TITLE
[BUG] [Movies] Can't Start Movies on Click

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon.2#160]
**Describe the bug**
On most movie items, I'm unable to start them by clicking them. It seems that library content is working fine, as well as add-on widgets, but in a regular add-on view (across multiple add-ons like TMDbHelper, Netflix, Disney+, etc...), I have to open the context menu and choose "Play".

**To Reproduce**
1. Go to any movie list from an add-on
2. Click on any movie
3. Nothing happens

**Expected behavior**
Movies should behave the same way as episodes, and start when clicked.

**Platform Information (please complete the following information):**
 - Platform: Windows 10
 - Skin Version: 0.1.36
 - Kodi Version: Matrix 19.0 😬

**Additional context**
This seems to work fine for episodes in most places, but I have also found a few that don't want to work out 🤔

**Comment by drinfernoo** [comment]
I have been testing on PC, so haven't tried with a remote, but neither a mouse click or Enter work for me.

My default action is set to Play.

It doesn't seem to matter which view, except that they *do* work from widgets and with library movies.

**Comment by krzysztofwinnik** [comment]
@drinfernoo I had a simmilar issue with one specific TMDB helper player (Seren) for TMDb helper based widgets.
Just like you described the problem - clicking play wouldn't do anything unless via context menu. 
That's why I decided to switch and replace Seren with one of Fen forks, which solved the problem for me.
I decided to share it with you just to shed some light on your problem and help @jurialmunkey reproduce it with specific players.

**Comment by drinfernoo** [comment]
@jurialmunkey, could it be an issue with what the content type is in the menu? I can also replicate it with TMDbHelper.

**Comment by drinfernoo** [comment]
@jurialmunkey I will need to double check, but it was working fine (in this same install) on Eminence and AH before I installed AH2.

**Comment by jurialmunkey** [comment]
@drinfernoo Did you have a chance to check this on another skin? And more importantly, if commenting out the context button include helps?

**Comment by drinfernoo** [comment]
Sorry I took so long to get back to you. I am able to start movies just fine in all add-ons in AH1, but there are apparently a few that I just can't in AH2.

I tried deleting the line you mentioned above, and there is no change.

**Comment by jurialmunkey** [comment]
I haven't been able to reproduce this issue and I haven't heard anyone else mention it. I really can't see any reason why the skin would prevent playing movies, so I have to put it down as being some unusual combo of settings causing something unexpected rather than it being specifically the skin.
