### ISSUE TITLE
[Feature] [Side Menu] "Add-on Settings" on Side Menu

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon.2#161]
**Is your feature request related to a problem? Please describe.**
Most other skins have the ability to access the current add-on's settings from the side menu within.

**Describe the solution you'd like**
Can we get that too?

**Describe alternatives you've considered**
Back out of add-on, and open them from the context menu.

**Comment by Goldenfreddy0703** [comment]
I would like that as well cause sometimes whenever I change something in an addon, I have to back all the way out till and right click that addon. Would help a ton to access the addon settings from the side menu.
