### ISSUE TITLE
[BUG] [Video Library] Watched Indicator Corrupted

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#162]
**Describe the bug**
When browsing the video library, the watched indicator on TV show episodes is corrupted. The checkmark appears together with a circle. The same happens in Movie Sets etc. This bug did not exist in version 0.1.32 (screenshots of both included)

**To Reproduce**
1. Go to TV shows
2. Click on 'any TV show with watched episodes.'
3. See error

**Expected behavior**
The checkmark image to be displayed

**Screenshots**
AH2 0.1.36

![screenshot00001](https://user-images.githubusercontent.com/67786207/173384055-67f9e32e-ebda-480b-9e48-5ffdfcc1e01b.png)

AH2 0.1.32

![screenshot00000](https://user-images.githubusercontent.com/67786207/173384228-4720f353-6455-4c87-bc43-0c6ae0856450.png)

**Platform Information (please complete the following information):**
 - Platform: [Windows ]
 - Skin Version [e.g. 0.1.36]

**Additional context**

**Comment by jurialmunkey** [comment]
Ah, derp, forgot the visibility condition! Should be fixed in 0.1.37 (will do a release in a sec, just want to add a couple of extra things - but you can get it from main branch).

@berkhornet btw what subs language do you have there? Looks like the flag pack resource is missing it.

**Comment by berkhornet** [comment]
Hi @***@***.***>

Many thanks.

I've checked but there are no subtitles on my system for that show.

Regards

Mick

**Comment by berkhornet** [comment]
@***@***.***>

I've checked the kodi database, There are only NULL entries for the episodes highlighted in the screenshots.

Regards
