### ISSUE TITLE
[Feature] [Series page] Replace the 'search' button with a 'go to series' button on the episode information page

### ISSUE THREAD

**Issue by Weevild** [jurialmunkey/skin.arctic.horizon.2#165]
**Is your feature request related to a problem? Please describe.**
Somewhat of an annoyance to have to search up the series of the episode you've got in front of you, an unnecessary roundabout way so to speak. Sometimes you want to just se how many episodes there are in a specific series/season and the only current way to see that is to play a video and use the OSD or use the search button but that's just another one unnecessary roundabout way with extra clicks.

**Describe the solution you'd like**
A button on the per-episode information page that takes me to the series that the episode I'm displaying belongs to.

**Describe alternatives you've considered**
You could add an extra line in the submenu that appears when long-pressing an episode (alongside the 'information' row) for the 'go to series' function.

**Additional context**
![20220614_024224](https://user-images.githubusercontent.com/89477083/173470877-5a065e4a-77de-4073-ad71-c1185cc600f4.jpg)
Additional/replace button here to...
![20220614_024243](https://user-images.githubusercontent.com/89477083/173470924-36dbcab4-7dcd-4300-a5bb-72b253b12685.jpg)
Take me to here. Alternatively an extra row here:
![20220614_025206](https://user-images.githubusercontent.com/89477083/173470968-66539b6f-6866-469e-8a07-b61c33a03c4d.jpg)

**Comment by derrgoo** [comment]
From your post if I understand you correctly. You want to see how many episodes in a tv series quickly. 

If you pull a TV section from a plug in or Watchlist just pull a widget and see each tv series number of episodes left to watch. See picture. 

![image](https://user-images.githubusercontent.com/63697905/173476498-7ad27376-4390-4f23-85f0-c03dd2fbd02a.jpeg)

**Comment by jurialmunkey** [comment]
> From your post if I understand you correctly. You want to see how many episodes in a tv series quickly.
> 

Nah, that's not it. 

Weevild wants a "Browse Seasons" button from an episode e.g. for a "Your Next Episodes" style widget but you want to browse the show because you actually finished watching that episode. Which definitely makes sense to have as a button in the info dialog but unfortunately I don't think is possible. 

I _might_ be able to do it for library content but definitely not for add-ons because they will all have their own specific seasons paths.

**Comment by Weevild** [comment]
> Weevild wants a "Browse Seasons" button from an episode e.g. for a "Your Next Episodes" style widget but you want to browse the show because you actually finished watching that episode.

Correct.

> I might be able to do it for library content but definitely not for add-ons because they will all have their own specific seasons paths.

Well anything to make it easier for me to navigate to the episode's season would be highly appreciated!
