### ISSUE TITLE
[BUG] [Skin Section] Short Description

### ISSUE THREAD

**Issue by Galicia86** [jurialmunkey/skin.arctic.horizon.2#166]
There is a problem when changing profiles... when I press disconnect it goes to the Master User instead of proposing the available profiles. The same problem with Adroid TV.

https://user-images.githubusercontent.com/104492321/173579552-cb3ef5e9-5a67-47ee-8cc3-18d0c016f559.MOV

https://user-images.githubusercontent.com/104492321/173579559-ebb3a5ed-9240-403f-afd3-5cba7b89ca5d.mov

**Comment by jurialmunkey** [comment]
Sorry I don't really understand what the issue is here. It looks like it is going to the profile selection screen to me?
