### ISSUE TITLE
[BUG] Cast loading

### ISSUE THREAD

**Issue by Talgold3** [jurialmunkey/skin.arctic.horizon.2#167]
**Describe the bug**
When entering the movie/tv show information page, pressing down to the cast information will result in a few seconds loading and then disappearing of the information categories.
*The same method worked great on 

**To Reproduce**
1. Select movie
2. Click on 'more information
3. Scroll down to 'cast

**Expected behavior**

**Screenshots**
![20220614_173908](https://user-images.githubusercontent.com/107051785/173605203-6b7bd6ae-3879-45ff-a871-db574c43c7e7.jpg)
![20220614_173903](https://user-images.githubusercontent.com/107051785/173605229-418eae64-d2b7-402d-be17-9fedb573e0f0.jpg)

And only the "Premiered in" appears:

![20220614_173912](https://user-images.githubusercontent.com/107051785/173605423-0e55e36a-8332-419a-84bf-cd4cd5ef5f06.jpg)

**Platform Information**
 - Platform: Nvidia shield pro
 - Skin Version: v0.1.32

**Comment by jurialmunkey** [comment]
Fairly sure this was fixed a while back. Or at least I can't reproduce it now.
