### ISSUE TITLE
[Feature] disable some widgets (fanart, poster etc) on movie information

### ISSUE THREAD

**Issue by georgew21** [jurialmunkey/skin.arctic.horizon.2#168]
Hello,

When we view the page of a movie we see some widgets with info (cast, crew, similar, reccomendations etc).

COuld it be possible to have the option to disable/enable only some of them? 

For example, I am not interested for fanart section , poster etc sections and I think that it could better to have the option to disable them to run kodi more smooth and quick.

* I use your plugin with the awesom arctic horizon 2.

**Comment by jurialmunkey** [comment]
This is a skin issue. Transferring it to the AH2 repo
