### ISSUE TITLE
Flixart(keyart) and multifanart support

### ISSUE THREAD

**Issue by Whiteripd0** [jurialmunkey/skin.arctic.horizon.2#169]
I wanted to know if you will ever add a new look in the libraries that was shown at the very beginning? That is, the full functionality of presets as you have in the video and in this photo
https://i.imgur.com/tPF5W6S.png
 And you also said that you would add multifanart support and I'm really looking forward to it!) I really hope that you will add something like that, as you wrote on the release day that you will add soon these functions that were not originally there ..

**Comment by jurialmunkey** [comment]
As mentioned on the very first post in AH2 thread, these view options are currently incomplete. They will be added when I have finished working on them. 

Enabling them in a broken state will just mean I get flooded by bug reports for things I already know about and distracts from more pressing issues. They will be ready when they're ready.

v0.1.39 will add multifanart support (will make a release soon, just a few extras to add first). Multifanart must be in the Matrix format which scans it to fanart1, fanart2, fanart3 etc.

**Comment by Whiteripd0** [comment]
Good evening:) Thank you very much for not ignoring my request and answering very clearly!) Sorry for disturbing.. I just thought that you changed your mind about adding this feature.. Thank you very much for adding multifanart support, I was madly waiting for this new feature !) But could you please add the multifanrt feature to the Home menu as well :) To be honest, I really wanted this feature to a greater extent because of Spotlight!) As for presets, take your time!) As soon as it suits you😌 I understand you very clearly😌 Thank you so much for your new creation and for your work🙏🏻 Thank you that thanks to you I also have the opportunity to enjoy this skin with you💛

**Comment by jurialmunkey** [comment]
Multifanart should work on home screen. 

Unless you're talking specifically about fullscreen widget only? In which case that is likely not possible due some kodi limitations with how widget container item layouts function.
