### ISSUE TITLE
[BUG] [Skin Section] Title Font overlapping  in widgets

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.arctic.horizon.2#173]
**Describe the bug**
The title Font seems to be overlapping as you'll see in the screenshot below. Just to confirm this is ONLY happening when you se widgets in the homescreen. If you navigate directly into addons this isn't isn't present as their seems to be a bigger space between the title font and the text info below it.

**To Reproduce**

Set any widget from TMDb, etc and make sure the Expand Information under the Widget setup is set to FULL so the title of content is displayed.

**Expected behavior**
There should be a little bit of more separation between the title font and text info below so overlapping no longer an issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/76958541/173728653-68224a13-e26a-45d3-844c-0964252a9b90.jpeg)

![image](https://user-images.githubusercontent.com/76958541/173728677-68772dc6-9bfb-47f5-832b-ba78e4da2856.jpeg)

**Platform Information (please complete the following information):**
 - Platform: [Nvidia Shield TV, latest update.]
 
- Skin Version [0.1.36]

- Kodi v.19.4

**Comment by jurialmunkey** [comment]
I agree, the overlap with the larger font of the widget title is bad.

I'm finding this solution that I implemented for displaying the widget title to be problematic. There's a lot of issues with it that I'm not happy about. 

Not sure what the solution is yet. I don't want to change the spacing because I want it to remain consistent with the skin but the larger font of the widget title is problematic. But I don't want to change the widget title font because I also want that to be consistent!

**Comment by jurialmunkey** [comment]
Actually looking at this closer, I realised my spacing here was slightly off from the standard skin spacing. The 5px of height gained by the default spacing makes a big difference here.

Can you try https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.38
I think that should make a decent difference to this overlap

**Comment by Nuklear92** [comment]
> Actually looking at this closer, I realised my spacing here was slightly off from the standard skin spacing. The 5px of height gained by the default spacing makes a big difference here.
> 
> 
> 
> Can you try https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.38
> 
> I think that should make a decent difference to this overlap
> 
> 
> 
> 

Sorry for the late reply, I had the chance to test the new version out, matter fact I jumped that version you pointed for the newest one ending in 1.42 that you released not long ago. And yeah there seems to be an improvement overall now still super close to each other as you'll see in the screenshot below, but way better than prior the fix which text was clearly overlapping. 👍

![image](https://user-images.githubusercontent.com/76958541/173907982-2fd0af13-efd9-4af4-b360-15af0ea65dde.jpeg)

Thanks for the fix and all the hard work you're putting into this skin! 😃

**Comment by jurialmunkey** [comment]
Yeah still fairly tight squeeze there. 

Also though - I think you were particularly unlucky in your screenshot with the descending characters in the item title almost exactly lining up with the ascending characters in the widget title!

Anyway - I don't think it is going to get much better without me entirely changing the approach to widget titles in expanded info (which I may still do) so I'm going to close this one for now as resolved.
