### ISSUE TITLE
Cant get other buttons than Music

### ISSUE THREAD

**Issue by inkatail** [jurialmunkey/skin.arctic.horizon.2#18]
I don't see Movies, and other, there is only Music btw im using 19.3 since its latest on Android instead of 19.4
I installed all things needed for this theme
Help!

**Comment by dm2912** [comment]
Do you have any movies or shows in your library?

Those menu options rely on having a local library, same as music

**Comment by jurialmunkey** [comment]
What dm2912 said.

Skinshortcuts hides movies/tvshows if you don't have items in your respective libraries.

You can edit the home menu in skin settings - navigate to the power menu settings cog on the right of the menu and in skin settings (paint brush icon) there is an option to configure the menus/widgets etc. - you just need to replace the movie/tvshows shortcuts with links to something else.
