### ISSUE TITLE
[BUG] [Videos] Unable to refresh metadata

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#180]
**Describe the bug**
There doesn't seem to be a way to refresh the metadata for TV shows or Movies - with AH1 this could be done via Info / Manage 

(same issue with Music Library also)

**To Reproduce**
1. Go to TV Shows or Movies
2. Click on a TV show or Movie
3. Press I (Info)
4. The "manage" button is missing

**Expected behavior**
Expect to access a method of refreshing metadata

**Screenshots**
n/a

**Platform Information (please complete the following information):**
 - Platform: Windows]
 - Skin Version [0.1.41]

**Additional context**

**Comment by jurialmunkey** [comment]
Keep pressing right from the buttons and you can open the side menu. It should be there.

**Comment by berkhornet** [comment]
Ok thanks. I’ll try that soon. I’m away for a few days.

Mick
________________________________

**Comment by berkhornet** [comment]
Got it thanks - I'll close issue
