### ISSUE TITLE
[BUG] Program Window Crashes

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon.2#187]
After installing AH2, I get a Texture Maker Error (Crash)

This was a fresh install

https://user-images.githubusercontent.com/2873112/173960703-d6710504-2c76-4eb0-9dfe-f816e8ad17fd.mp4

[kodi_crashlog-20220616_000032.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8914098/kodi_crashlog-20220616_000032.log)
[kodi_crashlog-20220616_000045.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8914099/kodi_crashlog-20220616_000045.log)
[kodi_crashlog-20220616_000157.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8914101/kodi_crashlog-20220616_000157.log)

Thanks

**Comment by cgcgcgcgcg** [comment]
Your Linux distro uses python v3.10 -like my Arch-, and that is probably what crashes your Kodi.
Try Flatpak Kodi -uses pythonv3.9, but doesn't crash.
https://flathub.org/apps/details/tv.kodi.Kodi
https://diggzwiki.com/index.php?title=Tips#Flatpak_Kodi_guide_for_Linux

**Comment by Blurayx** [comment]
> Your Linux distro uses python v3.10 -like my Arch-, and that is probably what crashes your Kodi. Try Flatpak Kodi -uses python v3.9, but doesn't crash, Kodi uses internally python v3.8, and that's as close as you can get. https://flathub.org/apps/details/tv.kodi.Kodi https://diggzwiki.com/index.php?title=Tips#Flatpak_Kodi_guide_for_Linux

I'm using Flatpak Kodi. kodi only crashes with AH2. AH works fine.

**Comment by cgcgcgcgcg** [comment]
> > Your Linux distro uses python v3.10 -like my Arch-, and that is probably what crashes your Kodi. Try Flatpak Kodi -uses python v3.9, but doesn't crash, Kodi uses internally python v3.8, and that's as close as you can get. https://flathub.org/apps/details/tv.kodi.Kodi https://diggzwiki.com/index.php?title=Tips#Flatpak_Kodi_guide_for_Linux
> 
> I'm using Arch xerolinux with Kodi Flatpak. Kodi only crashes with AH2. AH works fine.

Peeps here might need a full debug log, not just crash logs to see what's happening.
https://kodi.wiki/view/Log_file/Easy
I saw a lot of python v3.10 elements in your crash logs, for example where I have:
```
File "/app/lib/python3.9/site-packages/PIL/Image.py", line 2334, in getchannel
                                                       raise ValueError(f'The image has no channel "{channel}"') from e
```
You have a:
```
ile "/usr/lib/python3.10/site-packages/PIL/Image.py", line 1723, in point
                                                       return self._new(self.im.point(lut, mode))
```

**Comment by jurialmunkey** [comment]
@Blurayx - Could you try v0.2.6 of texturemaker?
https://github.com/jurialmunkey/script.texturemaker/releases/tag/v0.2.6

Pretty sure this is the same bug as https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/195#issuecomment-1157494226 in which case it should be fixed by 0.2.6 of texturemaker.

**Comment by Blurayx** [comment]
> @Blurayx - Could you try v0.2.6 of texturemaker? https://github.com/jurialmunkey/script.texturemaker/releases/tag/v0.2.6
> 
> Pretty sure this is the same bug as [#195 (comment)](https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/195#issuecomment-1157494226) in which case it should be fixed by 0.2.6 of texturemaker.

 TV shows, movies, next aired it works without issues. Clicking on Programmes is blank, then Kodi crashes


https://user-images.githubusercontent.com/2873112/174172653-b808e8d1-3a02-4a04-85c5-568cd1b3e322.mp4


[kodi_crashlog-20220616_213825.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8922682/kodi_crashlog-20220616_213825.log)

[kodi_crashlog-20220616_213909.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8922685/kodi_crashlog-20220616_213909.log)

thanks

**Comment by Blurayx** [comment]
Update regarding tvOS: 

*  using Kodi 19 Nightly build
* installed script skinshortcut 1.1.5
* addon.xml: changed  version="2.0.1" to 1.1.5
* turned off auto upate(optional)
* manually installed AH2, TMDB helper, texturemaker.

So far everything is working perfectly

**Comment by jurialmunkey** [comment]
So the programs window is working now without crashing?

**Comment by Blurayx** [comment]
Yes 😀

**Comment by jurialmunkey** [comment]
Okay amazing!  Not quite sure what would've fixed it but hopefully it'll be okay now

**Comment by Blurayx** [comment]
Update regarding Linux:
Now working without crashing when I click on programs😀
