### ISSUE TITLE
Certain seasons have a shuffled episode order

### ISSUE THREAD

**Issue by Weevild** [jurialmunkey/skin.arctic.horizon.2#19]
![20220604_205249](https://user-images.githubusercontent.com/89477083/172022016-fa401173-4234-40cc-82ba-88378f94c36d.jpg)

E.g season 2 starts on episode 6 for this specific series. I've found this for 2 shows thus far.

**Comment by jurialmunkey** [comment]
I'm pretty sure it should be fixed now in 0.1.4
Let me know if there's still any issues.

**Comment by Weevild** [comment]
@jurialmunkey No issues to report at this point in time, well done and thank you for your work!
