### ISSUE TITLE
[Feature] [PVR] Missing plot info in OSD

### ISSUE THREAD

**Issue by chcore** [jurialmunkey/skin.arctic.horizon.2#193]
As the title states, there is no plot info in the PVR OSD.

**Comment by jurialmunkey** [comment]
Focus the info button and it will display plot.

**Comment by chcore** [comment]
Thanks @jurialmunkey , OK I see that in the "Enter button" OSD now, but I was specifically referring to the "info" OSD (by hitting the 'i' key or the up/down arrow keys for channel switching). Should the plot info be included in these? Most skins including AZ2 do.

**Comment by jurialmunkey** [comment]
No plot is not shown with the seekbar and I don't have any plans to show it there. The seekbar is simplified in AH2 to keep in line with the minimal aesthetic.

However, I am planning to add an overlay when switching channels which will briefly display channel number, logo and plot outline to give a clearer sense of what is being switched to.

**Comment by chcore** [comment]
I agree that the seek bar OSD should be minimal. Does it need to be the same as the "i" (info) OSD?

Looking forward to the channel switch OSD changes, thanks.

**Comment by jurialmunkey** [comment]
Added in 2166b9b3f8aa12f32e35f989492dcef5ccaad679

**Comment by chcore** [comment]
Thank you for this one @jurialmunkey but on my system (a Nexus build from a couple of weeks ago) it now takes up more than half the screen:

![image](https://user-images.githubusercontent.com/83099052/206845957-deb91a01-4cb2-4d58-88e8-b2a22b6aad7d.png)

Might it be possible to:

1. Hide the genre
2. Hide the widget at the bottom, since it is displaying information that is already present elsewhere (channel, channel number, title)
3. Truncate the title a little less aggressively

I also noticed that the plot will scroll even when there should be enough space to display it in its entirety, but not sure yet if that's specific to this particular view.

What do you think?
