### ISSUE TITLE
[BUG] AH2 crashes when opening 'download subitle' menu for movies

### ISSUE THREAD

**Issue by vermope** [jurialmunkey/skin.arctic.horizon.2#194]
AH2 crashes when downloading subtitles from an external provider (a4ksubitles in this case). This happens only when searching subtitles for movies and not series.

AH2: 0.1.41
Kodi Matrix19.4
LibreElec 10.0.2

Crashlog: https://pastebin.com/3R7ehZx4

**Comment by jurialmunkey** [comment]
I can't reproduce this issue. 

Subtitles download fine for me using subtitle add-ons that are available from the official repo (e.g. OpenSubtitles.org)

Sounds like an issue with a 3rd party add-on rather than the skin.
