### ISSUE TITLE
[Feature] [OSD] Allow disabling media flags

### ISSUE THREAD

**Issue by chcore** [jurialmunkey/skin.arctic.horizon.2#199]
As stated in the title, I hope you would consider an option that allows us to hide/disable media flags everywhere they are currently displayed.

**Comment by chcore** [comment]
Thanks @jurialmunkey I am now able to hide the flags in the library, but they are still displayed in the info OSD when playing a video (side note, an option to show plot information in their place would be really handy, especially when watching live TV).

**Comment by jurialmunkey** [comment]
Ah sorry misread the title and thought it was the request to hide library flags
