### ISSUE TITLE
[Feature] Option to disable the star rating

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/skin.arctic.horizon.2#201]
Hi @jurialmunkey, can you add the option to disable the rating with a star icon (the first one in rating info line)? This is the rating from Kodi database, right? With other ratings (IMDB, TMDB, etc.) available by default, this star rating seems very odd to me, and I would rather disable it.

**Comment by jurialmunkey** [comment]
To be added with feature #209
