### ISSUE TITLE
[Feature] [View Types] Animate season switching in Landscape Combined view

### ISSUE THREAD

**Issue by chcore** [jurialmunkey/skin.arctic.horizon.2#212]
Switching between seasons of a TV show in the Landscape Combined view type has the episode thumbnails change instantly, which is a little jarring as virtually everything else is nicely animated in some way.

**Comment by jurialmunkey** [comment]
Unfortunately haven't been able to find a good way to do this. The animation triggers just aren't flexible enough to get a nice transition animation.
