### ISSUE TITLE
[Feature] Randomise FanArt backgrounds 

### ISSUE THREAD

**Issue by JacopoV** [jurialmunkey/skin.arctic.horizon.2#213]
Hi,

would be possible to randomise fanart backgrounds if more than one ?
Thanks

**Comment by jurialmunkey** [comment]
This should already work. Your extra fanart must be assigned as fanart1, fanart2, fanart3 etc. (not the old method of an extrafanart folder).

You can do this for library content using the Artwork Dump addon available on the forums. TMDbH also does this for its own content if you enable fanart tv lookups for widgets and plugin paths.

Other add-ons will depends on the addon supporting extrafanart. As long as the addon assigns fanart using the new Matrix naming system of ListItem.Art(fanart1) ListItem.Art(fanart2) etc. it will work.

**Comment by jurialmunkey** [comment]
Also note that if you are talking about the fullscreen widget I don't think that is possible.
