### ISSUE TITLE
[Feature] Fullscreen Widget - Add sorting options

### ISSUE THREAD

**Issue by JacopoV** [jurialmunkey/skin.arctic.horizon.2#214]
Hi,

would it be possible to add sorting options for fullscreen widgets, like the other regular widgets ?
Many thanks

**Comment by dm2912** [comment]
Yes, this really needs an option for random. If i use a specific source/list my home is looking very static :D

**Comment by jurialmunkey** [comment]
Maybe it should just be random by default anyway to give that "spotlight" feel. 

I'm trying to think of a scenario where anything other than random sorting would be desirable for fullscreen widget and I can't think of many. Maybe pvr channels but that's it.

My only concern about sorting options is that it adds two items because you need direction too - so it will clutter up the customisation dialog and make things harder to find. If I just set as random by default then I think that solves both issues really as I can't see much use for other sorting methods unlike with standard widgets where you can see more than one thing at a time.

**Comment by JacopoV** [comment]
@jurialmunkey this feature request came just for my page called "spotlight" and I use it for my watch list.
So having it random it's what I m looking for.

About having random by default, I dont see the problem with it. I ve also another one for trending in my movies sections, and another one for my collections in TV shows.

Up to you anyways =) I'm happy already..

**Comment by krzysztofwinnik** [comment]
@jurialmunkey you're right random sorting should cover 99% of the cases... but consider these 2 scenarios:
1) saved tMDBhelper discovery search - eg. recent movies excluding anime genre rteb by at least 100 people with ratings >6 sorted by release date (this gives me a list of recent movies worth watching)
2) different kinds of TOP10 lists... eg. TOP10 trending movies this week from TMDB

**Comment by jurialmunkey** [comment]
Kodi's sort method only applies to the page of results that are returned by the plugin. It won't cause the actual list to have different sorting.

So tmdb discover will still return the same 20 results as normal. Just those results will display in a random order in full screen widget.

Same goes for the top 10 lists - you'll still get the top 10 results. Just the fullscreen widget will shuffle up how they are displayed

**Comment by krzysztofwinnik** [comment]
Ok, but what is the point of having TOP10 on widgets if you can't tell which is no1 or most recent if you can't tell which is the latest?
I'm just saying I think default sort method should be NONE. This way if I have a pre-sorted list, it'd be displayed in the same order on widgets, while randomisation could be an option if you really need it. 
Still, it's just my opinion and i'm not going to argue if you are not convinced.

**Comment by jurialmunkey** [comment]
> Ok, but what is the point of having TOP10 on widgets if you can't tell which is no1 or most recent if you can't tell which is the latest? I'm just saying I think default sort method should be NONE. This way if I have a pre-sorted list, it'd be displayed in the same order on widgets, while randomisation could be an option if you really need it. Still, it's just my opinion and i'm not going to argue if you are not convinced.

How do you tell which item is first on the fullscreen widget? It's a carousel. It has no start or end.

Were only talking about the fullscreen widget here. Normal widgets already have options for sort methods
