### ISSUE TITLE
[BUG] Play button not working correctly for TMDbH managed info dialogs

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.horizon.2#215]
**Describe the bug**
When navigating through TMDbH managed info dialogs from the recommendations screen, the play button does not function correctly.

**To Reproduce**
1. View info dialog on a movie
2. Scroll down to recommendations
3. Click another movie
4. Click play creates an error

**Expected behavior**
The play button properly closes the info dialog and plays via TMDbHelper

**Comment by sabre6** [comment]
I think this is a good idea. Maybe for the final binding, it could be revert to "last channel", if that is an option?

And when brining up the OSD to start, perhaps it can focus on Stop, as that would likely be the most used binding in the group.
