### ISSUE TITLE
[BUG]0.1.47 update does not install. 

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.horizon.2#216]
**Describe the bug**
 The latest Arctic Horizon 2-0.1.47 update just goes black and freezes.

**To Reproduce**
1. Update from repo goes black
2. update from zip goes black

**Expected behavior**
Skin updates

**Screenshots**

**Platform Information (please complete the following information):**
 - MacOS Big Sur, Kodi 19.4

**Additional context**

**Comment by jurialmunkey** [comment]
Debug log?

**Comment by Liquidrag** [comment]
idk how much help it will be but here's a log.

https://paste.kodi.tv/zabifefiyo.kodi

**Comment by jurialmunkey** [comment]
The version of TMDbH that you have installed does not match the required dependency version in AH2

You log shows v4.8.12 is installed.
`2022-06-17 22:02:57.275 T:406975    INFO <general>: CAddonMgr::FindAddons: plugin.video.themoviedb.helper v4.8.12 installed`

However, v4.8.15 is required
https://github.com/jurialmunkey/skin.arctic.horizon.2/blob/b2eb0f9b859f7589ccfa7abc94b09c2b05a9978c/addon.xml#L7

**Comment by Liquidrag** [comment]
> The log is extremely helpful. Specifically this line `2022-06-17 22:05:48.481 T:407404 ERROR <general>: CAddonInstallJob[skin.arctic.horizon.2]: found dependency [plugin.video.themoviedb.helper/4.4.0] doesn't meet minimum version [4.8.15]`
> 
> The version of TMDbH that you have installed does not match the required dependency version in AH2
> 
> Your log shows v4.8.12 is installed. `2022-06-17 22:02:57.275 T:406975 INFO <general>: CAddonMgr::FindAddons: plugin.video.themoviedb.helper v4.8.12 installed`
> 
> However, v4.8.15 or higher is required
> 
> https://github.com/jurialmunkey/skin.arctic.horizon.2/blob/b2eb0f9b859f7589ccfa7abc94b09c2b05a9978c/addon.xml#L7
> 
> Kodi is trying to install the official repo version, not my repo version. Most likely you will need to install the new version of TMDbH manually because you aren't tracking updates from my repo.

Thank you! I have install updates from your repo and update official addons from any repositories enabled but for some reason it never updates. I have to manually check. Is there something I missed? 
![Screen Shot 2022-06-18 at 8 47 01 AM](https://user-images.githubusercontent.com/43726430/174442165-247dca33-8258-4b1e-986f-c9c147a3da2b.png)
![Screen Shot 2022-06-18 at 8 47 55 AM](https://user-images.githubusercontent.com/43726430/174442168-2f3aa96d-4913-4085-8f66-97678d7731b5.png)

**Comment by jurialmunkey** [comment]
Kodi tracks the repo you installed from. It won't install updates from another repo unless you specifically install from there via addon browser.

**Comment by Liquidrag** [comment]
I’ve only installed it from your repo. It still never updates. It’s been like that while now.

**Comment by drinfernoo** [comment]
@jurialmunkey There seems to be a flaw in the logic they're using for that: https://github.com/xbmc/xbmc/issues/21572

**Comment by Liquidrag** [comment]
Thank you @drinfernoo

**Comment by jurialmunkey** [comment]
I think you have to install in a specific way (and yes I think flawed as not at all intuitive and I can't even remember specifically what) 

My loungeroom htpc is set to install updates from the repo and it updated both tmdbh and the skin automatically on Matrix 19.4. 

However previously I had an issue with tmdbh not updating but now it does. I think it was something about how I updated in a particular way via addon browser that made it finally track but honestly I can't remember what.

**Comment by Liquidrag** [comment]
I'll try uninstalling and try again. Thanks!

**Comment by ambulancePilot** [comment]
Just want to add that I have never been able to get TMDB Helper to update by itself. I have always installed it from your repo FIRST before ever needing it as a dependency for anything else. It just never updates.

Further, ever since installing AH2, basically none of my repos update. I have to download zips of everything and do it manually. There used to be a way to force check a repo for update if it fails to refresh in AH, but I can't find that option in AH2. Does it exist? How do I force check a repo for updates?

**Comment by Liquidrag** [comment]
> Just want to add that I have never been able to get TMDB Helper to update by itself. I have always installed it from your repo FIRST before ever needing it as a dependency for anything else. It just never updates.
> 
> Further, ever since installing AH2, basically none of my repos update. I have to download zips of everything and do it manually. There used to be a way to force check a repo for update if it fails to refresh in AH, but I can't find that option in AH2. Does it exist? How do I force check a repo for updates? AH2 itself does not update for this reason. I was on 1.49 for the longest time because I didn't realize you had been dropping updates on GitHub.
> 
> Thanks for the great skin. Much smoother than AH!

Push left in the addons. You’ll see options for that.
