### ISSUE TITLE
[BUG] Path information in gear menu for TV shows is incorrect

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/skin.arctic.horizon.2#221]
### Current Behavior

The path seems only list the parent folder of TV shows folder

### Expected Behavior

The path should list the TV shows folder

### Steps To Reproduce

Open the video info dialog for any TV show and check the gear menu for path

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Hawkedon** [comment]
Thanks @jurialmunkey for the fix! The new location is perfect. The font size is too small for me on TV though. As there is no size constrain anymore for the path now, maybe you can make it bigger or same size as the gear menu item font size? :)

**Comment by jurialmunkey** [comment]
>  The font size is too small for me on TV though. As there is no size constrain anymore for the path now, maybe you can make it bigger or same size as the gear menu item font size? :)

Yep I agree. Bumped it up to the next font size definition to match the date label.
