### ISSUE TITLE
[BUG] Fullscreen Widget - Browse button opens information page

### ISSUE THREAD

**Issue by JacopoV** [jurialmunkey/skin.arctic.horizon.2#223]
### Current Behavior

At the moment, if Browse button on a fullscreen widget is pressed, it opens the page for informations instead jumping into the season. 
Not sure if it's the intended behaviour.

Skin version : 0.1.48

### Expected Behavior

Considering the Browse button , inside the information page, brings the user to the season for the tv show, i assume that clicking the Browse button directly from the fullscreen widget, to open directly all the season list.

### Steps To Reproduce

1. select a tv show fullscreen widget
2. click directly Browse (not from information page)
3. notice the information page is opened anyways

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
What setting do you have for Default Play Action?

**Comment by JacopoV** [comment]
@jurialmunkey "Default selection action" : Show information

I supposed my setup is wrong if you ask for it :)

**Comment by jurialmunkey** [comment]
All the browse/play button does on the fullscreen widget is perform `Action(Select)` - So it will do what ever your default select action is set as. It's the same as if you clicked on the widget directly.

**Comment by JacopoV** [comment]
@jurialmunkey thanks for the explanation 👍  i do recall a functionality, but can't remember on what skin, that gave some degrees of freedom to open or play or information separated for TV shows or movies, so i suppose under certain views it can be picked. At that point, not sure if you can really force browse on your end bypassing the action.
