### ISSUE TITLE
[BUG] Seasons list in recommendations dialog does not open season

### ISSUE THREAD

**Issue by georgew21** [jurialmunkey/skin.arctic.horizon.2#224]
### Current Behavior

If I am on movie information of a series and from widgets I select to go to a season it stays to movie information of series instead to go to episodes and seasons.

The problem has to do that I have enabled information instead of play in kodi settings for default action. 

### Expected Behavior

When select a season , then we expect to view the episodes of this season.

### Steps To Reproduce

1. Enable in kodi settings default action to information instead play.
2. Go to a series and then choose a season.
3. It doesn't go to season

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce this issue.

I turned on "Show information" in settings. Click a show tvshow, click Browse, click season, it opens the episodes.

**Comment by georgew21** [comment]
The problem is when instead click to Browse, go to widget row with
"Seasons" and choose a season from there.

Στις Σάβ 18 Ιουν 2022 στις 2:36 μ.μ., ο/η jurialmunkey <
***@***.***> έγραψε:
