### ISSUE TITLE
[Feature] Custom Widget Limits

### ISSUE THREAD

**Issue by titelheld** [jurialmunkey/skin.arctic.horizon.2#226]
### Is your feature request related to a problem? Please describe.

Currently, just with you other skins, there are only options for 10, 25, 50, 100, No Limit options. 

In the past I edited some XML to add my own limits but it would be amazing if there would be an option to set a custom widget limit for each widget from the settings menus. 

Perhaps by brining up a number pad to set the custom limit. 

### Describe the solution you'd like

Add a Custom Limit option that brings up a number pad that allows setting a custom widget limit for each widget. 

### Screenshots and Additional Info

![image](https://user-images.githubusercontent.com/25116213/174444991-c3e7670b-0271-481f-853a-0b3df6059f2e.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Tee77** [comment]
Interesting. I only recently discovered that setting a limit on an auto scrolling banner widget (in my case 10) prevents this widget from showing a blank next page banner every so often, whilst still allowing me to show next page items on other widgets. A widget limit of 19 (I think?) would be useful to me, allowing more items in the banner widget to display without showing the next page item in that widget. So yes, if this is possible I could definitely see the value in custom widget limits.

**Comment by jurialmunkey** [comment]
Custom limits are not possible. Kodi doesn't allow passing item properties or skin strings to xml to to value attributes. Attributes need to be evaluated on load so need to be hardcoded

What limit values do you feel are missing?

**Comment by titelheld** [comment]
The reason why I felt the need in the past was because I used autowidget and wanted some non-scrollable widgets that automatically refresh their content. 

For this purpose I added the following limits to the list

Poster 7
Landscape 4
Square 6
Banner 1
Icon 6


I am not sure about how to best integrate the selection into the interface without making it look like random numbers but perhaps it is possible to add a "Limit to display width" option that sets the limit according to the list above depending on what widget style (poster, landscape , etc) has been chosen. 

I hope I am making sense here

**Comment by titelheld** [comment]
On a side note

I have also noticed that the "icon" style is missing for widgets in AH2. I hope it won't be exclusive to the submenu widget because I used this style to link to some custom link lists. 

Would be great if you could enable the "icon" style for widgets again. (Attached screenshot example)

**Comment by jurialmunkey** [comment]
Submenu style already requested https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/91

**Comment by jurialmunkey** [comment]
> add a "Limit to display width" option that sets the limit according to the list above depending on what widget style (poster, landscape , etc) has been chosen.


That's a good idea! Should be possible.

**Comment by titelheld** [comment]
Would be amazing if you could make it work. :)

**Comment by jurialmunkey** [comment]
Should be working in v0.2.32 - Let me know how it goes
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.2.32

@titelheld - The "Auto-fit to width" option should adjust the widget limit according to the style selected. Pretty sure I got all of them correct but let me know if I messed any up.

@Tee77 - I've adjusted the `25` option to be `20` as I imagine in most cases where next page is displayed it will be either the 21st or 11th item (e.g. TMDb default pagination is 20 items per page, so next page will be 21st; and Trakt default pagination is 10 items per page so next page item is 11th).

I think these new options should cover all the main use cases for limits. I don't see much point having 25 now that there's a 20 option - so I added options for 30 and 40 instead.

**Comment by Tee77** [comment]
Lovely addition - works great, thanks.

**Comment by titelheld** [comment]
Sorry for the late reply, I’ve got around to testing them though and they work well. Thank you so much of adding this feature ? :)

**Comment by drinfernoo** [comment]
@jurialmunkey Just for what it's worth (sorry I'm here late), if users want to use AutoWidget's "Paged Widgets", they need to turn their widget limit up to at least 21 items. Since the original "Next Page" item is the 21st, AutoWidget won't show it either unless the limit is high enough.

**Comment by jurialmunkey** [comment]
> @jurialmunkey Just for what it's worth (sorry I'm here late), if users want to use AutoWidget's "Paged Widgets", they need to turn their widget limit up to at least 21 items. Since the original "Next Page" item is the 21st, AutoWidget won't show it either unless the limit is high enough.

In that case why even set a limit at all for that widget? Next page is always going to be the last item, so you need all items to display if you want to see it. There's no point setting an item limit for a widget unless you want to show fewer items than the list provides.

i.e. 
if you want all items including the next page item for that widget to display, then you don't set a limit for the widget.
if you want to cut-off the next page item and only display the content you set limit to 20.

**Comment by drinfernoo** [comment]
@jurialmunkey Makes sense to me! A lot of skins use 20 as the default, but no limit seems more useful 👍
