### ISSUE TITLE
[Feature] Additional Info on OSD

### ISSUE THREAD

**Issue by titelheld** [jurialmunkey/skin.arctic.horizon.2#227]
### Is your feature request related to a problem? Please describe.

In Arctic Horizon 1 there is an option to display additional OSD Information, such as Plot, Poster, Ratings, when pressing the „I“ button. Currently this feature doesn’t exist in AH2. 

At the very least pressing the i button should bring up the information menu that displays plot and cast so one does not need to navigate to it manually. 

### Describe the solution you'd like

Add additional OSD information option like in AH1 to the skin settings. 

Pressing the i button should bring up the information menu that displays plot and cast. 
(I attached a screenshot of the Menü I am talking about)

### Screenshots and Additional Info

![image](https://user-images.githubusercontent.com/25116213/174445391-f1edd391-6696-44f6-a6d2-0e1e927ae37b.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Kayzels** [comment]
Just a +1 from me for this. I was trying to figure out a way to get it so it displays the info popup when pressing I. I found the oninfo control, but that requires there to be something in focus. Would there be a way to implement that, maybe with a dummy background window or something?

**Comment by jurialmunkey** [comment]
Added in 2166b9b3f8aa12f32e35f989492dcef5ccaad679
