### ISSUE TITLE
[BUG] Crashing on widgets, info screen

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#228]
Using Nvidia shield 2019 pro K19.4 AH2 v0.1.48 ,TMDB Helper v4.8.15 ,context menu v1.1.0,Skinvariables v1.0.2 ,, it's only happening on info widgets screen for Movies ,tested TV shows seems fine no crashing there,, when you're on the information screen causes it to crash sometimes instant sometimes it takes a few seconds when you've been in that section,, also tested within TMDB H and get the same crashing issue after a few seconds,,Here's a few videos to help better explain my apologies didn't get a chance to get the log

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/174447406-34eabde7-e62b-4c2a-855e-44ff87de3739.MOV Home screen widgets

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/174447452-e05c5b25-4e6d-4201-9cba-3ff8123cda9f.MOV

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/174447574-fd7cf498-7778-4949-88d4-eec1859ef7d8.MOV

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/174447720-561b8ad8-e72b-4e30-971e-f553568670c4.MOV

**Comment by xyzfre** [comment]
Sometimes it happens instant but sometimes you have to be in the information screen for a few before it crashes not sure if anybody is also experiencing the same thing appreciate any help

**Comment by xyzfre** [comment]
I just tried reverting back to AH2 v0.1.46 and on this version the crashing is happening as well didn't notice on what version it started happening

**Comment by jurialmunkey** [comment]
Please follow the bug report template.
