### ISSUE TITLE
[BUG] Progress icons on last played Live TV Channels

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#229]
### Current Behavior

After the latest update I'm seeing progress icons on last played live TV channels which I guess is not correct.

### Expected Behavior

I think these icons should only show for Movies and TV Shows, or am I wrong? Is this a new feature of some kind? Please advise.

EDIT: On further checking I'm assuming that this is not a bug but a feature and is showing the progress of the currently live program on the TV channel. If I'm correct then this is an awesome feature that you added, and if so then you can close this issue.

### Steps To Reproduce

Check the last played Live TV Channels widget screenshot which I shared.

### Screenshots and Additional Info

![IMG20220618233950](https://user-images.githubusercontent.com/65297828/174451385-494e8c5b-da2a-4aea-a0cb-b53ee4b67eee.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yes it's intentional. It's the progress on the tvshow

Added in this commit
https://github.com/jurialmunkey/skin.arctic.horizon.2/commit/a7a604c877268b3817729b97da5e311b580eac88

Still not 100% sure if I'm going to keep that style or switch to a more traditional line for live progress - but either way definitely intentional.

**Comment by ShibajiCh** [comment]
> Yes it's intentional. It's the progress on the tvshow
> 
> Added in this commit [a7a604c](https://github.com/jurialmunkey/skin.arctic.horizon.2/commit/a7a604c877268b3817729b97da5e311b580eac88)
> 
> Still not 100% sure if I'm going to keep that style or switch to a more traditional line for live progress - but either way definitely intentional.

Hi @jurialmunkey,

Thanks for the info! The feature looks good.
