### ISSUE TITLE
[BUG] PVR - Unknown title of program

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#233]
### Current Behavior

On selecting any channel from the pop up box which is there just before the channel info button, the channel starts playing but it's title shows up as UNKNOWN.

### Expected Behavior

The title should show the name of the currently playing program.

### Steps To Reproduce

Hover over the button just before the info button. Select any channel from the pop up box.

### Screenshots and Additional Info

![IMG20220619002607](https://user-images.githubusercontent.com/65297828/174452972-768877d7-0f27-4933-81b3-92239122c71f.jpg)
![IMG20220619002558](https://user-images.githubusercontent.com/65297828/174452986-58cd81a9-69ca-4940-83cc-18fdf0e6c0a8.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I'm unable to reproduce this issue. It sounds like an issue with your PVR client rather than the skin.

That being said, the seekbar details *do* need a bit of work to suit PVR in general -- e.g. I'm sure a channel name and number would be appreciated! ;)

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Fine. If you're not able to reproduce the issue then it might be the PVR addon's problem. I'm using the JIO TV addon from BotAllen's repo. The issue is not so big, so I can live with it. 

Yes, the seekbar that you mentioned will be really good. 🙂

If you want you can close this ticket.
