### ISSUE TITLE
[BUG] Widget positioning issues caused by fade animations (Nexus nightly bug)

### ISSUE THREAD

**Issue by ffwell** [jurialmunkey/skin.arctic.horizon.2#234]
### Current Behavior

Once the full screen widget is created, an error occurs with the normal widget. It can't be displayed. The earliest version didn't have this problem. It was normal at 0.12. It has been around since then.

### Expected Behavior

Once the full screen widget is created, an error occurs with the normal widget. It can't be displayed. The earliest version didn't have this problem. It was normal at 0.12. It has been around since then.

### Steps To Reproduce

Once the full screen widget is created, an error occurs with the normal widget. It can't be displayed. The earliest version didn't have this problem. It was normal at 0.12. It has been around since then.

### Screenshots and Additional Info

https://user-images.githubusercontent.com/29617777/174462459-ea746085-5dab-4fdc-adc4-a5d43ebc5680.mp4

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I am unable to reproduce this issue. Please provide exact steps to reproduce.

**Comment by Dis90** [comment]
I have same problem. I'm using Ubuntu and Kodi 20. Unfortunately I can't provide any steps to reproduce because like described in first post, it happens if fullscreen widget is enabled.

**Comment by jurialmunkey** [comment]
> I have same problem. I'm using Ubuntu and Kodi 20. Unfortunately I can't provide any steps to reproduce because like described in first post, it happens if fullscreen widget is enabled.

So the new setup just magicked into existence without you doing anything? 

The video clearly shows a setup which is not the default so there must be steps taken which cause this issue occur.

How do I get from the default skin setup to a setup where this issue happens? What steps do I need to follow so that I can recreate this issue. 

 I can't fix it if I don't know how to make the issue occur in the first place.

**Comment by Dis90** [comment]
Is there some files I can attach here so you can take a look what is going wrong?

**Comment by jurialmunkey** [comment]
I just need to know the steps to reproduce! 

From a default install, what would I need to do for this bug to occur? What settings do I need change.

**Comment by Dis90** [comment]
Nothing special needed.

I reseted deleted/reseted skin and same thing happens. So I now have everything default.

Steps to reproduce. Press down from remote in TV Shows or movies. Then when you are in fullscreen widget press down from remote and it jumps over whatever widget you have below fullscreen widget.

**Comment by jurialmunkey** [comment]
I cannot reproduce using the default settings for skinshortcuts.

Did you delete `kodi/userdata/addon_data/script.skinshortcuts` and then restart Kodi? Otherwise your skinshortcut settings are saved from before.

**Comment by Dis90** [comment]
No I didn't delete that folder previously but I now deleted and restarted Kodi. Still same problem.

I also tried with my Mac with Kodi 19 and it works correctly there. So maybe something with OS or Kodi 20?

**Comment by jurialmunkey** [comment]
Do you have debug log? Sounds like a skinshortcuts and/or Nexus issue in that case as it cannot be reproduced on Matrix. Possibly related to this skinshortcuts error on Nexus #225

**Comment by Dis90** [comment]
Here's debug log after deleting skinshortcuts folder and reboot.
[kodi_log.txt](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8934929/kodi_log.txt)

**Comment by jurialmunkey** [comment]
Can't see any errors in the log but I also can't reproduce on Nexus either. 

Every issue like this relates to a Nexus alpha. The skin works fine on Matrix which is what it is designed for. I can't spend any more time bug hunting Nexus issues when the problem is likely just related to some nightly build on a specific platform.

**Comment by jurialmunkey** [comment]
@Dis90 
Okay I'm able to reproduce and have discovered it occurs in nightlies from 7th Jun onwards. I believe the bug is caused by this PR in Kodi https://github.com/xbmc/xbmc/pull/21387

I've lodged a bug report here: https://github.com/xbmc/xbmc/issues/21615

**Comment by ffwell** [comment]
I admire your hard work. However, due to the construction of V20, this problem has not been solved.

**Comment by jurialmunkey** [comment]
> I admire your hard work. However, due to the construction of V20, this problem has not been solved.

As above. It is related to a bug in Nexus nightly introduced by a new feature. Until the bug is fixed the skin won't work on nightly builds. You should revert back to alpha 1 if you want to use the skin on nexus until alpha 2 is out.

**Comment by jurialmunkey** [comment]
This issue should now be fixed as of the most recent nightly version `20220806-bb1f94ec`

**Comment by ffwell** [comment]
> This issue should now be fixed as of the most recent nightly version `20220806-bb1f94ec`
thx，perfect。
