### ISSUE TITLE
Bugs and Feature Requests

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#24]
Hi @jurialmunkey,

First of all thanks for this amazing looking skin! Thank you for all the hard work!

I'm on Arctic Horizon 2 version 0.1.4. Here are a few bugs that I noticed and also a few Feature Requests:

1) Genres widget is not showing icons for both Movies and TV Shows (see below screenshot).
![IMG20220605150354](https://user-images.githubusercontent.com/65297828/172044772-5efcfc0b-0895-4841-9a79-7ed0e4f8cf93.jpg)

2) Clear logo is sometimes appearing and sometimes not for various movies and TV Shows. For example, for the movie "Interceptor" the clear logo is appearing for a second and then changing back to normal text (see below screenshots).
![IMG20220605152131](https://user-images.githubusercontent.com/65297828/172044958-a15817f8-361f-43eb-a03e-d483104cb2bb.jpg)
![IMG20220605150618](https://user-images.githubusercontent.com/65297828/172044962-ba321cf3-e409-49b8-b1d1-8e2b5613f39d.jpg)

3) Clear logos are also taking time to load everytime while moving through the widget items, i.e. first the normal text is appearing and then slowly the clear logo is appearing.

4) Also, in multiple profiles the clear logos are not always appearing for the second profile.

5) Fanart background is not appearing for any widgets. Even though I've set Fanart as option in appearance settings. It's working fine in library view though.

6) Widget titles are disappearing on focus when the Expand Information is set as Full for the widgets.

7) Fullscreen widget is not changing automatically after few seconds like it used to happen in Arctic Horizon skin. Could you please add that feature?

8) Please add widget limit option.

9) Stop button is not showing up in Video Player for sometimes and sometimes not. I'm stopping a video by long pressing back button at present if such a such a situation occurs.

10) Trailer is playing in background but box is showing as black (see screenshot below).
![IMG20220605153123](https://user-images.githubusercontent.com/65297828/172045288-d010dc18-6045-4ea0-8a89-525d62774a45.jpg)

11) Player OSD is not auto disappearing after few seconds like Arctic Horizon. Could you please add that feature?

12) Disabled Options are showing up under the Settings menu.

13) Is there any way to disable the submenu widget at the bottom or move it to a different position?

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Please open separate issues for each bug/request so that I can properly track each one. 
Also please check that the issue hasn't already been reported/requested before opening an issue

Trailer issue is reported here: https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/17 
I'm not quite sure what the cause is on Android yet, as it works perfectly fine on Windows.

The widget item limit is reported here: https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/10

Disabled items is reported here: https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/15

**Comment by jurialmunkey** [comment]
Fanart on home is reported here: https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/23

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

I'll check and create separate tickets for all unreported issues.

Thanks and Regards,
ShibajiCh.
