### ISSUE TITLE
[Feature] Add PVR catchup indicator

### ISSUE THREAD

**Issue by ray2301** [jurialmunkey/skin.arctic.horizon.2#240]
### Is your feature request related to a problem? Please describe.

PVR doesn't show catchup indicator on channels with catchup enabled

### Describe the solution you'd like

in layouts.xml under "layout_PVRChannel_Programs" i've added

            <include content="Object_Control">
                <param name="control" value="image" />
                <param name="id" value="1" />
                <texture>indicator/library.png</texture>
                <aspectratio align="right">keep</aspectratio>
                <height>24</height>
                <top>5</top>
                <visible>ListItem.IsPlayable + !ListItem.IsRecording</visible>
            </include>
            
that works for all views.

### Screenshots and Additional Info

![Snimka zaslona 2022-06-20 013855](https://user-images.githubusercontent.com/8508752/174533224-3c92f8df-e28f-4764-9a99-b1e223fcca4a.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I'm not familiar with PVR clients offering these options. Can this "catch-up" status happen at the same time as HasTimer / IsRecording? Or are these unable to be recorded?

I've got to add timer/recording status to EPG so I'm wondering if I can catch all three statuses with a single variable icon

e.g.
IsRecording = Recording Icon
!IsRecording + HasTimer = Timer Icon
IsPlayable + !IsRecording + !HasTimer = Catch-up Icon

OR should it be the case that timer/recording is a separate independent indicator?

**Comment by ray2301** [comment]
i've tested it - it doesn't show when i only put
`<visible>ListItem.IsRecording</visible>`
but it shows with only
`<visible>ListItem.IsPlayable</visible>`

**Comment by jurialmunkey** [comment]
No I more meant does it make sense for there to be one indicator to show status? Or would it need to two separate indicators because the status can be both at the same time?

I think your comment about pvr simple not having recording options answers my question anyway though and one indictator should be fine.

**Comment by ray2301** [comment]
it doesn't need a separate icon, it's only an indicator that a programme
has catch-up available and you can view it.
catch-up has a limit on how far back you can watch, so if the limit is 3
days - icon will show on every programme for that channel 3 days back in
the guide but not further.

pon, 20. lip 2022. u 10:39 jurialmunkey ***@***.***> napisao
je:

**Comment by ray2301** [comment]
i'm not sure how far the possibilities of that catch-up icon go.
could you put that icon in the search results?

PVR has a search function, but when programmes i search for are listed in
search i never know which ones are available for viewing. if you can
quickly put that icon there too to show, that would be absolutely awesome.

pon, 20. lip 2022. u 10:39 jurialmunkey ***@***.***> napisao
je:

**Comment by krzysztofwinnik** [comment]
Generally catch-up is for past or present, timers for future or present and recording for present programms. 
Timers and recordings could be handlend by a single indicator for sure. Catch-up, on the other hand is a different thing. You could have a timer set that triggers recording and still be able to watch a particular programme from the beginning while it is being recorded. I guess two slots for indicators would be the best solution to solve this problem.
Also, it'd be great to have catch-up indicators enable/disable feature in skin settings.

**Comment by jurialmunkey** [comment]
@ray2301 @krzysztofwinnik Please test linked PR #336 and let me know your thoughts
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/pvr_guide_indicators.zip

**Comment by krzysztofwinnik** [comment]
Thanks @jurialmunkey. I see you used only one indicator - which is fine and probably expected by most users.

Personally, I'd love to see an option in skin settings to enable/disable catchup indicators (same way it possible to toggle video indicators). All my channels have catch-up for ended pvr items and therefore my EPG looks cluttered with all those indicators. Having them hidden (as it was before) would help to make the EPG view clean for me.

**Comment by jurialmunkey** [comment]
> Thanks @jurialmunkey. I see you used only one indicator - which is fine and probably expected by most users.
> 
> Personally, I'd love to see an option in skin settings to enable/disable catchup indicators (same way it possible to toggle video indicators). All my channels have catch-up for ended pvr items and therefore my EPG looks cluttered with all those indicators. Having them hidden (as it was before) would help to make the EPG view clean for me.

Don't worry, the option hasn't been forgotten! I'll be updating the PR with a skin setting before I merge into the main branch. I'm just still deciding on whether I want it to be disabled or enabled by default - and since that will change the setting naming convention I haven't added it yet.

With the current PR I more just wanted to check: (1) that it is actually working as expected; and (2) there's no issues with how I've combined the indicator (I expect it is fine but this is also something that I don't use so I'm not certain!).

**Comment by jurialmunkey** [comment]
@ray2301 Just wondering if you've managed to test these indicator changes in the linked PR?

https://github.com/jurialmunkey/skin.arctic.horizon.2/pull/336
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/pvr_guide_indicators.zip

**Comment by ray2301** [comment]
hey, just tested it and they work fine.
you could make them a little smaller and more on the top right like i did in the example cause sometimes they interfer with the text a little when it's a shorter show. 
![Snimka zaslona 2022-07-19 172148](https://user-images.githubusercontent.com/8508752/179789081-db7cbd31-1bf6-41af-95e1-32b41f592969.jpg)

if you want, i can provide you with my epg file, and an example m3u file which will allow you to see those indicators and see the "epgeventicons". you won't be able to play anything but if you load it with pvr simple, it could help you.

**Comment by ray2301** [comment]
[test PVRsimple.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9142727/test.PVRsimple.zip)
here if you'll want to use it.
this is everything you need to load into the pvr iptv simple client in the settings - channel logos, tv guide and a dummy m3u where all channels have catch-up except "nova tv" so you can use it as a reference that has no icon. the guide should be available for the next 2 days at least.

**Comment by ray2301** [comment]
by the way, if you'll use it maybe you could also add the epgeventicon to the guide while you're on pvr.
![Snimka zaslona 2022-07-19 183734](https://user-images.githubusercontent.com/8508752/179803474-a26062ba-0c27-460f-bcea-75f26ea35fcb.jpg)

**Comment by ray2301** [comment]
oh yes, if you'll try this - the setting for catchup in pvr iptv simple client should be set on disabled because the catchup channels are manually assigned in the m3u as well as how far they are available in the past.
![Snimka zaslona 2022-07-19 183734](https://user-images.githubusercontent.com/8508752/179816985-8a6fb575-7b67-40e5-ab80-a2af075f9079.jpg)

**Comment by jurialmunkey** [comment]
@ray2301 - Thanks. I'm actually able to test the indicator in the skin using the Demo PVR client add-on. 

My main trouble with PVR stuff is that the Demo add-on has fake channels (all channels play Big Buck Bunny) so it's basically like an interactive mock-up. I can see everything in action but it still doesn't give me a sense of those real-world day-to-day usage issues because obviously I'm not watching Big Buck Bunny ten times a day.

**Comment by jurialmunkey** [comment]
Okay I've adjusted the position slightly to avoid the label overlap and added in a setting to disable in indicator options 
`Skin Settings > Details > Customise Indicators > Catch-up`

I'll have a look at adding EPG Event Icon separately as there's some related stuff I want to clean-up with the picture-in-picture view etc.
