### ISSUE TITLE
[Feature] lite skin for low device

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#243]
### Is your feature request related to a problem? Please describe.

The skin is too heavy for weak devices

### Describe the solution you'd like

Release another version for weak devices
Or option to click settings and change
In light mode, the skin will not display all existing functions

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by dm2912** [comment]
the skin is as light as you make it.,

If you turn off background fanart, or set to simple. If you turn off clear-logos. If you set it to only show posters/covers without full details. If you have limited widgets that are pulling from local library, then it will perform just fine on low end devices

if you turn on fanart, want clear logos, have ten widgets on every page pulling from online sources as opposed to local, and want full details along with ratings on the widgets, then yes, it will perform like a turd in a tumble dryer

**Comment by jurialmunkey** [comment]
Yeah I have to agree with dm2912. If you want lite then only enable the "performance" settings in the appearance customisation and limit the number of widgets you use.

Every device is going to be different. Some devices are better at different things, so no single "lite" mode is going to suit every device. The tools are there to customise accordingly (and more options to disabled other parts like ratings and info lists are coming)

**Comment by chcore** [comment]
One way to make things faster, at the cost of some eye candy: delete, resize or replace some of the larger images/overlays. On my reasonably powerful machine there is a noticeable improvement when I replace the file "vignetted.png" with a small transparent PNG file.

**Comment by jurialmunkey** [comment]
> One way to make things faster, at the cost of some eye candy: delete, resize or replace some of the larger images/overlays.
> 
> On my reasonably powerful machine there is a noticeable improvement in smoothness when I replace the file "vignetted.png" with a small transparent PNG file.

Texture optimization will occur when textures are packed into an .xbt file.

The files on github are raw source textures, so are much slower to load (especially larger images such as the vignette) as they are not optimised for Kodi's GUI rendering. It is a requirement of the Kodi repo that textures are provided unpacked (instead they are packed on repo build) hence why I don't supply packed textures.

Users can pack their own textures using TexturePacker https://kodi.wiki/view/TexturePacker -- you will get much better texture performance with a Textures.xbt
