### ISSUE TITLE
[BUG] No Artwork on music boxsets when viewing from widget

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.horizon.2#244]
### Current Behavior

I have music boxsets as one of my music widgets

![screenshot00048](https://user-images.githubusercontent.com/25871666/174670019-6cd46a10-a591-4c94-a14e-539ce80c7b31.png)

However, when you go into the boxset there is no artwork present

![screenshot00046](https://user-images.githubusercontent.com/25871666/174670135-6cf37eae-c0e6-4075-be22-d070548f6503.png)

(neither from folder.jpg cover.jpg or cover1, cover2 etc)

### Expected Behavior

If you go into Boxsets from library view you get coverart

![screenshot00047](https://user-images.githubusercontent.com/25871666/174670226-984ed6b6-0e04-46d3-9201-e1027fab0688.png)

### Steps To Reproduce

Creat boxset widget, click on it :')

### Screenshots and Additional Info

Re: "I have confirmed that this bug does not occur in the default skin" - cannot test in default kodi skin (no widgets), but works as expected in Arctic Horizon Mk1

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Check your widget settings and make sure you set music as content type. Looks like it is opening in videos library instead (which will open in files mode since it doesn't match).

**Comment by dm2912** [comment]
doh
