### ISSUE TITLE
[Feature] Vertical home menu option

### ISSUE THREAD

**Issue by chcore** [jurialmunkey/skin.arctic.horizon.2#247]
### Is your feature request related to a problem? Please describe.

I think this is shaping up to be your best skin ever (and thus the best Kodi skin ever), but am really finding myself wishing the menu could be laid out vertically like I had it in Arctic Zephyr.

### Describe the solution you'd like

A vertical home menu similar to Arctic Zephyr.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
*Almost* ready... Sorting out some navigation issues and other small details but it hasn't been forgotten!


![screenshot00162](https://user-images.githubusercontent.com/4618719/210750332-61926908-7b86-47d9-add5-849fa9d9e279.jpg)

**Comment by Raitsa** [comment]
Hopefully this thread gets updated when this feature is released ;-)
