### ISSUE TITLE
[Feature] Moving the Clearlogo and Resizing it.

### ISSUE THREAD

**Issue by ChiTianJoPajie** [jurialmunkey/skin.arctic.horizon.2#248]
### Is your feature request related to a problem? Please describe.

I would like to suggest on moving the clear logo and resize it only for the fullscreen widget. Thank you.

### Describe the solution you'd like

Resize and move the clearlogo in left center side of the widget above the Film Description.

### Screenshots and Additional Info

![Homecoming](https://user-images.githubusercontent.com/107910433/174730636-6d0cb3b9-74aa-4e9e-806a-5422e533e6c9.jpg)
![Far From Home](https://user-images.githubusercontent.com/107910433/174730654-7d0daebf-e961-4d60-acf0-5d6e0fd6ddc3.jpg)
![No Way Home](https://user-images.githubusercontent.com/107910433/174730672-fb74f84c-8a43-4153-ad32-405e3ac83452.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
As discussed on the forums, elements must be consistently sized throughout the skin to ensure a consistent design language. I won't be introducing inconsistent sizing in different locations.
