### ISSUE TITLE
[BUG] Vertical list view / Vertical combined list view don`t have in progress indicator

### ISSUE THREAD

**Issue by ycodryn** [jurialmunkey/skin.arctic.horizon.2#249]
### Current Behavior

Setting view type to list and going to show folder, I can`t see the in progress view indicator.

### Expected Behavior

When half watching episodes, each file shoud have in progress icon on it.

### Steps To Reproduce

Switch view type on list/combined list, watch some minutes something, exit, go back to list.

### Screenshots and Additional Info

https://i.ibb.co/WPh0X2d/IMG-20220621-094342.jpg

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You're in files view there. Only library views have indicators.

**Comment by ycodryn** [comment]
I`m always is files and if I remember corectly (my kid is giving me headaches :)) ) in zephyr I had indicators.
But if you look at this image, https://i.ibb.co/BzQwtFD/IMG-20220621-150345.jpg only landscape combined and landscape list are not giving me indicators. On others I have indicators even if I`m in files view.
