### ISSUE TITLE
[Bug] [Widgets] Genre icons not displayed

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#25]
Genres widget is not showing icons for both Movies and TV Shows (see below screenshot).
![IMG20220605150354](https://user-images.githubusercontent.com/65297828/172046080-f3d06866-6492-4cfc-8da0-2d2be0ac2800.jpg)

**Comment by richard-lee-863** [comment]
Was also an issue in Arctic Horizon i believe. Would really love a fix for this too, currently have to use another addon for the Genres widgets to get the nice icons to show up, which defeats the purpose of the awesome functionality of TMDBHelper a bit!

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Thank you for adding this feature, but now another issue happened. The "Genres" icons are working fine now in Square widgets, but the Channel logos from my Last Played Channels Square widget have vanished. Prior to this update they were fine. See screenshots below:

Genres widget:
![IMG20220625104251](https://user-images.githubusercontent.com/65297828/175759373-68404006-2617-4130-813b-53ce88459908.jpg)

Last played channels widget before the update:
![IMG20220618233950](https://user-images.githubusercontent.com/65297828/175759390-a1498ae5-214b-4bf8-81ab-3fa1f39940e8.jpg)

Last played channels widget now after the update:
![IMG20220625104311](https://user-images.githubusercontent.com/65297828/175759413-74b0399b-7536-4f01-bdd6-4d8d6e9c68c4.jpg)

Could you please look into the issue?

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Anyways it's not much of a big issue, as I found the landscape view for last played channels widget is even better as it shows the currently playing program on the channels. Thanks a lot for adding this feature @jurialmunkey !

**Comment by ShibajiCh** [comment]
Thank you!
