### ISSUE TITLE
[Feature] Missing:  Fanart background for autoscrolling widgets (like AH1)

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/skin.arctic.horizon.2#250]
### Is your feature request related to a problem? Please describe.

On menu pages where there is no fullscreen widget and the top widget is set to autoscroll (or even if not), fanart is not being used as the background while focus is on the menu, the background is just the default blur.  The background does not change to fanart until focus is moved onto the widget row.

### Describe the solution you'd like

I'm assuming you intend to implement this and just haven't gotten to it yet, but I think it makes sense for AH2 to work the same way AH1 does in this situation.  The background should use the fanart of the far left widget item even while focus is on the menu.  And the background should change with each widget item if autoscrolling is enabled.  

### Screenshots and Additional Info

Hopefully I've explained this clearly.  If not, please ask for more details and screenshots.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Man, this one is really killing me. 

Haven't figured out a reliable way to identify the ID for the first widget in the group. The way it was done in AH1 was very much an unreliable hack. 

Just commenting to let you know that I definitely haven't abandoned this idea and it's just that I haven't found a good solution yet! I really really want this to work but keeping hitting dead-ends with skinning engine limitations.

**Comment by eengert** [comment]
Thanks for the update.  Hopefully you'll be able to find a solution eventually, but it's not the end of the world if you can't.  Thanks for your effort.
