### ISSUE TITLE
[BUG] View type when using Library Node Editor

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/skin.arctic.horizon.2#252]
### Current Behavior

I was not sure if I had to report it here or for TMDbH, but  Here is my issue:
I'm using LNE to create my custom home menus. Everything is OK, except when I try to create a node for ''Trending Movies'' from TMDbH item. 
Skin variable only shows me ''none'' as view type. So all movies from Trending menu  have square, landscape or tag as view type choices.
(I did the same with a personal trakt movie list and there is no issues.)

### Expected Behavior

I dont know if it is a ''real'' issue or if it just cant be done 😝

(Note that I tried to make sure that the same ''case'' is not reported, but my english is not as good as my french, so sorry if it was reported before)

### Steps To Reproduce

1. Create this node with LNE: `<path>plugin://plugin.video.themoviedb.helper/?info=trending_week&amp;tmdb_type=movie/</path>`  (**view type = none)**
2. When I create this node (from a personal trakt list): `<path>plugin://plugin.video.themoviedb.helper/?info=trakt_userlist&amp;list_name=Top+50+au+Box-Office&amp;list_slug=top-50-au-box-office&amp;user_slug=alkodique&amp;plugin_category=Top+50+au+Box-Office&amp;owner=true/</path>` (**view type = movie)**

### Screenshots and Additional Info

![Screenshot_20220621-172314](https://user-images.githubusercontent.com/49578130/174899708-8c06349c-83f5-472d-b76e-f34c40b5c105.png)
![Screenshot_20220621-172303](https://user-images.githubusercontent.com/49578130/174899713-8a301697-7180-4980-acd4-9743152cd988.png)
![Screenshot_20220621-172253](https://user-images.githubusercontent.com/49578130/174899716-12997555-ad57-4bd7-b959-b3375fb2e076.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It's a bug in LNE.

The problem is that `/` slash at the end of the plugin url shouldn't be there (it shouldn't be on any of them).

After adding the path to the node, if you then add the path again by clicking on it then LNE will set the correct path without the slash at the end (FYI - manually editing doesn't appear to work properly, so you just need to re-add a path).

**Comment by alKODIque** [comment]
Thanks!
It worked!!
And now I know why sometimes the node from other addons just didnt work 👍👍
