### ISSUE TITLE
[Feature] Adding the Hebrew language

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#259]
### Is your feature request related to a problem? Please describe.

There was no Hebrew

### Describe the solution you'd like

I translated the language
Please upload it

### Screenshots and Additional Info

[resource.language.he_il.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8957226/resource.language.he_il.zip)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Thanks! This file looks much better! Added.
