### ISSUE TITLE
Clear logo issues

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#26]
Clear logo is sometimes appearing and sometimes not for various movies and TV Shows. For example, for the movie "Interceptor" the clear logo is appearing for a second and then changing back to normal text (see below screenshots).
![IMG20220605152131](https://user-images.githubusercontent.com/65297828/172046116-0069c531-e5a7-4049-ab56-17e9ac5fa4fe.jpg)
![IMG20220605150835](https://user-images.githubusercontent.com/65297828/172046121-3c505815-e2ee-4349-8bd2-6ca97e8c537b.jpg)

Clear logos are also taking time to load everytime while moving through the widget items, i.e. first the normal text is appearing and then slowly the clear logo is appearing.

Also, in multiple profiles the clear logos are not always appearing for the second profile.

**Comment by jurialmunkey** [comment]
Do these items have clearlogos in when you go to Video Info > Settings Cog > Artwork ? If they don't then the delay is because TMDbHelper has to look them up manually because your plugin source hasn't set them to the item.

**Comment by ShibajiCh** [comment]
> Do these items have clearlogos in when you go to Video Info > Settings Cog > Artwork ? If they don't then the delay is because TMDbHelper has to look them up manually because your plugin source hasn't set them to the item.

Hi @jurialmunkey,

Yes, this issue is happening for most of the items and they all have the clear logos already downloaded locally. The logos are appearing and disappearing randomly for various items. I found some other users also posted similar issues, so I guess it's not an isolated issue for me. What I noticed is that the Blur option works much better than the Fanart option with clear logos. I have 2 profiles in Kodi and if I set Fanart for both of them then the second profile usually doesn't show any clear logos. However, Blur option works much better. However, I personally prefer the Fanart option. Also, I tried clearing the image caches for both my profiles but it didn't make any difference. Please advise.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

I guess you were correct. I'm not able to see any clear logos under the artwork window. However, I can see them in Manage artwork -> Choose artwork window. I'm not sure what's happening. See screenshots below.
![IMG20220606193540](https://user-images.githubusercontent.com/65297828/172178118-0b80b70c-6e4c-4b8e-ae84-14e11a8e73be.jpg)
![IMG20220606193608](https://user-images.githubusercontent.com/65297828/172178138-96219a18-c8ad-4171-8a4c-e55d96d33d94.jpg)

What might be causing this issue. Please advise. I'm using TMDB Helper for almost everything, including the widgets. Please see my TMDB Helper settings below.
![IMG_20220606_194104](https://user-images.githubusercontent.com/65297828/172178394-69ed7e20-262d-481e-b7f9-e4c15e794a4e.jpg)
![IMG20220606194029](https://user-images.githubusercontent.com/65297828/172178427-0f23417e-9984-4487-868d-9a5e564c4160.jpg)

Please advise.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

I think TMDB Helper is not treating the clear logos as Service monitor artwork. What do you think?

**Comment by jurialmunkey** [comment]
Use fanart.tv for plugin/widget artwork in fanart.tv settings. That will preload the artwork into the listitems rather than relying on the servicemonitor alone.

There will still be a resize delay when it crops but the logo should appear immediately (once it downloads of course).

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey, even after turning on the 2 above mentioned settings, I'm still facing the same issue. For example, for the movie Interceptor the clear logo is appearing for a second and then disappearing immediately. This is happening for many of the items. See screenshots below. Please advise.
![IMG_20220606_210901](https://user-images.githubusercontent.com/65297828/172195054-dabad8c2-fea9-4b26-b0f4-80d45df0fa2b.jpg)
![IMG20220606210542](https://user-images.githubusercontent.com/65297828/172195088-3a3f1a2e-bf08-4804-8993-067bb58adba9.jpg)
![IMG20220606193608](https://user-images.githubusercontent.com/65297828/172195157-7fc4096d-7e3c-4ed3-874e-7538322af989.jpg)
![IMG20220606210553](https://user-images.githubusercontent.com/65297828/172195191-508d85cc-be46-4eb1-bfae-1222d36becbb.jpg)

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,
I think I found the cause of the issue. Certain clear logos are not working. For example, the movie Interceptor has 2 logos from TMDB. One with the Netflix film logo and another without it. The clear logo with the Netflix logo is working fine but the one without the Netflix logo is not working. I guess you can do some R&D and find out the reason of what is causing these logos to not work with this skin. Please check and advise.

**Comment by ShibajiCh** [comment]
Some other movies/tv showd where I'm facing this issue with Clear logos are:

Movies-
Moana, Ford v Ferrari, the dry, the northman, father Stu,  the valet, etc.

Tv shows-
The boys, shining girls, moon knight, bel-air, prison break, etc.

**Comment by dm2912** [comment]
Personally I think clearlogos are always going to be hit and miss because fanart.tv and tmdb arent particularly strict over sizes, dimensions 

I tested clearlogos for a while and interestingly, everything music related was absolutely perfect, because AudioDB which is my source for music are very strict over both dimensions and size. So there is complete concistency. 

Film and TV, that consistency isnt there

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

I've now resolved this issue. The culprit was one setting in TMDB Helper which was "Prefer artwork from TMDB first if available". I've now turned off that setting and the clear logos are being downloaded from Fanart.tv by default. The clear logos from Fanart.tv are working flawlessly. I guess TMDB has issues with their clear logos which was causing the problem. Changing that particular setting and keeping only service monitor artwork setting as On is working perfectly for me. My current settings are as follows:
![IMG_20220607_130902](https://user-images.githubusercontent.com/65297828/172324904-80db0f2c-4429-4abb-8b2b-7e51fdea2a71.jpg)

Thank you so much for all your help! 🙂
You can close this ticket now if you want.

**Comment by jurialmunkey** [comment]
Hmm interesting. I'm not able to reproduce even with those settings but glad you found the cause!

Either way, will be a TMDbHelper issue rather than a Skin issue. I'll have a think about what might be the reason for it

**Comment by ShibajiCh** [comment]
> Hmm interesting. I'm not able to reproduce even with those settings but glad you found the cause!
> 
> Either way, will be a TMDbHelper issue rather than a Skin issue. I'll have a think about what might be the reason for it

Fine @jurialmunkey. Thank you!
