### ISSUE TITLE
[Bug/Question] Are empty ratings supposed to be shown?

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.horizon.2#261]
### Current Behavior

![image](https://user-images.githubusercontent.com/62456796/175142703-4acc33cd-ac0e-476f-9e18-8fb364e14bb2.png)
- Ratings with no information in them

### Expected Behavior

![image](https://user-images.githubusercontent.com/62456796/175141326-6b18ed20-70a6-4875-924a-1b2f4d3fdac6.png)
- I was too lazy to photoshop, sorry.
- They should be not shown if they don't have any information in them. 

### Steps To Reproduce

1. Update the skin to v0.2.0
3. Download TheMovieDb Helper v4.8.18
2. Go to TMDB Helper
3. Go to Movies
4. Go to Popular
5. Find a movie that does not have all the ratings like example: Dragon Ball Super: Super Hero
6. Notice that ratings are there but have nothing in them. 

### Screenshots and Additional Info

![image](https://user-images.githubusercontent.com/62456796/175142320-846deaef-35ed-4831-9463-ddb11f214737.png)
I think ratings should not be shown if there is no information in them. 

### Question
Are empty ratings supposed to be shown? (btw, I love the extra ratings you added to your skin)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Goldenfreddy0703** [comment]
Hey so turns out your adding an option soon to hide empty ratings so im gonna close this. 😅

**Comment by jurialmunkey** [comment]
> Hey so turns out your adding an option soon to hide empty ratings so im gonna close this. 😅

Yep should be in 0.2.1 in the ratings config dialog.

Some people prefer placeholders so they aren't jumping around and other people like them auto hidden.

**Comment by Goldenfreddy0703** [comment]
> Yep should be in 0.2.1 in the ratings config dialog.
> 
> Some people prefer placeholders so they aren't jumping around and other people like them auto hidden.

Ahh makes sense. Thank you very much and best skin ever.
