### ISSUE TITLE
[Feature] Add 'Select player' or just 'Player' to the info windows

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon.2#262]
### Is your feature request related to a problem? Please describe.

In the seasons view, you have the option to just select a season without really going 'into' it to see its episodes, the episodes are shown above it. The problem with this view is that you cannot use the context button on episodes. So, if you use the TMDBHelper addon with a default player and you want to use another one, you are forced to go into the season and then search for the episode again. 

### Describe the solution you'd like

Would it be possible to add a 'Select player' or 'Player' button to the info view as this is the only screen you can open for an episode in this view?

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The context issue in the skinning engine is solved in Nexus so I'm not bothering to add any workarounds for the combined views.

I think this will also be solved when feature #206 is added which will allow customisation of video info dialog buttons.
