### ISSUE TITLE
[Feature] Recommendations window for Music

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.horizon.2#265]
### Is your feature request related to a problem? Please describe.

Currently only videos have a proper recommendations window

### Describe the solution you'd like

Music should also have a recommendations window

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by rapteev** [comment]
This would be great.
Thank you for your fabulous work on this skin.
