### ISSUE TITLE
[BUG] Subtitle download selection menu stops responding

### ISSUE THREAD

**Issue by chcore** [jurialmunkey/skin.arctic.horizon.2#266]
### Current Behavior

When scrolling the list of subtitles available for download in the OpenSubtitles.org addon, the dialogue appears to eventually stop responding to input. Hitting "back" cancels out of the dialogue and I can re-open it again.

### Expected Behavior

One should be able to freely scroll through the list of subtitles to download

### Steps To Reproduce

1. Start playing some content
2. Use the OpenSubtitles.org addon to search for subtitles
3. Scroll down the list of results and notice it eventually stops responding to input (in my case, after scrolling less than 10 results)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I don't think this is a skin issue. I cannot reproduce. I can't even think of anything skin specific that would cause this behaviour. Sounds like a Kodi bug.
