### ISSUE TITLE
[Feature] Black Bars Remover

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#268]
### Is your feature request related to a problem? Please describe.

There are lots of movies that are not IMAX

### Describe the solution you'd like

A button that will allow you to reduce the black bar
A button that will be in the player itself
If it is not possible to do so, then there is a plugin that can be downloaded
https://github.com/milaq/kodi_addon_blackbarsremover
The button is still necessary

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can already do this by changing zoom amount by pressing z on keyboard or using the video settings menu from the osd

**Comment by jurialmunkey** [comment]
Zoom doesn't blur the sides. It just zooms in.

Can't add support for things not in official repo.

**Comment by koby455** [comment]
> Zoom doesn't blur the sides. It just zooms in.
> 
> Can't add support for things not in official repo.

But, that's what's happening to me
It always happens
