### ISSUE TITLE
[BUG] Hebrew text out of position

### ISSUE THREAD

**Issue by Talgold3** [jurialmunkey/skin.arctic.horizon.2#270]
### Current Behavior

When switching the language to Hebrew some text is out of its correct position.
I've noticed the problem on the movie page and the home screen.

### Expected Behavior

The text should be in place.

### Steps To Reproduce

1. Open Kodi
2. choose movie
3. enter the information page
4. text if out of place

### Screenshots and Additional Info

[https://imgur.com/IElNHGL](url)

[https://imgur.com/undefined](url)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Nothing I can do about it.

It's a kodi bug with auto width buttons and rtl languages. It needs to be fix in the skinning engine.
