### ISSUE TITLE
[Feature] Submenu style as standard viewtype

### ISSUE THREAD

**Issue by ray2301** [jurialmunkey/skin.arctic.horizon.2#271]
### Is your feature request related to a problem? Please describe.

In AZ there was that "icon" view i remember. I used it a lot on widgets. 
I see that "icon" view on [some views](https://gcdnb.pbrd.co/images/d0rhZv6qKxcz.jpg) but i [cannot select it by myself](https://pasteboard.co/2ndGS7pLCV3Y.jpg) or use it for widgets.

### Describe the solution you'd like

I'd like that icon/tag view on widgets and to be able to use it as a view globally (or at least for addons).

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It won't really work well as a widget due to height and there's no good way to have a multi-row fixed list currently.

In terms of missing from views, is it only playlists?

**Comment by jurialmunkey** [comment]
Your screenshot looks like you've modified the skin viewtypes as Tags is perfectly selectable for playlists content type using default unmodified skin

![Honeyview_screenshot00133](https://user-images.githubusercontent.com/4618719/175507858-97f8f4b7-cd52-4239-abee-20edd80c68dc.jpg)

**Comment by ray2301** [comment]
i have no problem with library views. i just can't explain this view properly :) 
i'm talking about the widget view with small icon landscape like the submenu widget looks like.

<a href='https://postimg.cc/SjpQTPxD' target='_blank'><img src='https://i.postimg.cc/jqDW5000/Snimka-zaslona-2022-06-26-042936.jpg' border='0' alt='Snimka-zaslona-2022-06-26-042936'/></a>

**Comment by ray2301** [comment]
if i want to put genres as a widget on my homescreen, there is no way it can display genre icons. if it's a landscape widget - no genre icons. if it's square - no genre icons. this small icon widget would be great for that.

**Comment by ray2301** [comment]
the second photo doesn't show "tags" because the tag view was already selected :) 
but this is what i was thinking about. the small icon view.

**Comment by jurialmunkey** [comment]
> i have no problem with library views. i just can't explain this view properly :) i'm talking about the widget view with small icon landscape like the submenu widget looks like.
> 

Ah I completely misunderstood you! For submenu style as a normal widget, this will be added in feature #91 

> if i want to put genres as a widget on my homescreen, there is no way it can display genre icons. if it's a landscape widget - no genre icons. if it's square - no genre icons. this small icon widget would be great for that.

This was fixed in 0.2.5 for #25 yesterday. Square should now properly display genre/studio etc. icons.

Landscape feels like a bit of a weird aspect for genres etc. so I didn't add it there. Only added to square but could expand to other styles if it is really wanted (I assume you more mentioned landscape as an example rather than a specific request).

**Comment by ray2301** [comment]
i can't wait for #91, that will look perfect on the homescreen for displaying things like menus, genres, studios.
most of the regular views display "bigger" icons or landscapes, i don't think it would be bad to add smaller types.
