### ISSUE TITLE
[Feature] Disable tmdb lookups PVR

### ISSUE THREAD

**Issue by Tee77** [jurialmunkey/skin.arctic.horizon.2#274]
### Is your feature request related to a problem? Please describe.

Not that I don’t appreciate artwork/logos that tmdb helper provides in the pvr guide, but it can only do so much in terms of matching epg listings. Would it be possible to provide an option to disable tmdb helper altogether in the pvr guide? (no logos/ artwork/ ratings). You mentioned the possibility of doing this when we discussed pvr artwork a while back. It would give a much more consistent experience for me. Cheers. 

### Describe the solution you'd like

disable tmdb helper altogether in the pvr guide? No logos/ artwork/ ratings. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
v0.2.33 adds an option to disable pvr lookups 
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.2.33

`Skin Settings > Details > TMDbHelper look-ups for PVR windows`

You will need to install v4.10.5 or higher of TMDbHelper

**Comment by ffwell** [comment]
> v0.2.33 adds an option to disable pvr lookups https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.2.33
> 
> `Skin Settings > Details > TMDbHelper look-ups for PVR windows`
> 
> You will need to install v4.10.5 or higher of TMDbHelper

so,v4.10.5,Not released yet haha

**Comment by jurialmunkey** [comment]
> > v0.2.33 adds an option to disable pvr lookups https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.2.33
> > `Skin Settings > Details > TMDbHelper look-ups for PVR windows`
> > You will need to install v4.10.5 or higher of TMDbHelper
> 
> so,v4.10.5,Not released yet haha

@ffwell - I think you will find it is released in my repo:
https://github.com/jurialmunkey/repository.jurialmunkey/blob/master/matrix/zips/plugin.video.themoviedb.helper/plugin.video.themoviedb.helper-4.10.5.zip

OR you can get it from the github main branch zip.
