### ISSUE TITLE
[Feature] Filtering Widget Content

### ISSUE THREAD

**Issue by lolgc** [jurialmunkey/skin.arctic.horizon.2#275]
### Is your feature request related to a problem? Please describe.

Hello ~

I was wondering, whether it would be possible to include a filtering option to the widget settings.
Currently, it is possible to only sort widgets by some criterea (title, date, etc).
Filtering could enable to allow for more specific widget content:

I use the "Next Episodes" Widget from "Skin Helper Widgets". While it works fine, it displays the next/in progress episodes of all my sources containing TV Shows. However, I'd like to seperate them by source (local, amazon lib. export) or/and by genre (western, asian content), etc. (Unfortunately, this cannot be done using Smart Playlists, because they do not support the display of "next episodes")

Thus, I wanted to ask you, if something like this is possible and/or even planned for AH2 :)

### Describe the solution you'd like

In the widget settings dialogue under "sort" could be another list item, that allows the user to enable and set specific filter options.
I fear it may require an extra dialogue to set the "conditions". 

### Screenshots and Additional Info

Thanks again for your hard work and the awesome skin :)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Not possible. You would need to ask the addon author for these features.
