### ISSUE TITLE
[Feature] Trailer while moving on the poster

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#276]
### Is your feature request related to a problem? Please describe.

Need to go into details to Watch a trailer

### Describe the solution you'd like

Similar to Netflix, when there will be a widget
When scrolling over the poster

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This would cause your widgets to constantly reload. Every time a video finishes playing, kodi reloads all containers. You would constantly lose your place.
