### ISSUE TITLE
[Feature] Icon On The Poster 

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#277]
### Is your feature request related to a problem? Please describe.

It is not possible to know from which network the film or series came

### Describe the solution you'd like

Add an icon option next to any movie or series
Disney / HBO / HULU / AMAZON
So we can know where it came from

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
This will be a nice feature my opinion the network logo if it fits will look good right after the last rating (Example)And this pic right after the IMDb rating![image](https://user-images.githubusercontent.com/49699869/175781201-4a623596-e02d-4fbf-9078-6f7992f0f284.jpeg)

**Comment by jurialmunkey** [comment]
You can already enable codec/studio info for full expanded widgets in the skin settings.

**Comment by jurialmunkey** [comment]
Make sure you are using the latest version of the skin before making requests please.

**Comment by xyzfre** [comment]
My apologies for that @jurialmunkey Next time I'll make sure I check first

**Comment by koby455** [comment]
> Make sure you are using the latest version of the skin before making requests please.

I'm on the latest version - and I do not see the icon
I meant it - that it would appear in small print next to the poster - so that I would not have to look for it

**Comment by jurialmunkey** [comment]
The studio icon is in the bottom right of the screenshot.

If it was on every poster it would look bad.

**Comment by koby455** [comment]
> The studio icon is in the bottom right of the screenshot.
> 
> If it was on every poster it would look bad.

My intention was that it would not write the name of the production "Marvel " but the name of the network that it is broadcast "Disney Plus" for example uploaded the movie Doctor Strange

**Comment by jurialmunkey** [comment]
> > The studio icon is in the bottom right of the screenshot.
> > If it was on every poster it would look bad.
> 
> My intention was that it would not write the name of the production "Marvel " but the name of the network that it is broadcast "Disney Plus" for example uploaded the movie Doctor Strange

This data does not exist on TMDb. I can't make data exist that doesn't exist
https://www.themoviedb.org/movie/453395-doctor-strange-in-the-multiverse-of-madness

Watch providers are displayed on the bottom left when the data is available. I cannot help that the TMDb website does not have this data for this movie or that it does not supply watch providers for your region.
