### ISSUE TITLE
[Feature] Button for trailer

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#278]
### Is your feature request related to a problem? Please describe.

A quick solution for watching the trailer

### Describe the solution you'd like

Button on the home page below the poster
That will allow you to watch the movie trailer without going into about
And on half screen or full screen to choose from

### Screenshots and Additional Info

![image](https://user-images.githubusercontent.com/102416233/175783895-34cc0f98-81f0-4ae8-9ed0-873825255d19.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry, not really possible with the way the Kodi skinning engine manages grouplist alignment.

Adding buttons will mess up the widget positioning when scrolling back up. It's the same reason why in AH1 the info would have a different position depending on scroll direction. I don't want to introduce that issue again.
