### ISSUE TITLE
[BUG] Music Lyrics not displayed correctly when using Skin Default colours

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#279]
### Current Behavior

When using Skin Default colours only the current line of lyrics is displayed. If using Dark colour scheme the display is correct - more lyrics are displayed with the current line highlighted. See screenshots

### Expected Behavior

As displayed when using the Dark colour scheme

### Steps To Reproduce

1. Go to Music
2. Select Song
3. Bring up lyrics (I have a remote button mapped to do this)

### Screenshots and Additional Info

![screenshot00003](https://user-images.githubusercontent.com/67786207/175806517-ee03a6d5-a651-4d2d-8d30-aba3916922a5.png)
![screenshot00002](https://user-images.githubusercontent.com/67786207/175806520-76b907e6-734a-400b-9bc9-b1ebfe55ca30.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by berkhornet** [comment]
Hi

I manually edited keyboard.xml and added: <t>RunScript("script.cu.lrclyrics")</t>

I mapped a spare key on my Harmony remote to "t"

Regards

**Comment by ray2301** [comment]
![Uploading Snimka zaslona 2022-07-08 185620.jpg…]()
+1 for this being more pleasant


> i tried manually doing..
> 
> `<keymap><musicosd><keyboard><key id="236">showlyrics</key></keyboard></musicosd></keymap>`
> 
> but thats just toggling the coverart/buttons :S
> 
> I also tried the more inventive
> 
> ` <visualisation><keyboard><key id="236">RunScript(script.cu.lrclyrics)</key></keyboard></visualisation>`
> 
> but to no avail

i used keymap editor to map it to the * button when in visualization fullscreen.
i use a MCE remote so it looks like this:
<visualisation>
<keyboard>
<key id="1568920">runscript(script.cu.lrclyrics)</key>
</keyboard>
</visualisation>

there are more "keys" under the visualisation category but that's the one for the lyrics.

**Comment by dm2912** [comment]
> +1 for this being more pleasant ![Snimka zaslona 2022-07-08 185620](https://user-images.githubusercontent.com/8508752/178038212-94ad6dce-38f2-4421-a47d-9b9b81ebcecb.jpg)
> 
> @dm2912
> 
> > i tried manually doing..
> > `<keymap><musicosd><keyboard><key id="236">showlyrics</key></keyboard></musicosd></keymap>`
> > but thats just toggling the coverart/buttons :S
> > I also tried the more inventive
> > ` <visualisation><keyboard><key id="236">RunScript(script.cu.lrclyrics)</key></keyboard></visualisation>`
> > but to no avail
> 
> i used keymap editor to map it to the * button when in visualization fullscreen. i use a MCE remote so it looks like this:
> 
> ```
> <visualisation>
> <keyboard>
> <key id="1568920">runscript(script.cu.lrclyrics)</key>
> </keyboard>
> </visualisation>
> ```
> 
> there are more "keys" under the visualisation category but that's the one for the lyrics. keymap editor sorted it for me nicely in categories so i just add a key under that category. you don't have to create a new `<visualisation><keyboard>` if it already exists. just add your key with the other keys for that category like this:
> 
> ```
> <visualisation>
> <keyboard>
> <key id="1568920">runscript(script.cu.lrclyrics)</key>
> <key id="61511">runplugin(plugin://plugin.audio.pandoki/?rate=up)</key>
> <key id="61508">runplugin(plugin://plugin.audio.pandoki/?rate=down)</key>
> </keyboard>
> </visualisation>
> ```
> 
> if nothing is interfearing with the keymap you are trying to use, it should work when you add it like this. if it doesn't work try another shortcut. also, i don't think you can use the same shortcut you already use globally. maybe that's the problem. if you already mapped "X" to "stop" for example as a global action, it cannot be a visualization shortcut because it's already used for stop globaly in all windows. that's my logic at least. i haven't tried to do it in reality.

Thanks for this. in seeing it worked for you using pretty the same thing i did gave me pause to look at it more closely, and it was simply a matter of **R**un**S**cript v **r**un**s**cript

I originally got that bit of code from kodi forums, so stuck with the upper case.. was my mistake, especially on a linux machine, case is everything :')

so for me

```<keymap>
    <fullscreenvideo><keyboard><key id="236">showsubtitles</key></keyboard></fullscreenvideo>
    <visualisation><keyboard><key id="236">runscript("script.cu.lrclyrics")</key></keyboard></visualisation>
</keymap>```

now happily brings up subtitles in video, lyrics in music
