### ISSUE TITLE
[Feature] Home page search results does not show title, year on selection

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon.2#280]
### Is your feature request related to a problem? Please describe.

Search feature in home page displays results without title, so it is difficult to find the one I am looking for.

### Describe the solution you'd like

When I select a search result (poster), it should display name and year on the top of the poster so that I can pick the one I intend to find. Please see screen record for details- https://imgur.com/a/hhOXNiA

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Expand information in search menu customisation will display plot title and ratings.
