### ISSUE TITLE
[BUG] Expanded Info not displayed correctly when using two widgets

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#281]
### Current Behavior

When using two widgets on a home page menu item, and using expanded info = plot for the first widget, the plot information is placed incorrectly, behind the second row of widgets (see Screenshot)

### Expected Behavior

Plot information to be visible

### Steps To Reproduce

Add two widgets to a home page menu item, using expanded info = plot.

### Screenshots and Additional Info

![screenshot00001](https://user-images.githubusercontent.com/67786207/175815171-36d8969a-5e2b-4513-9053-a88dda8b1029.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Expanded info doesn't work with button viewtype (not possible due to skinning engine limitations)

I need to add something to disable adding it for button style

**Comment by berkhornet** [comment]
@jurialmunkey - many thanks for reply

**Comment by eengert** [comment]
How about creating a "Title Only" option for expanded info on apps/button styles?  I opened a separate issue with this request, but based on your reply to this issue, I thought it might be relevant here.  I can see why you don't want to display the plot area for apps/button styles (unless you are able to change the spacing and display the plot higher up).  But could you just display the title above the widget row at least?

**Comment by jurialmunkey** [comment]
>  I can see why you don't want to display the plot area for apps/button styles (unless you are able to change the spacing and display the plot higher up). But could you just display the title above the widget row at least?

It is a technical limitation of the skinning engine not a specific design choice. And repositioning with another slide animation will make the animations worse and slow down the skin. This is one of the many problems that widgets with different heights cause.
