### ISSUE TITLE
[Feature] Delay time for big poster view

### ISSUE THREAD

**Issue by Blackysbd** [jurialmunkey/skin.arctic.horizon.2#282]
### Is your feature request related to a problem? Please describe.

Info appears to quickly

### Describe the solution you'd like

When looking through a movie set with big poster view, the info for first movie appears too quickly. Would it be possible to add a delay time in order to browse the set, particularly apparent on large sets such as James Bond movies. If you stop even for a sec info comes up.

![screenshot00001](https://user-images.githubusercontent.com/53400821/175815340-15f1e751-2c19-48ec-b14a-77238c19847a.png)
.

### Screenshots and Additional Info

What I'd like to see for a few extra secs
![screenshot00000](https://user-images.githubusercontent.com/53400821/175815349-47254418-24c5-4678-bd9e-e036321da19e.png)
.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
A custom user setting is not really possible due to the way Kodi handles $INFO[] in attributes but I agree the time is too fast so I've bumped it up from 1 second to a 3 second idle delay.
