### ISSUE TITLE
[Feature] Button style with full image

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/skin.arctic.horizon.2#284]
### Is your feature request related to a problem? Please describe.

Tiny thumbnail images are difficult to see on Button widget style

### Describe the solution you'd like

I'd like a style which uses the Button size but acts like Big Landscape where the image fills the entire button and there is no title text.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
So basically like the Google/Android TV apps widget style? Is that what you mean?

![](https://www.tcl.com/usca/content/dam/tcl/products/home-theater/3-series/s330/S330_740x480-teaser.png)
