### ISSUE TITLE
[Feature] Detect and handle Trakt VIP API features with fallbacks

### ISSUE THREAD

**Issue by francis-robert** [jurialmunkey/skin.arctic.horizon.2#287]
### Is your feature request related to a problem? Please describe.

Several features in AH2 rely on the Trakt API which require a VIP/premium account.

For example, Trakt requires a VIP account to be able to query for IMDB and RT ratings: 

Certain list features as well would require a paid account to access.

### Describe the solution you'd like

I believe the simplest solution would be a toggleable feature in the Skin settings that allows you to hide VIP-related features from the UI rather than having the placeholders. This would require checking for an additional property as to whether the Trakt user is a premium user or not when requesting user data via the API.

Although I'm unfamiliar with Trakt's API, I suspect it may be possible as part of the oauth response or even asserting on a `426` status code: https://trakt.docs.apiary.io/#introduction/status-codes. There may be other means of identifying whether the user has premium.

As a fallback, I think it would be great if users had the option of inputting their imdb/RT API credentials (oauth, u/p, API key, etc.) any rely on those APIs if the user doesn't have Trakt premium and its associated features. Admittedly this is definitely more involved and requires maintaining an additional API, however, it shouldn't be much if we're only talking about the ratings surface, as well as being consumed as a secondary/fallback solution.

### Screenshots and Additional Info

![image](https://user-images.githubusercontent.com/87673558/175834821-188fa9c5-fffb-4378-829e-a0bd9e557683.png)
<img width="582" alt="image" src="https://user-images.githubusercontent.com/87673558/175835255-5330be8f-9f0b-4659-ac17-f540abe1af45.png">

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by drinfernoo** [comment]
Those ratings are provided by TMDbHelper, which leverages metadata provided by OMDB, when provided with an API key.

I didn't even know Trakt *could* provide those 😅

**Comment by francis-robert** [comment]
Thanks for the clarification @drinfernoo . This might be a good point to add to a wiki or a Readme somewhere to avoid it being asked again in the future 😅

**Comment by jurialmunkey** [comment]
TMDbHelper does not support any VIP trakt functions (and so AH2 does not either). Some Trakt functions require authorisation with a Trakt account but never a VIP account.

TMDbHelper retrieves additional metadata from TMDb, Trakt, OMDb, and FanartTV. 

- OMDb supplies ratings data for metacritic, rottentomatoes, imdb, and award wins. TMDbH requires a personal OMDb API key for these functions.
- Trakt supplies ratings data for itself. The rating data is public so it does not require account authentication. However, other Trakt features relating to your personal account do (e.g. watchlists, up next etc.)
- TMDb supplies ratings data for itself and the release status. It also provides all other service data. It does not require an account and TMDbHelper supplies its own API key for you.
- FanartTV provides special artwork (e.g. clearlogos, clearart, landscape, extra fanart). It is recommended that you get a personal client key and add it to the TMDbH settings as it will improve your request speed but it is not necessary.

**Comment by jurialmunkey** [comment]
BTW you can disable specific ratings in the skin settings.
