### ISSUE TITLE
[Feature] Add "Title Only" option for expanded info in widgets

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/skin.arctic.horizon.2#288]
### Is your feature request related to a problem? Please describe.

Some widget types could benefit from having an expanded info option of "Title Only"

### Describe the solution you'd like

Could you please add an expanded info option that only displays the Title and not the plot?  This would be especially useful for non-video widgets such as a widget of video addons.  I would like to see the Title in expanded info for such a widget, but the "plot" is just a description of the addon and clutters the screen unnecessarily in my opinion, so I don't want to see that.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by eengert** [comment]
If you decide to implement this feature, please also consider enabling it for small widget styles (button/apps) as well.  I understand that the plot info area isn't compatible with the reduced vertical size of these styles, but it seems like the title and bi-line (or whatever you call the info line right below the title) could work fine with any size widget, is that right?

**Comment by jurialmunkey** [comment]
It's complicated. Widgets use both negative height and oversized controls to achieve proper alignment. The skin code is far more convoluted to achieve what you see on screen than what you'd imagine it to be. Throwing new scenarios into the mix will make it much harder to add new widget types. I'd need to put a pin in this for now until I'm happy that there's no more widget types I want to add because otherwise I'm going to back myself into a corner.

**Comment by eengert** [comment]
Fair enough

**Comment by jurialmunkey** [comment]
I tried a few different approaches but unfortunately I don't think it is going to work. I just don't have enough control over the animations to make it not completely janky and the approaches that are on the better side of things are really going to box me in terms of limiting my options for new widget styles.

I can see the benefit to the feature, so I might revisit it in the future but for the time being I'm going to close as not planned.
