### ISSUE TITLE
Stop button issue

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#29]
Stop button is showing up in Video Player sometimes and sometimes not. Next button is appearing in place of stop in such cases. I'm stopping a video by long pressing back button at present if such a situation occurs.

**Comment by jurialmunkey** [comment]
Already on my todo list under Player/OSD - https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/7

**Comment by ShibajiCh** [comment]
Fine. Thank you!
