### ISSUE TITLE
[Feature] Add settings shortcut to Libreelec settings when applicable

### ISSUE THREAD

**Issue by richard-lee-863** [jurialmunkey/skin.arctic.horizon.2#291]
### Is your feature request related to a problem? Please describe.

On devices running Libreelec as the OS, there is no way to access the Libreelec specific settings when using Arctic Horizon 2 skin. 

### Describe the solution you'd like

Add a shortcut to the settings dropdown list, or incorporate it into the settings menu of Kodi

### Screenshots and Additional Info

<img width="221" alt="Capture" src="https://user-images.githubusercontent.com/43104957/176104556-b7e9ef48-b62c-44fd-abcf-a63433a91f84.PNG">

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
That menu is just the power menu. You can already customise it in skin settings.

**Comment by gregorydk** [comment]
May this be reopened? @richard-lee-863 means there is no LibreELEC menu/options in the LibreELEC system settings. What needs to be done is to add the LibreELEC icon and conditional shortcut the same way that it's done for in the default Estuary skin,.

Below is a screenshot of the default LibreELEC system settings with LibreELEC icon at the bottom.

![VirtualBox_LibreELEC_31_07_2020_16_57_24-1958222836](https://user-images.githubusercontent.com/7804464/200135793-a7ee5ec8-fa2f-42d0-9077-5a4f133a98ca.png)

**Comment by jurialmunkey** [comment]
Just add a shortcut to that command in the power menu.

That settings landing page does not exist in this skin - it is replaced by the power menu on the side of the home page which you can customise however you like.
