### ISSUE TITLE
[Feature] Option to hide text on Big Landscape 

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/skin.arctic.horizon.2#292]
### Is your feature request related to a problem? Please describe.

Would you be able to add an option to hide text on Big Landscape widgets?  To me it looks cluttered and is often illegible on top of the show artwork and is redundant when Expanded Info is set to Full. 

### Describe the solution you'd like

I liked the Big Landscape style before v0.2.10 when there was no text overlay on the image. Since some people seem to want text, could you add an option to show/hide text?

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It was never intended not to show the text, that was an accidental bug introduced for one release.

**Comment by eengert** [comment]
Understood.  If it's easy to implement, I would prefer to hide the text overlay.  But if it's more work than that or it doesn't fit within your design, I've found a way to work with it as is.  

Just a thought...it seems to me that widget text and Full expanded info are mutually exclusive.  When I have expanded info set to Full, I don't want to see redundant info as a text overlay on the widget items.  But I can see how it would be useful when expanded info is set to Off or Plot.  If you don't want to add a toggle for text overlay, what do you think about automatically hiding text overlay when expanded info is set to Full (or Title Only, if you decide to implement [#288](https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/288)  )?  

Either way, thanks.

**Comment by eengert** [comment]
I hope I'm not being a pest and annoying you with requests.  Rather than start a new issue, I thought this would be a similar enough idea to just add to this feature request...

If you decide that it makes any sense to hide text overlay (or offer the option) for Big Landscape, what do you think about about including the Landscape style as well?  Here's what I'm envisioning (screenshot below) and think would look fine.  I like it as an alternative to Big Landscape because it allows you to fit one more item on the screen.  It leaves a blank space where the text overlay would be in order to work within the layout of the skin, but I don't think it looks strange.  What do you think?

![AH2 Landscape - no text](https://user-images.githubusercontent.com/33561812/176276992-2cd87945-9ddd-4715-9a90-2645788cab71.jpg)

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Please don't change the Big landscape and landscape widget styles. I myself and many others I guess like them as they are at present. The text titles on them along with the Expanded Info is very useful and looks amazing! See screenshots below. If needed then it's my kind request that you create a new widget style for @eengert.

![IMG20220629164949](https://user-images.githubusercontent.com/65297828/176425297-4b43a830-afe6-4c10-ab02-310561e257ec.jpg)

![IMG20220629165005](https://user-images.githubusercontent.com/65297828/176425345-783a29c7-2443-479e-817d-1dbc57bd3c4b.jpg)

![IMG20220629165037](https://user-images.githubusercontent.com/65297828/176425380-59abd3b3-8606-4976-91f2-0248935a435e.jpg)

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
> Please don't change the existing Big landscape and landscape widget styles.

No plans to change them. Might make an option to disable text on big landscape but the existing functionality will stay.

**Comment by ShibajiCh** [comment]
> > Please don't change the existing Big landscape and landscape widget styles.
> 
> No plans to change them. Might make an option to disable text on big landscape but the existing functionality will stay.

Thank you so much @jurialmunkey !

**Comment by xyzfre** [comment]
> Hi @jurialmunkey,
> 
> 
> 
> Please don't change the existing Big landscape and landscape widget styles. I myself and many others I guess like them as they are at present. The text titles on them along with the Expanded Info is very useful and looks amazing! See screenshots below. If needed then it's my kind request that you create a new widget style for @eengert.
> 
> 
> 
> ![IMG20220629164949](https://user-images.githubusercontent.com/65297828/176425297-4b43a830-afe6-4c10-ab02-310561e257ec.jpg)
> 
> 
> 
> ![IMG20220629165005](https://user-images.githubusercontent.com/65297828/176425345-783a29c7-2443-479e-817d-1dbc57bd3c4b.jpg)
> 
> 
> 
> ![IMG20220629165037](https://user-images.githubusercontent.com/65297828/176425380-59abd3b3-8606-4976-91f2-0248935a435e.jpg)
> 
> 
> 
> Thanks and Regards,
> 
> ShibajiCh.

Thank you @jurialmunkey Me as well I love the current text on the big landscape widgets , and landscape Widgets I think it looks GREAT The way it is right now,, AH2 is AMAZING Thank you so much for all the hard work that's been going into this project BEST skin I ever tried And I have played with a couple over the years but this is by far the best ever

**Comment by ShibajiCh** [comment]
> 

I agree with you @xyzfre that Arctic Horizon 2 is the best Kodi skin ever. Thanks a lot to @jurialmunkey for all the hard work! 🙂👍🏻

**Comment by ShibajiCh** [comment]
> > Hi @jurialmunkey,
> > Please don't change the existing Big landscape and landscape widget styles. I myself and many others I guess like them as they are at present. The text titles on them along with the Expanded Info is very useful and looks amazing! See screenshots below. If needed then it's my kind request that you create a new widget style for @eengert.
> > ![IMG20220629164949](https://user-images.githubusercontent.com/65297828/176425297-4b43a830-afe6-4c10-ab02-310561e257ec.jpg)
> > ![IMG20220629165005](https://user-images.githubusercontent.com/65297828/176425345-783a29c7-2443-479e-817d-1dbc57bd3c4b.jpg)
> > ![IMG20220629165037](https://user-images.githubusercontent.com/65297828/176425380-59abd3b3-8606-4976-91f2-0248935a435e.jpg)
> > Thanks and Regards,
> > ShibajiCh.
> 
> Thank you @jurialmunkey Me as well I love the current text on the big landscape widgets , and landscape Widgets I think it looks GREAT The way it is right now,, AH2 is AMAZING Thank you so much for all the hard work that's been going into this project BEST skin I ever tried And I have played with a couple over the years but this is by far the best ever

I agree with you @xyzfre that Arctic Horizon 2 is the best Kodi skin ever. Thanks a lot to @jurialmunkey for all the hard work! 🙂👍🏻

**Comment by krzysztofwinnik** [comment]
Hi @ShibajiCh - I'm curious... how did you manage to make widget of live tv genres and featured content?
I'm looking for a way to have 'movies broadcasted this evening' out of epg data as poster widgets, but haven't found a clue how to do it yet. It seems you might have a solution for this, right?

**Comment by ShibajiCh** [comment]
> Hi @ShibajiCh - I'm curious... how did you manage to make widget of live tv genres and featured content? I'm looking for a way to have 'movies broadcasted this evening' out of epg data as poster widgets, but haven't found a clue how to do it yet. It seems you might have a solution for this, right?

Hi @krzysztofwinnik,

The Jio TV addon from BotAllen's Repo has pre-defined lists for Featured Content and Genres for Live TV. I simply set the widget path to those lists.

Regards,
ShibajiCh.
