### ISSUE TITLE
[BUG] TMDB Reviews not opening

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#293]
### Current Behavior

Hi @jurialmunkey,

The recently added feature TMDB Reviews, which you placed under Recommendations context menu is not opening. The Reviewer names show up but nothing happens when I click on them. This issue looks similar to the Trakt comments issue which I mentioned in issue #231 few days back. Could you please check?

### Expected Behavior

The Reviews should open.

### Steps To Reproduce

Go to TMDB Helper context menu, click on fire icon, click on Reviews, click on any Reviewer name.

### Screenshots and Additional Info

![IMG20220628222729](https://user-images.githubusercontent.com/65297828/176238433-6e556327-0cc3-4031-a080-ab6263a79761.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Please actually test using the default kodi skin before ticking the box that you have. You will find that this also does not work in Estuary because it hasn't been implemented in TMDbH.

**Comment by ShibajiCh** [comment]
> Please actually test using the default kodi skin before ticking the box that you have. You will find that this also does not work in Estuary because it hasn't been implemented in TMDbH.

Hi @jurialmunkey,

Apologies for not checking properly! I thought that the feature has been added by seeing the updates in Github.

Thanks and Regards,
ShibajiCh.
