### ISSUE TITLE
I[Feature] Position of the navigation bar in the main menu

### ISSUE THREAD

**Issue by Hallo951** [jurialmunkey/skin.arctic.horizon.2#295]
### Is your feature request related to a problem? Please describe.

It would be very nice if there was a way to change the position of the navigation bar in the main menu.

### Describe the solution you'd like

Is it possible to add an option to place the navigation bar at the bottom of the screen?

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry no. It will be too complicated to do well and won't look good.
