### ISSUE TITLE
[Feature] Trailer button in the player menu

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#303]
### Is your feature request related to a problem? Please describe.

Sometimes I started watching a movie - and it started boring and I stopped it.

### Describe the solution you'd like

A button on the player that will allow the movie to stop
And watching the trailer

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry I don't understand what you're asking for here.

**Comment by koby455** [comment]
I want there to be a button in the player that will allow you to see the trailer - even though I've already played the movie

**Comment by xyzfre** [comment]
My apologies just my opinion but wouldn't it be better for you to see the trailer first before trying the movie or TV show

**Comment by koby455** [comment]
> My apologies just my opinion but wouldn't it be better for you to see the trailer first before trying the movie or TV show

You're right, but sometimes I do not see the trailer and then the movie starts boring .. and I do not know if it is good or not
Once there is a button I will already see the trailer and I can determine

**Comment by jurialmunkey** [comment]
Press info button and it will take you to movie info then you can play trailer from there.

Having a button dedicated to  watching a trailer on the osd is complete overkill
