### ISSUE TITLE
[Feature] Widget style

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#307]
### Is your feature request related to a problem? Please describe.

"Could we get previews of the view types/layouts before selecting them? These could be static images with fixed content, for example purposes. the same like [francis-robert](https://github.com/francis-robert) ask 
just in widget

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/102416233/177014378-2b0fe8de-950d-4011-8d04-9589eafa5e06.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Not possible. This is a default kodi select dialog so it can't be changed without messing it up elsewhere. Also skinshortcuts addon doesn't provide a way to attach images to the settings like these.
