### ISSUE TITLE
[Feature] clearlogo size

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/skin.arctic.horizon.2#308]
### Is your feature request related to a problem? Please describe.

When the logo is horizontal it appears very large. When the logo has two lines or is an image, it appears very small 

### Describe the solution you'd like

Proportional size of clearlogo

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This has been discussed several times on the forum thread already
