### ISSUE TITLE
[BUG] landscape combined

### ISSUE THREAD

**Issue by saxoloman** [jurialmunkey/skin.arctic.horizon.2#310]
### Current Behavior

When selecting tv show and season.when you press menu button on remote controler on any episode nothing happens.

### Expected Behavior

When pressing menu button on remote controler context menu should appear as it does with any other view

### Steps To Reproduce

Enter any tv show with landscape combined view
Select season 1
Press menu button on any episode or long press ok button on remote and nothing happens.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Matrix bug in kodi. Skin can't do anything about it. Will be fixed in Kodi in nexus.

**Comment by drinfernoo** [comment]
@jurialmunkey Is this the nested list bug where the context menu won't come up? If that's finally getting addressed in Nexus, that'll be great!

**Comment by saxoloman** [comment]
Just tried it in nexus nightly on my phone and indeed it is working
Thank you

**Comment by jurialmunkey** [comment]
> @jurialmunkey Is this the nested list bug where the context menu won't come up? If that's finally getting addressed in Nexus, that'll be great!

Yeah the bug where `Action(ContextMenu)` is not working in library windows for containers with custom content. The contextmenu itself *does* actually work in Matrix but only with mouse/touch, whereas in Nexus the keymap/remote command is also working properly too now.
