### ISSUE TITLE
[Feature] information page "press down" action disable

### ISSUE THREAD

**Issue by cremonies** [jurialmunkey/skin.arctic.horizon.2#312]
setup: Skin Settings>details>custom recommendation>none selected
1. click on tv show/movie opens information page.
2. click down
result: blank page.

### Describe the solution you'd like

disable down action to blank page

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can now achieve this by selecting to use library info for recommendations and then disabling them all.
