### ISSUE TITLE
[BUG] Hidden buttons got partly visible

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#314]
### Current Behavior

Since the latest button fix for RTL languages commit some buttons are not displayed properly.
Hidden buttons are only partly hidden.

### Expected Behavior

As it was before the commit.

### Steps To Reproduce

1. Select an item
2. Open infoview
3. If any button is supposed to be hidden, its round part gets displayed anyway. 

### Screenshots and Additional Info

<img width="1440" alt="Zrzut ekranu 2022-07-4 o 09 17 20" src="https://user-images.githubusercontent.com/679205/177102662-c0da1c63-f570-4f63-a3e1-eae5a00cfac7.png">
![Uploading Zrzut ekranu 2022-07-4 o 09.16.47.png…]()

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah I forgot to have the end slice of the button check visibility against the centre. Fix coming shortly.
