### ISSUE TITLE
Pause at the video osd. 

### ISSUE THREAD

**Issue by Romik2505** [jurialmunkey/skin.arctic.horizon.2#315]
### Skin section

Fullscreen Video OSD

### Feature description

Maybe it could be possible to add auto pause function for video playback when osd appears.  For example pressing on the remote control.

### Why is this feature needed? Please justify and explain.

You don't need to double-click the remote to stop the video. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Why?

**Comment by Romik2505** [comment]
To pause you have to double click on the remote and it will stop the first time.  Greater convenience

**Comment by jurialmunkey** [comment]
But why do you need to pause the video every time you open the controls? 

Also, it doesn't save any clicks because you still need to un-pause when you want to continue watching.

**Comment by jurialmunkey** [comment]
You can change your remote keymappings via the keymap editor addon. Keymaps have nothing to do with the skin.
https://kodi.wiki/view/Add-on:Keymap_Editor
