### ISSUE TITLE
[BUG] Buttons missing background texture

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/skin.arctic.horizon.2#316]
### Skin section

Home Widgets

### Current Behavior

Buttons are missing background texture.  See screenshot below.

Kodi 19.3 on Apple TV 4K, AH2 v0.2.26, TextureMaker v0.2.7

### Expected Behavior

Buttons should have a background texture.

### Steps To Reproduce

Move focus to a button on home widget

### Screenshots and Additional Info

![Screen Shot 2022-07-05 at 5 48 59 PM](https://user-images.githubusercontent.com/33561812/177424835-003ba8da-1325-4f80-bd8a-81dacd3650fb.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by eengert** [comment]
Also seeing this behavior on Mac OS.

<img width="1792" alt="Screen Shot 2022-07-05 at 7 50 58 PM" src="https://user-images.githubusercontent.com/33561812/177435234-b7d9e641-9f68-4634-bdaf-18d6b39411f2.png">

**Comment by jurialmunkey** [comment]
Did you try restarting? Looks like you skipped texturemaker rebuilding (possibly closed startup window before it had a chance). 

You can force a rebuild by changing the colours in skin settings.

If that doesn't work I might need a debug log of you changing colours.

**Comment by Goldenfreddy0703** [comment]
Hey, i didn't want to make this a bug sense its kinda slimier to this issue but whenever you guys setup submenus without using the submenu widget tab, do you guys see any submenu widgets on the bottom. 

Submenu that's supposed to have submenus on the bottem.
![image](https://user-images.githubusercontent.com/62456796/177457680-a1e42900-5a91-4405-842d-64cd4ddc512e.png)

Edit Submenu thats supposed to be on the bottem. 
![image](https://user-images.githubusercontent.com/62456796/177457854-045c503d-7f17-4eec-b6f4-15bb163e28ac.png)

**Note: I did not add any Widgets except a full screen widgets and submenus.**

**Comment by jurialmunkey** [comment]
@Goldenfreddy0703 - Please open as a separate bug report. Completely different issue.

**Comment by Goldenfreddy0703** [comment]
> @Goldenfreddy0703 - Please open as a separate bug report. Completely different issue.

Ok great thanks

**Comment by eengert** [comment]
After upgrading AH2 and all dependencies today, the problem is resolved.
