### ISSUE TITLE
[BUG] Submenu Buttons not showing

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.horizon.2#317]
### Skin section

Home Widgets

### Current Behavior

It's not showing the submenu.

### Expected Behavior

It's supposed to show the submenu

### Steps To Reproduce

1. Download Kodi, Jurialmonkey's repo, Skin Ah2
2. Setup a fullscreen widget, a submenu of anything. (Do not use the "Submenu Widget" button in the Customize Main Menu catagory) 
3. Go back the homescreen and notice that you don't see your submenus on the bottem anymore.
4. Optional, Press up from the home menu to open submenu and see if its there. 

### Screenshots and Additional Info

Submenu that's supposed to have submenus on the bottem.
![image](https://user-images.githubusercontent.com/62456796/177458725-f0f26a22-65ca-4f5a-af70-4aa8a81edfb5.png)

Edit Submenu thats supposed to be on the bottem. 
![image](https://user-images.githubusercontent.com/62456796/177457854-045c503d-7f17-4eec-b6f4-15bb163e28ac.png)

**Note: I did not add any Widgets except a full screen widgets and submenus.**

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.
- [X] I have confirmed that i am lazy with making this issue.

**Comment by jurialmunkey** [comment]
@Goldenfreddy0703  -- Have you set submenu widget to be the submenu?

![Honeyview_screenshot00033](https://user-images.githubusercontent.com/4618719/177479419-1ee3e55e-b3b1-4177-b55a-b667bdfcc7d4.jpg)

**Comment by Goldenfreddy0703** [comment]
> @Goldenfreddy0703 -- Have you set submenu widget to be the submenu?

Hey @jurialmunkey im sorry but no i have not, i just used the Submenu, not the Submenu widget
