### ISSUE TITLE
[BUG] Unable to update skin

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon.2#318]
### Skin section

Other

### Current Behavior

I am unable to update the skin version :(

### Expected Behavior

Should be able to update.

### Steps To Reproduce

1. Download the latest zip skin.arctic.horizon.2-0.2.29
2. Go to options- Install from zip, choose that zip
3.  Screen goes complete black, I waited 5 mins, still the same
4. When I click back button, I get that washed out screen (see screenshot)
5. Force close Kodi and restart, all looks normal but still on old version 0.2.7 which means update failed

### Screenshots and Additional Info

![Kodi_20220706_190525](https://user-images.githubusercontent.com/48493659/177615928-f6ab7baa-fef0-4123-bfd9-a74767911398.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Debug log?

It's not really a skin issue but the log probably has clues

**Comment by jurialmunkey** [comment]
Also try redownloading the zip and renaming it so the name is unique (eg add an a on the end 0.2.29a.zip etc). Kodi saves old zips so if you try reinstalling using a previous name it will use the package cache one (which possibly is corrupt in this case)

**Comment by onlytanmoy** [comment]
Things I have done so far: Downloaded the latest v0.2.31 zip, renamed it to latest.zip, opened via 7zip and tested the archive, no errors
Cleared Kodi cache via android settings, used OpenWizard for total clean up.
Tried installing the latest.zip, faced the same black screen issue.
I will get the debug log for you next.

**Comment by onlytanmoy** [comment]
Just came to know one of my friends also facing the same issue, will ask him to comment here @Macphesto

**Comment by onlytanmoy** [comment]
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9062017/kodi.log)
@jurialmunkey please find the kodi debug log attached

**Comment by jurialmunkey** [comment]
```
2022-07-07 09:49:27.829 T:23511   ERROR <general>: CAddonInstallJob[skin.arctic.horizon.2]: failed to find dependency script.texturemaker
```

Install latest version of texture maker first.

Recommend using my repo so that you don't need to manage dependencies or worry about manually updating
File manager source:
`https://jurialmunkey.github.io/repository.jurialmunkey/`

**Comment by onlytanmoy** [comment]
Many thanks mate, working like a charm now, able to update to latest version 0.2.33 :)
