### ISSUE TITLE
[BUG] Logo not cleared properly

### ISSUE THREAD

**Issue by JacopoV** [jurialmunkey/skin.arctic.horizon.2#319]
### Skin section

Home Widgets

### Current Behavior

Running on 0.2.29

After hovered in focus a full screen widget, the logo stays as placeholder while hovering on all the other covers (visible if they take time to load) 

### Expected Behavior

The last movie/show should be the last one always visible (or nothing at all if focus is lost) if the UI is still loading the correct logo. 

### Steps To Reproduce

1 focus of a full screen widget
2 scroll to other widgets
3 start scrolling on other covers and notice the logos loading, always showing temporary the one from the full-screen widget 

### Screenshots and Additional Info

In the video example, I'm using Arcane as reference 

https://www.veed.io/view/7fd01702-8d75-4b63-994d-ec39e6a33b3c?sharingWidget=true

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I know what you mean as it annoys me too but unfortunately I don't think it can be fixed. That's just the way kodi manages image controls - the old texture continues to display in the control until the new one loads. 

There's no way in the skinning engine to check if a texture is loading/downloading. All I can do is check if there's a url for kodi to download the image from.

**Comment by JacopoV** [comment]
@jurialmunkey no worries, i might have explained not in a good way! 
However you did the trick because it's now fixed :)   Works like a charm! Thanks a lot! 
 Closing the ticket, thanks for the support!!!

**Comment by JacopoV** [comment]
@jurialmunkey no worries, i might have explained not in a good way! 
However you did the trick because it's now fixed :)   Works like a charm! Thanks a lot! 
 Closing the ticket, thanks for the support!!!

**Comment by jurialmunkey** [comment]
Excellent! 

And no issues with your explanation. I just didn't watch the video close enough and assumed you were talking about a different but very similar issue where image controls don't clear the previous image while the next image is loading.
