### ISSUE TITLE
Browse for image titles

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#32]
While choosing icons for submenu, etc. earlier in Arctic Horizon the image titles were visible. However, in Arctic Horizon 2 I'm not able to see the titles anymore. Could you please add that feature back? (See screenshot below)
![IMG20220605154901](https://user-images.githubusercontent.com/65297828/172046502-b8b1a63d-cf08-409f-ad29-b1cc460512e3.jpg)

**Comment by jurialmunkey** [comment]
Why do you need the filenames?

**Comment by ShibajiCh** [comment]
Nothing much, but it helps in identifying which icon is for what purpose like for Settings, Collections, Movie Sets, etc. If it's too much trouble then you can leave it. It's upto you. Thanks!

**Comment by jurialmunkey** [comment]
> Nothing much, but it helps in identifying which icon is for what purpose like for Settings, Collections, Movie Sets, etc. If it's too much trouble then you can leave it. It's upto you. Thanks!

That make sense! I went back and looked at AH1, and you're right, it does make it feel a little easier to navigate. Added.

**Comment by ShibajiCh** [comment]
Thank you so much! 🙂
