### ISSUE TITLE
[Feature] Integrated View Types

### ISSUE THREAD

**Issue by skiTzoCogniTionz** [jurialmunkey/skin.arctic.horizon.2#321]
### Skin section

Library Views

### Feature description

Integrated view type with buttons for "info", "trailer", "trakt", ect..

### Why is this feature needed? Please justify and explain.

I can't honestly justify this request as an absolute must for functionality,  but the integrated view types from the original Arctic Horizon were amazing and my absolute favorite since the entire existence of Kodi.

### Screenshots and Additional Info

![pwD6R6A](https://user-images.githubusercontent.com/96932276/177988121-e8734b04-6175-4070-a5dd-8a255b1927a9.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What feature do you find yourself missing?

Most of these options are available from the context menu which works in every viewtype - not just rows.

With the position of the scrollbar and other design guides of AH2 there is no room for these buttons. Having these buttons would be at the expense of some other on screen element.

**Comment by skiTzoCogniTionz** [comment]
I just really liked the integrated view types from the original arctic horizon. It's all good man. The skin looks great, thank you for all your hard work.
