### ISSUE TITLE
[Feature] Option for default select action

### ISSUE THREAD

**Issue by skiTzoCogniTionz** [jurialmunkey/skin.arctic.horizon.2#322]
### Skin section

Video Info Dialog

### Feature description

An option for the default select action to show info when selecting a movie only. 

### Why is this feature needed? Please justify and explain.

There is an option in the base Kodi configuration to choose the default select action, but it applies to both movies and TV shows. It's really nice having the tmdb helper info pop up when selecting a movie instead of having to use the menu diologue to show info, but it is annoying when selecting a TV show. It would be great to have an option for the default select action to apply only to movies. It would go perfect with the existing tmbd helper integration.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skins can't change the default select action in media windows. Skins can only control onclick action on widgets so any skin based override would be inconsistent. This should be a kodi setting not a skin matter.
