### ISSUE TITLE
[BUG] Submenus missing even though enabled

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon.2#323]
### Skin section

Home Widgets

### Current Behavior

Submenus are no longer displaying, please see screen record https://streamable.com/wa4xq6
I am sure I am missing something in settings which you can help with :)
Let me know if you still need the debug log

### Expected Behavior

Submenus should get displayed below the home screen widgets

### Steps To Reproduce

https://streamable.com/wa4xq6

### Screenshots and Additional Info

https://streamable.com/wa4xq6

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Your submenu widget is not set to submenu.
`Customise > Submenu widget > Default widgets > Submenu`

**Comment by onlytanmoy** [comment]
You are a Rockstar 😊 that fixed it instantly, thanks buddy.
