### ISSUE TITLE
[BUG] kodi crashes way more frequent on AH2

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.horizon.2#324]
### Skin section

Other

### Current Behavior

I tested this on a Windows 10, MacOS 12, tvOS (Apple TV 4K), and Nvidia shield pro. AH2 crashes on me 2-3 an hour. it only happens on this skin. I also tried it on Kodi 13.3 and 13.4 same results

### Expected Behavior

less crashes

### Steps To Reproduce

update skin is for sure a solid reason for the crash
but many more random circumstances that I could not pin point. a lot of times, I open up kodi, it starts and loads up the Home Screen then crashes immediately. some time, on the addons page, others while loading tmdb widgets.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Without more information about how exactly to cause the crash I can't fix it. I need a reliable steps to reproduce or a specific error that happens. Let me know if youdiacover more information. But vague "it crashes more often" statements aren't useful.
