### ISSUE TITLE
[Feature] Adding MPA rating - R, PG-13, PG, etc

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.horizon.2#325]
### Skin section

Home Widgets

### Feature description

it would be very helpful to add MPA rating next to the movie year. Also, there is an exact parental guide on imdb that rates violence and nudity in a movie, having it somewhere would be fantastic.

thank you for the amazing work

### Why is this feature needed? Please justify and explain.

it helps determining if parental control is needed or not and if a movie is suitable for family movie night or not

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/178124947-de848d21-a479-4ee9-b5b0-1d764cc5fc98.jpeg) do you mean like this ,because they should show up already

**Comment by jurialmunkey** [comment]
Mpaa rating is already available in the skin as in xyzfre screenshot above.

Scraping imdb data is not permitted by their terms of use. You need to pay to use their api.
