### ISSUE TITLE
[Feature] Play the series directly

### ISSUE THREAD

**Issue by ffwell** [jurialmunkey/skin.arctic.horizon.2#327]
### Skin section

Other

### Feature description

Is it possible to add a setting: after selecting a series on the main interface, click the play button to directly play the record of an episode of a recent season, rather than entering the season list of the series, entering the episode list, and then finding an episode by memory, which will be much easier to play. thank you

### Why is this feature needed? Please justify and explain.

I hope it's easier to play, not afraid to forget where I saw last time

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Not possible unfortunately.
