### ISSUE TITLE
[Feature] Option to have album artwork always displayed in visualization and lyrics sections

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#328]
### Skin section

Music Visualisation OSD

### Feature description

Currently album artwork is displayed only for a short time when music playback starts in music visualization section and on key press in lyrics section.
I'd like to have an option in skin settings to make it always visible.

### Why is this feature needed? Please justify and explain.

I believe album artwork is an important part of music experience and there should be an option to have it always on top.

### Screenshots and Additional Info

n/a

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Press info (i on keyboard) and it will always display

**Comment by jurialmunkey** [comment]
If you've only got a six button remote (directions, select, back) then I believe by default long press select is mapped to info on visualisation screen. You only need to toggle it once and then the setting stays on (until you toggle it off again with another press of info)

It was good that you made this issue anyway, as it got me to test the lyrics without info enabled -- didn't realise it was hiding on that condition, so I've fixed that (i.e. art should always display with lyrics even if info is off).

**Comment by krzysztofwinnik** [comment]
Oh, Now I recall it worked the simmilar way in AH1. It is one of those features you turn on once and than forget. Anyway, thank you for your quick and helpful response - as always ;-)
