### ISSUE TITLE
Menu select option as submenu popup

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#33]
Earlier in Arctic Horizon we could select the default menu select option as submenu popup. However, it's not available in this skin anymore. Could you please add that feature back? The action was earlier SetFocus(303,0,absolute). It's not working any longer in this new skin.

**Comment by jurialmunkey** [comment]
Ah I completely forgot about that. I'll add in a selectable shortcut soon.

The ID for submenu changed to 302, so for the meantime you can add this manually by swapping 303 for 302 in the SetFocus command.

**Comment by ShibajiCh** [comment]
The ID 302 is working fine for now. Thanks a lot!

**Comment by ShibajiCh** [comment]
Thank you!
