### ISSUE TITLE
[Behavior] Last played LiveTV widget behavior

### ISSUE THREAD

**Issue by sabre6** [jurialmunkey/skin.arctic.horizon.2#332]
### Skin section

PVR and Live TV

### Feature description

After playing a Live TV channel, and returning to a LiveTV section with a Last Played Widget, the behavior is rather unexpected requiring several clicks to resolve.  When hitting stop from viewing a current channel, it will take you back to that channel on the Last Played widget (fine). But then clicking right to get to the Last Played channel next to it will not take you to that channel, but rather up to the LiveTV section header.  And then you will need to click down, and then right again to get to the channel that you want to play.  Like AH1, could it just remain on the Last Played widget rather than moving up, then requiring a move down?

I hope this makes sense.  

### Why is this feature needed? Please justify and explain.

To remove extra clicks to get where originally intended. Makes skin more streamline/efficient.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I can't reproduce this issue

**Comment by jurialmunkey** [comment]
I need more information about how to recreate this issue as it does not happen for me. I play from a PVR widget and then stop playback and focus is back on the PVR widget.

**Comment by sabre6** [comment]
Hi, thanks for following up.  Agreed to what you see "I play from a PVR widget and then stop playback and focus is back on the PVR widget."  However, the next move for me is where it goes off.  When the focus is back on the channel on the PVR widget, I would expect clicking right to move to the PVR channel next to it.  In reality, clicking right moves the focus up to the top [TV / Movie / Shows etc]. One then needs to click down to get back to PVR widget, and then click right to get prior last played channels.

**Comment by jurialmunkey** [comment]
And I'm saying I can't reproduce that behaviour. I click play, stop, go back to widget and can move right/left as normal.

**Comment by sabre6** [comment]
ok, thanks for checking. It happens on all my devices.  I will learn to live with it. 

Cheers.

**Comment by jurialmunkey** [comment]
Really weird. No idea what would've been causing it but if it is fixed it is fixed I guess!
