### ISSUE TITLE
[BUG] PVR icons do not display properly on widgets

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#34]
PVR channels' icons do not display properly on widgets - i.e. on square and poster widgets they appear cropped (see screenshots).
Other aspects - poster and landscape - do not display properly too
<img width="1348" alt="s1" src="https://user-images.githubusercontent.com/679205/172047097-2fa5a957-6411-4a0a-8be0-e294f3ea4480.png">
.

**Comment by jurialmunkey** [comment]
Hahaha, oh dear! That is certainly some unfortunate cropping!
Should be fixed now
