### ISSUE TITLE
No Clearlogo with widget created with Autowidget

### ISSUE THREAD

**Issue by ludovik35** [jurialmunkey/skin.arctic.horizon.2#343]
### Skin section

Home Widgets

### Current Behavior

Clearlogo of widgets or shortcuts that have been created with Autowidget plugin doesn't appeared when they're used in widget menu.

### Expected Behavior

One of the Autowidget plugin feature is the definition of banner view, landscape view,  icon view and clearlogo for every elements created with the plugin. 

This view can be later select is the home menu widget customization. Since this customization have been done, this Autowidget will appeared like a classical widget. 
This also mean that clearlogo prevously defined will be shown in home screen. 

In AH2 the clearlogo doesn't appeared 

### Steps To Reproduce

1- Create a group in Autowidget plugin
2- Define clearlogo for each element in this group
3- Select this group like a widget in home menu customization 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by drinfernoo** [comment]
These are set into `ListItem.Art(xxx)`, for what it's worth.

**Comment by jurialmunkey** [comment]
Does this behaviour still occur in most recent versions of the skin/tmdbh?

**Comment by ludovik35** [comment]
Hi Jurialmunkey,
Many thanks to you because you solve this bug.
Sorry for my delay to close this bug. I have'nt many time for kodi last week. The little time I have last month,  I spend it to config my pvr backend (hts).
If I have enough time, I'll try to suggest you some improvements for tour Pvr screen. Even AH2 is one most advanced skin for Pvr section, I hope my suggestion will be interesting for you ;-)
Thanks again
