### ISSUE TITLE
EPG guide randomly switchback to classical view

### ISSUE THREAD

**Issue by ludovik35** [jurialmunkey/skin.arctic.horizon.2#345]
### Skin section

PVR and Live TV

### Current Behavior

On the EPG Guide screen. 
Sometimes the view automaticaly switch back to the classical view.

### Expected Behavior

Sometimes epg view automaticaly switch from icon+info view to classical view. 

### Steps To Reproduce

1. Go to view EPG guide screen
2. Switch to icon+info view
3. Navigate in epg guide
4. Switch automaticaly to initial view

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The skin doesn't control which viewtype is set in the guide (other than providing the button in the menu to call Kodi's switch viewtype command). Which viewtype is currently set is controlled by kodi.
