### ISSUE TITLE
[BUG] [Fullscreen PVR Info] no background on infoview when opened in pvr mode

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#35]
Infoview displays inproperly and lacks background when opened during PVR playbac
![s3](https://user-images.githubusercontent.com/679205/172047192-bdbb1599-502e-42bd-aec4-e51c4ebe6084.jpg)
k

**Comment by jurialmunkey** [comment]
Is this opening from OSD channels list?

**Comment by krzysztofwinnik** [comment]
yes

**Comment by jurialmunkey** [comment]
Okay looks like this is going to take a bit of work. Latest commit will at least fix the background issue but there's a few other problems to fix like transition animations and some info not updating.

**Comment by krzysztofwinnik** [comment]
This seems to be already solved - I'll close it then

**Comment by krzysztofwinnik** [comment]
This is already completed ad well
