### ISSUE TITLE
[Feature] Skin Option for a High Contrast Dark

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.arctic.horizon.2#350]
### Skin section

Other

### Feature description

As the title says, if I remember correctly in AH1 there are two Dark options for the skin color one regular Dark which has a more greyish tone similar as we have currently in AH2, and then there's a second one called High Contrast Dark which is way more comfortable in eyes when viewing at night time or in a dark room. It would be great if you could eventually bring this option also to AH2, specially for some users myself included which use OLED TVs the darker the tone the more everything else pops color wise within the skin, or as I previously said simply for less eye strain when viewing in a dark environment or at night.

### Why is this feature needed? Please justify and explain.

Just an extra option for a darker and less eye strain when viewing the skin in a light controlled room, or night time as the current Dark theme has a lighter shade of grey which can still be a bit bothersome instead of a true black or higher contrast dark shade.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Are you meaning the background of dialogs or more the background overlay fade?

**Comment by Nuklear92** [comment]
> Are you meaning the background of dialogs or more the background overlay fade? 

Yeah, the background of dialogs. Currently the dark theme seems a bit more like a shade of grey instead of true black. I mean you can clearly see it for yourself if you select the AH1 skin and switch between the Dark and High Contrast Dark Colours option under Look and Feel. 🙂

**Comment by jurialmunkey** [comment]
Yep I know which one you mean. It's just that I also had one for AZ2 that changed the background fade to be darker - so wanted to make sure it was the dialogs version not that one.

**Comment by Nuklear92** [comment]
> Yep I know which one you mean. It's just that I also had one for AZ2 that changed the background fade to be darker - so wanted to make sure it was the dialogs version not that one. 

Yeah, I mean it would be nice if it was an all around darker one which included both background fade and dialogs. However, if that's a bit more difficult to make happen, I'll be happy with just making the dialog boxes with a darker shade as those seems to be the most bothersome due to the lighter shade of grey they currently have. 🙂

**Comment by jurialmunkey** [comment]
> Yeah, I mean it would be nice if it was an all around darker one which included both background fade and dialogs. However, if that's a bit more difficult to make happen, I'll be happy with just making the dialog boxes with a darker shade as those seems to be the most bothersome due to the lighter shade of grey they currently have.

No not difficult. It's just a different colour theme definition. I was just trying to identify if the contrast issue is in both areas or just the dialogs or just the background.

I know exactly the issue - it really just depends on graphics cards and/or display. e.g. on my living-room tv things look great via my NUC's integrated graphics (especially since I've tweaked its gamma settings to suit getting good black levels for video) but when I switch over to the NVidia RTX card in my eGPU things get much more washed out.

The main reason I use dark grey rather than black in the background by default is because it helps eliminate some banding by allowing me to add noise to the gradients. When you switch to full black, there's no noise anymore because there's no colour range (since everything is black) so on cheaper TVs you end up getting banding as a result. But it really just depends on the TV.

**Comment by jurialmunkey** [comment]
@Nuklear92 - Could you try the `darker_theme` branch using the "Darker" colour scheme
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/darker_theme.zip

I think this is just about as dark as I can go without losing definition of dialog edges. Even then, I think it is maybe still *too* dark as seen on the power menu in the second screenshot. Thoughts? Should I go slightly lighter or does it look good on your display?

![Honeyview_screenshot00074](https://user-images.githubusercontent.com/4618719/179907742-6242fb30-38d5-4db0-9e9d-034385687f50.jpg)

![Honeyview_screenshot00073](https://user-images.githubusercontent.com/4618719/179907847-2a8818df-5e42-47bc-965b-9411a41424af.jpg)

**Comment by jurialmunkey** [comment]
@Nuklear92 - I decided to merge the changes as I'm happy with them and we can tweak it as needed if it needs to go slightly lighter for better contrast against the background. 

When you get a chance to test, let me know if you think it is okay or if the dialog background needs a slight bump for better contrast.

**Comment by Nuklear92** [comment]
> @Nuklear92 - I decided to merge the changes as I'm happy with them and we can tweak it as needed if it needs to go slightly lighter for better contrast against the background. 
> 
> 
> 
> When you get a chance to test, let me know if you think it is okay or if the dialog background needs a slight bump for better contrast.

I just test it, it looks a little nicer, however I have two screenshots with slight descriptions that hopefully could make it even better if there's no downsides to either one. Let me know if those adjustments could be fine or any darker from what I point out could bring those negative effects you mentioned above. 

![image](https://user-images.githubusercontent.com/76958541/179985052-d41fcc54-59a4-44db-8d3a-2686c5167b5e.jpeg)

![image](https://user-images.githubusercontent.com/76958541/179985078-049c8ab3-4f2c-45ee-9ff3-51c5e2708571.jpeg)

**Comment by jurialmunkey** [comment]
I did have darker background in before but someone complained about it being too dark so I'm going to split that off into a separate theme.

Inverting the order of the overlays is not really possible because it is setup for the default theme. The overlay adds the foreground colour to the background colour so when you have a dark dialog with light text then the overlay gets progressively lighter from left to right (whereas with light background dark text it gets progressively darker)

**Comment by Nuklear92** [comment]
> I did have darker wibdow background in before but someone complained about it being too dark so I'm going to split that off into a separate theme.
> 
> 
> 
> Inverting the order of the dialog overlays is not really possible because it is setup for the default theme. The overlay adds the foreground dialog colour to the background dialog colour so when you have a dark dialog with light text then the overlay gets progressively lighter from left to right (whereas with light dialog and dark text it gets progressively darker from left to right) 

Oh, gotcha! 👍 No problem then, I can deal with what you brought in the new Darker color option. However if in the near future you can do the separate theme as an additional option that would be great too. As of now, no rush on this you can leave it as it is. I wouldn't like to be taking off time from you that you can spend working in other areas of the skin which might still need adjustments, etc. than this nonsense of a darker theme. That can definitely wait. Thanks by the way for adding the new darker option, much appreciated! 🙂

**Comment by jurialmunkey** [comment]
@Nuklear92 - HighContrast options added in v0.3.10

Let me know what you think / if tweaks still need to be made etc. 

Basically it is the same as the default scheme but the background is dropped down from 9% grey (18 hex) to 0% (00 hex) and foreground text is bumped up from 87% grey (de hex) to 93% (ed hex). Going up to 100% (ff) for main text felt a little *too* high contrast on my TV but I can bump it up higher if you think is necessary.

**Comment by Nuklear92** [comment]
> @Nuklear92 - HighContrast options added in v0.3.10
> 
> 
> 
> Let me know what you think / if tweaks still need to be made etc. 
> 
> 
> 
> Basically it is the same as the default scheme but the background is dropped down from 9% grey (18 hex) to 0% (00 hex) and foreground text is bumped up from 87% grey (de hex) to 93% (ed hex). Going up to 100% (ff) for main text felt a little *too* high contrast on my TV but I can bump it up higher if you think is necessary.

Just tested and it looks great so far on my OLED TV. It's displaying full black now in the background! 👍
