### ISSUE TITLE
[Feature] Slightly more background in the new night mode

### ISSUE THREAD

**Issue by ctanyp** [jurialmunkey/skin.arctic.horizon.2#353]
### Skin section

Library Views

### Feature description

Could you make a brighter background for the background images.. I also prefer a darker mode at night! But now the fanart has also become darker.. And thank you very much for adding a new mode!) I just wish the backgrounds of the images were a bit brighter in the new night mode.

### Why is this feature needed? Please justify and explain.

In the darker theme, the background of the images is not so well visible, but I really like this mode!) I would like a brighter background (quite a bit) not directly bright, just to see the extrafanart more clearly and 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by ctanyp** [comment]
Thank you very much!)

**Comment by xyzfre** [comment]
Great request dark mode definitely looks much better with the fanart being more visual
