### ISSUE TITLE
[BUG] Home Screen Widgets (from TMDB H) reloads everytime you exist the video player

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.horizon.2#356]
### Skin section

Home Widgets

### Current Behavior

I am noticing when i exist the video player and go back to the home screen. Some widgets reloads (not the whole skin) 

It happens on android (Nvidia Shield Pro 2019)

### Expected Behavior

No reload

### Steps To Reproduce

1- Play a video from the home screen widgets
2- stop the video
3- go back to home screen
4- navigate the tabs to see the widgets reloading

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Hardcoded kodi behaviour. Whenever you stop video it refreshes all containers. Nothing the skin can do about it.
