### ISSUE TITLE
[BUG] Cast, Recommended section strange behavior 

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.horizon.2#357]
### Skin section

Video Info Dialog

### Current Behavior

Before the recommended sections (In Video Dialog Info) load, the expanded information appears with data.

![C72C56B8-A52A-431C-8811-73B54C10CB74](https://user-images.githubusercontent.com/9439671/180377304-12819c0b-1c36-4beb-9189-f25b31c987bc.jpeg)
![83DB2087-FDF8-4723-AA1E-AF133F0529BE](https://user-images.githubusercontent.com/9439671/180377323-8ccd6860-0b1f-4d4e-965e-18ff132b6e8c.jpeg)
![000D63F8-9185-4604-8E9C-77B3F57F471F](https://user-images.githubusercontent.com/9439671/180377333-3ad1a9a4-f6f7-4b00-9c19-f8801b18dfb4.jpeg)
![0F5357E3-F906-48A5-8CF7-7A341C994C3D](https://user-images.githubusercontent.com/9439671/180377342-242cec1c-3bc0-4de5-9c61-5ac31429e848.jpeg)
![DF30D736-894C-4ED4-B3E0-031EDD6FCABE](https://user-images.githubusercontent.com/9439671/180377354-c6e9cea7-405b-4f7d-864c-b890e5f97a0a.jpeg)
![F9E0CCBA-C200-413B-8699-1E1771D79D96](https://user-images.githubusercontent.com/9439671/180377366-337d4d17-e817-4556-92f1-b24bdf5a2cb0.jpeg)

### Expected Behavior

The expanded info section to be loaded after the widget loads and upon selecting a movie not before the widget loads

### Steps To Reproduce

Go to any movie
Show information
Click down
Navigate between recommended, studio, keywords, similar, etc

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I think the recent changes to the recommendation dialog loading and handling effectively resolve this issue.
