### ISSUE TITLE
[Feature] opening info dialog

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon.2#360]
### Skin section

Fullscreen Video OSD

### Feature description

The option is not to pause when using the info dialog

### Why is this feature needed? Please justify and explain.

Great feature. Always used it in AH.

### Screenshots and Additional Info

AH
![Screenshot 2022-07-23 at 07 50 05](https://user-images.githubusercontent.com/2873112/180594432-f4ba0b47-dd9f-4409-aed2-c76734b05eb1.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It *should* already pause by default when opening the info dialog. Is that not happening? 

Or do you want an option to be able to disable pausing?

**Comment by Blurayx** [comment]
The option Not to pause 🙂
