### ISSUE TITLE
[BUG] Infoview for EPG programs lacks correct action buttons

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#37]
**How should this work?**
There should be PLAY button for catch-up and SWITCH TO button for playing PVR stream

**How is it now?**
 There is only PLAY button which does no action
![s5](https://user-images.githubusercontent.com/679205/172047475-bdb48e9e-3979-4380-8387-7b94d32ca7a0.jpg)

**Comment by Dis90** [comment]
Same problem here. Play button doesn't do anything.
