### ISSUE TITLE
[Feature] Option to hide date

### ISSUE THREAD

**Issue by piejanssens** [jurialmunkey/skin.arctic.horizon.2#372]
### Skin section

Home Widgets

### Feature description

I would like to have the option to hide date and only show the time (centers of time and settings icon aligned vertically).

### Why is this feature needed? Please justify and explain.

Less cluttered UI

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Added with "minimise" furniture option.
