### ISSUE TITLE
[Feature] TV Show (and Season) Info Line Episode Counts

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/skin.arctic.horizon.2#376]
### Skin section

Home Widgets

### Feature description

First of all, apologies for so many messages.

Now that you have got the End Time and Duration parts working well (thank you for that, by the way), the TV show info line is looking a little barebones, with only the year and possibly the certification.
As there is the extra space, I was wondering whether there would be a way to add the watch count to the line, similar to what AH1 had.
So something that says "Watched 23 of 35".

I know the Library Views display that information on the Info screen, and bottom left, so it may be excess information there.

If you like this proposal, I could probably implement this, as it is in my skillset. 

### Why is this feature needed? Please justify and explain.

Add extra information that could be useful to viewers of a TV show widget in Fullscreen view. Also, makes the Infoline a little longer for TV shows, so it is more consistent with the info display for other items.

### Screenshots and Additional Info

![TV show infoline](https://user-images.githubusercontent.com/72696811/181294025-c62b8072-40ac-4891-a913-6795253e9927.png)
(Plot is missing, as I'm still testing that)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I'm not really keen on the idea of the information being duplicated but I agree that it looks a little sparse.

I think actually the duration info could work quite well for tvshows too:

![Honeyview_screenshot00091](https://user-images.githubusercontent.com/4618719/181458564-a03e5c25-4339-4e53-b705-096d3f78c456.jpg)

**Comment by krzysztofwinnik** [comment]
@jurialmunkey I understand you are considering adding duration to tv series in fullscreen widget, but just in case you wanted to implement this to other styles, please note that the lack of duration is the only way to determine if an item is a movie or tv series for mixed widgets like 'popular now on hbo max' or 'netflix search results'. I am not saying duration wouldn't work for tv series infoline... but if all items - no matter if they are movies or tv shows - had duration in infoline or label2 in landscape style, there should be some other way to tell which of these two they actually are.

**Comment by jurialmunkey** [comment]
@krzysztofwinnik - Good point. However, you should already be able to differentiate them by the "Quality" flag indicator at the start of the info line

Playable items (e.g. movies) will display one of Web / SD / HD

![image](https://user-images.githubusercontent.com/4618719/181463602-84979a65-69ee-413f-93b9-aa7df4e10ccd.png)

Whereas folders (e.g. tvshows) will display "i" info icon

![image](https://user-images.githubusercontent.com/4618719/181463873-a92b3166-77fd-48a1-a399-d428614dc6d5.png)

(These were both taken from the same combined widget).

**Comment by Kayzels** [comment]
Just checking: is the infoline on the Fullscreen widget the same as elsewhere? Or does it make a distinction?
Because if it is not the same, then that information isn't repeated.

**Comment by jurialmunkey** [comment]
> Just checking: is the infoline on the Fullscreen widget the same as elsewhere? Or does it make a distinction? Because if it is not the same, then that information isn't repeated.

Infoline is the same everywhere (except for VideoPlayer)

**Comment by krzysztofwinnik** [comment]
> @krzysztofwinnik - Good point. However, you should already be able to differentiate them by the "Quality" flag indicator at the start of the info line
> 
> Playable items (e.g. movies) will display one of Web / SD / HD
> 
> ![image](https://user-images.githubusercontent.com/4618719/181463602-84979a65-69ee-413f-93b9-aa7df4e10ccd.png)
> 
> Whereas folders (e.g. tvshows) will display "i" info icon
> 
> ![image](https://user-images.githubusercontent.com/4618719/181463873-a92b3166-77fd-48a1-a399-d428614dc6d5.png)
> 
> (These were both taken from the same combined widget).

Thanks for this tip @jurialmunkey - I wasn't aware of this until now
