### ISSUE TITLE
[Feature] Additional button in "VideoInfoDialog'' 

### ISSUE THREAD

**Issue by ctanyp** [jurialmunkey/skin.arctic.horizon.2#377]
### Skin section

Video Info Dialog

### Feature description

Thank you very much for adding infolines!) And also for the ability to rotate story lines in VideoOSD :) Could you please add an additional button ''Artwork beef'' or ''Artwork Downloader'' to the ''Video Information Dialog'' I I know that in the context menu there is this button in the ''controls'' but in full screen mode, unfortunately, you can not enter the context menu.  I can send you the code that fits to add this button but it seems that this code allows you to add this button only in '' Titan Bingie Mode'' Widget mode also lacks the ability to change artwork using the Artwork Beef or Artwork downloader, so an extra button like this would be very useful!)

### Why is this feature needed? Please justify and explain.

The integration of this button would make it very convenient to change the work of art (which is not in the basic version) AND have more experience in works of art!) I would really like a button like Manage artwork but which would also not work only with the ''TMDBHelper'' library but and with the Kodi library..

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Artwork beef isn't supported for Matrix because there's no need for it.

For artwork downloader, I thought this does a bulk add of all artwork. Is there a way to make it do only a single item?

**Comment by ctanyp** [comment]
And hello again!) In fact, there is a version that is supported by the matrix. But it's not from the original author) I like Artwork beef because it supports ''extrafanart'' =) The same one, for example, Artwork Dump, does not have this function) I don't know a way that allows you to integrate all available illustrations into the standard button that is now (But in the standard version there is not so much choice of the same ''clearlogo', 'Poster', 'fanart', 'landscape' So I thought maybe it could be improved somehow!) I like Artwork beef because it is so the same is supported for TV shows, unlike the same "Artwork Downloader" lol. Now I think maybe this button is really not so necessary😅😅Thank you very much for agreeing to add the function of hiding library names!) This is the function that I probably wanted most!)

**Comment by jurialmunkey** [comment]
> it supports ''extrafanart'' =) The same one, for example, Artwork Dump, does not have this function

Not true. Artwork Beef is not necessary for extrafanart.

Use Artwork Dump to export multiple fanart to your library and then scan it and you will have extrafanart. I've only ever used Artwork Dump on Matrix and all my library items have extrafanart.

**Comment by jurialmunkey** [comment]
![image](https://user-images.githubusercontent.com/4618719/181497235-19be1caa-8cfb-46c6-8e0e-235663ca5a31.png)

**Comment by ctanyp** [comment]
I haven't used Artwork Dump for a very long time and haven't seen this word before!) Thank you so much for saying😃 I disabled ''Artwork beef'' for a while and uninstalled ''Artwork Downloader''. . I'll wait and expect that it will be supported as well as ''Artwork Beef'' It would be very good actually, since I usually use two illustration loaders and I think it's not very good for performance😅

**Comment by ctanyp** [comment]
I think it's a scan)) Since I chose 20 additional illustrations😂 I hope you find it funny:D

**Comment by ctanyp** [comment]
It turns out I put on 10)

**Comment by ctanyp** [comment]
It turns out I put on 10)

Thank you very much!) It really works!)
