### ISSUE TITLE
[Feature Request] Adding buttons to the poster viewtype.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.horizon.2#379]
### Skin section

Library Views

### Feature description

Hey there, so what this feature does is that it gives you dialog on the poster view so that you don't have to go to the context menu or access the information view all the time. Its like the original Artic Horizon skin design.

### Why is this feature needed? Please justify and explain.

It's not really needed but i just thought about it and it reminded me of Artic Horizon and it gives it an Artic Horizon feel to the skin.

### Screenshots and Additional Info

 - This was what Artic Horizon has on the poster view and i thought it was a really great idea. I think it would be a great idea to have something like this in Artic Horizon 2
![pwD6R6A](https://user-images.githubusercontent.com/62456796/181609285-102329a4-93e7-4847-a4e0-b38bb192adc2.jpg)

 - This is just an example i photoshopped with and i think it would fit perfectly to give it that Artic Horizon feel. 
![Feature Request](https://user-images.githubusercontent.com/62456796/181615231-19f848ac-8b94-4d0a-81a7-4051f586fa4b.png)

 - If this feature request does get rejected, i totally understand sense it may take alot of time to add and the way the Kodi skinning engine manages grouplist alignment. Im fine with the the way it looks so far and i love this skin. 

### Checklist
- [X] I have searched the issues and this feature is kinda similar to this issue: https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/278#issue-1284662897
- [X] I have searched the issues and this feature has not been requested for poster view.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
Just my opinion but I Love the new information layout that was added to AH2 makes it unique and different from AH ,,It was actually one of the MANY really nice features that was added to make it different just my opinion

**Comment by Goldenfreddy0703** [comment]
Oh yeah I agree, I love the information page too and its wonderful especially when clicking down. I just thought about this as a feature sense it was originally on the original Artic Horizen skin.

**Comment by jurialmunkey** [comment]
Way too cramped in that screenshot. Doesn't follow spacing guides of skin. The whole point of this skin is to allow properly designed space around elements so there is breathing room rather than craming every possible thing on screen. It is a big part of what makes the skin nice to use and you will see lots of space in most modern tv guis. 


There needs to be 80px of space from poster edge and other content to allow room for divider. Divider extends 40px and then needs 40px space to info as per skin standard 40px spacing between elements.

**Comment by Goldenfreddy0703** [comment]
Ehhh that's true, there is not enough spacing and I can see why it would be way too cramped. If you were to add this tho, you would probably put an option in the skin settings or something like that. 

Thank you tho

**Comment by jurialmunkey** [comment]
I wouldn't add any option which compromises skin style guides. That's a big part of the reason for the upcoming changes to full expanded info - to bring it inline with the guides. 

If there was an option for buttons then it would replace either codecs or plot.
