### ISSUE TITLE
[REQUEST] bring back custom BACK button action in EPG view

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#38]
As for now it works the following way:
When I click BACK in EPG view, context menu pop-up is displayed. Then clicking BACK again brings HOME view to front.

Why is it wrong:
During PVR playback user presses a button mapped for EPG view and wants to go back to PVR playback by clicking BACK.
However that requires to click BACK three more times (first for opening context popup, second for closing EPG and opening HOME, and third to close HOME and bring PVR stream to front.

How should this work:
- clicking BACK while in EPG view should result in bringing the last displayed view (e.g. PVR playback) to front
- contest menu in EPG view should be mapped some other way (possibly by clicking RIGHT afrer last category item in topmenu?)

**Comment by jurialmunkey** [comment]
There's no good way to open the options menu from the EPG. Back is the best of a bad situation.

- Right from Channel Group Switcher will change the visible group, so there is no way to get the options for anything but the right-most channel group.
- EPG scrolls all directions so a direction press is not available
- Info button opens info screen so is not an option.
- The `menu` command (M on keyboard or long press C) will also open the options menu. However, for devices without a keyboard, there is no default remote button mapped to this command and many remotes don't have a spare button.

**Comment by jurialmunkey** [comment]
Option added for 0.1.6 to disable back menu behaviour
`Skin Settings > Navigation > Pressing back from EPG opens menu`
