### ISSUE TITLE
[Feature] Display Episode Name in Info Line or near

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/skin.arctic.horizon.2#380]
### Skin section

Fullscreen Video OSD

### Feature description

At the moment, the show title (with clearlogo) shows, and it's got the episode number under it, as Episode 4x01.
What I would love would be for the name of the episode to show in the info line, or somewhere on the OSD, as well as the show.
In AH1, it showed the episode name as the title, and the show name was in the info line, but I like having the show clearlogo.
That might be tricky due to excess width.
Another possibility (idk if possible) would be to right align the episode name above the episode time info, so it would be in line with the show title on the left. 

### Why is this feature needed? Please justify and explain.

It would be a nice to have. At the moment, to access that info, you need to open the episode list or the info panel, which are extra clicks. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
> In AH1, it showed the episode name as the title, and the show name was in the info line, but I like having the show clearlogo. That might be tricky due to excess width.

You've pretty much nailed exactly why the current choices were made. TVShow is the title so that it can be replaced by clearlogo; and then long episodes names are a problem in the infoline.

> Another possibility (idk if possible) would be to right align the episode name above the episode time info, so it would be in line with the show title on the left.

Right aligned text is not great -- quite difficult to read.

Definitely agree that episode title somewhere would be nice - just not quite sure *where*!

**Comment by Kayzels** [comment]
Maybe between the show title and the info line? Not sure if that might look weird. It wouldn't be consistent with the rest of the style. 
It also can't be on the same line as the title in case there is a really long clearlogo, like Brooklyn 99.

**Comment by ctanyp** [comment]
Again, sorry to interrupt!( I was just watching ''Sheriff'' and noticed the top left empty line. This is a very strange thought)) I'm sorry) But if you insert the title of the episode in the left place like the name of the widget, it would probably be very strange looked?)😅

**Comment by ctanyp** [comment]
Again, sorry to interrupt!( I was just watching ''Sheriff'' and noticed the top left blank line. This is a very strange thought)) I'm sorry) But if you insert the title of the episode in the left place like the name of the widget, it would probably be very strange looked like?)😅 Either to the left or where the date is located. It would be possible to hide the date and show the name of the series instead, but I'm not quite sure how "harmonious" it would look =)

**Comment by ctanyp** [comment]
Either to the left or where the date is located. It would be possible to hide the date and show the name of the series instead, but I'm not quite sure how "harmonious" it would look =)

**Comment by ctanyp** [comment]
It would be possible to hide the date and show the name of the episodes instead, but I'm not quite sure how "harmonious" it would look =)
An interesting opportunity to replace the name ''Pause'' with the name of the episodes during a pause *

**Comment by Kayzels** [comment]
> It would be possible to hide the date and show the name of the episodes instead

@ctanyp I wouldn't want to lose the air date, personally.

> An interesting opportunity to replace the name ''Pause'' with the name of the episodes during a pause. 

It's not always paused showing there, it's the status, so if it's caching it shows the cache percentage. That's a useful thing I wouldn't want to lose.
It also wouldn't work properly if you have a long episode name, like all the Friends episodes that start with "The One..."

Obviously I'm not @jurialmunkey, and what he says goes, but I just thought I'd give some input 😄

**Comment by ctanyp** [comment]
But I also thought that all these ''free spaces'' are not for this purpose) And I don't know where else😅 Therefore, @jurialmunkey probably still can't find a suitable free space that would fit the general design of the player) But me I really like the logo!) As for the name.. I don’t know, but the absence of it didn’t bother me at all!) Moreover, there are even much better ones 😀 The ability to see the names of all episodes at once/switch is very convenient and fast without leaving the player😌

**Comment by ctanyp** [comment]
But I also thought that all these ''free places'' are not for this purpose) And I don’t know where else😅 I really like the logo!) As for the name .. I don’t know, but the absence of it didn’t bother me at all!) Especially there is even much better 😀 The ability to see the names of all episodes at once / switch is very convenient and fast without leaving the player😌

**Comment by jurialmunkey** [comment]
Yeah I wouldn't want to replace other info or move things around (e.g. no changing clock or replacing other parts of the infoline). Any change should aim to for more consistency of elements not less. 

Top left is possibly a good choice though (I had the same thought). Then that same position could adapt for movies/livetv to display chapter or channel numbers.

![Honeyview_screenshot00106](https://user-images.githubusercontent.com/4618719/181875895-6be91e1c-b25b-44c2-9846-d8123071e7ba.jpg)

**Comment by ctanyp** [comment]
And hello again @jurialmunkey!) I understand you ..) I That is, in order to insert some element, there must be consistency with all elements that will be in focus along with this element .. I seem to understand it this way) As for the left line, look good!) I like it..) But I wonder how it would look with longer episode titles? Most episode titles are not that long, limited to 3-4 words per sentence. But it also happens 😅 ''I'm Luffy! The Man Who's Gonna Be King of the Pirates''! In principle, I think this is also not a problem, since long names can be made a little shorter in your own way with the help of an editor add-on)

**Comment by ctanyp** [comment]
Is it possible in the case of a movie to add an option that will show the slogan of the movie instead of the chapter number?  Although the slogans have longer names of course..

**Comment by jurialmunkey** [comment]
I think the tagline for a movie will be too long. Long episode titles are not too bad but I think taglines can get even longer and I wouldn't want it to be much longer than this:

![Honeyview_screenshot00110](https://user-images.githubusercontent.com/4618719/181906523-8661e2ec-de04-417d-94fd-571e8a9c7718.jpg)

**Comment by ctanyp** [comment]
The slogans are really probably not something that should be located in this free area..) I agree with you.. But the titles of the episodes look very good!) I really like it!) I thought it would look a little worse, but it looks good even in case with long episode titles. To some extent, it even stirs up interest in viewing :)

**Comment by ctanyp** [comment]
Sorry for asking a question that is not related to this topic! I just wanted to ask all the time. In the case of future flixart/keyart mode changes, will extrafanart work? I will delete the message if that would not litter the extra garbage.

**Comment by Kayzels** [comment]
I like the name in the top left, like in the screenshots. If that's what you implement, that would be a +1 from me, and would close the issue 😃

**Comment by Kayzels** [comment]
I don't mean to nag - I'd just like to know if this is still something planned?

**Comment by jurialmunkey** [comment]
> I don't mean to nag - I'd just like to know if this is still something planned?

Oops. Forgot to assign it to the milestone.

Yes definitely planned - I'm quite happy with the top left solution. Just got to sort out the variable to work with movies/pvr properly and then I'll merge my local branch for the feature into main.

**Comment by ctanyp** [comment]
@jurialmunkey  Could you also please add the function "hide widget labels or library names" in the next release? I will really hope!) Thank you very much)

**Comment by ctanyp** [comment]
Could you also please add the function "hide widget labels or library names" in the next release? I will really hope!) Thank you very much)

**Comment by ctanyp** [comment]
Could you also please add the function "hide widget labels or library names" in the next release? I will really hope!) Thank you very much)

**Comment by xyzfre** [comment]
This is a really GREAT feature having the episode title in the left-hand corner looks good ,,Thank you @jurialmunkey AH2 is amazing seems to get better and better ever since AH2 came out sometimes I spend more time playing with the skin And actually watching anything it's addicting lol in a positive way

**Comment by ctanyp** [comment]
Same thing!)) I also probably play with the skin more than I watch something!) It's really addictive. But yesterday I finally watched the movie in this beautiful skin) Thank you very much for the new feature @jurialmunkey :) I also really like this new feature!)

**Comment by ctanyp** [comment]
Same thing..)  I also probably play with the skin more than I watch something!) It's really addictive. But yesterday I finally watched the movie in this beautiful skin) Thank you very much for the new feature @jurialmunkey :) I also really like this new feature!)

**Comment by ctanyp** [comment]
Same thing..)  I also probably play with the skin more than I watch something!) It's really addictive. But yesterday I finally watched the movie in this incredible skin!) Thank you very much for the new feature @jurialmunkey :)  I also really like this new feature!)
