### ISSUE TITLE
[Feature] Ability to view seasons or episodes in extended widget information

### ISSUE THREAD

**Issue by ctanyp** [jurialmunkey/skin.arctic.horizon.2#381]
### Skin section

Home Widgets

### Feature description

I wanted to offer you a feature that may seem interesting and promising to you!) Especially now with the new layout of widgets! The function is that if only 1 group of the widget is installed (which does not apply to fullscreen) and it is mainly only for TV shows..That is, when pressing down any TV show in the extended widget information, a list of seasons opened instead of recommendations, or if there was only 1 season, then a list of episodes would open!) That is, it would also repeat the same thing that is in the library, but now it could also be done for convenience in the extended widget information. No problem if it's not possible :) The new look makes me insanely happy!) It's just that no one has offered something like this before, so I thought you should write my idea about it =)

### Why is this feature needed? Please justify and explain.

Perhaps this is impossible..But if this function were possible, it would greatly simplify the navigation of season selection, episodes selection, and would improve the experience in the convenience of this use!) The ability to quickly switch between TV shows without going into the details. That is, in my opinion, there is a perspective in this function!) It would be like pressing down opens recommendations, but for the 1st group widgets for TV shows, it would open a selection of seasons like a library and a selection of episodes if the season is only 1. Sorry that everything is so intricately written!(I just came up with an idea that I wanted to describe to you!)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is a really interesting idea. I like the idea but it might be difficult to implement. I'll have to have a bit of a think about how it might be handled.

**Comment by ctanyp** [comment]
I was worried that this idea would seem pointless to you!😅) I'm very glad that you liked this idea!) 🙂 At first it was inconvenient to offer a function that probably needs to be redone for extended information( But I also considered it a promising and interesting feature that might not seem unnecessary on the contrary, it is very useful for many. But yes, maybe it's not so simple( In any case, thank you very much for supporting this idea😌

**Comment by ctanyp** [comment]
I'm very glad that you liked this idea!) 🙂 At first it was inconvenient to offer a function that probably needs to be redone for extended information( But I also considered it a promising and interesting feature that might not seem unnecessary on the contrary, it is very useful for many. But yes, maybe it's not so simple( In any case, thank you very much for supporting this idea😌
