### ISSUE TITLE
[BUG] Missing dependency

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#382]
### Skin section

Other

### Current Behavior

'Customise startup image' in skin settings does nothing unless Toolbox Script is installed and active.

### Expected Behavior

Since Toolbox Script is not on dependency list I believe it should be added

### Steps To Reproduce

1. Deactivate Toolbox Script (if installed and active)
2. Go to Skin Settings
3. Click 'customise startup image'
4. See that nothing happens

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Toolbox just helps make the selection dialog to choose the image. It isn't actually used anywhere else and isn't needed once you choose an image so I dont have it as a dependency - no reason to force people to install it

**Comment by jurialmunkey** [comment]
Toolbox dependency will be removed in next version and will use native skin based custom dialogs instead.
