### ISSUE TITLE
[Feature] Option for not hiding menu when first widget row is in focus

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#383]
### Skin section

Home Widgets

### Feature description

The latest release has introduced many changes including autohiding menu if menu is not in focus.
I can see a benefit of it for new full expand widgets, but for regular widgets or plot expand widgets the new layout looks imbalanced and unintuitve when an item from first row widget is focued.

<img width="1440" alt="Zrzut ekranu 2022-07-29 o 23 28 21" src="https://user-images.githubusercontent.com/679205/181846865-065d7ac2-06ce-4afc-bacd-be626b0613b0.png">

I'd love to have an option to make my home view look as it was before the recent update - with menu and clock visible if first widget row is not full expand widget row.

### Why is this feature needed? Please justify and explain.

- the new layout seems imbalanced (lots of space above widget row, but not so much below)
- hiding menu makes it difficult to tell that the current row is the first or which menu section I'm curreently in

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Yeah I had the same though myself. Just trying to figure out a good way to identify that it is the first row because the ids can be wrong if some widgets are disabled or empty.

**Comment by jurialmunkey** [comment]
Okay I'm still struggling to find a good way to identify that something is the *first* widget (just annoying skinning engine limitations).

What about this as a compromise: Header title and clock always display with an up arrow to indicate where the menu is. That way we get a consistent look without needing another option

For example:

**Moving from Menu to Standard Widget**
![Honeyview_screenshot00099](https://user-images.githubusercontent.com/4618719/181872772-8f9393c3-06ce-4dfc-a34f-21febbe315cb.jpg)

**Moving from Menu to Expanded Widget**
![Honeyview_screenshot00097](https://user-images.githubusercontent.com/4618719/181872785-6f7f6adf-f03b-443a-bcb8-7373e0839edf.jpg)

**Moving from Menu to Expanded Widget with codecs enabled**
![Honeyview_screenshot00098](https://user-images.githubusercontent.com/4618719/181872799-06c3d74c-6722-44a4-ac54-972fddc6211e.jpg)

**Comment by krzysztofwinnik** [comment]
Many thanks @jurialmunkey - seems like a neat solution to me.

**Comment by jurialmunkey** [comment]
> Many thanks @jurialmunkey - seems like a neat solution to me.

Yeah after trying it out for a bit this afternoon, I'm actually pretty happy with it in general. Feels a lot more balanced and is more consistent overall too.
