### ISSUE TITLE
[BUG] TMDbHelper Discover not working probably with AH2

### ISSUE THREAD

**Issue by psp2111-ADSLGATE** [jurialmunkey/skin.arctic.horizon.2#384]
### Skin section

Library Views

### Current Behavior

Discover section is acting weird with AH2, I can't add more than one rule if I add a second rule the first one disappear.
I think it is a Bug with AH2 not TMDbHelper, because I changed the skin back to Estuary and Discover is working as it should be. and I can add as many rules as I want with no issue.

I also can't go to "Options" (Gear icon) inside Discover with the remote or keyboard arrows, I have to use the mouse to get to the (Gear icon) in the corner.
also Changing the Viewtype does not do anything inside Discover section, and it is stuck on "Poster Combined" Viewtype for some reason.

### Expected Behavior

TMDbHelper Discover section and changing the Viewtype should work and function like it should be when using AH2.

### Steps To Reproduce

while using AH2 as interface skin, go to TMDbHelper Discover section and try add multiple rules.
also try to change the viewtype with in that section.

### Screenshots and Additional Info

I will provide it of needed.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You can't change the viewtype in discover in AH2 - it is a special viewtype that is forced.

I'm able to add multiple rules fine. Is this only in Arabic with the ignore region setting on?

**Comment by psp2111-ADSLGATE** [comment]
> You can't change the viewtype in discover in AH2 - it is a special viewtype that is forced.
> 
> I'm able to add multiple rules fine. Is this only in Arabic with the ignore region setting on?

yes it is with Arabic with the ignore region setting on
I tried the previous tmdb release same thing!

I will try a fresh install of kodi on my other system to make sure.

**Comment by jurialmunkey** [comment]
I can't seem to reproduce the issue. Flying a little blind since I don't speak Arabic but fairly sure I've managed to add Genre=Action and PrimaryYear=1990 as rules with both my Kodi Language and TMDbH language/region set to Arabic (SA).

![Honeyview_screenshot00092](https://user-images.githubusercontent.com/4618719/181870837-60fe30bb-d857-417d-a65e-76782e1ab7c5.jpg)

I don't seem to have any issues adding additional rules.

**Comment by psp2111-ADSLGATE** [comment]
> I can't seem to reproduce the issue. Flying a little blind since I don't speak Arabic but fairly sure I've managed to add Genre=Action and PrimaryYear=1990 as rules with both my Kodi Language and TMDbH language/region set to Arabic (SA).
> 
> ![Honeyview_screenshot00092](https://user-images.githubusercontent.com/4618719/181870837-60fe30bb-d857-417d-a65e-76782e1ab7c5.jpg)
> 
> I don't seem to have any issues adding additional rules.

ok it is working now after a clean reinstall of AH2 and TMDbHelper in my main system.
I really dont know how to reproduce the bug now. maybe I cause it somehow when I was translating AH2 and TMDbHelper. and playing with every settings while doing that.
If I find a way to reproduce the bug in the next 24 hours. I will report it or close the comment.
