### ISSUE TITLE
[BUG] Arrow Down not disappearing

### ISSUE THREAD

**Issue by JacopoV** [jurialmunkey/skin.arctic.horizon.2#385]
### Skin section

Home Widgets

### Current Behavior

At the moment, since the home changes for expanded widgets, the bottom arrow icon is displayed even if there are no more rows at the very bottom.

### Expected Behavior

Considering the top arrow icon disappears at the very top, i suspect this is a very tiny tiny bug, so the bottom arrow icon should disappear if there's not more content at the bottom row in the home page.

I checked the in the extra informations page > physical arrow down , to see cast, actors etc and in that page, at the very bottom, the down arrow icon disappears :)

### Steps To Reproduce

1. Go to home
2. Be sure you have some rows of widgets
3. Scroll to the bottom and notice the down arrow icon is displayed with no further rows 

### Screenshots and Additional Info

I know it's a tiny hyper ultra small bug @jurialmunkey , i just wanted to let you know 👍 
Thanks for your all work and support. You're the king !!

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I cannot reproduce. Screenshots?

**Comment by JacopoV** [comment]
Oh interesting 🤨

I made a video so you can see the whole behavior (on shield) : https://www.veed.io/view/e93c3db2-7143-443e-951f-5ac2f6bfa796

**Comment by jurialmunkey** [comment]
> Oh interesting 🤨
> 
> I made a video so you can see the whole behavior (on shield) : https://www.veed.io/view/e93c3db2-7143-443e-951f-5ac2f6bfa796

Ah, you don't have submenu widget enabled. I know what the issue is. Give me one sec and I'll fix it.

**Comment by JacopoV** [comment]
Sure no worries, don't need to fix it now ☺️
Batch together with future changes in new releases 🎉

Thanks a lot!

**Comment by jurialmunkey** [comment]
> Sure no worries, don't need to fix it now ☺️ Batch together with future changes in new releases 🎉
> 
> Thanks a lot!

Super easy fix. There's a special condition that shows it when expanded because the slide animation pushes the submenu offscreen and you need the arrow for the mouse navigation to it. I just needed to add a condition to check that the submenu widget is actually enabled!

**Comment by JacopoV** [comment]
I see! Well glad it was a super easy to fix!

Thanks again!

**Comment by krzysztofwinnik** [comment]
Sorry to bother you @jurialmunkey, but it seems there is one more case with arrow down not disappearing that needs your attention. Please consider a scenario with just one row of fullscreen widget (no other rows, no submenu) as on photo below.
<img width="1440" alt="Zrzut ekranu 2022-07-30 o 16 11 21" src="https://user-images.githubusercontent.com/679205/181918226-e7abac70-77f4-4a4b-8a76-f89cda77c0e2.png">

**Comment by jurialmunkey** [comment]
Okay *now* I think I've sorted out all the scenarios the arrow shouldn't display!
