### ISSUE TITLE
[Feature] Option to display Group Switcher when pressing "back" in EPG

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#387]
### Skin section

PVR and Live TV

### Feature description

An option to open the Group Switcher bar when the back button is pressed when the EPG is open (as exists in AH1). 

### Why is this feature needed? Please justify and explain.

Currently to open the Group Switcher you have to press up from the first row of the EPG which can take a lot of keystrokes. Pressing 1 to get to the first row is a good shortcut but this only works if channel 1 exists in the already selected group.

In addition to the current option to "press back from the EPG" to open the options menu, pressing "M" also achieves this. So if this option existed, it would be possible to open the Group Switcher or Options Menu from the EPG. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by berkhornet** [comment]
Many thanks

**Comment by berkhornet** [comment]
Hi. I've been thinking a bit more about this, and the most logical solution may be that Menu(M) opens the Options Menu and Back optionally opens the Group Switcher. Thanks for looking at this.

**Comment by jurialmunkey** [comment]
> Hi. I've been thinking a bit more about this, and the most logical solution may be that Menu(M) opens the Options Menu and Back optionally opens the Group Switcher. Thanks for looking at this.

Yeah I think a toggle between three options is the way to go here: i.e. back either does nothing; goes to menu; or goes to switcher. Menu key would always open menu regardless of the setting.

**Comment by berkhornet** [comment]
Yep. Sounds good to me.

Mick
________________________________
