### ISSUE TITLE
[Feature] Info line tag genre

### ISSUE THREAD

**Issue by ctanyp** [jurialmunkey/skin.arctic.horizon.2#389]
### Skin section

Other

### Feature description

Sorry to bother you again! (I noticed that you added the ability to view the genre in the info bar. I actually missed something like that when viewing the info line!) Thank you very much!) Just wanted to ask you, at the moment.. For example ' 'Boys' it shows that it's a comedy (but for the most part it's crime/sci-fi and action) It's a bit disorienting when viewing information. It is hardly possible that a genre in the future would automatically accidentally end up on a genre that fits the selected content*
But in general, the matches are more or less decent :) It's just that there are some errors in my opinion in some content ..

 EDIT:Actually I think I'm probably exaggerating these inaccuracies.. I've tested it on most TV Shows and it really shows the right genre!  The only one, it shows the genre that can be immediately understood by the image of the content itself!) Therefore, it would still be very good if it could be made more informative
### Why is this feature needed? Please justify and explain.

It would be helpful. That is, this is not the most important thing, but it is a very useful thing when choosing content in full screen mode and extended information. Ability to see more ''in-depth genre information'' that cannot be understood from the image'' * For example, the movie ''Monster Truck'' at the moment shows that it is an action movie, but most of all it is a comedy and science fiction) That is, is it possible to slightly correct this information?

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The info line displays the first genre in the list of genres. If you want to see the full list of genres you need to open info. There isn't enough room to display all the genres listed.

**Comment by ctanyp** [comment]
Sorry for opening an unnecessary topic. I've tested this on most of the content and it really works properly) Now it also makes sense to enter the information dialog more often and admire it..)

**Comment by jurialmunkey** [comment]
> Sorry for opening an unnecessary topic. I've tested this on most of the content and it really works properly) Now it also makes sense to enter the information dialog more often and admire it..)

No not a problem at all. I completely see what you're saying about the first genre sometimes not being the best overall choice. It's merely a matter of space, especially since some genres are combined names  (e.g. "Action & Adventure" is one genre).

For example, "Science-Fiction & Fantasy / Action & Adventure" is already quite long and that's only *two* genres!

**Comment by ctanyp** [comment]
In fact, I really liked that only 1 or 2 type of genre is shown!) Because it made me want to enter the information dialog!) And the information dialog is also very beautiful and there is a lot of information in it) It will seem strange but it is interesting reason and method =) As if it was done for this🙂 I checked it on most and almost everywhere everything is the same!) I absolutely like how you implemented this ability to view genres :) And it absolutely does not spoil the overall look!) On the contrary, it complements🙂

**Comment by ctanyp** [comment]
Forgive me for asking this question in a closed and inappropriate topic, but I noticed that the line about the episode endings is not shown in most TV shows. For example, it is shown in a TV show called "How To Change You Mind" but in other TV shows there is no line about the end time *
