### ISSUE TITLE
[Feature] Possibility of information about the endings of the continuation after (x) number of episodes

### ISSUE THREAD

**Issue by ctanyp** [jurialmunkey/skin.arctic.horizon.2#390]
### Skin section

Fullscreen Video OSD

### Feature description

Sorry again!( I just didn’t know how to write to you and created a topic again. Don’t worry!) I won’t create another topic!) I just got one strange idea again😅 It’s something like a watch time tracker for episodes* For example, now it shows in Fullscreen OSD above the button "Stop'" all episodes of the selected season* And at the bottom there is a date line under each episode* Is it possible next to the line of the release date of the episodes in the Fullscreen OSD above the "Stop" button to add an end time like this: 1 episode: (do not write the episode only end time in 00:00 format) 1 episode:20:23,2 episode 20:46 or 1 episode 20:59,2 episode 21:55,3 episode 22:45.

### Why is this feature needed? Please justify and explain.

This is only in the Fullscreen OSD where all the episodes are located, that is, the information line is not needed!) Since it is clear that this will be very disorienting when scrolling through the episodes (But in the Fullscreen OSD, this information about the endings of the episodes is not currently located, so this function would be extremely helpful!) And it would help a lot to find out how much time you need to spend on a certain (x) number of episodes

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry, I don't understand. It already displays the duration:

![Screenshot 2022-07-31 122355](https://user-images.githubusercontent.com/4618719/182006987-58e4c801-9d50-47d0-b2dd-06d574038008.jpg)

**Comment by ctanyp** [comment]
Hello again @jurialmunkey :) For some reason, I don’t see a line about the continuation time .. Only the date.

**Comment by ctanyp** [comment]
Hello again @jurialmunkey :) For some reason, I don’t see a line about the continuation time .. Only the date. Also, for some reason, the logo for films does not work (On the example of the film "Lockout" This is not such a big problem .. But I want it to be shown 🙂 
<img width="1080" alt="Screenshot_18" src="https://user-images.githubusercontent.com/108543572/182018745-0526437c-2a9a-4d92-b514-84837b287009.png">
<img width="1920" alt="Screenshot_112" src="https://user-images.githubusercontent.com/108543572/182018750-5aab0172-76bc-4a50-b75f-d33dc6e9019c.png">

**Comment by ctanyp** [comment]
On the example of a cartoon, it looks like this (i.e. no logo, no episodes .. I will test today and tell you for sure in many TV shows this problem or only in some.
<img width="1920" alt="Screenshot_21" src="https://user-images.githubusercontent.com/108543572/182019085-656e551e-1494-479c-8590-bca5c870aed8.png">
<img width="1036" alt="Screenshot_22" src="https://user-images.githubusercontent.com/108543572/182019087-af4e6a60-b5aa-4f4a-bbe4-6244550ea20c.png">

**Comment by jurialmunkey** [comment]
> I don’t see a line about the continuation time .. Only the date. 

Then that's a problem with whatever add-on you're using. If the add-on you're using creates a playlist when playing tvshows, then the stop button will display that playlist. If the items in the playlist don't have duration that's because the add-on you're using doesn't supply duration info.

> Also, for some reason, the logo for films does not work

Check your TMDbHelper settings. TMDbHelper gets clearlogo from FanartTV via the Service Monitor so this must be enabled in API settings. Also, if your TMDbHelper language is not English then you should enable the setting for English language artwork fallbacks.

If you still aren't getting clearlogos and you have the service monitor artwork enabled and English fallbacks on then it is likely a problem with whatever add-on you're using not having enough information for TMDbHelper to find the items.

**Comment by ctanyp** [comment]
God, I can’t believe it!) Thank you so much @jurialmunkey🙏 It worked!) I suffered so much with this problem, but it turns out that the service monitor was not turned on 😅 Now it works equally well for movies and TV shows!) Thank you so much😀 I still can’t believe it that it works without problems!) But the line about the time is not displayed, but this is not the most important thing :)
<img width="1903" alt="Screenshot_25" src="https://user-images.githubusercontent.com/108543572/182020116-1a51a873-89a4-4d21-8f88-ee270075b029.png">
<img width="1920" alt="Screenshot_23" src="https://user-images.githubusercontent.com/108543572/182020123-a392c25c-4d4d-4db2-88b3-624764d35aac.png">

**Comment by ctanyp** [comment]
Sorry for asking, but just so as not to create unnecessary garbage and make a new request ..I just wanted to know if this mode will work in the "extrafanart" mode or will extrafanart only work with the "Fanart" mode in the mode change settings?
![pa0Ypm3](https://user-images.githubusercontent.com/108543572/182021010-058f43a5-3d43-414c-85df-fe8e27465754.jpg)

**Comment by ctanyp** [comment]
Sorry for asking in the wrong place!) Just wanted to ask if future style change modes will work with "extra fanart" mode?)

**Comment by jurialmunkey** [comment]
> Sorry for asking in the wrong place!) Just wanted to ask if future style change modes will work with "extra fanart" mode?)

Sorry, I don't really understand what you mean?

**Comment by ctanyp** [comment]
Sorry that maybe the question was not very clear ..) That is, I meant now in the "Customise appearance" settings it's "Fanart" "Blur" "Simple" and with the fanart mode, extrafanart works!) But will the background rotate with future modes such as flixart, keyart?) Or will the background be permanent? I really like extrafanart!) That is, in the extended information of widgets, it looks great☺ And I'm so looking forward to these new modes, I can say I can't wait 😁

**Comment by jurialmunkey** [comment]
> Sorry that maybe the question was not very clear ..) That is, I meant now in the "Customise appearance" settings it's "Fanart" "Blur" "Simple" and with the fanart mode, extrafanart works!) But will the background rotate with future modes such as flixart, keyart?) Or will the background be permanent? I really like extrafanart!) That is, in the extended information of widgets, it looks great☺ And I'm so looking forward to these new modes, I can say I can't wait 😁 It’s just that I personally would be very sorry if extrafanart doesn’t cover this .. (But if it’s necessary, then I understand everything!)

Ah I understand now. 

With flixart/keyart foreground art you have to have either None, Simple, or Blur background art. 

If you have Blur enabled then the image for flixart/keyart is static because Blur doesn't work with extrafanart. However, if background is set to None or Simple it will be possible to use extrafanart with flixart/keyart.

**Comment by ctanyp** [comment]
In fact, I may even have been afraid that there would be no support for "extrafanart" in future modes. And today there are two good news thanks to you!) I am very glad that this will also work with future modes 😀 Now I will wait for them even more!) I just don't even know what it will look like without the "Blur" mode, since I thought that the new future modes+Blur are two very strongly interconnected things that will not work without each other..It turns out there will be 🙂 But I realized it seems that then the bottom line will not change to match the background color as well as the information dialog?)Due to the fact that you have added a very convenient function that allows you to switch to the mode settings even in the library, this is not at all the problem!) That is, there are choices for every taste and color:)In a word, there are many of them:)

**Comment by ctanyp** [comment]
In fact, I may even have been afraid that there would be no support for "extrafanart" in future modes. And today there are two good news thanks to you!) I am very glad that this will also work with future modes 😀 Now I will wait for them even more!) I just don't even know what it will look like without the "Blur" mode, since I thought that the new future modes+Blur are two very strongly interconnected things that will not work without each other.. It turns out there will be 🙂 But I realized it seems that then the bottom line will not change to match the background color as well as the information dialog?)Due to the fact that you have added a very convenient function that allows you to switch to the mode settings even in the library, this is not a problem at all!) That is, there are choices for every taste and color:)In a word, there are many of them:)

**Comment by Kayzels** [comment]
Question/ request regarding the above with the duration. As it is a playlist, is the end time for the playlist available? Could that maybe be posted in the header? I'm aware that each individual episode has the duration listed, but I thought that would be a cool thing to add.

**Comment by ctanyp** [comment]
The possibility of information about the endings of a playlist of a certain season..That's what I wanted!) Even dreamed of something like this..)

**Comment by ctanyp** [comment]
Please tell me, one of me has completely stopped working YouTube? At first I noticed that the trailers did not work, then I started checking YouTube itself and in the YouTube Kodi application itself, the video also stopped working (

**Comment by jurialmunkey** [comment]
> Question/ request regarding the above with the duration. As it is a playlist, is the end time for the playlist available? Could that maybe be posted in the header? I'm aware that each individual episode has the duration listed, but I thought that would be a cool thing to add.

There is `Container.Totaltime` but it only works inside the library/playlist windows. There's nothing to give the full time of a custom container and the skinning engine can't do any math so there's no way to calculate it.

**Comment by ctanyp** [comment]
@jurialmunkey sorry for the question!) Can I find out if you have a YouTube in kodi? That is, the launch of trailers and the launch of individual videos in the Youtube-Kodi application itself

**Comment by ctanyp** [comment]
Forgive me for not answering right away .. I was just fiddling with setting up YouTube, all of a sudden the trailers stopped working for no reason and the videos also don’t play (I changed the API, deleted all YouTube data, updated and did everything that could be done ..  And authorization goes without any problems .. Then took a walk and went to bed (right now I just woke up) Thank you for explaining that such a function cannot be made real in code. To some extent I thought that this is most likely impossible (Sorry of course) But this is not the most critical!) Nothing at all scary!)

**Comment by ctanyp** [comment]
Forgive me for not answering right away .. I was just fiddling with setting up YouTube, all of a sudden the trailers stopped working for no reason and the videos also don’t play (I changed the API, deleted all YouTube data, updated and did everything that could be done .. And authorization goes without any problems .. Then took a walk and went to bed (right now I just woke up) Thank you for explaining that such a function cannot be made real in kodi due to the limitations of the kodi itself . To some extent I thought that this is most likely impossible (it's sad of course() But this is not the most critical!) Nothing at all scary!)

**Comment by ctanyp** [comment]
Forgive me for not answering right away .. To some extent I thought that this is most likely impossible (it's sad of course() But this is not the most critical!) Nothing at all scary!)
