### ISSUE TITLE
[Feature] Tweak Logo Positioning 

### ISSUE THREAD

**Issue by JacopoV** [jurialmunkey/skin.arctic.horizon.2#392]
### Skin section

Home Widgets

### Feature description

Hi @jurialmunkey,

Im opening this one in case you have the time and possibility to tweak the logo positioning. Not sure it's a bug actually, or even if it's possible to handle differently.

Anyhow, in the video below, if you pay attention to the logo, moving from content to content, it try to center itself and then move to the left, kinda like the anchor or pivot is actual the center.

https://www.veed.io/view/adfb4679-fa71-4f02-95cb-ce5065ba32a9

It's a very minimal thing to be fair, but somehow my OCD constantly focus on these bumps while browsing content.

If it matters it's on Shield. Maybe on pc it's so fast that might have a different behavior.

Anyhow, thanks a lot for your time, really appreciated.
Also, as usual, you rock!
🎉💪❤️

### Why is this feature needed? Please justify and explain.

It's a bit eye catching due the bump and repositioning, just because the rest of the skin is butter smooth and perfect 😉

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
There's not much that can be done about it. The delay is tmdbhelper cropping the logo. Either the logo is not aligned properly due to blank space or there's a delay while tmdbhelper crops it.

The only way to avoid it is to use logos that are already cropped (ie remove empty transparent space around edges).

**Comment by JacopoV** [comment]
I see, fair enough. I suspected there wasn't anything possible to do otherwise you would hade done it already 😉

Well thanks anyways!
