### ISSUE TITLE
PVR infoline customisation (same as for videos)

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#394]
### Skin section

PVR and Live TV

### Feature description

Since infoline for PVR / EPG items is different than for videos, the recent infoline customisation feature doesn’t affect it.
My idea is to introduce two changes related to the PVR infoline:
* the existing ‚genre’ radiobox should toggle displaying the first genre not only for videos, but also for PVR items (in EPG and OSD)
* there should be an option to display channel name as the first item in infoline - same way as it was in AH1

### Why is this feature needed? Please justify and explain.

This feature request is a follow-up to what has already been done in terms of infoline customisation.
On top of that - introducing genre in infoline could help distinguish genres in epg (genres are currently visible only in some of many available views), whereas channel name could be beneficial especially in pvr osd - eg. when changing channel by clicking up/down (currently there is no info which channel is active in osd)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I was thinking about this when I was adding in the genre option.

Two questions:

1. Should the setting be global (i.e. affects both types) or should PVR have its own separate Genre setting?
2. Should the PVR genre be from TMDbHelper (which is where movies/shows comes from) or should it be the PVR genre category?

In a way, I guess the answer to the second question will influence the first -- if both are coming from TMDbHelper then probably just one global setting is sufficient. However, if it is the PVR category then possibly should be its own setting.

**Comment by jurialmunkey** [comment]
For example, here's a couple of screenshots -- the 1st genre is the TMDbHelper one and 2nd is the PVR one.

You can see both "Friends" and "Storage Wars" are classified by my PVR as "Entertainment" which isn't really all that useful whereas the TMDbHelper genres are a bit more specific ("Comedy" vs "Reality"). The downside is that the TMDbHelper matches on PVR can be a bit fuzzy at times.

![image](https://user-images.githubusercontent.com/4618719/182103817-c1ee50e1-2c3c-4ac5-b73a-647531d831e6.png)

![image](https://user-images.githubusercontent.com/4618719/182103918-54de3a1c-ae2a-457c-96c0-b062c939faae.png)


Also, depending on PVR used the PVR genre is sometimes completely useless (e.g. "Other / Unknown")

![image](https://user-images.githubusercontent.com/4618719/182103986-b06726c4-4c00-4d4f-ab71-5d226e8ac4e0.png)

**Comment by krzysztofwinnik** [comment]
Yeah, you have touched an issue which is very much dependend on EPG quality. 
I'm pretty sure whatever option you decide to implement, sooner or later there will be users who would complement about it.
Perhaps it should be solved the same way PVR artwork is handled? I mean with an option for genre lookup via TMDBhelper and EPG fallback?

Personally I would be most happy with EPG genre as a default choice with only first genre, since EPG genres usually have tree structure (for example see how genre mappig work in iptv simple client: https://github.com/kodi-pvr/pvr.iptvsimple#using-a-mapping-file-for-genres)

**Comment by krzysztofwinnik** [comment]
One more thought... You say 'crime' is more specific to 'entertainment', but crime could be a movie, tv show or entertainment, while entertainment tag tells us exactly it is not a movie, nor a tv show. That is what I would expect from epg genre and why I prefer EPG genres to TMDBhelper ones.
Also, think about news, sport and local productions - they would all be very difficult to be handlend by TMDb.

**Comment by jurialmunkey** [comment]
Well, "The Wire" is definitely a tv series... It's one of the highest rated tv series of all time (No. 6 on IMDb Top 250 tv).

But fair point about sports and news etc. - TMDb will definitely struggle with those so I agree PVR backend genres will probably be the overall better option.
