### ISSUE TITLE
[Feature] Submenu names corresponding to the icons

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon.2#395]
### Skin section

Home Widgets

### Feature description

Submenu names to be displayed under the icons

### Why is this feature needed? Please justify and explain.

So that I am aware which icon relates to what before I click one.

### Screenshots and Additional Info

https://imgur.com/a/USgym8l

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What are your settings? It already has a label for me. Looks like you've chosen a style that isn't button.

![image](https://user-images.githubusercontent.com/4618719/182111184-955ca263-ad2e-4752-9959-5700eecdc56b.png)

**Comment by onlytanmoy** [comment]
Thanks mate, I had 'Image' selected against Style 😄 all good now with Style as 'Standard'.
