### ISSUE TITLE
The Global Search addon results are displayed using Estuary Skin views, add support to this addon by using one of AH2 views in it

### ISSUE THREAD

**Issue by movianlost** [jurialmunkey/skin.arctic.horizon.2#399]
### Skin section

Other

### Feature description

The[ Global Search](https://kodi.wiki/view/Add-on:Global_Search) is an old and well maintained addon that is in Kodi official repository, it only search the local library, and it does a pretty good job at it.

Right now if I use this addon on AH2, it works as expected, but the search result page that I get is using a view from Estuary Skin, so it looks like I'm using Estuary skin not AH2.

Here is a screenshot of what the search results from the Global Search looks like while using the AH2 skin latest version
![2](https://user-images.githubusercontent.com/81398427/182704626-baf245ad-fbca-4613-8e55-5eaaad2e0649.png)
So as you can see, this doesn't look like AH2 at all, this is similar to Estuary skin. Also the black font with black background is impossible to read the titles of the search results or the menu on the left.
![4](https://user-images.githubusercontent.com/81398427/182705191-efeae72a-4734-4f1e-b340-02cd7bc3b404.png)
If I choose one of the series, the same view continue and there is no way to choose a different view.
![5](https://user-images.githubusercontent.com/81398427/182705510-7db56d3d-b455-40c9-ac70-ba7e09f25f8d.png)
The same after choosing a season, the same view continue and I don't any AH2 views.

### Why is this feature needed? Please justify and explain.

The Global Search is used by many as it is very fast and reliable to search the local library, most of the skins add a new view or use one of the already created  views to change how the Global Search result page looks because otherwise, Estuary view breaks the user experience of the skin.

And to be precise, I'm not asking to replacing the internal search in home page with this addon as I know It will be difficult or impossible to do, My feature request is to make the Global Search addon work well when used so that it uses one of AH2 views instead that of Estuary.
### Screenshots and Additional Info

Here is a quotes from Ronie Team-Kodi member and the developer of Global Search addon about using custom views for his addon that I took from[ this post in kodi.tv forum](https://forum.kodi.tv/showthread.php?tid=326903)

> the main window (script-globalsearch.xml) is now a window instead of a dialog (as much requested by skinners)
> 
> the globalsearch window behaves (almost) like a regular videolibrary/musiclibrary window:
> - the addon will use DialogMusicInfo.xml / DialogVideoInfo.xml from your skin, no need to create a globalsearch infodialog anymore
> - you can define multiple viewtypes if you like
> - using Container.Content() should work
> - ListItem.Art() should work
> - you can now use normal infolabels like you're used to: for instance ListItem.Genre instead of ListItem.Property(genre)
> 
> ... **it might even be as simple as just including the views you've already created for the video/music library in the globalsearch xml file.**

And here is a mod of your skin Aura where the developer customized the look of the Global Search addon to fit into Auramod Skin.

![182433415-6e829a40-01b7-4ccb-8e6a-42875888e359](https://user-images.githubusercontent.com/81398427/182708012-06765428-a722-4d14-a713-8cfc90c2160c.png)
The above picture shows the search result page after doing a search using Global Search, This skin didn't add a new view for the Global Search addon, it just used one of the already created view and set it to be used for the results.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Closing this as fairly sure the fix to the edit control in Nexus will make the need for global search addon support obsolete anyway.

**Comment by drinfernoo** [comment]
@jurialmunkey What is this "fix to the edit control"?

**Comment by jurialmunkey** [comment]
> @jurialmunkey What is this "fix to the edit control"?

@drinfernoo - this one pending merge into Nexus https://github.com/xbmc/xbmc/pull/21746

Fixes some RTL direction and ligature handling issues in the edit control for Arabic text where the incorrect unicode block was being used and direction was flipped to LTR.
