### ISSUE TITLE
[Feature Request] Having the option to change the art style for the Fullscreen widget. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.horizon.2#400]
### Skin section

Home Widgets

### Feature description

Hey there, i was doing a new build using this skin and i came across something that might be needed. In the Fullscreen Widget, you don't have the option to choose your own art style for the widget you used. You can't choose landscape, thumb, nor icon in the Fullscreen Widget and i think its a problem.

### Why is this feature needed? Please justify and explain.

Reason why this is needed is so that you could display landscape, thumb, or icon then seeing the fanart all the time. 

### Screenshots and Additional Info

For Example this is Youtube. 
![image](https://user-images.githubusercontent.com/62456796/182716505-43099351-57ea-44e5-b576-0387ed5f002b.png)
From looking at it, its just using Fanart, its not using icon or thumb sadly. 
![image](https://user-images.githubusercontent.com/62456796/182717183-4b690b35-60d8-43ce-8f12-71f84d048e00.png)
That's why i think its a problem and i feel that it can be possible to have an option to choose what art style you would like to use. 

I know that enhancing an image or icon or thumbnail will make it blurry but it would still be nice to have an extra option  for art styles, that would be really appreciated. 
![image](https://user-images.githubusercontent.com/62456796/182716986-a4b1f845-bc61-41b9-b7b4-114320077a31.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have searched the issues and this feature could kinda similar to #250 but im unsure. 
- [X] I am using the most recent skin version.

**Comment by Goldenfreddy0703** [comment]
Actually from looking at it, you would have to stretch the image and all and the thumbnail would be pixelated so its probably not worth it. Sorry to taking up too much of you time making this feature. 

Thank you

**Comment by jurialmunkey** [comment]
Yeah really only fanart is high res enough to suit being fullscreen. I did consider the same thing for episodes but the quality was just too low. Anything less than 720p looks bad - and really only fanart is at that res or higher.

**Comment by Goldenfreddy0703** [comment]
True, thank you very much for responding, I just have one last question about those trakt genres I'm you can respond to that soon. Thank you
