### ISSUE TITLE
[Feature] Fetch tags as search result

### ISSUE THREAD

**Issue by Prahlis** [jurialmunkey/skin.arctic.horizon.2#402]
### Skin section

Other

### Feature description

Today when I use the built in search it seems to only be looking at titles. Would be great if the search results could include movies and tv shows with tags matching the search string.

### Why is this feature needed? Please justify and explain.

That way you could search for themes like 'Christmas', 'Summer', 'Stand-up' etc. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Are you talking about a search of library content?

Is it possible to use tags in smart playlists? 

The reason I ask is because anything that can be done as a smart playlist should be possible to use for search but if it isn't possible as a smart playlist then it won't work for search either.

**Comment by Prahlis** [comment]
Yes, Im talking about library content and they are indeed possible to use in smart playlist. You can set some scrapers (like UMS) to save keywords from TMDb or IMDb as tags automatically or you can add them manually to your NFO with <tag></tag>

So I imagine a search result where title matches have priority and is followed by movies with matching a matching tag. Kind of how Netflix works.

![Untitled-1](https://user-images.githubusercontent.com/1683012/183238446-080634ca-c09f-45d2-8c2c-51ebd3c69cbc.jpg)
s

**Comment by Prahlis** [comment]
Thank you. It only seems to return movie results and no TV show results though. Is this on purpose or have I screwed something up? Would be nice to have TV shows as well if it's possible. 

Thanks again.

**Comment by jurialmunkey** [comment]
> Thank you. It only seems to return movie results and no TV show results though. Is this on purpose or have I screwed something up? Would be nice to have TV shows as well if it's possible.
> 
> Thanks again.

It's only movies. Kodi smart playlists can't mix different types of content together.

As far as I could tell, there aren't any TV scrapers that provide tags anyway so I didn't add a TV version.

**Comment by Prahlis** [comment]
> > Thank you. It only seems to return movie results and no TV show results though. Is this on purpose or have I screwed something up? Would be nice to have TV shows as well if it's possible.
> > Thanks again.
> 
> It's only movies. Kodi smart playlists can't mix different types of content together.
> 
> As far as I could tell, there aren't any TV scrapers that provide tags anyway so I didn't add a TV version.

That's, true. It would be only for manually added tags. Sadly I don't know if any such scraper either.
