### ISSUE TITLE
[Feature] Option to change back full info design

### ISSUE THREAD

**Issue by LucifersCircle** [jurialmunkey/skin.arctic.horizon.2#404]
### Skin section

Home Widgets

### Feature description

I don't really know if this was an intentional change or not, but its been like this for a few builds now so I am going to hope there is a way the old "full info" on widgets can be adjusted to how it was in the 0.2.53 build. Newer builds shows duplicate information and doesn't display the description quite as well in my opinion. I've browsed the settings quite a bit but haven't found anything so far that could help me achieve this without simply downgrading the version I'm on. I've attached images to hopefully explain better.

### Why is this feature needed? Please justify and explain.

After version 0.2.53 the full info widget looks worse to me.

### Screenshots and Additional Info

Newest view (0.3.11 - the info shows only one line, and takes at least 10s to start scrolling).
![image](https://user-images.githubusercontent.com/31424518/183296858-2ebadaba-b812-4d8e-891e-119d327ebad7.png)

Newest view (often repeats info already in the header, like title/season/episode).
![image](https://user-images.githubusercontent.com/31424518/183297054-e97c02b6-5740-4a67-86b5-854688daa54a.png)

Old view (as of version 0.2.53 shows the whole description and has no duplicate information).
![image](https://user-images.githubusercontent.com/31424518/183297248-07a2caa5-d02f-431f-ad7e-28799c875ef1.png)

I wanted to make an edit here to show that it looks especially bad in the calendar widget.
Newest view
![image](https://user-images.githubusercontent.com/31424518/183298028-285d02af-1fa6-4ef8-b638-ba73331b02a1.png)

Old view (0.2.53 - gives a good glance at everything from title to air date to the full description that only needed one line, however on the new view you would have had to wait 10s to see that it was only one line anyway). 
![image](https://user-images.githubusercontent.com/31424518/183298114-36f4f85f-ab6c-4ff4-bdb7-8c67f1679f3e.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Kayzels** [comment]
There was a whole discussion about this over [here](https://github.com/jurialmunkey/skin.arctic.horizon.2/discussions/361).

If you want 2 lines to show instead of 1, have the line for codecs enabled, which will move the widget title to the top.

**Comment by LucifersCircle** [comment]
> There was a whole discussion about this over [here](https://github.com/jurialmunkey/skin.arctic.horizon.2/discussions/361).
> 
> If you want 2 lines to show instead of 1, have the line for codecs enabled, which will move the widget title to the top.

Thank you! This has added a second line and already is looking better, however the duplicate informations are still there, specifically in the, “Next up, Calendar, Continue watching” widgets. Plus enabling the codec information kind of obscures the next widgets title (not the biggest issue but I didn’t want to display this codec information in the first place). I do love this skin though and hope there can be another solution!

**Comment by jurialmunkey** [comment]
None of this pink text or anything of that sort is added by me. That's due to whatever addon you're using. The only info I display in the section under ratings is plot. I can't help it if the addon your using fills the plot with extra information.
