### ISSUE TITLE
[BUG] Clear logo showing on episode thumbs for some TV Shows

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#405]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

I noticed that the clear logo is showing on top of episode thumbs for some TV Shows like "The Sandman". For others like "Black Bird" it's not showing which I guess is correct.

### Expected Behavior

The clear logos should only show on landscape images for TV Show main images (poster landscapes) and not on their episode thumbs or am I wrong? Please advise.

### Steps To Reproduce

Go to "The Sandman" TV Show episode page. The clear logos will show on top of episode thumbs.

### Screenshots and Additional Info

![IMG20220808012850](https://user-images.githubusercontent.com/65297828/183309234-0f7718b8-a265-4cee-ae9e-463dac4038c7.jpg)

![IMG20220808012936](https://user-images.githubusercontent.com/65297828/183309236-9285f62c-2b8a-412d-bc5c-1b5996facae3.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I'll double check when I'm back at home, but I don't remember anything like that being added. It's possibly the actual artwork itself.

**Comment by ShibajiCh** [comment]
> I'll double check when I'm back at home, but I don't remember anything like that being added. It's possibly the actual artwork itself.

Hi @jurialmunkey,

Fine. I shall wait for your update.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Fine. I shall wait for your update.
However, I checked on TMDB website now and the thumbs for that TV Show's episodes don't appear to have the clear logos embedded on them. See screenshot below.

![Screenshot_2022-08-08-07-45-41-07_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/65297828/183325344-501a6a60-7261-44db-88de-963fdb90e7ff.jpg)

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Ah yep, you're right. It's on standard landscape view that the logo is not added. On big landscape it is added to attempt to fake landscape art by overlaying the logo on fanart.

Not sure why I only did that for big landscape and not the standard one. Either way, should be fixed now.

**Comment by ShibajiCh** [comment]
Thank you @jurialmunkey !
