### ISSUE TITLE
[BUG] Custom Search Path for TMDB Sets (Collections) widget not displaying any results

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#406]
### Skin section

Other

### Current Behavior

Hi @jurialmunkey,

If I'm not wrong then the custom search path for TMDB Sets should redirect to TMDB Collections which should be:

plugin://plugin.video.themoviedbhelper/?info=search&tmdb_type=collection&widget=true&query=

However, the current TMDB Sets widget option under custom search is not redirecting to Collections and not displaying any results.

### Expected Behavior

The TMDB Sets option under custom search should redirect to TMDB Collections.

### Steps To Reproduce

Go to custom search, select TMDB Sets under Widget option. No results display on searching.

### Screenshots and Additional Info

![IMG20220808020618](https://user-images.githubusercontent.com/65297828/183310371-3889a14f-340b-4a17-b1c2-4921715f3462.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Oops. Capitalisation issue so path wasn't getting added properly in the template.

**Comment by ShibajiCh** [comment]
Thank you @jurialmunkey !
