### ISSUE TITLE
[Question] Where is "available updates" option?

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.horizon.2#41]
If you have updates set to "notify, but dont install updates" where on earth is the available updates listing?

![screenshot00018](https://user-images.githubusercontent.com/25871666/172053989-9ef3d7ec-4b8e-48bb-a343-d475e8b6f425.png)

It doesn't appear to be in main addons menu, (Where we have recently updated etc) but its also not on the right hand context menu (Where install from zip is)

I have updates available, but zero idea how to install them outside of drilling down into the repo > addon and updating there :')

**Comment by jurialmunkey** [comment]
Should be fixed in 0.1.5 - Adds an option under "Recently Updated" if there are updates available.

I'll leave this issue open for the time being as it is one of those things that's a little bit difficult to test properly but fairly sure it is fixed.

**Comment by Weevild** [comment]
@dm2912 Sorry for this being unrelated, but how did you go about adding the "check for updates" card? And does this check for new Horizon 2 updates or just Kodi updates?

**Comment by dm2912** [comment]
> @dm2912 Sorry for this being unrelated, but how did you go about adding the "check for updates" card? And does this check for new Horizon 2 updates or just Kodi updates?

push the remote all the way to the right to bring up the side menu

(there may be easier ways on desktop or on android devices - im using my tv remote via hdmi cec to coreelec so i just push it to the right)

**Comment by onlytanmoy** [comment]
> push the remote all the way to the right to bring up the side menu

yeah, I have to do the same thing on my Shield TV Pro with the shield remote.
