### ISSUE TITLE
[Feature] Playback speed additions

### ISSUE THREAD

**Issue by jhawkstar** [jurialmunkey/skin.arctic.horizon.2#410]
### Skin section

Fullscreen Video OSD

### Feature description

Hi,

Is there any way to add more "incremental" playback speeds, I think at the moment there is x1, x2, x3, -x1, -x2 etc

Youtube for example which I think is perfect offers 0.25, 0.5 etc, which allows you to watch things essentially "in slow motion" (See attached)

Is there any way of adding this to the skin, or is this more of a Kodi issue?

Thanks! :)

### Why is this feature needed? Please justify and explain.

Adds the ability to watch in slow motion

### Screenshots and Additional Info

![Playback speed](https://user-images.githubusercontent.com/110822707/183402639-31e13b58-3589-4596-a0f6-948b45b8e655.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Already exists. 

![image](https://user-images.githubusercontent.com/4618719/183406526-c9d7a169-4694-4842-af91-292912c13272.png)

https://kodi.wiki/view/Settings/Player/Videos#Sync_playback_to_display
