### ISSUE TITLE
[Feature] Cast Information - Movies and TV Shows does not show title, year on selection 

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon.2#413]
### Skin section

Video Info Dialog

### Feature description

Cast Information - Movies and TV Shows displays results without title and year, can we have expand info option for that like how we have under search menu customisation?

### Why is this feature needed? Please justify and explain.

When I select a result (poster) from either Movies/TV shows as cast member, it should display name and year on the top/bottom of the poster. Please see screen record for details- https://streamable.com/lhtvtc

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
Must be a setting you miss cause I checked on my end and it does display the full info widgets

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/183498636-31a675d0-dc0b-493e-8600-68a3fd56dbff.MOV

**Comment by jurialmunkey** [comment]
I can't remember exact setting name off the top of my head as I'm not at my computer but GOTO skin settings and under details you can customise recommendations including enabling expanding plot. 

Skin settings > details > customise recommendations > expand plot
