### ISSUE TITLE
[BUG] Sub-menu widgets no longer display (since release 0.3.13)

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#414]
### Skin section

Home Widgets

### Current Behavior

Sub-menu widgets do not display on home page.
![screenshot00005](https://user-images.githubusercontent.com/67786207/183481589-dd93d421-45f2-4750-bd8b-0e2ac974fc81.png)

### Expected Behavior

Sub-menu widgets display, as in release 0.3.12.

![screenshot00007](https://user-images.githubusercontent.com/67786207/183486370-64dcd43e-63be-4746-b6a3-cf5db2cee423.png)

### Steps To Reproduce

1. Install release 0.3.12
2. Create menu item with a sub-menu widget
3. Show home page (sub-menu widget should display)
4. Install release 0.3.13
5. Show home page (sub-menu widget will not display)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by berkhornet** [comment]
Screenshot from 0.3.12

![screenshot00006](https://user-images.githubusercontent.com/67786207/183485712-a9d775e5-113d-4cf0-9e76-a6dd6297115f.png)

**Comment by berkhornet** [comment]
Screenshot from release 0.3.12

![screenshot00007](https://user-images.githubusercontent.com/67786207/183486165-bcc3726c-d4f8-4470-9bc1-51bfbb0975d4.png)

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Yes, like @berkhornet I too noticed that the submenu widget vanished after the latest update. See screenshot below:

![IMG20220809011602](https://user-images.githubusercontent.com/65297828/183501979-32adf9cf-d20b-4675-bc82-2969441ac3cb.jpg)

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
I have also noticed this too and hope this could be fixed soon.

**Comment by jurialmunkey** [comment]
I made a quite significant change to underlying include methods to workaround a crashing issue on Linux. It pretty much required changes everywhere in the skin - I probably just made a typo somewhere as there were a lot of little annoying changes to make.

**Comment by Goldenfreddy0703** [comment]
> I made a quite significant change to underlying include methods to workaround a crashing issue on Linux. It pretty much required changes everywhere in the skin so I wasn't able to test everything properly - I probably just made a typo somewhere as there were a lot of little annoying changes to make. Ill look into fixing for next update.

Thank you very much.

**Comment by berkhornet** [comment]
Many thanks for the prompt fix.

**Comment by ShibajiCh** [comment]
Thank you @jurialmunkey !
