### ISSUE TITLE
[Feature] Speech to text on the Search Bar.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.horizon.2#415]
### Skin section

Search in the home menu bar

### Feature description

Hey there, I use a google tv for kodi and its been the best but on the search in the home menu bar, i press it and it shows the keyboard layout and all and when i hold down in the keyboard layout, i get this option to use Speech to text. 

Is there anyway i can have that option when just holding the search in the home menu bar and not in the keyboard layout?

### Why is this feature needed? Please justify and explain.

It's not really needed but i thought it would be a great future to add for people that use android tv's and that have the voice search with kodi. 

### Version:
Android TV 10
Kodi v20 (Nexus) Alpha2 

### Steps the reproduce to use Speech to text: 
1. Download any version of Kodi v20 (Nexus) on any android tv of your choice. (I do recommend this test build if you have a 32bit Android TV: [Arm32-v7a](https://mirrors.kodi.tv/test-builds/android/arm/kodi-20220712-0dc430d1-transparent-controls-26098-armeabi-v7a.apk))
2. After installing Allow Microphone and Storage in the app permissions. 
3. Launch Kodi and download  and add the Artic Horizon 2 skin.
4. To use Speech to text, click the search in the home menu bar.
5. Hold the done key or any other key on the keyboard layout. 
6. You will notice Speech to text on the top right. 

From the steps reproduced, if you hold on the search in the home menu bar. Nothing happens which is why i requested this to be a feature. 

### Screenshots and Additional Info

On the Keyboard layout, if you hold on any button, Speech to text shows up on the top right of your screen. 
![image](https://user-images.githubusercontent.com/62456796/183499467-d03cbb91-9ab3-4bee-9126-22511c7d043a.png)

If i could hold on the search bar instead of the going to the keyboard layout for speech to text, that would be really great. 
![image](https://user-images.githubusercontent.com/62456796/183499704-5007af19-8ae7-4bfc-823e-da71a3e922cc.png)

Sorry for not explaining this future really well. I can't really screenshot my android tv cause i don't have a capture card on me at the moment. If you need more context on this, i will try my best to explain it better. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I don't have an Android device so I have no idea. Pretty sure this is a kodi feature you would need to request for edit controls.

The search menu just uses a standard edit control, so kodi would need to add a feature to allow using speech to text on an edit control.

**Comment by Goldenfreddy0703** [comment]
Oh i didn't think you would need to request for edit controls cause i just thought, if you could make custom keyboards like Auramod did with the Netflix style keyboard, you could also make a part of the skin have speech to text as well. Oh well, thank you for telling me and maybe i can talk to the xbmc devs about adding speech to text as a edit control. 

Thank you

**Comment by jurialmunkey** [comment]
At least I'm not aware of anything like that for edit controls but it's also not something that I use personally so I dont really have any experience with it.

The edit control takes normal keyboard input so I would expect some sort of speech recognition that sends keyboard input would work - just not aware of something directly in the skin that you do (I imagine on-screen keyboard it is built in)

**Comment by Goldenfreddy0703** [comment]
> (I imagine on-screen keyboard it is built in so it automatically works if enabled)

True, i always thought that when your on a touchscreen phone or tablet, it would open up an on-screen keyboard and i never understood why that is not a feature cause it would be very useful if you were on a phone or tablet and you can type without having the keys being too small.
