### ISSUE TITLE
[BUG] HighContrast+Darker theme has poor contrast for EPG progress bars

### ISSUE THREAD

**Issue by chcore** [jurialmunkey/skin.arctic.horizon.2#417]
### Skin section

PVR and Live TV

### Current Behavior

This might be just my viewing setup, so I don't mind if you close this issue if you are not experiencing it.

In the various EPG views, there are progress bars for each channel. These can be quite difficult to see at a glance with the HighContrast+Darker theme, as the "filled" part is very similarly dark to the "non-filled" part.

### Expected Behavior

The progress bars should have better contrast to be more easily visible

### Steps To Reproduce

1. View the EPG in any of these views: Default, Fullscreen, Information, Detailed
2. Observe the low contrast on the progress bars

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The "HighContrast" scheme is probably badly named. 

The purpose isn't to make individual elements have higher contrast. The purpose is to make background blacks darker and foreground text whiter: i.e. there is greater contrast range between the foreground text overlayed on the background image.

**Comment by chcore** [comment]
There may have been some slight miscommunication on my part, I'm wasn't trying to suggest "the high contrast theme must be high contrast at all times". I just prefer using the theme because I really like the dark elements (they look particularly nice on an OLED screen) and happen to find these progress bars difficult to see when compared to other user interface elements. Just with my eyes and my display though.

**Comment by jurialmunkey** [comment]
One possible option might be to flip the colour

A light progressline definitely helps with visibility on unfocused items, but comes at the expense of visibility on the focused item:

![Honeyview_screenshot00146](https://user-images.githubusercontent.com/4618719/183602951-3e35c59a-ac66-436f-8b8b-f142a4756091.jpg)

By comparison, the darker progressline has much better visibility on the focused item but is definitely much poorer visibility especially when HighContrast schemes are in action and background is dark

![Honeyview_screenshot00149](https://user-images.githubusercontent.com/4618719/183603025-1d779d67-de9d-4b7e-955f-51c7c3e251c0.jpg)
