### ISSUE TITLE
[BUG] Auto Match Framerate NOT triggering when playing Trailers from the Context Menu Info tab

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.arctic.horizon.2#419]
### Skin section

Other

### Current Behavior

There seems to be a bug that for a while I’ve been trying to ping point until recently. If you set Kodi to Auto Match FrameRate on “Start/Stop” video Playback. You usually get a brief black screen flash every time before you play a video file which is Kodi setting your display’s Framerate to match the video file’s recorded FPS. Fine, it always work regardless of being a YT video trailer, or any other file you might select. Since a while back I’ve been noticing that whenever I’m navigating through titles when using either AH1, AH2, etc. If I select a title and open **context menu**, click on **Information** you get the **Trailer** option. Now here’s the issue when I click on the **Trailer** option from **Information** tab under context menu. The Display doesn’t flash and it just plays the trailer without triggering the Framerate matching. For a while I thought it was something wrong with the YT addon in Kodi since when you play a trailer it opens in within the YT addon if I’m not mistaken. Furthermore, I discovered it’s not the YT’s addon fault it’s that there seems to be a bug within the Information tab under context menu that when you click on play the trailer it does NOT trigger the Auto Framerate match automatically the only way is if you, navigate through **Context Menu**, then **Browse Lists**, then select **Videos**, then play the trailer through there it will play it correct which is flashing a black screen a second or 2 before it opens the video. 

### Expected Behavior

When clicking on **Trailer** from the **Context Menu**, **Information tab** the display should flash a black screen 1-2 seconds before the video starts meaning that Kodi successfully Auto Matched Framerate from Display and Video when having Auto Match Framerate set to Play/Stop from Kodi settings.

### Steps To Reproduce

1. Go to Kodi Settings, Player, Videos, Playback

2. Set: Adjust display refresh rate ON Start/Stop

3. Navigate to any movie, tv show title, open context menu, click on Browse Lists, go to Videos, click on any trailer, your screen should do a black screen flash 1-2 seconds before the video starts.

4. Now, again within the same title, open Context Menu, go to Information, click on Trailer.

5. See issue, the screen won’t do the black screen flash before the video starts and it will just open the video directly, meaning Auto Framerate Match didn’t trigger. When video starts hit on any button from remote or key and before OSD seekbar appears it will do a Black Screen Flash meaning It triggers the Auto Framerate Match manually instead somehow which seems more like a bug to me.

### Screenshots and Additional Info

I recorded a click that I could post showing the issue but it seems useless because it doesn’t capture the black screen flash moments. So pretty much the only way to see it is by doing it manually through your own screen with the steps I provided above. After you review this, if you find out this is more of an TMDb issue than the skin let me now. However, I did tested the issue with the Default Stuary Skin from Kodi and the bug is NOT present and auto match Framerate triggers normally when playing trailer from Information tab from context menu. Which leads me to believe and decided to post it as a Skin bug since it also happens on AH1 as well. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Trailer is set to play in background to avoid closing the info dialog. Refresh start / stop only happens when fullscreen video window opens.

There's nothing that can be done for this without forcing the info dialog to close which is undesirable.

**Comment by Nuklear92** [comment]
> Trailer is set to play in background to avoid closing the info dialog. Refresh start / stop only happens when fullscreen video window opens.
> 
> 
> 
> There's nothing that can be done for this without forcing the info dialog to close which is undesirable. 

Oh, I understand. Well it's fine, I'm already kind of used to the issue either way. I just wanted to share the findings since I didn't know what was the cause or if it was a bug of some sort. 😅 Thanks for the clarification.

**Comment by jurialmunkey** [comment]
Yeah I also notice it and it's really annoying - there's just no way to play fullscreen video without closing the video info dialog. It's because the fullscreen video is a window whereas info is a dialog on top - basically it's a "need to take off your shoes to change your socks" type of thing. 

The setting to turn off the mini trailer just fakes fullscreen by overlaying a video control on top of the dialog - that's why clicking into the trailer does change the refresh because that switches to the real fullscreen video window (but also closes info).

**Comment by Nuklear92** [comment]
> Yeah I also notice it and it's really annoying - there's just no way to play fullscreen video without closing the video info dialog. It's because the fullscreen video is a window whereas info is a dialog on top - basically it's a "need to take off your shoes to change your socks" type of thing. 
> 
> 
> 
> The setting to turn off the mini trailer just fakes fullscreen by overlaying a video control on top of the dialog - that's why clicking into the trailer does change the refresh because that switches to the real fullscreen video window (but also closes info). 

Gotcha, this further clarifies the the problem. Definitely understand why the refresh isn't triggered automatically and instead happens when you click any button of the remote after the trailer is playing. 

No worries then, I'll just continue with the same routine of clicking any button from the remote as soon as the trailer start playing so the Framerate matching is set. 😅

Thanks for the explanation! 👍
