### ISSUE TITLE
Blank Screen on Open Wizard

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#42]
I use OW to do back ups and restore unfortunately when I try to open it I just get a black screen I also tried EZ Maintenance And the same thing also get a black screen

**Comment by jurialmunkey** [comment]
Is it a program add-on? 

MyPrograms isn't skinned yet. See TODO list

**Comment by xyzfre** [comment]
So far loving the skin runs smooth,AMAZING work thank you @jurialmunkey

**Comment by jurialmunkey** [comment]
Is this fixed now? Should be fixed now that MyPrograms is in.

**Comment by RagnarLothbrok-Odin** [comment]
I use OW, and can confirm it is now working.

**Comment by xyzfre** [comment]
> Is this fixed now? Should be fixed now that MyPrograms is in.

I can confirm as well it is working thank you @jurialmunkey
