### ISSUE TITLE
Widget Video Playlists 

### ISSUE THREAD

**Issue by erwin-hc** [jurialmunkey/skin.arctic.horizon.2#422]
### Skin section

Home Widgets

### Feature description

Hello! Thanks for this wonderful skin!
I'd like to set one of my vídeo playlists as a widget, but it's only showing two of them for pickup, is it a normal behavior? 
I want to set the video playlists generated for themoviedbHelper ...

### Why is this feature needed? Please justify and explain.

I think is faster to load widget this way.

### Screenshots and Additional Info

![IMG_20220811_124939](https://user-images.githubusercontent.com/34582476/184177201-f36dbcec-fc42-4977-871c-98b747816bea.jpg)
![IMG_20220811_124924](https://user-images.githubusercontent.com/34582476/184177214-e63fd814-fd4c-4a68-9ac9-ea6e36563b36.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skinshortcuts issue. Not much the skin can do about it. You'll need to ask in the skinshortcuts thread on the forum why your playlists aren't showing up.
