### ISSUE TITLE
[Feature] Additional info in "Media Info Wall" view

### ISSUE THREAD

**Issue by 43v3rLoCo** [jurialmunkey/skin.arctic.horizon.2#423]
### Skin section

Library Views

### Feature description

Would it possible to add the title of the movie and the genre of it in the info part of the dialog?

### Why is this feature needed? Please justify and explain.

Some movies do not have the title of it in the poster and don't show in the info part either. I am attaching a pic of an example. As for the genre, other views display it, so I think it would be great if the info wall had it as well. 

Thanks. 

### Screenshots and Additional Info

![screenshot00001](https://user-images.githubusercontent.com/13120383/184181655-f2d77576-53c1-41ca-b8d5-a7c74a8ca76d.png)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Both pieces of information are available already:

![Honeyview_screenshot00155](https://user-images.githubusercontent.com/4618719/184289301-42902866-c8c9-470f-aec6-bcf101fd7350.jpg)


You just need to have landscape art available. If not landscape art is available, the skin will overlay the clearlogo instead.

Genre can be enabled in Skin Settings > Details > Info line

**Comment by 43v3rLoCo** [comment]
You're awesome! 
Thank you!
