### ISSUE TITLE
[BUG] Widgets not respecting Media Settings>Videos>Default select action>Resume

### ISSUE THREAD

**Issue by titelheld** [jurialmunkey/skin.arctic.horizon.2#424]
### Skin section

Home Widgets

### Current Behavior

My Kodi is set to automatically resume videos without asking. (Kodi settings>Media Settings>Videos>Default select action>Resume)
This works correctly while inside the TheMovieDB Helper addon where when I select a video to play and it does not ask whether I want to resume or start from the beginning.

However when playing the same video from an Arctic Horizon 2 widget Kodi asks whether to resume or not. (The pop-up that shows when selecting [Kodi settings>Media Settings>Videos>Default select action>Play] in the Kodi settings.

### Expected Behavior

Not being asked whether to resume or not when playing a video from an Arctic Horizon 2 widget when (Media Settings>Videos>Default select action) is set to Resume.

### Steps To Reproduce

1. Go to Media Settings>Videos>Default select action and set to Resume
2. Go into TheMovieDB Helper addon and select a video to play.
3. Kodi does not ask whether to resume or not.
4. Select the same/or any other video with resume point from a TheMovieDB Helper widget on the home screen and play
5. Kodi shows the pop-up that asks whether to resume or not.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Neither the skin nor the addon controls this behaviour. It is kodi which opens the context menu to resume

**Comment by titelheld** [comment]
I understand that as the (Media Settings>Videos>Default select action) is a Kodi setting.

I am just a bit perplexed that when setting it to **Resume** and selecting a video from within TheMovieDB Helper addon (ex. Your in progress Movies) it does not open the context menu. But when selecting the video through a widget that points to the exact same TheMovieDB Helper list it opens the context window.
Does Kodi then treat Widgets and addons differently in regards to what is set under (Media Settings>Videos>Default select action)?

**Comment by titelheld** [comment]
I would have expected that the triggered action would be the same for videos addons and widgets.

That is why i thought that perhaps the widget does not adhere to what is set under (Media Settings>Videos>Default select action).

**Comment by jurialmunkey** [comment]
I did a quick test and it also happens in Estuary for in-progress widgets on library items. So it is neither a skin or addon issue. Kodi simply does not apply the default select action to widget container items.

If this issue also occurs on latest Nexus nightly then I would suggest opening a bug report on Kodi xbmc github: https://github.com/xbmc/xbmc/issues/new?assignees=&labels=&template=bug_report.md

See also: https://forum.kodi.tv/showthread.php?tid=368880

And here you can see in Estuary it also happens despite my default play action being resume:

![Honeyview_screenshot00154](https://user-images.githubusercontent.com/4618719/184288081-534ec22e-6519-443c-8007-8d64abe730a6.jpg)

**Comment by titelheld** [comment]
Thanks for taking the time to test. 
I will give this nightly build a try and perhaps file an issue with the kodi repo.
