### ISSUE TITLE
[Feature] pvrosdchannels

### ISSUE THREAD

**Issue by Tee77** [jurialmunkey/skin.arctic.horizon.2#425]
### Skin section

PVR and Live TV

### Feature description

On the skin’s initial release, pvrosdchannels (against a dark background) was attached to the stop button, which has now moved to the menu icon on pvr osd. Not sure if it was meant to behave like this, but it used to reset itself to the current channel being watched each time it was opened. Is this still possible or was it just a bug on release? I’d actually love to see this behaviour in the main guide as well but imagine there’s probably a reason why this doesn’t already happen. 

Also, regarding the stop button’s channel list…would it be possible to have both direction up/down initiate navigating the list rather than just direction up? It would feel more natural pressing down twice to get into the list and move a channel down, rather than pressing up then down. 

Ps. Am I missing a setting somewhere or has the video window in pvr guide not been reintroduced yet? Disappeared not long after release and haven’t seen it since. Thanks. 

### Why is this feature needed? Please justify and explain.

Prevent unnecessary scrolling/ button presses to get bearings. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It still behaves as you describe for me. You're talking about the first icon on the right side of the OSD correct? This one?

![Honeyview_184357660-88e5118f-0296-4c34-9eb1-2675d59ae02f](https://user-images.githubusercontent.com/4618719/184357838-e7825797-e694-4768-9889-9ddb464138d9.jpg)

That icon always takes me to the currently playing channel in pvrosdchannels.

> Also, regarding the stop button’s channel list…would it be possible to have both direction up/down initiate navigating the list rather than just direction up? It would feel more natural pressing down twice to get into the list and move a channel down, rather than pressing up then down.

Makes sense. Shouldn't be too difficult to implement.

> Ps. Am I missing a setting somewhere or has the video window in pvr guide not been reintroduced yet? Disappeared not long after release and haven’t seen it since. Thanks.

No it hasn't been reintroduced. I was never particularly happy with how it was originally and the PVR in general has quite a few things I still need to work on. Just haven't quite got to it yet.

**Comment by Tee77** [comment]
> It still behaves as you describe for me. You're talking about the first icon on the right side of the OSD correct? This one?

Yes, exactly. Maybe it's an issue on my side, but I don't think I explained myself properly either. That icon does initially take me to the currently playing channel, but if I browse down the channel list and end up not selecting anything, dismiss the menu, then call it back up again, the channel highlighted is the last one I was browsing, not the currently selected channel. I was pleasantly surprised when the skin was released as it would reset itself back to the currently selected channel regardless of recent browsing activity. Maybe this was never meant to happen and was just a bug with the early release? If it is possible, could pvr guide replicate this as well perhaps?

> Makes sense. Shouldn't be too difficult to implement.

Great!

> I was never particularly happy with how it was originally and the PVR in general has quite a few things I still need to work on.

No problem. Quite happy knowing I'm not missing a setting to enable this and that it will make a comeback. I thought it looked bloody great but obviously have much lower standards than you hehe.

**Comment by jurialmunkey** [comment]
> That icon does initially take me to the currently playing channel, but if I browse down the channel list and end up not selecting anything, dismiss the menu, then call it back up again, the channel highlighted is the last one I was browsing, not the currently selected channel. Is this expected behaviour?

Nope, that doesn't happen to me. I open it up, scroll to a different channel and then hit back. Next time I open it I'm on the channel that is playing.

**Comment by Tee77** [comment]
Ah ok cool. Nope, doesn't work for me - maybe it will resolve itself down the line. Thanks anyway!
