### ISSUE TITLE
[BUG] Always display stop button 

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.horizon.2#426]
### Skin section

Other

### Current Behavior

I just installed kodi and AH2 on a brand new Apple TV 4K (a2169).
The video player doesn’t show the usual controls (stop, play, pause, subtitle settings , etc). So my initial thought was to head over to (skin-> playback -> always display stop button). 
But, it turned out to be already checked. I tried toggling it on and off, neither made any change (even tried to reload skin after each selection).
I played around with the rest of the settings in the playback menu, none of them helped out displaying the player controls.

### Expected Behavior

Enable/disable stop button in the video player dialog.

### Steps To Reproduce

Play a video file

### Screenshots and Additional Info

![Uploading 896A4405-D957-4139-9E9F-48D1B6607652.jpeg…](

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Mr-7mdan** [comment]
![56CA7BA1-75FA-41FA-9D61-411E1983F6C7](https://user-images.githubusercontent.com/9439671/184424026-e06164f5-4bd7-4d32-8e68-80ec2a67d852.jpeg)

**Comment by jurialmunkey** [comment]
Working fine for me with that setting enabled and a playlist queued:

![Screenshot 2022-08-13 121854](https://user-images.githubusercontent.com/4618719/184464893-6c20980a-cdb5-498a-adaa-188ddc72c9d8.jpg)

**Comment by Mr-7mdan** [comment]
@jurialmunkey, I think the issue is related to “Skin.shortcuts” because version 2.0.0 and 2.0.1 aren’t compatible with kodi for tvOS. Only version 1.1.5 is compatible. By default the skin doesn’t load and shows skin shortcuts error and when i rolled back to 1.1.5 as per the community recommendations, everything works except the stop button.
I dont know the reason for the incompatibility, but the community recommended me to roll back and it worked.
https://mirrors.xmission.com/kodi/addons/matrix/script.skinshortcuts/
![63D8B6F1-699C-4275-8760-854E6432A15C](https://user-images.githubusercontent.com/9439671/184477702-f995ad3e-b6e9-4f16-846e-6c957cdbbd3b.jpeg)
![0B89281F-349A-4502-B2E8-5C85B1965F0E](https://user-images.githubusercontent.com/9439671/184477712-8e2d8bca-dae4-469b-9e29-1391cc2a8ac2.jpeg)
![B8F655DC-FB6C-492E-A006-BD65D1CF31D6](https://user-images.githubusercontent.com/9439671/184477729-c1e5eb87-d8a1-489c-b0ae-cd654bb04c37.jpeg)
![6451DD4C-9C9E-487D-84EE-C6478240F042](https://user-images.githubusercontent.com/9439671/184477752-403b2ce5-95c9-4c59-b2e1-f69cce0e6818.jpeg)

**Comment by jurialmunkey** [comment]
Skinshortcuts has nothing to do with the video OSD.

Your problem is that whatever key you are using is mapped to `Action(Info)`

**Comment by Mr-7mdan** [comment]
> Skinshortcuts has nothing to do with the video OSD.
> 
> Your problem is that whatever key you are using is mapped to `Action(Info)` (or possibly play/pause).
> 
> Your screenshots show the seekbar not the osd controls. You need to remap whatever remote button you are using to call `Action(OSD)` instead.

You are absolutely right, it is related to Apple Siri Remote keys. Unfortunately in tvOS i cannot copy custom keymap.xml file to the profile directory and the “Keymap editor” addon doesn’t capture siri remote key strokes.
I found a work around that might help others:
A - Go to settings in tvOS
1 - Remote and devices
2 - change Clickpad to “Click Only”
3 - TV Button to “Home Screen”


B - Goto Accessibility 
1- Physical and Motor
2- click on switch control
3- for “Long press” change it to 1s instead of off.

Now the video osd appears when you hold the “Ok” button (The central button called Clickpad)
