### ISSUE TITLE
[BUG] Media Provider Icons Not Respecting Setting

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/skin.arctic.horizon.2#427]
### Skin section

Home Widgets

### Current Behavior

The media providers icons using JustWatch are shown in the bottom left when a file doesn't have codecs. But I have set it so that media providers shouldn't show. 

### Expected Behavior

Until I updated, it was just displaying the Kodi logo in the bottom left. Having that Behaviour return if Media Provider Icons is disabled would be ideal. 

### Steps To Reproduce

1. Create a widget for movies or episodes (something playable) with full information.
2. Set the setting for displaying media providers to off.
3. View the widget, and the media providers using JustWatch are shown in the bottom left, when they shouldn't be. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by JacopoV** [comment]
Same in here 😊
