### ISSUE TITLE
[Feature] Option to open information on widget click

### ISSUE THREAD

**Issue by Mycale11** [jurialmunkey/skin.arctic.horizon.2#431]
### Skin section

Home Widgets

### Feature description

In previous versions of this skin when a movie or episode widget is clicked, the information page would open. Now a click causes the item to play.

Of course there are pros and cons to both options. An option to toggle the info page on click would be wonderful. 

### Why is this feature needed? Please justify and explain.

The info page can be brought up with a long press, but it’s not entirely intuitive for a casual user who might want to see cast/trailer info.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Not a skin issue.

https://kodi.wiki/view/Settings/Media/Videos#Default_select_action
