### ISSUE TITLE
When entering a section from TMDb H From the home screen the clear logo from the Home screen widgets previous film or TV show ,shows up first and slowly fades away

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#432]
### Skin section

Home Widgets

### Current Behavior

When entering a section from TMDb H or another plugin From the home screen the clear logo from the movie or TV show displayed on the home screen widgets shows up first and fades away trying to explain the best that I can the video explains better I see this only happening on my Nvidia shield 2019 Pro but not on my PC

### Expected Behavior

When entering TMDb or another plugin from any home screen shortcut for the clear logo not to show up from the previous Home screen widgets

### Steps To Reproduce

1. Use a shortcut from the sub menu to a specific section of TMDb , 2. When the section is open you’ll see the clear logo from the previous TV show or movie from the home screen widgets

### Screenshots and Additional Info

https://user-images.githubusercontent.com/49699869/184990909-ba8beae5-9506-4ee8-a10c-a19ff8910b19.MOV

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
What version of TMDbhelper?

**Comment by xyzfre** [comment]
V4.10.24

**Comment by jurialmunkey** [comment]
@xyzfre - Please try v0.3.27 of AH2 with v4.10.25 of TMDbH. Should fix the issue.

Both should be in the repo now.

**Comment by xyzfre** [comment]
> @xyzfre - Please try v0.3.27 of AH2 with v4.10.25 of TMDbH (or higher of either). Should fix the issue.
> 
> 
> 
> Both should be in the repo now.
> 
> 

Definitely fix the issue clear logos are working much better than before on Nvidia Shield ,I've been using AH2 since beta came out ,,Thank you @jurialmunkey for this AMAZING❣️💯 skin

**Comment by Brandon1212b** [comment]
I am experiencing a similar issue and I have the most updated version in the repo. Clear logos have not been reliable for me. It usually loads the white text first, then the clear logo. Sometimes it will load the wrong clear logo for the previous movie. I am using Nvidia Shield

**Comment by xyzfre** [comment]
Are you on the latest versions AH2 and TMDB H , Skinvariables ,, because ever since this committ was added clear logos work perfectly on Nvidia shield 2019 K19.4

**Comment by Brandon1212b** [comment]
https://user-images.githubusercontent.com/111893060/189121519-d74d5085-73de-44fc-aecc-1005bb0081ac.MOV

Here’s a video of what im experiencing.

I am AH2 v0.4.14, TMDB H v4.11.10, Skin Variables v1.0.7 on 2019 Nvidia Shield with latest Kodi.

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/189131388-cbd492df-d937-4f8b-85be-af6c92b617af.MOV Also Nvidia Shield 2019 Pro clearlogos working smooth ,maybe there's a setting you miss , like fanart.tv service monitor or your own fanart API Key 🔑

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/189132839-c0b7a831-7c16-4918-878a-2233bd5e9c23.MOV Also Nvidia Shield 2019 Pro clearlogos working smooth ,maybe there's a setting you miss , like fanart.tv service monitor or your own fanart API Key 🔑

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/189132984-0792c4b5-5dd8-44fb-b108-a98b969c423f.MOV

**Comment by Brandon1212b** [comment]
Okay that was it. The problem was I did not have the setting fanart.tv service monitor checked. The issues I am having now is the clear art will show instantly but will be slightly too small. Takes about half a second an resizes it to take up the space. Any way to speed up this process?

**Comment by xyzfre** [comment]
> Okay that was it. The problem was I did not have the setting fanart.tv service monitor checked. The issues I am having now is the clear art will show instantly but will be slightly too small. Takes about half a second an resizes it to take up the space. Any way to speed up this process?

This recent update got push today fix this delay on my end working perfect hopefully for you as well
