### ISSUE TITLE
Hello again @jurialmunkey! Just wanted to say a huge and endless thank you again!) Please forgive me for not being able to thank you in the form of coffee( I live where paypal is unfortunately not available(I would like to express a huge and monetary thank you for all your work  and hard! Because you really deserve it! 

### ISSUE THREAD

**Issue by ctanyp** [jurialmunkey/skin.arctic.horizon.2#436]
### Skin section

Other

### Feature description

Hello @jurialmunkey!  Sorry for being gone for so long..Actually, I haven’t fixed my computer yet..I need an extension cable that is not available anywhere (But I still use your skin on the console!) I just want to thank you again!🙏🏻I never forget about  you when I use the skin😌 I am extremely grateful to you!  Once again, thank you very much for giving me the opportunity to use this wonderful skin and until now I notice that it is getting better and better!) Although it’s much better😅Everything works smoothly, easily, quickly even on the console.  I bought a usb flash drive and it started working even better!) Thanks to you, every day I am happy when I wake up🙏🏻😀 Sorry again for the absence..)

### Why is this feature needed? Please justify and explain.

.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Hahaha, thanks! 😁 

And no worries about not being able to make a donation. Donations are nice obviously but I'm also just glad that people enjoy the skin!
