### ISSUE TITLE
[BUG] "Whitespace" at left side of "List" viewtypes

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#443]
### Skin section

Other

### Current Behavior

When displaying lists from some add-ons there is unused whitespace at the left hand side of the list, as shown in screenshot.

![screenshot00009](https://user-images.githubusercontent.com/67786207/186837875-3fb7b423-d46b-4fd9-92b3-663fd32ec6cb.png)

### Expected Behavior

No whitespace should appear

### Steps To Reproduce

1. Open video addon (Catchup TV & More from the Kodi repo used in screenshot)
2. Navigate to list of available episodes

### Screenshots and Additional Info

I suspect the whitespace appears when the item(s) do not have an episode (displayed as NxNN for items in the Kodi library) or a Year associated with them. I will investigate a bit further

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
> I suspect the whitespace appears when the item(s) do not have an episode (displayed as NxNN for items in the Kodi library) or a Year associated with them. I will investigate a bit further

Yeah that will be it. Episode type without episode numbers. I should be able to check for it fairly easily and display the basic layout instead in that case.

**Comment by berkhornet** [comment]
Thanks for the fix which I've installed and tested. I've noticed one situation where the whitespace still appears when we have episode type without episode numbers. I've tested the following change in Includes_Lists.xml at line 268:
- episode condition changed to [String.IsEqual(ListItem.DBType,episode) + !String.IsEmpty(ListItem.Episode)]

This fixed the problem for me but it may not be universal. I can raise a PR if required. 

Thanks

**Comment by jurialmunkey** [comment]
@berkhornet - Ah, I only tested with catch-up tv and realised it set dbtype as videos (not episodes as I originally thought). Didn't realise there were also other addons with a similar issue.

Yes please if it's easy for you to do a PR then I'll merge (otherwise I'll add it a bit later). That would be the best approach with that condition.
