### ISSUE TITLE
[Feature] Include Weather Widget 

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#448]
### Skin section

Home Widgets

### Feature description

Would it be possible to include a weather widget in AH2 (similar to that available in AH1). Many thanks

### Why is this feature needed? Please justify and explain.

Simplified access to weather information

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Goldenfreddy0703** [comment]
Ooo I would like that as well.

**Comment by Bart666** [comment]
that would be a great enhancement to an already superb skin.

**Comment by jurialmunkey** [comment]
In next release

`Fullscreen Widget > Default Widgets > Other > Weather`

**Comment by Liquidrag** [comment]
@jurialmunkey weather widget seems to be broken in Omega
