### ISSUE TITLE
Not a request but a Question on how to use this feature

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#450]
### Skin section

Fullscreen Video OSD

### Feature description

I saw this added to the commits ,,chapter markers and de-zoom codecs on seekbar,, how do you use this feature or make it show up on the OSD screen,, yesterday when I was watching a episode I saw the markings on OSD seekbar But today they didn’t show up ,,my apologies for posting this here didn’t know where else to ask really appreciate any feedback thank you @jurialmunkey

### Why is this feature needed? Please justify and explain.

chapter markers and de-zoom codecs on seekbar 

### Screenshots and Additional Info

chapter markers and de-zoom codecs on seekbar 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Nothing needs to be done to use it. It automatically displays if the video file has proper chapter markers embedded into the file (or a cut-list in the case of a PVR recording).

**Comment by jurialmunkey** [comment]
FYI - you should be able to ask questions in the discussions section rather than needing to open an issue:
https://github.com/jurialmunkey/skin.arctic.horizon.2/discussions/categories/discussion
