### ISSUE TITLE
[Feature] Flixart widget modification

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#457]
### Skin section

Home Widgets

### Feature description

Hi @jurialmunkey,

First of all many thanks for adding the Flixart widget style. However, I've a small request, is it possible to make each widget row of Flixart fullscreen instead of the previous row widgets hiding the current layer's Flixart partially?

### Why is this feature needed? Please justify and explain.

This will make the Flixart widgets look even more beautiful.

### Screenshots and Additional Info

What it looks like currently:
![IMG20220906213651](https://user-images.githubusercontent.com/65297828/188684294-b023f4a0-a174-4b45-9c3b-e5c36024a53d.jpg)

How I want it to look:
![IMG20220906213948](https://user-images.githubusercontent.com/65297828/188684437-f265aa6c-94be-4532-b217-f969dd3ba458.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Thank you so much for this! One question, currently the date on the top left is displayed as Wednesday, 14 September 2022 (see below screenshot). Is it possible to display it as a shortened version like Wed, 14 Sep 2022? That will look very neat with Flixart view. If this is possible then how to do it? I checked in Kodi Regional unit formats setting but We'd, 14 Sep 2022 date type is not available. Please advise.

![IMG20220914174645](https://user-images.githubusercontent.com/65297828/190151765-43434b08-6f94-4182-8bf3-a39cbc08bbd8.jpg)

If you want me to raise a separate ticket for this then I can do so. Kindly let me know.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
That's actually a Kodi issue for the date format. I'm not quite sure what determines those options or if you can set a custom one.

**Comment by ShibajiCh** [comment]
Fine @jurialmunkey. Thanks for the feedback!
