### ISSUE TITLE
Add-ons icon not appearing in submenu

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#46]
I've created a submenu widget for add-ons but the icon that I set for add-ons is not appearing in the first submenu item (see screenshot below).
![IMG20220605212832](https://user-images.githubusercontent.com/65297828/172059365-50174c91-f02c-43e7-9948-6d769af372b0.jpg)

Could you please check?

**Comment by jurialmunkey** [comment]
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.6

**Comment by ShibajiCh** [comment]
Yes, it's fixed now. You can close this ticket. Thank you so much!
