### ISSUE TITLE
[BUG] Unable to install on Kodi 20 Nexus

### ISSUE THREAD

**Issue by chcore** [jurialmunkey/skin.arctic.horizon.2#462]
### Skin section

Other

### Current Behavior

I am not able to install the skin on Kodi Nexus 20 using either the repository or manually installing each required addon.

### Expected Behavior

The skin should install successfully.

### Steps To Reproduce

1. Install the @jurialmunkey repo
2. Attempt to install Arctic Horizon 2
3. Notice that TheMovieDb Helper and Skin Variables addons are "Not Available"
4. Attempt to install the addons manually via zip files, and encounter errors in the log similar to:

`ERROR <general>: CAddonInstallJob[plugin.video.themoviedb.helper]: failed to find dependency script.module.tmdbhelper`

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by chcore** [comment]
OK manual install worked after installing this: https://github.com/jurialmunkey/script.module.tmdbhelper

**Comment by jurialmunkey** [comment]
That dependency should be available on my repo and install automatically with TMDbHelper. Check that you have enabled Kodi settings to allow installing updates from any repos and aren't forcing manual install.
