### ISSUE TITLE
[Question] Accessing library from next Aired Trackt

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon.2#463]
### Skin section

Other

### Feature description

would it be possible to access my library from the next Aired Trackt or is it a Kodi limitation?

### Why is this feature needed? Please justify and explain.

Easy to access instead of exciting Next Aired Library. 

### Screenshots and Additional Info

https://user-images.githubusercontent.com/2873112/189473072-e8cc66fd-eff7-40aa-bc22-2779ee70e278.mp4

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry, I thought I replied to this issue ages ago but clearly I didn't! 

Unfortunately not really possible. Would need the tvshow DBID to open the library folder and TMDbHelper can only get the DBID if the episode is already in the library.
