### ISSUE TITLE
[Feature] options for infoline (director etc)

### ISSUE THREAD

**Issue by georgew21** [jurialmunkey/skin.arctic.horizon.2#465]
### Skin section

Home Widgets

### Feature description

It's great how many options has your skin, but I would like to suggest one more. 

There is already a setting to show/hide "genre" and "end time". 

I would also like to have the possibility to hide the icon in the beggining ( I see usually "Web") , hide MPAA and show director of film.

In general, it could be nice to have more options for infoline (I mainly want to see the director).

Thanks for your time. 

### Why is this feature needed? Please justify and explain.

Every user can view whatever he wants (disable or enable mpaa, show genres) and have the skin even more customisable.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by georgew21** [comment]
Hello, The latest realeses were awesome in feautres. Is there any possibility to implemen the current feature?

If not, I have achieved in some way (after hours of tryings as I don't know how to code) to replace MPAA with director name. But as your skin has very often updates, I lose my edits on your code. Is there any way to implement a change to override your code after release?

thanks for your time.

**Comment by jurialmunkey** [comment]
Option for disabling MPAA and enabling Director added.

Disabling icon is not possible for technical reasons.
