### ISSUE TITLE
Elcinema

### ISSUE THREAD

**Issue by bassemhelal18** [jurialmunkey/skin.arctic.horizon.2#466]
### Skin section

Home Widgets

### Feature description

Can you add this movies database website for arabic movies and tv shows 

### Why is this feature needed? Please justify and explain.

It will help 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
No idea what this request is. What does a website have to do with a kodi skin.?
