### ISSUE TITLE
Search function from Add-on menu crashes kodi

### ISSUE THREAD

**Issue by gRullo** [jurialmunkey/skin.arctic.horizon.2#467]
### Skin section

Other

### Current Behavior

In the home screen, going on the right top menu "add-ons" , then from the left side going on "Search" , whatever you type in it crashes kodi when you enter the word.

### Expected Behavior

do not crash

### Steps To Reproduce

Go to Addons menu (top right)
Click on the "Search" on the left side
Enter Keyword
kodi Crashes.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is an inbuilt Kodi function so the skin shouldn't matter. Please confirm that it works correctly in Estuary.

**Comment by gRullo** [comment]
> This is an inbuilt Kodi function so the skin shouldn't matter. Please confirm that it works correctly in Estuary.

You'r right. It ain't working in Estuary too.

**Comment by jurialmunkey** [comment]
Yeah I had this happen to me once. I can't quite remember what caused it but it was something with Kodi's addons db getting corrupted and it was a real pain to fix.
