### ISSUE TITLE
[BUG] Menu Bar Background Gone

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/skin.arctic.horizon.2#469]
### Skin section

Home Widgets

### Current Behavior

There used to be a slightly transparent rounded bar behind the icons for the menu bar. That seems to have disappeared, so the icons are shown directly on the background. 

### Expected Behavior

I really liked that rounded menu bar look, so it would be great if that could return. 

### Steps To Reproduce

1. Start Kodi with Arctic Horizon 2 skin
2. View Arctic Horizon 2 menubar

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by berkhornet** [comment]
I noticed that the home menu background texture disappeared with version 0.4.20 of AH2. Screenshots show versions 0.4.19 and then 0.4.20
![screenshot00003](https://user-images.githubusercontent.com/67786207/190494852-62fcc868-0102-4cfe-b954-5797f83986ba.png)
![screenshot00002](https://user-images.githubusercontent.com/67786207/190494884-6f49a139-7610-4625-aee6-f8aec2af121f.png)

**Comment by jurialmunkey** [comment]
It was removed intentionally because the positioning and sizing for it is a complete pain to manage -- but I can consider adding it back.

**Comment by berkhornet** [comment]
You can't please all the people all of the time! But if there was a poll I would vote for it's return. Many thanks for a great skin.

**Comment by xyzfre** [comment]
> It was removed intentionally because the positioning and sizing for it is a complete pain to manage -- but I can consider adding it back.

My opinion I think it looks better the way it is now transparent,, hopefully you can add an option to disable/enable

**Comment by Goldenfreddy0703** [comment]
I think it's a great idea cause it does kinda give you a google tv ui menu style feel to it but i also think if you were setting up icons, it would feel empty inside like in @berkhornet screenshot. I think having an option to disable/enable would be the best solution sense some people may like it the way it is.

**Comment by ambulancePilot** [comment]
I love the new look without the background... I agree with the other guy, if you bring it back please have an option to disable it! Such a clean look.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Yes, I myself too liked the rounded menu bar look like @Kayzels and @berkhornet mentioned. It'll be really great if you can add it back or even better if you can provide an option to add it or remove it as per the user's preference like @Goldenfreddy0703 and @xyzfre requested.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
Awwww that's ok tho, I gotten use to it without the menu bar surprisingly.

**Comment by AakashC2020** [comment]
> Awwww that's ok tho, I gotten use to it without the menu bar surprisingly.

Yes, me too... 🙂👍🏻

**Comment by jurialmunkey** [comment]
I was considering adding it back originally but its too complicated now with the additional menu options available now. Much easier to manage the various options without also needing to worry about the backing panel. I figured everyone had gotten used to it by now anyway!

**Comment by AakashC2020** [comment]
> I was considering adding it back originally but its too complicated with the additional menu options available now. Much easier to manage the various options without also needing to worry about the backing panel. I figured everyone had gotten used to it by now anyway!

Hi @jurialmunkey,

Yes, we got used to it now. No problem. Thank you!
