### ISSUE TITLE
[Bug] [Widgets] Fanart background does not clear

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#47]
In version 0.1.6, for the menu items which do not have any fanart, the last displayed fanart is showing up as default background. For example, in the below screenshot the Live TV menu is showing fanart from the TV Show menu item.
![IMG20220605214203](https://user-images.githubusercontent.com/65297828/172059992-7df802cd-f8c7-411b-bbff-26548218b1ae.jpg)

**Comment by onlytanmoy** [comment]
@ShibajiCh do you mind sharing the names of the Live TV Kodi add-ons you are using for the Indian content? :)

**Comment by ShibajiCh** [comment]
> @ShibajiCh do you mind sharing the names of the Live TV Kodi add-ons you are using for the Indian content? :)

Hi @onlytanmoy,

I'm only using Jio TV addon from BotAllen repo for the Indian channels under Live TV.

**Comment by ShibajiCh** [comment]
@onlytanmoy, you're welcome. Sure. You delete your comments and I'll delete mine.

**Comment by ShibajiCh** [comment]
Thank you!
