### ISSUE TITLE
[Feature] Customize time interval for Extrafanart

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/skin.arctic.horizon.2#474]
### Skin section

Home Widgets

### Feature description

Customize time interval for Extrafanart

### Why is this feature needed? Please justify and explain.

I really like this function but I would like the time between each image to be shorter or to be able to customize it.
ADD: Could this Extrafanart also work in fullscreen widget? It would be incredible :)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can customise autoscroll interval in 
Skin Settings > Behaviour > Autoscroll time interval
