### ISSUE TITLE
[BUG] Short Description

### ISSUE THREAD

**Issue by unicornsandcandies** [jurialmunkey/skin.arctic.horizon.2#475]
### Skin section

Fullscreen Video OSD

### Current Behavior

After some time of watching, kodi crashes. Problem exist only on this skin on both my devices (ubuntu laptop and raspberry pi 4)

### Expected Behavior

Playback continues 

### Steps To Reproduce

1. Use addon (fen, umbrella, seren and otaku - kaito fork tested) to watch a tv show
2. Watch for some time
3. Playback freezes and kodi crash

### Screenshots and Additional Info

[kodi_crashlog-20220820_211432.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9629700/kodi_crashlog-20220820_211432.log)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
According to your log, you don't even have Arctic Horizon 2 installed.

This isn't Auramod.

**Comment by unicornsandcandies** [comment]
> According to your log, you don't even have Arctic Horizon 2 installed.
> 
> This isn't Auramod.

I use artic horizon 2 from your repo. I've switched from auramod like a month ago

**Comment by jurialmunkey** [comment]
The log you attached does not have arctic horizon 2 even installed.
