### ISSUE TITLE
[BUG] Watched Indicators for Movies as Cast Member Aren't Showing

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/skin.arctic.horizon.2#476]
### Skin section

Video Info Dialog

### Current Behavior

When selecting a cast member from the info pane, it shows the person info. Pressing down on that page shows a list of the movies and TV shows they were involved in. In that list, the watched indicator circle shows, but the icon inside is missing. 

### Expected Behavior

The icon inside the watched indicator circle should be displayed. 

### Steps To Reproduce

1. Play a movie or TV show
2. Go to the info panel where it shows the movie description and cast
3. Select a cast member that is in another movie that has been watched
4. On the page for the cast member, press down to show Movies as Cast Member
5. The movies that have been watched with that cast member have the circle, but not the watch icon itself. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yeah I noticed this the other day - I messed something up with the conditions. Was trying to get number of episodes the cast member appears in for tvshows.

Probably will revert that change entirely as it was a bit confusing with what the number represents. I think I'll separate it out and put it elsewhere (maybe a corner tab on the poster with appearance count)
