### ISSUE TITLE
[Feature] Fullscreen fanart in video info

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/skin.arctic.horizon.2#477]
### Skin section

Video Info Dialog

### Feature description

Fullscreen fanart in video info pressing Up and then Right or Left (like AH1).

### Why is this feature needed? Please justify and explain.

I really liked this feature in AH1. Every time I press "Up" in the info window I subconsciously press "Right" to see the fanart 😅

Please if this is already requested you can close it.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Artwork gallery now available in info dialog.
