### ISSUE TITLE
removed osd codecs 

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#484]
### Skin section

Fullscreen Video OSD

### Feature description

Would it be possible to have an option to disable and enable , osd codecs when using auto play this feature comes in handy so when the next episode starts I'm able to know the quality 1080 ,h264 ,h265 etc 

### Why is this feature needed? Please justify and explain.

it can be very useful when using auto play to know the quality of the stream

### Screenshots and Additional Info

One thing I do notice ever since v0.4.31 and above not sure if something has changed in the background but I’m using an Nvidia shield 2019 Pro K19.4 and on start up I noticed now it takes about an extra 5 to 7 seconds to load up ,,always thankful for all the hard work you put into AH2

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

I agree with @xyzfre and would really like to see the OSD video and audio codecs back too. They were very useful and I used to view them regularly. It is my kind request that you please add them back.

Thanks and Regards,
ShibajiCh.

**Comment by ivarbrandt** [comment]
I agree with @xyzfre and @ShibajiCh on bringing back the video codecs. I do think that the way they were implemented wasn't too clean though. So check this out, what if you bring back the codecs but in a more subtle way? And they would only appear once at the beginning of playback. Something along the lines of this example:

[https://www.dropbox.com/s/wmgh29fiwunqd96/Example.mov?dl=0](url)

I think this would be a much cleaner implementation. Let me know what you all think.

**Comment by ahmedashed** [comment]
Hi,

First of all thank you for the updates and amazing smooth skin <3

I am not sure if this was intended but the OSD codec information has been completely removed today for me. They're just no there anymore, is there an option where we have the choice of toggling where they are. Thanks. Happy to provide photos if needed.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Okay, looking forward to the addition of the codecs shortcut in the video settings popup as mentioned by you above.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Thank you @jurialmunkey !

**Comment by xyzfre** [comment]
Thanks @jurialmunkey🙌🏼 for the codecs easy access and Love the new feature with the playlist on the OSD screen looks so so much better and gives it a clean look
