### ISSUE TITLE
Info button on OSD gives wrong information 

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#488]
### Skin section

Fullscreen Video OSD

### Current Behavior

When watching a TV show and you click on the info button in the OSD screen it is displaying the wrong TV show seems to display same title older show for Example Euphoria   , (Nvidia Shield 2019 Pro K19.4)

### Expected Behavior

When watching a TV show and clicking on the info button on OSD screen for it to display the proper information please

### Steps To Reproduce

1.Play a TV show EX. Euphoria 2. Click on the info button and you will see it’s displaying the wrong TV show

### Screenshots and Additional Info

![45A9A564-FD1B-424D-8F58-380379C78D75](https://user-images.githubusercontent.com/49699869/192761724-1b36ffd7-b9d4-47a7-968e-0c75ce7c7b46.jpeg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yep, I just noticed this before. Accidentally set the type to "movie" instead of "tv"! 

Should be fixed now.
