### ISSUE TITLE
Reg. Binocular icon (Discover) option under context menu

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#49]
Regarding the binocular icon option under context menu, I guess it is for Discover, but it's view is not coming properly (see screenshots below). I'm even not able to change its view from options. It's stuck at Big poster row option. Also, what is the purpose of the icon on it's right side. It simply closes the context menu.
![IMG20220605220519](https://user-images.githubusercontent.com/65297828/172060943-a2d5fc63-fd50-4252-a98d-1ec867f2fa54.jpg)
![IMG20220605220532](https://user-images.githubusercontent.com/65297828/172060953-9d813a41-f4ff-46de-b640-6a2c13793e7c.jpg)

**Comment by jurialmunkey** [comment]
Discover shouldn't look like that. I think that bigposter bug should be fixed now, could you test v0.1.12?

The other icon is fullscreen. It opens fullscreen video / music visualisation if something is playing.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Thank you! The discover Big poster bug is now resolved in version 0.1.12. However, I've one question. What are the default movies/tv shows that are displayed when the discover window opens. I noticed that they are same for all movies/tv shows, so are they like popular movies/tv shows? Please advise. See screenshot below.
![IMG20220606184319](https://user-images.githubusercontent.com/65297828/172169265-68992b17-602b-4a02-9e6b-58b15dc23d0c.jpg)

Also, thanks for letting me know about the Fullscreen icon!

**Comment by ShibajiCh** [comment]
> Yeah default list with no parameters is `Sorting = popularity.desc`
> 
> Eventually I will setup discover to use some of the parameters from the item it comes from e.g. same actors / genres / directors / year etc. but haven't decided yet on what makes most sense.

Hi @jurialmunkey,

Thanks for the detailed explanation!
I guess suggestions based on Genres will be good, or something like a mixed suggestion based on multiple parameters, if possible, will be even better. 🙂
