### ISSUE TITLE
Clicking information on home screen widget and then browse when backing out takes you inside TMDb H

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#492]
### Skin section

Home Widgets

### Current Behavior

If you highlight a TV show from the home screen widgets bring up the context menu click on information then press on browse when you back out it takes you inside TMDb H menu instead of taking you back to the home screen widgets ,, on full screen widgets it seems to be working correctly , I have tried on the PC and Nvidia Shield same behavior on both

### Expected Behavior

When highlighting a TV show from the home screen widgets and bringing up the context menu click on information and then browse when backing out for  it to take me back to the home screen widgets not inside TMDb H menus Please 

### Steps To Reproduce

1. Highlight a TV show from home screen widgets 2. Bring up the context menu and click on information 3. Then press on browse and when you back out it takes you inside TMDb H menu and not back to the home screen widgets

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/193126915-3f1dd410-bae0-4646-a00a-8558d081eb5c.MOV

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/193132010-5bc0d900-1907-4191-aaea-83e8adde8b63.MOV

**Comment by xyzfre** [comment]
One more thing I notice and you'll see it in the video above in both ,if you're inside TMDB H example popular TV shows when you back out you will see the previous clear logo from the TV show or movie slightly fading away in the left Side top corner always grateful for all your hard work

**Comment by xyzfre** [comment]
My apologies I know I posted a few issues the past few days not trying to be a bother but I use AH2 on a daily basis Skin is addictive lol AMAZING work

**Comment by jurialmunkey** [comment]
That's actually the default behaviour of that button. If you go to Estuary you will see the same problem.

**Comment by jurialmunkey** [comment]
Added a workaround for it.

**Comment by xyzfre** [comment]
> Added a workaround for it.

Thank you @jurialmunkey working like a charm and love the new codec info display amazing job
