### ISSUE TITLE
[Feature] Remove Cast List from below Plot in OSD Info

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/skin.arctic.horizon.2#494]
### Skin section

Fullscreen Video OSD

### Feature description

I love the new interface for the info, although it's quite different from before.

At the moment, the names of the cast appear below the plot, and you can press down to get their images. Would it be possible to remove the names list, seeing as the info can already be found by just pressing down one more time.

Related to that, would it be possible to show more than 5 cast portraits. To my eyes, it seems that 7 could fit, while still having the text on the right. Or possibly this space on the right could be used for the list above? 

### Why is this feature needed? Please justify and explain.

This would give extra space for the plot info. It would also prevent two scrolling textboxes from being right under each other, which can be jarring. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
> ### Skin section
> 
> Fullscreen Video OSD
> 
> ### Feature description
> 
> I love the new interface for the info, although it's quite different from before.
> 
> 
> 
> At the moment, the names of the cast appear below the plot, and you can press down to get their images. Would it be possible to remove the names list, seeing as the info can already be found by just pressing down one more time.
> 
> 
> just trying to help out but it already displays more than five cast members The last show I was watching I counted 14 cast members all display proper with the new feature ,, there is a setting to display full cast members not in front of my device to point you out where the setting is at the moment
> Related to that, would it be possible to show more than 5 cast portraits. To my eyes, it seems that 7 could fit, while still having the text on the right. Or possibly this space on the right could be used for the list above? 
> 
> ### Why is this feature needed? Please justify and explain.
> 
> This would give extra space for the plot info. It would also prevent two scrolling textboxes from being right under each other, which can be jarring. 
> 
> ### Screenshots and Additional Info
> 
> _No response_
> 
> ### Checklist
> 
> - [X] I have searched the issues and this feature has not been requested.
> - [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
> Related to that, would it be possible to show more than 5 cast portraits. To my eyes, it seems that 7 could fit, while still having the text on the right. Or possibly this space on the right could be used for the list above? 

Just trying to help ,,At the moment there is a setting that will display the full cast members an example I was watching Pantheon the TV Show and I counted 14 cast members ,, not in front of my device at the moment to point you out exactly where the setting is,, on my end I LOVE  the new layout Definitely something different it's always good

**Comment by Kayzels** [comment]
Yes, I'm fine scrolling the cast portraits. But there is a large amount of unused space on the right of the portraits, that I thought could be used.

**Comment by jurialmunkey** [comment]
The space to the right will display biography if you've previously looked up the cast member (ie extra details were previously cached). I've just got to make a change in tmdbhelper to make it possible to do an on the fly lookup in the osd so that I can add it for all cast members.

For me, I find most of the plot overviews I have fit on two lines, so expanding it further just leaves lots of empty space. Definitely can make an option though.

**Comment by daviddia5** [comment]
I agree with the partner. For me the plot in two lines falls short (In my language it normally uses 3 or 4 lines).
I would add the slogan and genre in that space and remove the cast.
I would even enlarge the poster and shift Director, Writer, and Studio to the right.

I thought to add a new enhancement with these things, but I understand that in the end it is a matter of taste.
I also love all the info we can get with these skins. The best! :)

**Comment by daviddia5** [comment]
Thanks for the changes! I think it's much better now, right?
I ask here, is there any key in Kodi to open that info screen directly? I have tried with the "i" but it does not appear.
