### ISSUE TITLE
[BUG] Plugin path is appearing in bottom of screen when clicking right on info screen

### ISSUE THREAD

**Issue by TechXXX** [jurialmunkey/skin.arctic.horizon.2#498]
### Skin section

Video Info Dialog

### Current Behavior

Plugin path is appearing in bottom of screen when clicking right on info screen, this is before: 

<img width="1728" alt="Screenshot 2022-10-02 at 09 26 02" src="https://user-images.githubusercontent.com/10571873/193443140-019f013f-7544-4346-8cd5-3e72f3c83225.png">

Then arrow right: 

<img width="1728" alt="Screenshot 2022-10-02 at 09 26 18" src="https://user-images.githubusercontent.com/10571873/193443160-ac572501-37fc-4588-b8fa-fb860e323188.png">

And the path appears on the bottom of the screen. Pretty ugly on a big screen. 

### Expected Behavior

No path should show at any time in the bottom of the screen. 

### Steps To Reproduce

Any info screen - from wiki - arrow right 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The path is shown intentionally when you open the side menu as it is frequently needed for many management functions, especially if you have a local library. This is the only way to see the full file path for a file and many people rely on it, so it won't be removed.

**Comment by TechXXX** [comment]
ok, too bad, no way to wraparound or what do you call it, i.e. if you press arrow right on wiki for it to goto play again, like the behaviour of the widgets, which was a really great improvement vs Arctic Horizon 1 by the way...I remember you had the scroll all the way back to the beginning.
