### ISSUE TITLE
[BUG] TV Series won't open from info dialog

### ISSUE THREAD

**Issue by TechXXX** [jurialmunkey/skin.arctic.horizon.2#499]
### Skin section

Video Info Dialog

### Current Behavior

From info dialog you can't open a TV show. Too many steps, I made a short video: 

https://www.youtube.com/watch?v=A0EKvlTOpJs

Movies work great. 

### Expected Behavior

Open TV series. 

### Steps To Reproduce

https://www.youtube.com/watch?v=A0EKvlTOpJs

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
I noticed a similar behavior when I pick a show from recommendations there is no browse button a play button shows up clicking that takes you back to the home screen

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/193450376-d8c3eb3e-59ea-447d-ab66-4e52629bba21.MOV

**Comment by TechXXX** [comment]
Yeah it's everything from TMDB helper, tv shows that is, movies work fine and this feature is absolutely brilliant in this skin.

**Comment by xyzfre** [comment]
Thank you @jurialmunkey it's working correctly now this is a really great feature good to have it working again🙌🏼
