### ISSUE TITLE
[BUG] OSD Playlist Current Item Missing Title

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/skin.arctic.horizon.2#502]
### Skin section

Fullscreen Video OSD

### Current Behavior

The currently playing item in the OSD Playlist doesn't have text over the image, unlike the other items. I'm not sure if this is intentional or not.

The text also disappears in the widgets on the home screen when an item is selected for playback. 

### Expected Behavior

The text for the episode Name and show should appear on the thumbnail for the currently playing item as well as the other items in the playlist. 

### Steps To Reproduce

1. Play a TV show with more than one episode remaining.
2. View the playlist that is generated in the OSD. 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yeah I saw this yesterday. Definitely unintentional. Not quite sure why the label isn't displaying.

**Comment by jurialmunkey** [comment]
Fixed in https://github.com/jurialmunkey/skin.arctic.horizon.2/commit/d5705004cd741f11af9a24453a45913c532ed86b
