### ISSUE TITLE
Ratings from recommendations

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#503]
### Skin section

Home Widgets

### Current Behavior

If you click a movie or TV show from your home screen widgets and go to information then click down for recommendations ratings show up blank but if you click on a movie or TV show from the recommendations menu and  back out the ratings show up this only happens with home screen widgets ,a video is the best way to explain this issue (Nvidia Shield 2019 Pro K19.4)

### Expected Behavior

//

### Steps To Reproduce

//

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/193478351-a0c952a0-8c23-4692-a7f4-384179292fba.MOV

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/193478401-1d4a4589-096a-4ba2-907c-13e42276da39.MOV

**Comment by xyzfre** [comment]
The second video is within TMDb H

**Comment by jurialmunkey** [comment]
What version of tmdbh?

**Comment by xyzfre** [comment]
Latest from GitHub commit (modal wait time) not Repo

**Comment by jurialmunkey** [comment]
@xyzfre - Can you try latest github version of AH2 and see if that fixes it (main branch not release)

**Comment by xyzfre** [comment]
> @xyzfre - Can you try latest github version of AH2 and see if that fixes it (main branch not release)

Yep all working correctly thank you @jurialmunkey for all your hard work and dedication AH2 is amazing
