### ISSUE TITLE
[BUG] Last played channels widget doesn't work

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon.2#504]
### Skin section

PVR and Live TV

### Current Behavior

Last played channels widget doesn't work, it shows the list in the order it was created.

### Expected Behavior

For the list to show the last played channels. 

### Steps To Reproduce

 Just create a the last played channels widget.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Did you set the sort by method to last played and descending?

**Comment by juanma-cvega** [comment]
No, I didn't. Now it works. But then I don't get why I need to add the sort method when using the last played widget from the default widgets list. I think in Arctic Horizon (1) I didn't have to do it this way. 
Anyway, it works now. Feel free to close the issue if this is the expected behavior when using the widget I mentioned.
