### ISSUE TITLE
Blank screen for a couple seconds

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#506]
### Skin section

Home Widgets

### Current Behavior

I have created a sub menu shortcut for TMDb H when entering TMDb through the shortcut and backing out back to the home screen when you click on a TV show you get a blank screen for a couple of seconds   (Nvidia Shield 2019 Pro K19.4

### Expected Behavior

//

### Steps To Reproduce

1. Enter TMDb through a sub menu shortcut 2. Back out to the home screen 3. Click on a TV show and you will see a blank screen for a few seconds

### Screenshots and Additional Info

https://user-images.githubusercontent.com/49699869/193797655-739263a7-3141-467b-868e-6235bf88893a.MOV

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/193934625-e3101a7d-0ba4-4428-b04b-354072ccb0ae.MOV

**Comment by xyzfre** [comment]
Been testing a little more looks like after leaving the shortcut any section of the skin you go to you get that blank screen for a few seconds but then after that if you go back to the same TV show the blank section doesn't show up again until I go back to the shortcut and back out

**Comment by jurialmunkey** [comment]
I don't understand what the issue is here? Are you complaining that things from the internet take time to load? 😆

**Comment by xyzfre** [comment]
I understand sometimes things take a little longer to load but prior this blank screen wouldn't show up before entering a TV show if it's intentional my apologies ![image](https://user-images.githubusercontent.com/49699869/193960744-52b062fd-06b1-4712-991d-aeccee86871b.jpeg)

**Comment by jurialmunkey** [comment]
That had to be removed due to the other issue where it was not loading unless you went back out. Either I hide it and then it doesn't load at all after a video finishes, or I don't hide it so it loads.

**Comment by xyzfre** [comment]
The recent update has fixed this issue And also as of now it's fixed issue #490 on my end everything seems perfect thank you so much @jurialmunkey
