### ISSUE TITLE
[Feature] Show last played channels instead when pressing down when on the stop button in the OSD

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon.2#507]
### Skin section

PVR and Live TV

### Feature description

Would it be possible to show the last played channels list when pressing down on the OSD? There are already shortcuts that can be assigned to buttons to show the list of channels but there is nothing to show the last played ones. Every time I want to go back to some channel I watched recently I wish Kodi would add last played/favorites as an option. 
By the way, would also be possible to move the down press option from the stop button to the play button? When playing videos it makes sense to have the skip options at hand but this is not something you can use on PVR (unless maybe with catch up service I guess) so I think it'd make more sense to have the list of previous played channels under the play button as it's shorter to get to . 

### Why is this feature needed? Please justify and explain.

As explain above, I think it'd be a nice feature to have. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by r95sguy** [comment]
That would be great! Or if a channel group can be selected
