### ISSUE TITLE
[BUG] Black screen after every update due to TMDBH

### ISSUE THREAD

**Issue by stvg88** [jurialmunkey/skin.arctic.horizon.2#509]
### Skin section

Home Widgets

### Current Behavior

Auto-update is ON for AH2

Everytime there is a new AH2 update, Kodi will update and go to a black screen. From my checking, it's due to TMDBH failing to update (probably it's looking at official Kodi repo instead of your repo).

So, I have to manually reinstall TMDBH to latest version in your repo each time, then reinstall AH2 update.

Is there any way for TMDBH to auto-update from your repo instead of from official Kodi repo?

I'm using Kodi 19.3 on Windows 10 if that helps.

### Expected Behavior

AH2 can auto-update without black screen.
TMDBH can auto-update from your repo.

### Steps To Reproduce

Just start Kodi after there is a new AH2 update.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
no its a Matrix bug in Kodi that addons on official repo don't update properly on some systems.it is fixed in Nexus.
