### ISSUE TITLE
[BUG] Genre recommendation not working properly

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/skin.arctic.horizon.2#511]
### Skin section

Video Info Dialog

### Current Behavior

Genre recommendation not working properly. I think it is a language problem (Spanish in my case) because in English it works correctly.

### Expected Behavior

Genre recommendations working correcly.
As you can see in the picture the genres of "Hocus Pocus 2" are fantasy, comedy, family. And the movies it recommends me are not of that genres 😅

### Steps To Reproduce

1. Go to video info dialog, press down, Genres.

### Screenshots and Additional Info

![IMG_2022-10-05-19-57-23-493](https://user-images.githubusercontent.com/74454397/194129410-a0e5772a-6d9f-46e6-877e-8c0ba3a147c0.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Genre names via TMDbHelper are in English. If your genre names are in a different language then the lookup will fail and you get the default discover section instead (i.e. movies sorted by popular). There's nothing the skin can do about this.

If you want TMDbHelper to support genre lookups in other languages then you will need to open a feature request for TMDbHelper: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues

**Comment by jurialmunkey** [comment]
Have you set your language in TMDbHelper? I forgot that I added translation for genres ages ago.

**Comment by daviddia5** [comment]
> Have you set your language in TMDbHelper? I forgot that I added translation for genres ages ago.

Yes. My language is set to Spanish (Spain).

**Comment by jurialmunkey** [comment]
Please try v5.0.13 of TMDbHelper
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v5.0.13

You might need to delete your Item Details cache via Expert settings and then restart Kodi.

**Comment by daviddia5** [comment]
For movies now it's perfect! Thank you!

For TV Shows it keeps giving the same error. I have noticed that some genres are translated and others in English. For example "Sci-Fi & Fantasy" appears in English (in Spanish it would be "Ciencia Ficción y Fantasía")

Apart from this I would like to contribute with the translation of AH2 into Spanish. How could I do it?

Thank you for your work, dedication and kindness :)

**Comment by daviddia5** [comment]
![IMG_2022-10-07-12-48-25-283~2](https://user-images.githubusercontent.com/74454397/194536787-78961b47-3069-4dfd-92dc-336419f37a84.jpg)
Here an example for "Futurama". The genres in yellow are in Spanish and in blue in English.

**Comment by jurialmunkey** [comment]
Did you delete the item details cache and restart kodi?

**Comment by daviddia5** [comment]
> Did you delete the item details cache and restart kodi?

Yes, and for the movies it has been fixed. Now the error is in the tv shows. Look at my last photo, there is a mix of languages ​​in the genres.

**Comment by jurialmunkey** [comment]
Those are correct and match the TMDb website when Spanish language is set:
![Screenshot 2022-10-08 135328](https://user-images.githubusercontent.com/4618719/194684626-b257e16f-63d0-4076-ab19-b0ffe69c0a88.jpg)

https://www.themoviedb.org/tv/615-futurama

Genre name translations are provided by the TMDb API server. If there is a missing translation then you would need to make a request on TMDb to update them: https://www.themoviedb.org/talk

**Comment by jurialmunkey** [comment]
The genres list will break when there is an `&` in the name as this is a reserved url character. The Kodi skinning engine does not provide any proper way to percent url encode infolabels so it is impossible to pass these genres correctly to TMDbHelper.

**Comment by daviddia5** [comment]
Thanks as always for the reply and all the detailed explanation.
I'm going to write to TMDB about the translations.
The only thing I don't understand about the "&" character is why it works in English and not in other languages.

**Comment by jurialmunkey** [comment]
It won't work in English either (or at least shouldn't). The & character splits the url at that point, so possibly in English where it splits it is still a proper genre that an id can be looked up for. I'm going to try switching these to use IDs (rather than names) via the background helper service to try to avoid this issue as much as possible.

Re translating the skin - if you submit a pull request with a translated strings.po file, I will include it. If you don't know how to do a pull request, you can uoload the file in a zip to a feature request instead and I'll add it.

**Comment by daviddia5** [comment]
> It won't work in English either (or at least shouldn't). The & character splits the url at that point, so possibly in English where it splits it is still a proper genre that an id can be looked up for. I'm going to try switching these to use IDs (rather than names) via the background helper service to try to avoid this issue as much as possible.
> 
Thanks! 
In case it helps, I've noticed that genres that carry an accent (á, é, í, ó, ú), for example "Acción, Fantasía, Ciencia Ficción" also don't work correctly when recommending similar genres.

**Comment by daviddia5** [comment]
I have continued testing and indeed the error when recommending genres happens with the character & or with the accented vowels (á é í ó ú).
However from the Discover section of TMDBHelper everything works correctly

![1666454541029611658974921938820](https://user-images.githubusercontent.com/74454397/197349272-7cc990f1-f9d6-40de-9113-bd6b37780114.jpg)

**Comment by daviddia5** [comment]
Thanks for this update!
I think there is a small bug. Now it only gives recommendations for a single genre, before it used all genres to give more precise recommendations. For example:
![IMG_2023-02-12-16-22-15-705](https://user-images.githubusercontent.com/74454397/218319921-24863f68-0149-4950-b8d8-34b0f671220a.jpg)
It only gives recommendation of Action. The genre of the movie is Action / Adventure / Science Fiction.
