### ISSUE TITLE
Suggestions for the main navigation

### ISSUE THREAD

**Issue by ProtoTypeRepo** [jurialmunkey/skin.arctic.horizon.2#512]
### Skin section

Other

### Feature description

I have two suggestions to tweak the main menu. On a single/first widget or sub menu screen the nav disappears and is replaced with a header of the current nav title. While it's a neat effect, I personally think it would improve the overall functionality of the skin of the navigation just stayed there. The entire nav has the appearance of it floating on top of the content, but as you scroll down multiple levels of widgets the floating clock isn't super easy to see as it is, so maybe it would be better to keep it docked at the top of the page? Maybe that would even be the better way to treat the nav, like a fixed row that you can navigate up to. Very similar to the way your Aura skin was.

My second suggestion is giving an option for a nav with text always visible. So while I'm on one item I can still read what's on the rest of the nav. Also very similar to the old Aura way. Honestly I really liked Aura and this feels very very close to a modern version and I'm beyond excited for it! 

I'm a big fan of the power menu being a drop down on the side and so far everything just works perfectly! 

### Why is this feature needed? Please justify and explain.

I wouldn't say it's needed exactly, but I do think having a nav that's easier to see and access would make the skin more appealing to all audiences.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
If you use a normal fullscreen widget, the menubar stays in place. The menubar will only hide once you navigate down from the fullscreen widget buttons to the widget group underneath. A fullscreen fanart widget with a set of widgets underneath is the default layout and how the skin is expected to be used.

More generally, the only reason the menubar hides at all is to make way for the widget title because people demand that expanded widgets must have two lines of plot. The behaviour cannot be changed without people complaining.

You can choose whether to hide the clock in furniture settings. It needs to be on a fixed position in the screen because the clock is reused for many other functions like volume, progress, busy, nowplaying, and powermenu.

**Comment by jurialmunkey** [comment]
FYI I do have plans for a text only menu, just haven't settled on a design yet

In my head my plan is three menu options: icon-only, icon+text, text-only

**Comment by ProtoTypeRepo** [comment]
I totally understand the nav disappearing as you scroll down, and honestly after a few days of using the skin I've gotten very used to it and I am okay with how things with the nav are.

I'm actually pending neck surgery so I'm down a lot and I've had too much time to tinker with things. And please forgive this picture taken from my phone, I don't have access to a computer at this second to take a screenshot. But I'm going to show you my full page of widgets, as I do have a suggestion.

![20221009_165825.jpg](https://user-images.githubusercontent.com/5466878/194779307-275c8be6-231d-49de-80a8-1e66a7b1d8b0.jpg)

You added this black curved faded bit to the bottom, I can completely understand why, to show the user there's something down there to scroll to, but there's a part of me that thinks that space would be better utilized if you moved the widget row to the bottom of the screen and increased their size a little (or only increase the size of the selected item). Then you could add even a third line to the plot or at least have enough room to increase that font size some to make it easier to read on TV's. 

Honestly a lot of my decision making when picking a skin to use is how well can my wife use this. Her biggest complaints have been the font sizes on the plot and not knowing where things are (the nav having only icons was hard for her to figure out). While these things aren't THAT big of a deal I understand if you just disregard all of this.  I just thought I'd give a little feedback.

Also I do understand in the furniture settings there are footer options, I'm just big on trying to avoid wasted blank space is all. Thank you so much for even responding though!

**Comment by jurialmunkey** [comment]
There are specific positioning rules and design guidelines for the skin. Moving the widget down will break those rules.

I disagree with this idea of trying to fill every possible space. If you look at *any* modern UI design you will see a *lot* of space around elements. There are very specific reasons why spacing between elements is important. A cluttered screen is disorientating and fatiguing to look at. If anything I would be *removing* more elements not adding them!
