### ISSUE TITLE
[Feature] add criticker ratings to addon

### ISSUE THREAD

**Issue by georgew21** [jurialmunkey/skin.arctic.horizon.2#516]
### Skin section

Home Widgets

### Feature description

Hello,

I would like to add ratings from criticker site.  This is awesome site offers personalised ratings and for this reasons requires a profile. This site hasn't api, but I have created a simple code to get this:

```
import requests

url = 'https://www.criticker.com/authenticate.php'
login_data = dict(si_username='#######', si_password='######')
session = requests.session()

r = session.post(url, data=login_data)
mov = "tt11138512"  #here we need to pass the imdb id 

r2 = session.get(f'https://www.criticker.com/?search.{mov}')

try: 
    from BeautifulSoup import BeautifulSoup
except ImportError:
    from bs4 import BeautifulSoup
html = r2.content
parsed_html = BeautifulSoup(html)
val = parsed_html.body.select('[class^="psi_div"]')
print (val[0].text) # this is the value for the rating of movie (number from 1-100)
```

With this code, I can get the rating of the film. 

My problems is how to intergrate this code to your addon, so I can view the ratings from criticker along with imdb rating etc?

And is possible to store the cookies of session to avoid make a new login request each time?

Thanks anyone for any help

### Why is this feature needed? Please justify and explain.

Criticker is an awesome site with big user base. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Scraping and data mining of that website is not permitted by their terms of use

https://www.criticker.com/terms/
