### ISSUE TITLE
[BUG] Codec icon issue

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#517]
### Skin section

Fullscreen Video OSD

### Current Behavior

There's a codec icon which is displaying "???" In video OSD. What is that and why is it displaying "???". See attached screenshot.

### Expected Behavior

Not sure what that codec icon is and what it should display.

### Steps To Reproduce

Go to video OSD while playing any video. Click on Options then click on Codecs. Under "Player Process Info" popup that particular codec icon with "???" will show up.

### Screenshots and Additional Info

![IMG20221008190646](https://user-images.githubusercontent.com/65297828/194711341-e656bfe5-fc1e-45bf-b394-1959b8781af7.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I noticed this last night actually. It is the fallback icon for the source info (eg DVD bluray etc). I probably messed up the file path so it isn't pointing to the right texture (hence the fall back icon). I'll fix soon.

**Comment by ShibajiCh** [comment]
> I noticed this last night actually. It is the fallback icon for the source info (eg DVD bluray etc). I probably messed up the file path so it isn't pointing to the right texture (hence the fall back icon). I'll fix soon.

Fine @jurialmunkey. Thank you! I'll wait for the fix.

**Comment by ShibajiCh** [comment]
Thank you @jurialmunkey !
