### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by rizreflects** [jurialmunkey/skin.arctic.horizon.2#52]
1- The clear logo seems to resize just after the fade animation. View the video below:

https://streamable.com/hurssq 

2- whebn a particular list is set to "full view" you can no longer see the list title.

![20220605_172544.jpg](https://user-images.githubusercontent.com/76912707/172061049-886dbb9b-e6a5-432c-9b25-4cafda2c4120.jpg)

Could you possibly move the list title to the right hand side in this case? I have quite a lot of widgets configured and can sometimes forget which one I'm on.

3- When going back from seasons view it does not take you back home. But rather the main page of the addon you are using (only happens with this skin as far as I can tell). See video:

https://streamable.com/f6sdlx

4- I can't find a way to change/ remove watch indicators as well as ratings (but I assume this is something already on your to do list).

Thanks for your work! One hell of a skin you've created here.

**Comment by jurialmunkey** [comment]
1. TMDbHelper crops logos on the fly to improve the sizing. It is impossible not to have a delay. If you want it to be immediate you will need to set your own clearlogos in your library that have all empty transparent space already cropped.
2. Already fixed
3. Yeah browse button still needs a bit of additional work
4. Thanks for the reminder! I meant to add that to my todo list and then forgot I will add it now.
