### ISSUE TITLE
TMDBHelper Look-Ups for PVR widgets and FlixArt view for live tv guide

### ISSUE THREAD

**Issue by r95sguy** [jurialmunkey/skin.arctic.horizon.2#521]
### Skin section

PVR and Live TV

### Feature description

Add the ability to get fanart via TMDBHelper for PVR widgets including the full screen for better quality, and adding the Flixart or spotlight view for TV Guide.

### Why is this feature needed? Please justify and explain.

EPGEventIcon can be of low quality and won't look good on the full screen widget, and it would be nice to have the same view in TV guide to the movies and TV libraries. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Please don't combine requests. Open separate requests for each one please.

Your first request for TMDbHelper lookups is not to do with the skin. That is a request for TMDbHelper. Regardless, it is not possible for technical reasons.

I have no idea what you mean by "spotlight" view.

The TVGuide is not suited to a row based view, so flixart is not something that would work there.
