### ISSUE TITLE
[Feature] Trakt - Add to user list as a direct option in context menu

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon.2#522]
### Skin section

Home Widgets

### Feature description

Hi mate, trust all good at your end.
At the moment to add a movie to my Trakt user list, I need to go through several hops, instead can we have a direct option in the context menu as 'Trakt - Add to user list'?

### Why is this feature needed? Please justify and explain.

I'm always frustrated when I need to go through so many clicks for adding a movie to my user list, therefore a direct option will be convenient and time saving.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
There's already a Trakt button in the info dialog. 
`Open info > trakt > add to user list`

Surely that's always quicker than the context menu.

**Comment by onlytanmoy** [comment]
Yes, of course, I forgot that navigation is already there 😄
Cheers mate!

**Comment by jurialmunkey** [comment]
Hahaha no worries! Yeah that's why I've got that button in the info dialog - I hate having to scroll through the context menu to find it!
