### ISSUE TITLE
[Feature] Trakt - Suggestions for non-library users

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/skin.arctic.horizon.2#524]
### Skin section

Other

### Feature description

Several ideas for Trakt users who do not use the Kodi library.

1) Add a new indicator if we have the movie/TV show in our watchlist.
2) Add a new icon for my Trakt rating.
3) Add the possibility of rate the movie/TV show/episode in Trakt from the context menu (TMDBhelper)

### Why is this feature needed? Please justify and explain.

I think it would be very useful for those of us who only use Trakt as a progress backup etc.
These are just ideas that come to me from the daily use of our fantastic AH2 :)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
None of these are things a skin can do without an addon providing the option.

There's already a request for TMDbHelper to support rating items on Trakt
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/450

Getting an indicator for whether something is in your watchlist will depend on the add-on supplying the content setting an indicator. It is not possible to add metadata to listitems -- that's why the service monitor only provides ratings and extra artwork for the currently focused item and there's a short delay when there's a changeover.

**Comment by daviddia5** [comment]
> None of these are things a skin can do without an addon providing the option.
> 
> There's already a request for TMDbHelper to support rating items on Trakt [jurialmunkey/plugin.video.themoviedb.helper#450](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/450)
> 
> Getting an indicator for whether something is in your watchlist will depend on the add-on that you're using to set that value. The skin cannot check for data that doesn't exist.
> 
> It is not possible to add metadata to listitems -- the end add-on needs to add that. That's why TMDbHelper's service monitor can only provide ratings and artwork for the focused item and there's a short delay when the focus changes.

True, I was also the one who added that request :)

The watchlist indicator, I mean that it takes that state from Trakt and shows it with an icon. It would be like when TMDBhelper gets the seen/unseen state or when it gets the resume point from Trakt.

**Comment by jurialmunkey** [comment]
Like I said, adding information to list items is not possible. The only way to display an indicator is if the addon providing the list adds that information to the item.

TMDbHelper can only lookup extra info for the *focused* item. It is not possible to lookup data afterwards and add it to *unfocused* items.

**Comment by daviddia5** [comment]
I think I must be very clumsy because I don't fully understand it 🥹
The seen status is given by Trakt, right? And TMDB helper takes care of displaying it in the list.
Couldn't the same be done with the "on watchlist" status?
I give you an example of an app for managing Trakt on mobile. The blue icon indicates that item is on my Trakt watchlist.

![Screenshot_20221016-201654_CineTrak](https://user-images.githubusercontent.com/74454397/196051637-01678dd9-3fe4-45f4-9a31-53e742c400ad.png)

Sorry for being so heavy, and if it can't be done or it's not planned, perfect too. Thank you!!

**Comment by jurialmunkey** [comment]
I cannot control the kodi library or other addons.

How would the kodi library or another addon get this data? I cannot add it for them.

**Comment by daviddia5** [comment]
Ok, I got it now hehe. Thanks again :)

**Comment by jurialmunkey** [comment]
FYI - I know it's been a long time coming but ability to rate items from TMDbHelper Trakt Options context menu is now in the latest Nexus github version (not in a release yet but will be later today).
