### ISSUE TITLE
[question] what these icons do?

### ISSUE THREAD

**Issue by georgew21** [jurialmunkey/skin.arctic.horizon.2#525]
### Skin section

Home Widgets

### Feature description

Hello, in the context menu, what do the last two icons ? https://imgur.com/AjJZPSa

the "binoculars" go to "discover movie" of tmdb but the selected movie from which I clicked the icon doesn't seem to play any role to filters or in other way. What is the scope?

the last icon just close the properties. is this its role?

thanks!

### Why is this feature needed? Please justify and explain.

just need some clarifications.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Discover and Fullscreen.

Discover isn't currently related to the item but I plan to add something like that eventually where it will pull some default filters from the item
