### ISSUE TITLE
[Feature] Back Button focus start of widget row

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#526]
### Skin section

Home Widgets

### Feature description

Good Evening,

I am trying to move from Auranod to AH2, bit a major downside for myself personally, and I am sure other fire users may had noticed it.

When I watch a trailer from a widget, I then decide I do not wish to watch that movie, obviously kodi then refreshes that widget line, which is fine.

My question is, is it possible to have the back button on the remote, make it go back to the starting movie on that widget instead of to the top of the toolbar?
Or an option added within to be able to do this?

Hope this makes sense 

### Why is this feature needed? Please justify and explain.

As explained above, this will save having to go back possibly through a 100 movies to get back to the start of the widget line. Instead just pressing 1 button, once. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
This would be a really good feature I know exactly what you mean

**Comment by jurialmunkey** [comment]
Yeah I like this idea. Just wondering what the relevance of firetv has to it?

**Comment by adamosborne83** [comment]
> Yeah I like this idea. Just wondering what the relevance of firetv has to it?

Back button on fire tv remote. 
Apologies, I do use any other devices so could not comment in regards to them.

**Comment by jurialmunkey** [comment]
> > Yeah I like this idea. Just wondering what the relevance of firetv has to it?
> 
> Back button on fire tv remote. Apologies, I do use any other devices so could not comment in regards to them.

Ah okay. All Kodi actions are generic. Some devices might not have buttons for all the actions, but the actual button.remote itself doesn't matter - all that matters is that the keymap defines that keycode as the back action.

**Comment by adamosborne83** [comment]
Thank you for correcting me, and.hopefully adding this :-)

**Comment by xyzfre** [comment]
Thank you for adding this feature @jurialmunkey  definitely makes things a lot better especially when you're at the end of a widget roll now the back button brings you back to the beginning of the widget roll ,, and still having the feature that if you're on the last widget roll on your home screen pushing the back button once again brings you all the way to the top of the screen GREAT JOB💯

**Comment by adamosborne83** [comment]
> Thank you for adding this feature @jurialmunkey definitely makes things a lot better especially when you're at the end of a widget roll now the back button brings you back to the beginning of the widget roll ,, and still having the feature that if you're on the last widget roll on your home screen pushing the back button once again brings you all the way to the top of the screen GREAT JOB💯

Agreed, thank you.
