### ISSUE TITLE
[BUG] crashing when i try to download subtitle 

### ISSUE THREAD

**Issue by d7mi91** [jurialmunkey/skin.arctic.horizon.2#527]
### Skin section

Fullscreen Video OSD

### Current Behavior

kodi crash when i try to download subtitles with this skin (**only**).
 I change it back to Default skin no issue at all then i tried many skins no problems so far but when i go back to AH2 skin it will crash immediately when i click on download subtitles 

log file have been attached 

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9770259/kodi.log)

### Expected Behavior

its works fine at any skins i have expect the arctic horizon 2 

### Steps To Reproduce

play video 
download subtitles  

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by psp2111-ADSLGATE** [comment]
Are you using A4Ksubtitle ?

if Yes, Try to disable this setting "Get resume points (experimental) (slower)" in TMDb Helper.
You will find it in "Trakt" section.

**Comment by d7mi91** [comment]
its works 
شكرا لك لو دريت كان من زمان دخلت البوابة الرقمية وطرحت المشكلة :) 

> Are you using A4Ksubtitle ?
> 
> if Yes, Try to disable this setting "Get resume points (experimental) (slower)" in TMDb Helper. You will find it in "Trakt" section.

**Comment by jurialmunkey** [comment]
Hmmm, that's interesting. Very close to removing that option altogether because it just causes way to many issues.
