### ISSUE TITLE
[BUG] Search menu limit not working and next page item box not appearing

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#528]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

The limit in search menu is not working. It's always defaulting to 20 items no matter what limit I set. Even the next page item box is not appearing at the end of the list which can take me to the next page. My current search provider is set as TMDB Helper. So even if the default page count for TMDB Helper is 20, at least the next page item box should appear at the end of the list. Earlier it used to appear fine. In the TMDB Helper addon the next page item box is appearing properly. Could you please check and fix the issue?

### Expected Behavior

The search limit should work and shouldn't default to 20 items. There should be a next page item box at the end of the list like it appears in the TMDB Helper addon search.

### Steps To Reproduce

Go to Search menu and search for any Movie, TV show, People or, Movie Collection with more than 20 items in the list.

### Screenshots and Additional Info

In Search menu:

![IMG20221013154029](https://user-images.githubusercontent.com/65297828/195569472-96851ea9-e9d1-485b-b0f1-ad3d1bc8bf75.jpg)

In TMDB Helper addon:

![IMG20221013153944](https://user-images.githubusercontent.com/65297828/195569536-5582bef4-0839-4832-b137-b8292ee4c0bb.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

I further investigated and found out that the issue is happening only with the default TMDB widgets of Arctic Horizon 2 in the search menu. If I add the search widget using custom item from the TMDB addon path then everything appears perfectly. Hope this will help you further in resolving the issue.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Tmdb is always limited to 20 items per page. That's a pagination limit enforced by the api. 

The default widget sets for tmdb deliberately put the next page setting to false because next page should only be shown when browsing in via the media windows and not on widgets. The default behaviour of TMDbhelper is that next page items on widgets are hidden.

All functioning as intended, and as you have discovered there is a way to change the next page being hidden if need be.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Thanks for the info! Actually most of the searches don't show all the items within the first page of the default 20 items. This is the main reason that I created this issue ticket. Nevertheless, if that is how the default TMDB search widgets are intended then it's fine. I'm happy as long as the Next page items appear by creating custom item widgets from the TMDB Helper addon which I'm using currently. It is really important for me to view the next page items under the Search menu as so many items are not available in the first page like I said earlier. I even use the next page items for all my widgets in Arctic Horizon 2 as I always like to see what more is there in those next pages. Nevertheless, thanks for everything!

Thanks and Regards,
ShibajiCh.
