### ISSUE TITLE
Landscape List Seasons

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#529]
### Skin section

Video Info Dialog

### Feature description

It may be me, just on TV Shows wehn I go into it from a home screen widget, I have the view as Lamdscape List, but it does not show the Season number. 

### Why is this feature needed? Please justify and explain.

Just to help me know the season

### Screenshots and Additional Info

![20221014_212651](https://user-images.githubusercontent.com/78307374/195938126-a1b711b8-7236-40b3-93e7-3d04381464b8.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by adamosborne83** [comment]
Good Morning Jurial,

I have updated, and even checked the lines in the code to make sure they show the updates, but I still have the same issue in regards to Seasons

![16659109560572230312534570721142](https://user-images.githubusercontent.com/78307374/196027247-3a6edb71-e382-4a1d-8a2c-d74fc689a542.jpg)

**Comment by jurialmunkey** [comment]
This sounds like an addon problem then. I'm setting Title and if not available Label. Can't help if the addon you're using doesn't have a label for seasons.

This works correctly for me both in the library and TMDbHelper.

**Comment by adamosborne83** [comment]
Just tested, tmdb helper works fine with it..... thank you.

**Comment by umbrellaplug** [comment]
> 

Not sure if there was an issue with fallback to label or what, but I was able to check this and Label property is being set, but not title and it's showing blank. I've addressed it on my side and started adding Title property for seasons, but you may want to check your fallback as well.

**Comment by jurialmunkey** [comment]
The variable checks if the title string is empty and shows label if it isn't. If label was set and no text was displaying then that would mean your title field has something in it which *looks* blank  - eg a single space or some formatting tags but with no text.

**Comment by umbrellaplug** [comment]
I wasn't assigning a value to title in the list item property. Not a blank. Like I said originally, just a heads up. May not be an issue, may not be something you're concerned about.

**Comment by MoojMidge** [comment]
I think there is a typo in the [new variable](https://github.com/jurialmunkey/skin.arctic.horizon.2/blob/main/1080i/Includes_Labels.xml#L88)

Fallback should be ListItem.Label

**Comment by jurialmunkey** [comment]
Ugh, my apologies! Looked at that so many times and didn't see the error. 
Bloody [Muphry's Law](https://en.wikipedia.org/wiki/Muphry%27s_law).
