### ISSUE TITLE
Similar Movies (Skin Helper)

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#530]
### Skin section

Home Widgets

### Feature description

So, on my main page, I use Similar Movies from Skin Helper, and on other skins it will say 'Similar to.........' then the Movies are based in that. Would it be possible to add that? 

### Why is this feature needed? Please justify and explain.

Just gives clarity to watch the suggested Movies are based on.

### Screenshots and Additional Info

![20221014_212651](https://user-images.githubusercontent.com/78307374/195938714-0a8c14dc-2e07-48f6-85a6-7333279b57d5.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by starseed420** [comment]
I have added the "Based on latest watched..." from TMdB's TV-Show Discovery section. Then what you do is do not edit the label, leave it as it is. It works perfect.

Back to your home screen, It now should say "Because you watched The Matrix" and it should contain similar Movies to the Matrix.

**Comment by adamosborne83** [comment]
> I have added the "Based on latest watched..." from TMdB's TV-Show Discovery section. Then what you do is do not edit the label, leave it as it is. It works perfect.
> 
> Back to your home screen, It now should say "Because you watched The Matrix" and it should contain similar Movies to the Matrix.

Thanks for this, I was selecting based on recently watched, hence not suggesting.
