### ISSUE TITLE
When playing a trailer from recommendations when you hit stop or let the trailer finish you just get the loading circle

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#533]
### Skin section

Other

### Current Behavior

When in recommendations screen for a movie or TV show when you choose a trailer it plays but if you stop or let it finish you just get the loading circle and you have to press the back button to get back to the previous screen this is only happening with the recommendations ,does not happen on home screen widgets or on the info screen they work properly

### Expected Behavior

When playing a trailer from the recommendation screen when the trailer is stopped or finish for it to go back to the previous screen and not get stuck with the loading circle

### Steps To Reproduce

1. Pick a movie or TV show and bring up the info screen 2. Click down for recommendations pick a movie or TV show 3. Play a traitor from recommendations if you stop it or let it play to the end you just get the loading circle 4. You have to press the back button for the loading circle to go away and bring you back to the previous screen

### Screenshots and Additional Info

//

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/196006583-571d4510-9d48-4287-9e33-4bc7195f301f.MOV

**Comment by xyzfre** [comment]
Not sure after which update it started happening I noticed it today really appreciate if you could look into this issue please

**Comment by adamosborne83** [comment]
> Not sure after which update it started happening I noticed it today really appreciate if you could look into this issue please ,, I tried on Nvidia shield and also on PC both same behavior

Totally unrelated, are you using Classic View???

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/196006982-7cd802be-19f8-4bdc-9ef3-37350d994a9d.jpeg)  no, these are my Settings I have fanart enabled in the background ,, if you're referring to these appreciate the help

**Comment by xyzfre** [comment]
Thank you @jurialmunkey trailers are working perfect
