### ISSUE TITLE
[Feature] Automatically navigate up if listing is empty

### ISSUE THREAD

**Issue by piejanssens** [jurialmunkey/skin.arctic.horizon.2#534]
### Skin section

Library Views

### Feature description

On each load of the view check for the number of items and navigate one level up in case there are no items. 

### Why is this feature needed? Please justify and explain.

When "Hide watched" is enabled, you return to an empty library view after playing the last episode of a series (or the last movie of a collection. Since the option isn't available in Kodi, maybe this skin could provide the functionality in the library views.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is not something a skin can do. There is no "onfinishedloading" type of trigger available to the skin to trigger an action after a container loads. 

And a skin shouldn't really be taking this level of control over navigation anyway. If anything it should be something handled by Kodi not the skin.
