### ISSUE TITLE
[BUG] Up Next button disappeared 

### ISSUE THREAD

**Issue by yanivz** [jurialmunkey/skin.arctic.horizon.2#535]
### Skin section

Other

### Current Behavior

At first there were a buttin of up next that jumps to the unseen episode. something maked him disappear 

### Expected Behavior

show up next button on series view

### Steps To Reproduce

install arctic horizon 2

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I don't know what you're talking about. Screenshots or a better description would be helpful.

**Comment by starseed420** [comment]
can confirm. The up next button was also not compelet, I did only see the left and right part of the button (rounded corners) the middle part was not visible.

**Comment by jurialmunkey** [comment]
What the hell is this "up next" button that youre talking about. I have no idea what you're referring to. 

As I said, screenshot please so I know what you're talking about. I have no clue what you're referring to

**Comment by starseed420** [comment]
The Up Next Button is part of the Umbrella Addons functionality. It will Autoplay the next Episode. It appears on top of the screen in case the current episode is about to end. Not sure if it is only an Umbrella issue tho

**Comment by yanivz** [comment]
I found it on tmdb helper addon. On series

**Comment by jurialmunkey** [comment]
Still no screenshot... Still have no idea what is been talked about here.
