### ISSUE TITLE
[BUG] New trailer screen returning 2 levels up when stopped in middle using the back button

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#537]
### Skin section

Fullscreen Video OSD

### Current Behavior

Hi @jurialmunkey,

After the latest update today, the new trailer screen is returning 2 levels up if stopped in the middle using the back button (as there is no stop button anymore in the video OSD). For example, say you are in the video info screen and play the trailer and stop it in the middle using the back button, then instead of returning to the video info screen again it directly returns to the home widget screen, which is 2 levels up. Earlier this was not the case as the video OSD was full form like the normal video OSD and we could stop the trailer using the stop button. Now since all the buttons are removed from the trailers window so using the back button is the only way to stop the trailer. Could you please check and kindly resolve?

### Expected Behavior

When the trailer is stopped using the back button after being played using the trailer button on the video info screen it should return in it's correct page, that is the video info page and not the home widget screen.

### Steps To Reproduce

Go to video info screen, play a trailer, stop it in the middle using the back button (as there is no stop button anymore in the video OSD). It will return to the home widget screen instead of the video info screen from which the trailer was actually played.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't control the back button in the info dialog.  

The trailer screen is a fake fullscreen to keep the info dialog active underneath. This is the only option to avoid the info dialog being forced to close when playing a trailer. 

It never worked the way you described. This change was specifically to address the issue of the recommendations and info dialog getting forced to close by kodi when switching to fullscreen. 

You are likely just pressing back twice. 

 I can't win here. There is no solution that will make everyone happy. This is the best approach to ensuring that the info and recommendations dialog can remain open. 

The only thing I can do is make the select action Stop instead of Pause - that's the only command available to me.

**Comment by jurialmunkey** [comment]
See this issue for context of why the change was made https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/533

Returning to a blank screen is a more serious bug than not accessing the controls.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Thanks for the detailed explanation! Okay, if that's the case then I can live with this issue. There's no harm that pressing the back button goes up 2 levels. However, I'm not pressing the back button twice. I'm pressing it only once to stop playing the trailer and it goes back 2 levels. Not sure why. I'm using an Nvidia Shield TV Pro remote. Nevertheless, it's not so much of a big issue. Also, I don't think making the select action stop instead of pause will be a good option as we might need to pause the trailer in the middle rather than stopping it entirely. Please do whatever you think is the best. Thank you for all your work as always!

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Latest commit will allow closing the trailer with up/down. You can still seek back/forward with left/right and pause/play with select.

I can't do anything about the back button as Kodi does not honour what I set for it (it just closes info anyway). But I don't go two levels back when I press back - it just closes the info dialog for me not the library too.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Thanks for adding the option to close trailer using the up/down button! Yes, by 2 levels back I meant that pressing the back button, closes the trailer and then the video info skin and then goes back to the home widget screen. The up/down option is a great alternative for the back button. Thanks again!

Thanks and Regards,
ShibajiCh.
