### ISSUE TITLE
[BUG] Navigation colour / button 

### ISSUE THREAD

**Issue by luckylukz02** [jurialmunkey/skin.arctic.horizon.2#538]
### Skin section

Video Info Dialog

### Current Behavior

![P_20221016_175350](https://user-images.githubusercontent.com/80491975/196047975-e864f042-1f05-4945-8808-f0a5e3b7502a.jpg)

### Expected Behavior

Just noticed that the button disappears behind the browse, trailer and additional icons. Current selection is in white (browse in screenshot) and no button surround. This was confusing at first. 

### Steps To Reproduce

Video Information 

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Kayzels** [comment]
+1 for this issue. It seems the blue texture that is normally shown on the focused selection is gone, and it is transparent. Happens in full screen widgets,  and in the information panel.
Quite confusing to have a transparent selection that is in less focus than the button beside it.

**Comment by xyzfre** [comment]
I had the same situation after the update ,,I exited Kodi and went back in and everything is back to normal,, I made it a habit after a skin update to always power down Kodi right after and then fire it up again

**Comment by alKODIque** [comment]
I saw that  texture Maker has been update.
I just restart Kodi after last uptdate and button  texture back to normal for me too ;)

**Comment by Kayzels** [comment]
@xyzfre @alKODIque thank you. Restarting Kodi did the trick for me :)

**Comment by luckylukz02** [comment]
Excellent. Worked for me too.

**Comment by jurialmunkey** [comment]
Texture maker was updated so you need to restart kodi or reselect your colour scheme to force it to build the textures.
