### ISSUE TITLE
[BUG] Widget screen background image issue and background colour changes

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#541]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

In certain custom widget screens like for addons (see 1st screenshot) incorrect image is showing up after the latest update if the widget is not focused. Also, the default background colour has changed to greyish black after the latest update (see 2nd screenshot). The previous background colour was better according to me. Could you please check and advise?

### Expected Behavior

No image or blurred image should show up in background if the addons widget is not focused. Also, the default background colour was better earlier according to me.

### Steps To Reproduce

Go to custom widget screen for say addons and check it when not focused.

Check the default background colour in empty search menu.

### Screenshots and Additional Info

![IMG20221018213550](https://user-images.githubusercontent.com/65297828/196485539-76d8a2b4-9c11-4b7e-a368-42ae31ac070e.jpg)

![IMG20221018213602](https://user-images.githubusercontent.com/65297828/196485571-e28e61ed-cba3-4e4a-9732-6d2405b836b3.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Please try v0.5.27

Note that background options have now changed. 

| Options | Artwork Displayed |
|  :--- |  :--- |
| :white_large_square: Simple background &nbsp;&nbsp;  :white_large_square: Expanded widget artwork | All widgets |
| :white_check_mark: Simple background &nbsp;&nbsp;  :white_check_mark: Expanded widget artwork | Expanded and Fullscreen |
| :white_check_mark: Simple background &nbsp;&nbsp;  :white_large_square: Expanded widget artwork | Fullscreen only |

![screenshot00002](https://user-images.githubusercontent.com/4618719/196594623-5a32cc58-a4a5-4555-92be-bb2053e33259.jpg)

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

I checked the latest version. It looks much better now. I've enabled both Simple Background (information) and Simple Background (widgets). However, if I'm enabling Simple Background (expanded) then the Flixart is getting disabled in the widget and only appearing in video info screen. Is this correct or a bug?

Also, the newly added shadow at the bottom of fullscreen/square widgets is not looking so good and it is causing the animation to lose it's fluidity while moving from one menu to another. For example, while moving from the movie menu to the search memu, the black shadow is appearing for a few seconds at the bottom and then disappearing. See screenshots below.

![IMG20221019222816](https://user-images.githubusercontent.com/65297828/196758546-0d992074-0d4f-4b65-9b36-c1022fa9a269.jpg)

![IMG20221019223017](https://user-images.githubusercontent.com/65297828/196758676-35145b50-932f-48f8-a61f-90f3dae544e4.jpg)

Kindly check and advise.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
The shadow has always been there. I don't know what people are talking about it being a new addition.

As you can probably tell, I rearranged the background settings to remove the extra dialog. The "expand" option is now the opposite of what I described. It is working correctly. Enabling simple background for expanded widgets means you cannot see artwork on them.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey ,

Thanks for the information! However, as you can that others are noticing the almost same issue as me with the shadow transition, so I think it's not an isolated issue with my setup. In the above screenshots that I shared you can see that the shadow is appearing for a few seconds in the search menu as well while moving from the other Movie menu, which is not looking nice. Prior to the last few updates everything was working fine. After the newly added background image in the video info screen it all started. Also, I personally prefer the much cleaner blurred background image look in the video info screen like earlier so I'm using that currently. I achieved the same using the previously mentioned simple background settings. Hope those are okay? Could you please check and try to replicate the shadow transition issue? Earlier I couldn't even notice the shadow. Now it very much catches the eye while transitioning from one menu to the other. It mainly appears on the fullscreen widgets. I didn't want to nitpick suck minor issues but it looks like as if the shadow is somehow stuck at the bottom which doesn't make it look good.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
No, you are mistaken. The shadow has always been there and the transition animation has always worked like that. I can go back in the git commit history and prove it.

This screenshot below of the transition in motion is from THREE HUNDRED commits ago.  That is almost three months ago (6th Aug) and is exactly the same as the "bug" you are only just noticing now... I have not made changes here. 

![Screenshot (2)](https://user-images.githubusercontent.com/4618719/196892174-cd0c128f-b89a-470c-900c-5e49a2f026ca.jpg)


The only thing you are noticing is that the background fade transition is now faster and the shadow is more obvious on a plain background than on fanart where there is more detail. Nonetheless, I will look at smoothing it a bit but I've already wasted a lot of time on all these minor background bugs for what is ultimately tagged as an experimental feature.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Fine. Thanks for the info! It's not such a big issue. Please carry on with other major updates. However, Flixart is the best thing that could happen to this skin. Thanks a lot for all your hard work! 🙂👍🏻 Looking forward to the Vertical combined list view that I mentioned in ticket #70. Hope it comes soon. Thanks again!

Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

In the latest update the shadow and transition effects are looking much better. I think this issue is resolved for me now. Thank you so much!

Regards,
ShibajiCh.
