### ISSUE TITLE
[BUG] top and bottom gradient 

### ISSUE THREAD

**Issue by starseed420** [jurialmunkey/skin.arctic.horizon.2#545]
### Skin section

Home Widgets

### Current Behavior

After latest update there is a weed black gradients visible on too and bottom bar, see pictures. 

### Expected Behavior

Getting rid of those black gradients to achieve a much cleaner look.

### Steps To Reproduce

Go to home menu, select menu entry on top bar and press down to access the widgets.

### Screenshots and Additional Info

![IMG_20221019_181727_edit_104572605655917](https://user-images.githubusercontent.com/107289029/196815100-e6784f58-caf9-4f55-8e76-e8e565173130.jpg)
![IMG_20221019_181741_edit_104555286885607](https://user-images.githubusercontent.com/107289029/196815119-a2878af9-4773-42dd-86b0-d59964cc0989.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce. Works fine for me on several widgets

![screenshot00003](https://user-images.githubusercontent.com/4618719/196829353-b471f814-2ed7-4359-af3c-3ae589eefbac.jpg)


![screenshot00004](https://user-images.githubusercontent.com/4618719/196829354-eff11567-b9bc-44cd-971f-7f24543e82ba.jpg)

**Comment by saxoloman** [comment]
This only happens on seccond widget row. If first widget is fullscreen widget widget under it will have gradient on top and bottom,third,forth and so on...widget row is ok

**Comment by starseed420** [comment]
I have created a feature request to manually turn those gradients on/off for user who don't like them.

**Comment by jurialmunkey** [comment]
> I have created a feature request to manually turn those gradients on/off for user who don't like them.

There are very specific reasons for the gradient. It cannot be disabled as it is required to mask an ugly layout issue caused by the top alignment of widgets. I will not be adding an option.

**Comment by jurialmunkey** [comment]
> @jurialmunkey For me this only happens on seccond widget row. If first widget is fullscreen widget,widget under it will have gradient on top,third,forth and so on...widget row is ok https://youtu.be/FX8B0u8hUIA

Hmm that shouldn't happen. My two screenshots were that same layout (fullscreen top and then second widget expanded). What version of the skin are you using?

**Comment by jurialmunkey** [comment]
@saxoloman - Should be fixed in v0.5.32 - please let me know if the problem still persists but I'm fairly confident it is fixed now.
