### ISSUE TITLE
Know how many Items in Library

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#547]
### Skin section

Library Views

### Feature description

Just wondering if is it possible to see the amount of items in library etc
On other skins it would tell me how many movies I have in library, or how many movies in particular Genre and so forth

### Why is this feature needed? Please justify and explain.

Keep trakt of library updates.

### Screenshots and Additional Info

![20221020_195952](https://user-images.githubusercontent.com/78307374/197035406-c90ff6cb-7109-41b0-9027-d3aa4871b2cd.jpg)
![20221020_200012](https://user-images.githubusercontent.com/78307374/197035471-4b37e2c5-c746-4815-92e8-68c1fecdd9c3.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Go to titles and focus the scrollbar. The number of items (and pages) will be displayed with the clock.

**Comment by adamosborne83** [comment]
> Go to titles and focus the scrollbar. The number of items (and pages) will be displayed with the clock. (you need the clock enabled to see it)

Yup, needed the clock on to show, well, at least I know, but clock off for me it is.
Thanks.
