### ISSUE TITLE
Not identifying unaired episodes 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#549]
### Skin section

Video Info Dialog

### Current Behavior

Episodes do not show in chosen colour unreleased episodes. 

When I am in Landscape Info unaired show in red.

Media Info List, does not show colour. 

### Expected Behavior

To show the chosen colour in all views chosen 

### Steps To Reproduce

Chose different views. 

### Screenshots and Additional Info

![b4dd334a-7595-43cc-b2d3-0569e9209c44](https://user-images.githubusercontent.com/78307374/197039062-98653a81-5d50-4a27-aff7-6bb661fab310.jpg)
![4723ffca-92e7-4422-b2c5-0a6f0efdfcf3](https://user-images.githubusercontent.com/78307374/197039092-ac9602d8-bec5-42b5-acfa-eb16b50ae89b.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Kayzels** [comment]
The color you select in Arctic Horizon 2 is the background color for the selection. The text is set by the other addon. Umbrella is setting the color to red for unreleased episodes. That is a setting to change in that addon, not Arctic Horizon 2, as far as I can tell.

**Comment by adamosborne83** [comment]
> The color you select in Arctic Horizon 2 is the background color for the selection. The text is set by the other addon. Umbrella is setting the color to red for unreleased episodes. That is a setting to change in that addon, not Arctic Horizon 2, as far as I can tell.

But the text is Red in one view and not the other, so the addon is set for Red.

**Comment by Kayzels** [comment]
> But the text is Red in one view and not the other, so the addon is set for Red.

Yes, Umbrella is setting the text to red italics for unaired episodes. I don't use that addon, but you will probably find a setting to change the color for unpaired episodes in the settings for Umbrella. This does not seem to be related to Arctic Horizon 2.

**Comment by Kayzels** [comment]
Oh, I see what you're saying. Sorry 🙈. So the skin seems to be overwriting the color changes that should be shown? So you want it to still be red in the info list?

**Comment by adamosborne83** [comment]
> > But the text is Red in one view and not the other, so the addon is set for Red.
> 
> Yes, Umbrella is setting the text to red italics for unaired episodes. I don't use that addon, but you will probably find a setting to change the color for unpaired episodes in the settings for Umbrella. This does 


> Oh, I see what you're saying. Sorry 🙈. So the skin seems to be overwriting the color changes that should be shown? So you want it to still be red in the info list?

Correct. It should be Red in BOTH views, not just the 1.

**Comment by umbrellaplug** [comment]
The skin is using the title property on two views. On the others it's using the label property. I do not set the color property on the title.

LandscapeList is using title and not label, mediainfo list is using title and not label. It's only those two views. Not sure why that's happening as I don't know the ins and outs of skins, but hopefully that helps.

**Comment by jurialmunkey** [comment]
Media info list uses title not label because of the layout where episode number and title are split by the indicator.
