### ISSUE TITLE
[Bug] Kodi Android TV application crashing upon startup/initialising

### ISSUE THREAD

**Issue by Weevild** [jurialmunkey/skin.arctic.horizon.2#55]
Here's the log file:
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8840485/kodi.log)

**Comment by Weevild** [comment]
Might add that it's only sometimes that i experience this, it'll crash 2 times or so but then if I close the application and then start it up again it'll work.

**Comment by jurialmunkey** [comment]
I'm really not sure what this issue could be caused by. Log doesn't really give me any info (and I don't have an Android TV so I can't reproduce obviously!).

If you find any other details/info/patterns to what causes it, let me know because at the moment I have no idea.

**Comment by Weevild** [comment]
Hi @jurialmunkey 
Now the odd thing is that nowadays I'm not experiencing what I've spoken about here, but I have crashed one or two times when navigating some home page menus. This might be more that my Shield TV Tube (2019) is rather weak, but I have nothing to report that's harmful to my user experience. I'll be closing this issue and open up a new one if I come across a reoccurring issue.
(Pardon I should've closed this issue sooner).
