### ISSUE TITLE
[Feature] Ability to hide Main Menu Item Textlabel

### ISSUE THREAD

**Issue by starseed420** [jurialmunkey/skin.arctic.horizon.2#550]
### Skin section

Home Widgets

### Feature description

It would be great to be able to hide the TextLabel of Main Menu Items (Widgets) which are not set to Full Expanded Information.

If set to no expanded information the Main menu Items TextLabel, in my case "Shows" is visible. It would be great to hide this label. 

For widget with full expanded information, the shown source TextLabel should stay visible as they fit nicely the UI.

### Why is this feature needed? Please justify and explain.

The feature is needed to make the overall UI appearance more reduced, clean and organized. It would also benefit the overall UI consistency, meaning to only show the Header TextLabel for the specific Widget content, for example "Best Action Movies" and not for the Main menu Item, in my case "Shows".

### Screenshots and Additional Info

![IMG_20221020_212605](https://user-images.githubusercontent.com/107289029/197041205-0192cc2c-e843-47c5-8ca6-72507ebd7e84.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/197064451-7dc80ad0-6acc-4f15-acd3-95994aa5ca20.jpeg) have you tried disabling this setting that's what worked for me

**Comment by starseed420** [comment]
Yes but this would disable all of the textlabels which is not what I want. In case the expanded Information is set to Full, this TextLabel is very nice and helpful.

**Comment by ShibajiCh** [comment]
I agree with @starseed420. This feature will make the UI look even better.
