### ISSUE TITLE
[Feature] Ability to hide top and bottom home menu gradients 

### ISSUE THREAD

**Issue by starseed420** [jurialmunkey/skin.arctic.horizon.2#551]
### Skin section

Home Widgets

### Feature description

It would be awesome to be able to hide to top and bottom dark gradients. Ideally this could be triggered vis a settings switch. "Turn paged gradients on/off" or so.

### Why is this feature needed? Please justify and explain.

The feature is need to give the overall UI a more clean "wall" look without fading out content which is above or below your current position. It would also help for overall orientation since the Text Headlines are more visible for the content that sits below your current position.

### Screenshots and Additional Info

![IMG_20221019_181741_edit_104555286885607](https://user-images.githubusercontent.com/107289029/197044540-f5710e54-40fd-4d4f-86bb-2bbf3db3327e.jpg)
![IMG_20221019_181727_edit_104572605655917](https://user-images.githubusercontent.com/107289029/197044545-8fee62a3-37ed-4545-a44e-d774553dc6f2.jpg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
There are specific reasons for the gradient which are needed to mask an ugly alignment issue. It is also required for text visibility.

These issues where it is displaying when it shouldn't need to be fixed rather than an option added.
