### ISSUE TITLE
[Feature] Landscape Widget-Style without TextLabel

### ISSUE THREAD

**Issue by starseed420** [jurialmunkey/skin.arctic.horizon.2#552]
### Skin section

Home Widgets

### Feature description

Having the option to select the landscape widget without the TextLabel. As of right now, this TextLabel is fixed and cannot be removed.

### Why is this feature needed? Please justify and explain.

This would give the user more flexibility in terms of customization. Right now the BigLandscape is the only landscape style available without the TextLabel. On the other hand the BigLandscape is rather big :) and something smaller would be perfect to play with the sizes of each widget rows.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What would be displayed in the blank space?

All widgets need to be the same height, so the widget cannot be made smaller. There would be a blank space without the text label.

**Comment by starseed420** [comment]
The blank space stays blank, there should be no text at all, just a plain widget similar to the big landscape widget look. Would this be possible?

**Comment by jurialmunkey** [comment]
Like I said. All the widgets need to be the same height to work with the expand options. The space cannot be blank.

**Comment by starseed420** [comment]
Is it possible to add a transparent part below the widget, like PNG with no pixels in it to achieve the correct/needed height?

**Comment by jurialmunkey** [comment]
But then the spacing between widgets will be inconsistent and there will be a larger gap. The spacing between all widgets needs to be the same.

**Comment by starseed420** [comment]
True, I thought about that but since the next widget line is not visible or let's say barely visible, the gap might be okay looking. In my opinion is the "new" Widget Style without text way more benefitial than a consistent widget gap logic.

**Comment by jurialmunkey** [comment]
No. It has to work with expanded both on and off and the sizing has to be consistent.
