### ISSUE TITLE
[BUG] Ratings not showing only in the Information window

### ISSUE THREAD

**Issue by jabir15** [jurialmunkey/skin.arctic.horizon.2#556]
### Skin section

Video Info Dialog

### Current Behavior

On pressing `I` to get to the information window of a movie or a tv show, the ratings (metacritic, trakt, tmdb, rottentomatoes, imdb) do not show, though they show in all the other views.

### Expected Behavior

The ratings should show.

### Steps To Reproduce

1. Go to any movie or tv show detailed information window/dialog

### Screenshots and Additional Info

Screenshot of the movie in the default poster view with ratings data
<img width="1280" alt="Screenshot 2022-10-21 160149" src="https://user-images.githubusercontent.com/16897932/197214793-ec6e2ce2-4d6f-460b-91c6-da25cefa5497.png">

Screenshot of the information window with the missing ratings data
<img width="1280" alt="Screenshot 2022-10-21 160318" src="https://user-images.githubusercontent.com/16897932/197214842-5ef78fa2-ecf2-4df0-8ade-abdc57690cca.png">

Skin version: 0.5.31
TMDB Helper version: 5.0.20

All relevant APIs have been setup in TMDB Helper addon.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.

**Comment by kcook98765** [comment]
Double check that your API key is still set (I may have done something to cause this, but found my API key was no longer set)

Enter your API key in TMDbHelper settings
Skin Settings > Manage Dependencies > plugin.video.themoviedb.helper > API Keys > OMDb API Key

After I added it (and restarted) I began to get ratings again.

Maybe worth a double check.

**Comment by jurialmunkey** [comment]
Ratings working fine for me in the info dialog (even checked this specific movie).

Echoing kcook98765's comment above. Double check that your API key for OMDb is correctly entered. Due to the way Kodi handles the "back" button in the edit control, it is really easy to accidentally delete a character. Also, make sure you press OK on the dialog after making changes otherwise Kodi won't save the new settings.

**Comment by jabir15** [comment]
Thank you for the suggestion. Yes, I checked the OMDb API field again. It contains the 8 letter alphanumeric API.
My thinking is that if the API was set incorrectly, then the ratings would not have shown in any of the views.

I tried deleting the OMDb cache in TMDBHelper settings, but the issue remains. I also checked that the api is valid and working correctly (sent GET requests in Postman, not rate limited or anything like that)

I attach the log if it could be of any help. I see there are some 404 errors with Fanart but I don't think that should be the cause for this issue.
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9843925/kodi.log)

Any help is appreciated.

**Comment by jurialmunkey** [comment]
Why are you using an old version of Matrix? You've got 19.2 installed and 19.4 is most recent.

**Comment by jabir15** [comment]
There's no reason, I just didn't bother to update. I have now updated to 19.4, but the issue remains.
I attach a video, where I think the api fetch can be seen, but going to the info window, the ratings don't show up.

https://user-images.githubusercontent.com/16897932/197354761-420a0d09-b923-41cf-a475-880454f0839f.mp4

Log: 
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9844951/kodi.log)

Thank you for your patience.

**Comment by jabir15** [comment]
I think the bug is due to some issues on my end. Such a commonly used window with this issue would have been reported by other users. When I updated to v19.4, I also installed it to run in [portable mode](https://kodi.wiki/view/Portable_mode) and the issue gets resolved.

I hope there is a solution without nuking and setting it up again, though it has been a long time since a good refresh, and with the addition of the Movie and TV hubs (it is brilliant), maybe I change my whole setup to use them prominently.

I wish there was a quick fix. I don't want to prioritize your time with a bug which cannot be replicated on your end.

Btw, I don't think it is related, but I checked with Arctic Horizon skin in my main Kodi. The info window does show the ratings data.

I attach the log of the portable mode in case it is of any help: [kodi portable.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9845472/kodi.portable.log)

Thanks. All the help is very much appreciated.

**Comment by jurialmunkey** [comment]
Lets try deleting the cache folder to force it to rebuild.
Quit Kodi, delete database_v5 folder, then restart Kodi.

`kodi/userdata/addon_data/plugin.video.themoviedb.helper/database_v5/`
^^^ That's the location of the database (assuming you aren't using profiles and didn't manually set a different path). You should delete the entire database_v5 folder.

**Comment by jabir15** [comment]
Sorry, no luck. Thank you for the suggestion.

**Comment by jurialmunkey** [comment]
As far as I can tell from the log, I think one of your other addons are interfering with the python thread lock and not releasing it properly. My guess is skin helper but that's really only a guess.

**Comment by jabir15** [comment]
Ok. I will try to reinstall this addon and maybe try with others just randomly. In any case, I will do a complete refresh in a few weeks.
You may close the issue for now.

Thank you for all the help and suggestions.

**Comment by jurialmunkey** [comment]
I think this issue is related to some other addon in your system. Either way, I don't think it is anything caused directly by the skin, so I'm going to close this issue.

You could try reducing max threads in TMDbHelper's expert settings as the error in the log relates to python's threading module but it is unlikely to help. Considering TMDbHelper works as expected on the same system using a fresh portable mode install, I would think that it is another of your add-ons causing the issue.
