### ISSUE TITLE
[BUG] Title and plot disappears when Settings menu pops up

### ISSUE THREAD

**Issue by jabir15** [jurialmunkey/skin.arctic.horizon.2#557]
### Skin section

Home Widgets

### Current Behavior

In the Home window, when you press `S` to bring up the Settings menu, the title and the plot disappears. If the title is configured to show as Clearlogo (in Customize appearance) then it does not disappear. The plot disappears in any case. 

This is the case only when you press `S` to pop up the Settings. If you navigate to the Settings by pressing the right arrow keys, then the plot and title does not disappear.

### Expected Behavior

The title and the plot should not disappear when the Settings menu is activated by pressing `S`.
This is a minor issue, as the Settings menu can be easily navigated to using the arrow keys.

### Steps To Reproduce

1. Customize the appearance (Settings->Appearance->Customize appearance) to Thin or Bold font.
2. Go to the Home window.
3. Press `S` to bring the Settings menu

### Screenshots and Additional Info

Screenshot after pressing `S` on the Home window to bring up the Settings menu
<img width="1280" alt="Screenshot 2022-10-21 163442" src="https://user-images.githubusercontent.com/16897932/197222868-a741e7ec-d0b4-4ac1-94fb-6f5b3e1c78cb.png">

Video of navigating to the Settings menu using right arrow keys.

https://user-images.githubusercontent.com/16897932/197226396-75878275-6dd8-4bc7-8eab-55f4adfa67d1.mp4

### Checklist

- [x] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Are you on Matrix? This is a skinning engine issue with variables and there's not much the skin itself can do about it. Fairly certain this bug is fixed in Kodi's skinning engine in Nexus.

**Comment by jabir15** [comment]
Yes, I am on Matrix v19.2. As I said, it is not much of an issue.
Thank you for the explanation.
