### ISSUE TITLE
[Feature] widget always shows latest/first item

### ISSUE THREAD

**Issue by Tee77** [jurialmunkey/skin.arctic.horizon.2#558]
### Skin section

Home Widgets

### Feature description

e.g. a new episode appears on next episodes widget, or a new movie appears on an mdblist ‘latest movies’ widget sorted by release date. 

Wonder if it’s possible for widgets to reset their position to the first item in the list when a new item is added, so the latest item added is automatically visible?

### Why is this feature needed? Please justify and explain.

Currently, if I’m at the top of a widget list and a new item is added, the new item appears off screen to the left. I wouldn’t call it an issue at all, but if new items could be ‘presented’ to the user rather having to navigate to them, that would be a nice feature. 

Have a feeling this may be a kodi thing rather than something a skin could implement, but wanted to ask. 

Keep up the good work, this skin really is something else! 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Yeah its a Kodi thing. When a container reloads Kodi will focus the last focused item if it exists in the list - otherwise it focuses the first position. Don't think there's anyway the skin can override that behaviour

**Comment by Tee77** [comment]
Ah ok. Thanks for getting back to me.
