### ISSUE TITLE
[Feature] big poster fullscreen widget

### ISSUE THREAD

**Issue by A3006B** [jurialmunkey/skin.arctic.horizon.2#560]
### Skin section

Home Widgets

### Feature description

Loving the new big poster view type, would it be possible to be able to use this view type in the full screen widget?

### Why is this feature needed? Please justify and explain.

The full screen widget has a more limited choice of view types.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by starseed420** [comment]
+1

**Comment by A3006B** [comment]
To clarify I mean the new feature poster widget style :)

**Comment by jurialmunkey** [comment]
How would that work? It takes up practically the whole screen already...

**Comment by A3006B** [comment]
I just thought when the first widget row is set to feature poster it looks great, and when it’s not the fullscreen widget you lose the fanart background without having to click down from the menu icon. No worries though :)

**Comment by jurialmunkey** [comment]
That's a really roundabout way to address a different issue. There is already a bug report filed for this scenario
https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/250
