### ISSUE TITLE
[Feature] Brighter Flixart/Keyart 

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/skin.arctic.horizon.2#562]
### Skin section

Home Widgets

### Feature description

Brighter Flixart/Keyart In widgets/plugins and darker (as it is now) in video info.

### Why is this feature needed? Please justify and explain.

I think this artwork would look better with full brightness since the letters are on the left.
In video info it does make perfect sense as it is :)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry not going to happen. If you increase the brightness of the image then the brightness of the blur also needs to increase to colour match properly. On a light background it becomes impossible to read text.

**Comment by daviddia5** [comment]
Perhaps I have explained myself wrong. I mean in this kind of view:
![IMG_2022-10-24-01-51-12-008](https://user-images.githubusercontent.com/74454397/197424419-9e2a7609-e21d-4c92-82a1-a5b803d409f7.jpg)

In the information view it is perfect. The text must be read correctly
![IMG_2022-10-24-01-51-40-367](https://user-images.githubusercontent.com/74454397/197424521-8e649a9b-ebd8-4829-949e-90c013592697.jpg)

**Comment by jurialmunkey** [comment]
Those are the same brightness.

If you increase the brightness of the image on the right, then the brightness of the blurred part on the left must also be increased so that the colour values match. On a light background, if the brightness of the blur on the left increases then you won't be able to read the text.

**Comment by jurialmunkey** [comment]
Here's a particularly ridiculous example

![screenshot00013](https://user-images.githubusercontent.com/4618719/197437588-c360aae9-1d70-4d6a-bcda-ad45b2ffda1f.jpg)

**Comment by daviddia5** [comment]
You're right. Perhaps with a mask or gradient in the seam area something could be done.
But that's great, we already look for the detail to achieve perfection hehe.
Thanks for everything, amigo.

**Comment by daviddia5** [comment]
Hello jurial, long time without writing here, I hope you are well :)
I'm returning to this thread because I was testing Artic Fuse and I've seen that the brightness of the fanart is much higher (I like it!)
In my case I still stick with AH2, it runs smoother on my system (Google TV) and I like big posters hehe
Would something similar be possible in our beloved AH2?

**Comment by jurialmunkey** [comment]
No because I specifically made design choices in Arctic Fuse to accomodate this. I would need to redesign the whole skin... which is why I made a new one in the first place...
