### ISSUE TITLE
[Feature] Remaining Episodes in Footer

### ISSUE THREAD

**Issue by Kayzels** [jurialmunkey/skin.arctic.horizon.2#563]
### Skin section

Home Widgets

### Feature description

The footer for a TV show widget currently shows the number of watched episodes, and the total episodes. The bottom circle in the widget has the remaining episode count.

Would it be possible to include that remaining episode count in the footer as well. 

### Why is this feature needed? Please justify and explain.

It works well in the circle, so I don't want to remove that. However, it is easier to read text in the footer. And if I'm looking at the screen from further away, I can more clearly see a number in the footer rather than in the circle.

So being able to see how many episodes I have left in the footer as well would make it easier for me to see. Numbers like 3 and 5 aren't as easily distinguishable in the circle. And having 33 or 55 episodes remaining is a significant difference.

Possible downsides would be that it takes up more horizontal real estate, and that it is repeated information. However, there doesn't seem to be any other information in the left footer for TV shows, and I have motivated above why it would be nice to also have it in the footer. 

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I tried a few things but I don't really like it. Having an extra label really adds to the clutter and makes it hard to see relevant info at a glance.

There's also a *lot* of duplication of info if no episodes have been watched as you can see here:

![Screenshot 2022-11-14 181351](https://user-images.githubusercontent.com/4618719/201597527-0068e322-52a5-4852-be18-3ea81176600a.jpg)

I think the disadvantages significantly outweight the benefits. Also I would hope most people can quickly calculate a rough idea of the number of unwatched by subtracting the watched count from the total (and you should be able to see enough of the number in the circle to have a vague idea already).

**Comment by Kayzels** [comment]
Agreed, looking at the screenshot. Does look a bit crowded.
