### ISSUE TITLE
[BUG] Bug on pressing back button from submenu widget

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#565]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

Happy Diwali! 🙂

If I press back button while on the submenu widget at the bottom then the widgets on the screen totally freeze and get messed up with the background changing to the fullscreen widget fanart, and appears like the attached screenshot. Please check and advise.

### Expected Behavior

Pressing back button while on the submenu widget at the bottom should either move the focus to the start of the submenu widget or to the main menu.

### Steps To Reproduce

Go to submenu widget at the bottom and press back button.

### Screenshots and Additional Info

![IMG20221024194242](https://user-images.githubusercontent.com/65297828/197548288-43887615-46df-4bea-9648-53b8c81eb17f.jpg)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The menu is focused in your screenshot.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Yes, the menu is focused in my screenshot. However, the widgets should also move accordingly, i.e. the first top widget should show under the focused menu, which is the fullscreen widget for me. Instead after pressing back from the submenu widget at the bottom only the top menu is getting focused, but the widgets don't move accordingly (only the top widget fanart is showing up, but not the actual widget is getting focused). This is not happening while pressing back from any other widgets. They are working fine. Only while pressing back from the bottom submenu widget this issue is happening. Once the menu gets focused we need to press down again to align/focus the widgets in the correct order. You can do the same and try to replicate the issue. You should also notice the same that I'm experiencing. The screenshot is not able to justify the issue properly I guess.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Thank you @jurialmunkey !
