### ISSUE TITLE
[BUG] New "Feature Poster" Positioning Bug 

### ISSUE THREAD

**Issue by starseed420** [jurialmunkey/skin.arctic.horizon.2#567]
### Skin section

Home Widgets

### Current Behavior

The positioning of new Poster Layout is buggy when navigation through home menu, see video.

### Expected Behavior

Posters are positioned more vertically centered

### Steps To Reproduce

Define new Poster style in widget section and navigate back to home menu. Scroll through content.

### Screenshots and Additional Info

https://user-images.githubusercontent.com/107289029/197563508-cc63fc59-9f86-4553-9bd7-d3b38e54fd42.mp4

https://streamable.com/k83rhg

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You can't put it as the last row without a submenu widget. This is the problem with multiple height widgets. There is nothing I can do about this situation.

**Comment by jurialmunkey** [comment]
Actually manage to figure out a workaround for this issue. Will be in next release.
