### ISSUE TITLE
[Bug] Overspill on now playing with (very) long titles.

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.horizon.2#57]
Granted, this is an obscenely long track title, but there should probably be limiting on now playing length :D

![screenshot00022](https://user-images.githubusercontent.com/25871666/172065990-cc70ca09-a8af-43cd-b301-edf6a21ba024.png)

Very rare anyone will have track titles this long, but possible with orchestral pieces which often have very long names. 

but it should be noted, this is a stupidly long track title :') 

![image](https://user-images.githubusercontent.com/25871666/172066036-952d2865-5592-4596-9171-f1df1303c82b.png)

**Comment by dm2912** [comment]
Doesn't mention "Night of the Day of the Dawn of the Son of the Bride of the Return of the Revenge of the Terror of the Attack of the Evil, Mutant, Alien, Flesh Eating, Hellbound, Zombified Living Dead"

**Comment by xyzfre** [comment]
How do you change the background to gray instead of white I noticed in your pic appreciate any feedback

**Comment by dm2912** [comment]
Theme settings > colour--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 05/06/2022, 20:17 xyzfre ***@***.***> wrote:

   
  How do you change the background to gray instead of white I noticed in your pic appreciate any feedback

**Comment by xyzfre** [comment]
Thank you got it
