### ISSUE TITLE
Would you consider 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#570]
### Skin section

Other

### Feature description

Good Evening,

I trust you're well.

I was wondering if you'd consider not making the weather fanart and icons, an dependency of installing the app?

### Why is this feature needed? Please justify and explain.

I use this skin on all TVs around my home, it is not an issue on the main TV as I use a FireCube,  but on my other TVs I use the FireStick woth are limited for space..... I must be honest I do uninstall the weather aspects of it, and there is no detriment to the skin personally.

So was wondering if you'd consider making this an option?

### Screenshots and Additional Info

![1666816840923163198004648217130](https://user-images.githubusercontent.com/78307374/198133249-a686f791-649d-4cf7-a0bd-3c6a52f4bb51.jpg)
Working fine without weather ...

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I could make the fanart optional as it is only needed in the weather window (and I can do a prompt to install when the window loads)

The icons I can't make optional though because those are used in common ui elements like the clock and side menu - you'd be constantly getting prompts to install them everytime you opened settings.

I doubt the icons take much space anyway. I'd expect the fanart would be the main space hog.

**Comment by adamosborne83** [comment]
> I could make the fanart optional as it is only needed in the weather window (and I can do a prompt to install when the window loads)
> 
> The icons I can't make optional though because those are used in common ui elements like the clock and side menu - you'd be constantly getting prompts to install them everytime you opened settings.
> 
> I doubt the icons take much space anyway. I'd expect the fanart would be the main space hog.

Thank-you for that, it is around 100mb, which on the FireCube is fine, but on lower spec devices can be quite a lot. That possibly not every user would use.
Thanks again,

**Comment by saxoloman** [comment]
@adamosborne83 
Hi,how did you remove settings icon ? I would love to get rid of it

**Comment by adamosborne83** [comment]
> @adamosborne83 Hi,how did you remove settings icon ? I would love to get rid of it

![16669754692035842197467818851019](https://user-images.githubusercontent.com/78307374/198689619-e8e5e57f-e823-478d-b611-60fb7e361a07.jpg)
