### ISSUE TITLE
[Feature] hide top row widgets when scrolling down

### ISSUE THREAD

**Issue by Mycale11** [jurialmunkey/skin.arctic.horizon.2#572]
### Skin section

Home Widgets

### Feature description

When browsing a home page with multiple widgets, the first widget looks great. The whole flixart is shown and it looks very clean.

If you scroll down to the second widget and below, the widget above is dimmed, but it is still visible above the flixart, but under the clock. This cuts the flixart and makes the clock difficult to read, especially if there are watched indicators on the widget above. 

### Why is this feature needed? Please justify and explain.

The feature isn’t needed from a functional point of view, however it would make scrolling the homepage look much cleaner. There are already chevrons on the top of the screen if it’s possible to scroll up to another widget, so showing the bottom of the widget above isn’t necessary. 

I hate to say it, but this is how Netflix works as well; the art position is fixed and all that’s visible are the widgets below. Once you scroll down, the above widget disappears completely so that the art is unobstructed. 

### Screenshots and Additional Info

![552E3161-2C1C-41A1-87B0-F4148692A6B6](https://user-images.githubusercontent.com/107252205/198573855-577b8372-fa68-4c22-a8b8-1f819f72824a.jpeg)

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skin settings > menus > expanded widgets move title to header.
