### ISSUE TITLE
[Feature] Sub Menu 

### ISSUE THREAD

**Issue by koby455** [jurialmunkey/skin.arctic.horizon.2#574]
### Skin section

Home Widgets

### Feature description

Hey
I would like to be able to click on one of the categories above
And a SUB menu window will open - with a picture on the side
Secondly, I want the submenu to be as a widget on the screen
And I can determine what will be there more easily

### Why is this feature needed? Please justify and explain.

comfort

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can already set the action to open the submenu from common. 

You can also already set a widget as the submenu by choosing submenu from default widgets.
