### ISSUE TITLE
[Feature] Some ideas for the new Lovefilm widget (I love it!)

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/skin.arctic.horizon.2#575]
### Skin section

Home Widgets

### Feature description

I love Lovefilm, you can use it as a home widget, using autoscroll, and it's very visual. Thanks!

A couple of ideas:
- Being able to select the autoscroll time. In this case, which is very visual and quick information, for example 5 seconds.
- Five stars with the rating (type AH1 in yellow or red) would be very cool and film. I don't know the location, maybe under the clearlogo?
![IMG_2022-10-28-23-19-09-498](https://user-images.githubusercontent.com/74454397/198735213-d8e10988-5c0d-41f7-918a-0e8654cb301e.jpg)

### Why is this feature needed? Please justify and explain.

They are only suggestions. Thanks again!

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You should be able to choose autoscroll time under behaviour in skin settings. Is it not working for lovefilm?

**Comment by daviddia5** [comment]
> You should be able to choose autoscroll time under behaviour in skin settings. Is it not working for lovefilm?

It works, but the minimum is 10 seconds. Could another 5 second option be added?

**Comment by jurialmunkey** [comment]
> It works, but the minimum is 10 seconds. Could another 5 second option be added?

Yeah, no worries. I wish it was possible to have a user set value rather than hardcoding them, but easy enough for me to add some additional options. 

I also added a 8 second option, as I think you'll find the 5 second option is probably a bit *too* fast once you try it out.

**Comment by daviddia5** [comment]
Wow! Spectacular! Thanks!
https://user-images.githubusercontent.com/74454397/198886792-ee7f5b7f-5f81-4eef-a983-6678c1ee16ca.mp4
Would it be possible that when you focus, the footer with the studio logo etc. appears? Like any other expanded widget.

Another detail, I have noticed that when you change some artwork the posters disappear for a while, until it is updated.
