### ISSUE TITLE
Collections when pressing down.

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#576]
### Skin section

Video Info Dialog

### Current Behavior

This might be an error...... so when I press down for more info, the 'Collections' is a lot more sporadic than what it use to be in AuraMod for example, and correct me if I am wrong, but I thought TMDBhelper grabbed this information?

![20221029_110836](https://user-images.githubusercontent.com/78307374/198825800-bda9b0b7-a7af-4d18-9181-44658b17efc5.jpg)
![20221029_110852](https://user-images.githubusercontent.com/78307374/198825807-83ecc850-5bea-4256-9df8-74f1f1a9f0cb.jpg)
![20221029_110858](https://user-images.githubusercontent.com/78307374/198825813-7e7cf60e-d934-4ae1-b221-4ba3b09681fa.jpg)

### Expected Behavior

That collections would all be grabbed. 

### Steps To Reproduce

Go into info on movie
Press down
Sporadic if collections show up.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It's because the plugin that you're using is not setting the ListItem.Set infolabel. I can add a workaround but the plugin should add that infolabel because it is what Kodi uses to identify that a movie is part of a collection.

**Comment by adamosborne83** [comment]
> It's because the plugin that you're using is not setting the ListItem.Set infolabel. I can add a workaround but the plugin should add that infolabel because it is what Kodi uses to identify that a movie is part of a collection.

Thanks for doing the work around in this, I did also let the developer know of the issue too.

Thanks again,
