### ISSUE TITLE
[BUG] mistranslation on full width widget

### ISSUE THREAD

**Issue by yanivz** [jurialmunkey/skin.arctic.horizon.2#577]
### Skin section

Home Widgets

### Current Behavior

![PXL_20221029_164939790](https://user-images.githubusercontent.com/4169780/198843509-8f70977c-4ef4-48f9-8245-311e28a29b18.jpg)
After updat the full screen widget is in English. It was in Hebrew before also set in tmdb to Hebrew.

### Expected Behavior

It should be Hebrew 

### Steps To Reproduce

Its just happened after update. Before it was fine.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This has nothing to do with the skin. The skin doesn't control the language of the content in a widget.
