### ISSUE TITLE
[Feature] Define Highlight cursor thickness

### ISSUE THREAD

**Issue by starseed420** [jurialmunkey/skin.arctic.horizon.2#578]
### Skin section

Home Widgets

### Feature description

It would be cool to select between different cursor thicknesses. The current cursor is very prominent which works great on smaller TVs but when watching on a large screen like a beamer, the borders are very big :) 

### Why is this feature needed? Please justify and explain.

To give a beautiful UI experience on large screens without having this "chunky-feel".

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Not possible. The kodi skinning engine does not allow for coordinates to be defined with variables. It would also require separate textures for every possible thickness of the border.

**Comment by jurialmunkey** [comment]
BTW There *will* likely be an option to toggle a thinner selectbox soon. It's only that it's not possible for the user to define exactly how thick or thin - it has to be a fixed size.

**Comment by starseed420** [comment]
sounds good 👍
