### ISSUE TITLE
[BUG] Remapping play button

### ISSUE THREAD

**Issue by ddsarad** [jurialmunkey/skin.arctic.horizon.2#584]
### Skin section

Home Widgets

### Current Behavior

When I try to remap one of my buttons to the play function, it does not work when I am viewing movies on widgets on my home screen. The button does work when in TMDB helper though. Also, it does not work when in the landscape combined seasons view for tv shows. Thank You

### Expected Behavior

Remapped play button will launch the video.

### Steps To Reproduce

1. Remap another button to play the video
2. Go to home widget and find a video
3. Press remapped button

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The skin does not control what play does. This is controlled by Kodi and as you are finding it will only work on library views not widgets (episodes in combined view is a widget) 

If you want the button action to work for widgets then you should map it to select not play

**Comment by ddsarad** [comment]
Thank you again for the beautiful skin and the answer, I however am trying to use one button as a play function and another to show information. I initially tried to map a key to opening the information, and keep the select button as play,  but that wasn't working so I changed my select button function from play to show information. I know it's not a big deal but would be very helpful for me, if possible. I am using an NVIDIA Shield

**Comment by jurialmunkey** [comment]
You can set the action of buttons per section. Actions do not need to be global. There are also long press actions to use a button twice. 

In media windows (eg home / myvideonav etc) you should use the Select action not Play. Select will play playable items. 

Select is a core action which is necessary for parts of the gui involving navigation - you will struggle to use kodi without a select action. 

You should only replace select with play in Windows involving playback without navigation (eg in the fullscreen video window the playpause action is more useful than select). 

The kodi wiki documents how to make a proper keymap with section specific actions
https://kodi.wiki/view/Keymap
