### ISSUE TITLE
[Feature] Changing the size of the mouse pointer

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/skin.arctic.horizon.2#585]
### Skin section

Mouse and Touch

### Feature description

Nowadays, to change the size you have to edit the file manually

### Why is this feature needed? Please justify and explain.

Changing the size by changing the skin settings

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Not possible. The skin engine does not allow for coordinates to be defined as variables.
