### ISSUE TITLE
Background wedges 

### ISSUE THREAD

**Issue by timiman1996** [jurialmunkey/skin.arctic.horizon.2#586]
### Skin section

Home Widgets

### Current Behavior

how can i change the background of the widgets? now it's dark

### Expected Behavior

how can i change the background of the widgets? now it's dark

### Steps To Reproduce

how can i change the background of the widgets? now it's dark

### Screenshots and Additional Info

how can i change the background of the widgets? now it's dark

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by timiman1996** [comment]
Sorry for my bad englisch

**Comment by timiman1996** [comment]
![Uploading 16674730388184133112324609216718.jpg…]()

**Comment by jurialmunkey** [comment]
Skin settings > customise appearance.
