### ISSUE TITLE
[BUG] Posters disappear in Lovefilm widget

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/skin.arctic.horizon.2#587]
### Skin section

Home Widgets

### Current Behavior

Posters disappear in Lovefilm widget. Every time something is played or an artwork is updated. They disappear for a few seconds and then come back.

### Expected Behavior

Don't let the posters disappear :)

### Steps To Reproduce

Home widgets, Lovefilm

### Screenshots and Additional Info

![IMG_2022-11-03-17-28-27-584](https://user-images.githubusercontent.com/74454397/199778256-e80e509f-9845-47ff-8ed2-2ceb8512ccea.jpg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by starseed420** [comment]
I randomly have the same issue. The posters sometimes just disappear.

**Comment by jurialmunkey** [comment]
I can't seem to reproduce this issue.
