### ISSUE TITLE
[Feature] wider header-text placeholders  

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#589]
### Skin section

Home Widgets

### Feature description

The latest updates introduced some changes in font sizes. I have to admit I have mixed feelings about it. 
Bigger headlines / titles look really good and modern in OSD - that's for sure. 
On the other hand, when it comes to titles in expanded widgets and titles in info dialog, my experience  is less pleasant.
The reason for that is that most (if not all) european languages - like polish, german or french - are not as concise as english (in terms of lenghth of words and sentences), so if you use polish or german meta-data provided by TMDBhelper, you can expect longer titles and longer descriptions than origianl ones. 
Now, when titles got bigger, but the width of text-placeholders remained not changed, most titles need to be scrolled to be desplayed fully (Ihope that makes sense...). That's obviously not what good user experience should be. 
Please see attached screenshots.
<img width="1440" alt="Zrzut ekranu 2022-11-3 o 21 57 00" src="https://user-images.githubusercontent.com/679205/199838688-8bfdb5e6-db0c-4412-99a8-8ca4f7fab358.png">
<img width="1440" alt="Zrzut ekranu 2022-11-3 o 21 57 10" src="https://user-images.githubusercontent.com/679205/199838701-92257712-6f15-46b4-a039-64859a163f92.png">
<img width="1440" alt="Zrzut ekranu 2022-11-3 o 21 57 41" src="https://user-images.githubusercontent.com/679205/199838708-b6461e97-9b13-42d8-9ff6-134f959dc077.png">

Of course one possilble solution is to enable auto-scrolling (which I find personally anoying)
Another solution could be to make that text placeholders wider like (100% - margins) for info dialog script and +150px for home-screen based full expanded widgets. Would that be possible?

Another thing (but still related to the same problem) is the width of text placeholder for loading widgets. One of my widget groups is "Popularne w tym tygodniu" (which means Popular this week) - now, see how the loading text is rendered. Could it get wider as well? 
<img width="1440" alt="Zrzut ekranu 2022-11-3 o 21 59 01" src="https://user-images.githubusercontent.com/679205/199838736-231755b3-559d-4872-ab33-550108f36940.png">

### Why is this feature needed? Please justify and explain.

Two words: user experience ;-)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I knew this was going to come up. I've already got something planned to address this issue - just working out some rough edges.

Plan is for oversized titles to shrink to a half height font over two lines:


Oversized title:

![screenshot00060](https://user-images.githubusercontent.com/4618719/199928863-d1b524d5-2173-4f69-8691-4d9b5be6ad0d.jpg)

Standard title:

![screenshot00059](https://user-images.githubusercontent.com/4618719/199928933-099f874e-611c-4132-8613-15d4af5ae5e5.jpg)

**Comment by krzysztofwinnik** [comment]
Even better - looks really nice! Thank you

**Comment by krzysztofwinnik** [comment]
Yup, oversize titles look great again - many thanks for that.
Before closing the issue, could you please stretch the placeholder for loading widget's title (as in my last screenshot)? 
It's a tiny thing, which shouldn't mess with the grid...

**Comment by krzysztofwinnik** [comment]
And obe more thing @jurialmunkey. I,ve just noticed that the double line trick doesn't work for OSD as in photo![image](https://user-images.githubusercontent.com/679205/200110938-5742a79c-694f-4416-a3dd-ad382f86683b.jpeg)

**Comment by jurialmunkey** [comment]
Yeah I noticed the OSD issue last night actually.

I'm trying to decide whether it would be better to just expand the allowed width there since there's plenty of room -- but maybe it's better to go for consistency instead.

**Comment by jurialmunkey** [comment]
I expanded the busy spinner width. Hopefully it is by enough.

There was some reason why I didn't just make it full width but I can't remember what exactly. There must've been somewhere that wider text wouldn't fit -- shouldn't be any harm in making it a bit wider though.
