### ISSUE TITLE
[BUG] Nexus Video Information

### ISSUE THREAD

**Issue by luckylukz02** [jurialmunkey/skin.arctic.horizon.2#590]
### Skin section

Video Info Dialog

### Current Behavior

Currently when your on the video Information screen the buttons are hidden. 

![P_20221103_230145](https://user-images.githubusercontent.com/80491975/199851282-611544f1-5f4a-4ca1-9cff-cbd3fc97861d.jpg)

### Expected Behavior

You need to press ok (or left arrow) on remote to show the buttons that appear on the left. This is an extra step to take to eventually play or use any of the buttons. 

![P_20221103_230151](https://user-images.githubusercontent.com/80491975/199851297-223370a3-ab97-4d0a-9316-7870f841e4fd.jpg)

### Steps To Reproduce

Video Information Screen

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is not a bug. It is the intended behaviour.

**Comment by luckylukz02** [comment]
> This is not a bug. It is the intended behaviour.

OK, thanks. Just seems counter productive.

**Comment by jurialmunkey** [comment]
Option available in next release to focus buttons by default.
