### ISSUE TITLE
[Feature] Autoscroll Fullscreen Widgets

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/skin.arctic.horizon.2#591]
### Skin section

Home Widgets

### Feature description

Could you add an option to allow fullscreen widgets to autoscroll?

### Why is this feature needed? Please justify and explain.

Since fullscreen widgets are displayed at the top of a page, it would be nice to see the content autoscroll.  At the moment we are forced to choose between a fullscreen widget that doesn't autoscroll and a regular widget with does (but lacks some of the features of fullscreen widgets).

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What exactly do you mean by "fullscreen" widget because if you mean the fanart with buttons, then that autoscrolls for me already.

**Comment by eengert** [comment]
I have the fullscreen widget for one page set to big landscape style, and on another page set to poster style. Neither autoscrolls. Regular widgets do autoscroll.

**Comment by eengert** [comment]
Fullscreen widget settings:

![Screen Shot 2022-11-04 at 9 14 42 AM](https://user-images.githubusercontent.com/33561812/199981579-7006c69e-2d2f-41ae-9cb6-03c40ee06965.png)

![Screen Shot 2022-11-04 at 9 15 05 AM](https://user-images.githubusercontent.com/33561812/199981668-f15dc6d3-3e67-4710-9218-fd02d91e6656.png)


Fullscreen widget displayed, but doesn't autoscroll:

![Screen Shot 2022-11-04 at 9 15 31 AM](https://user-images.githubusercontent.com/33561812/199982021-d735eb29-fd1a-4dad-8df8-772f8bd1fd55.jpg)
