### ISSUE TITLE
Year , Rated  , Gene, Duration  disappears randomly only within TMDb

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#593]
### Skin section

Other

### Current Behavior

Year ,Rated , Gene , Duration disappears only within TMDb not on home screen widgets , when I go in to TMDb H on Start up the Year etc.. show up properly but when I back out and go back in for the second time that’s when it comes up blank for Year ,Rated etc.. shows up blank, using Nvidia Shield 2019 Pro K19.4

### Expected Behavior

/

### Steps To Reproduce

1. Go into TMDb H Year ,Rated etc.. shows up fine 2. Back out from TMDb H to the Home Screen 3. Go back into TMDb H and that’s when the Year, Rated, etc.. go blank

### Screenshots and Additional Info

https://paste.kodi.tv/zukevuhuli.kodi

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [ ] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/199986738-02240192-8c18-4eed-992f-e06af9ca9205.jpeg)

**Comment by xyzfre** [comment]
I just tried on a brand new fresh install on my PC and the same behavior hope my log helps they didn't notice when this started happening hopefully it's something you can address soon thank you for all your hard work and dedication

**Comment by xyzfre** [comment]
Been testing some things out this is really messing with me but it looks like if I change the view from square list which was what I was using back to square row in TMDb H main section it fixes the issue

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/200042775-06146c46-6d16-4b28-9e20-75e804045364.jpeg) changing back to square row fixed it

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/200042905-d118b224-93d4-4268-bbf7-e1ce0c5b2916.jpeg) changing to square list on all my plug-ins (only 2 including TMDb H) it's when the issue comes back

**Comment by jurialmunkey** [comment]
That is intended behaviour on Square List. With the recent resizing of the infopanel, all the lists will only show title.

Is this only happening when you go from a list view to a row view?

**Comment by jurialmunkey** [comment]
Can you try the latest version from the main branch? (Not in the releases yet).

Hopefully that will fix the problem.

**Comment by xyzfre** [comment]
Just tried it on my PC seems to be working correctly now when I get a chance going to try on my Nvidia Shield 🤞🏼 Will definitely keep you posted thank you so much @jurialmunkey

**Comment by xyzfre** [comment]
Didn't want to open up another thread not sure if this is intentional but when in recommendations in the background you can see episode and watch count my apologies for posting this here

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/200129150-13ae7983-6a1a-421b-9fc6-8ea461157a74.MOV

**Comment by xyzfre** [comment]
crappy video sorry😬
