### ISSUE TITLE
[BUG] auto update for addons

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/skin.arctic.horizon.2#595]
### Skin section

Other

### Current Behavior

Automatic update for all addons
Also for the Skin

### Expected Behavior

For some reason the addons don't just get updates manually
When I try to set them to automatic, it goes back to manual mode

### Steps To Reproduce

go to the addons and click update

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce. This is not something the skin controls anyway - it's a kodi setting.

Have you properly tested in the default skin or did you just tick that box without actually checking? I very much doubt that you have this issue only with AH2  and not Estuary as it simply not something the skin has any control over.

**Comment by The-cpu-max** [comment]
I didn't know how to check.
Anyway ,
I thought if it was a bug that everyone has
We will know about her

**Comment by jurialmunkey** [comment]
You must test in Estuary first before reporting bugs. Don't tick the box that you have tested in Estuary if you haven't.
