### ISSUE TITLE
Show Information

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#596]
### Skin section

Video Info Dialog

### Feature description

OK, stick with me here......
In kodi settings, media settings, videos, I have it set to Show Information.
As when on movies I love the one click, that then goes into the Information for trailers, cast info etc.

But I have the show Information aspect for TV Shows and just wish it would play.

There is an addon, that will BYPASS the kodi setting, so I can have kodi to set to Play, but will come up with movie Information if I set it that way, and then just play TVShows.

Can you somehow add this? As you can see in the pics, your layout is visually more appealing for me. 

![1a879c80-f76f-49af-8427-b99e90091171](https://user-images.githubusercontent.com/78307374/200058413-4f560091-2345-42ec-b6a2-7abe03544bc8.jpg)
![045373c7-9529-4240-9fdf-cda766deb521](https://user-images.githubusercontent.com/78307374/200058452-499acec2-987a-418e-b75b-3fe74f05a14c.jpg)

### Why is this feature needed? Please justify and explain.

Great option to have.

### Screenshots and Additional Info

![845af8d3-e6ce-479c-a19f-084be546e006](https://user-images.githubusercontent.com/78307374/200058552-890bc737-1fac-4f86-a08f-2b1f5e76cd5c.jpg)
Then tv shows will just play straight from here, as I have the info I need, and have no interest in trailers and cast etc, as I already know that. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It's not really possible unfortunately. The skin can't control the click action inside media windows (at least not without hacks that break other things like context menu). It needs to be added in kodi core. 

I completely get where you're coming from though. I've never understood why this setting isn't applied separately per content type. To me it completely makes sense to want to view info about a movie before playing but not episodes. By the time you're at episodes you already know what you're watching. Also it is really annoying if  watching multiple episodes in a row.

**Comment by adamosborne83** [comment]
> It's not really possible unfortunately. The skin can't control the click action inside media windows (at least not without hacks that break other things like context menu). It needs to be added in kodi core.
> 
> I completely get where you're coming from though. I've never understood why this setting isn't applied separately per content type. To me it completely makes sense to want to view info about a movie before playing but not episodes. By the time you're at episodes you already know what you're watching. Also it is really annoying if watching multiple episodes in a row.

Glad you see and understand the frustration. Although feel free to make a hacked version 😁 I did think it was more of an addon option instead of a skin to be able to do what I want. 
Thanks as always
