### ISSUE TITLE
[BUG] mouse and touch screen left side playback buttons

### ISSUE THREAD

**Issue by phantom9s** [jurialmunkey/skin.arctic.horizon.2#597]
### Skin section

Fullscreen Video OSD

### Current Behavior

when i try to pause or reach any of the left side buttons in playback the playlist open instantly this only happen to left side button for some reason this glitch happen for both mouse and touch screen

### Expected Behavior

be able to pause or use any of the left side buttons with mouse or touch screen

### Steps To Reproduce

play any tv show
try to pause using touch screen or a mouse

### Screenshots and Additional Info

https://user-images.githubusercontent.com/61731686/200067480-81f50a8b-b7dc-42a5-8c6c-82a3469adc5b.mp4

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Mouse is not official supported in this skin.

I try to get it working where I can but the skin engine mouse support is poor so it is not always possible.
