### ISSUE TITLE
[Feature] Lovefilm Header Alternative-Position

### ISSUE THREAD

**Issue by starseed420** [jurialmunkey/skin.arctic.horizon.2#599]
### Skin section

Home Widgets

### Feature description

It would be great to re-position the Text-Header which is used in Lovefilm Layout Style. 

To make the UI more consistent to the other Layouts positioning the header above the Clearlogo would make it...

A: more easy to understand & read (from UX perspective).
B: more consistent to other Layouts (as they also use TextHeader above Clearlogo)

To make space for the header the Clearlogo, media details, ratings and plot need to be lowered a bit, ideally same distance as used in Fanart layout with full plot.

### Why is this feature needed? Please justify and explain.

This feature will bring more consistent framework behavior to the skin and will benefit the UX.

### Screenshots and Additional Info

![IMG_20221105_112014_edit_241562340100638](https://user-images.githubusercontent.com/107289029/200115343-3cec27d2-4af1-41fe-98de-13e53d4bc1ee.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
> B: more consistent to other Layouts (as they also use TextHeader above Clearlogo)

I disagree with this point. The only time the label is above the text is if the option is enabled to expand to the header. The default behaviour is for widget labels to be directly above the widget.
