### ISSUE TITLE
Stop button for series.

### ISSUE THREAD

**Issue by darkmantom** [jurialmunkey/skin.arctic.horizon.2#60]
Can you add a stop button for series like in movies?
Tx alot for this beautiful skin!

**Comment by darkmantom** [comment]
Sorry is already on your todo list... Read that too late🤓

**Comment by jurialmunkey** [comment]
Haha no worries! Closing this one just to avoid duplicates!.

**Comment by Goldenfreddy0703** [comment]
Hey, I know I was late to respond but if your reading this, could you also add a stop button for tv shows?
