### ISSUE TITLE
[BUG] Incorrect ratings on certain movies

### ISSUE THREAD

**Issue by cboRD181** [jurialmunkey/skin.arctic.horizon.2#600]
### Skin section

Library Views/Home Widgets/Throughout

### Current Behavior

Getting incorrect ratings even while the rest of the metadata appears correctly.  This has occurred in the past but was resolved by refreshing info a few times.  For the movie in the screenshot, refreshing info does not fix the issue.  

<img width="1440" alt="Screen Shot 2022-11-05 at 8 39 28 PM" src="https://user-images.githubusercontent.com/111588077/200148865-e5e31a04-81e1-49ee-a47e-93d5b5331e6e.png">

I've only had it occur with foreign movies so far.  

### Expected Behavior

Correct ratings.

For this movie, per omdbapi:  ,"Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"96%"}],"Metascore":"N/A","imdbRating":"7.7","imdbVotes":"30,817","imdbID":"tt0119250"

### Steps To Reproduce

1. Add dummy file "fireworks.1997.mkv" to library

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Not a skin issue. TMDbHelper looks up ratings.

There's many reasons you might get wrong information. The most likely is that your scraper or the addon you are using is not adding a proper IMDb ID.

Without an IMDb ID, TMDbHelper has to *guess* which item it is by doing a search for the Title. In that case, it will take the first result returned by TMDb with a matching year.

IF you search "Fireworks" via TMDbHelper you will see that there is another movie with the year 1997 that comes up in the search results first. You are getting the ratings for that movie.

I cannot fix this issue. Without an IMDb ID it is impossible to get a perfect match all the time.


You are getting this movie which is the first search result with a matching year.

![200154708-521cad8f-bdf5-40e3-9600-3f8b688e0bfb](https://user-images.githubusercontent.com/4618719/200154732-71218246-72ba-4def-9693-ff00e3321855.jpg)

**Comment by jurialmunkey** [comment]
As you can see, if you use a scraper or addon that properly adds an IMDb ID number for the movie, then you will get the correct results. TMDbHelper can only do so much with incomplete data.

![screenshot00061](https://user-images.githubusercontent.com/4618719/200154816-b7286930-f0b9-484f-9404-83d769cac85c.jpg)

**Comment by cboRD181** [comment]
Got it, thanks. I was using Kodi's default scraper.  I'll try again with the universal movie scraper addon
