### ISSUE TITLE
Option to configure what osd buttons are shown

### ISSUE THREAD

**Issue by Shawn9347** [jurialmunkey/skin.arctic.horizon.2#604]
### Skin section

Fullscreen Video OSD

### Feature description

Options that allow you to choose what osd buttons are shown in the player. 

### Why is this feature needed? Please justify and explain.

I personally never use the playback speed control or the buttons to skip 30 seconds forwards or backwards. I like my osd to be as clean as possible. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry, I don't plan to offer this level of fine grain control. It makes features in the OSD too difficult to manage.
