### ISSUE TITLE
[BUG] Long to short text for Wikipedia button

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#606]
### Skin section

Video Info Dialog

### Current Behavior

Hi @jurialmunkey,

This is not exactly a bug but a request. In the latest update the texts for the left side buttons in the video info dialog look really nice and helpful. Only the text for the "Wikipedia" button looks a bit long and is getting cropped. Could you change it to only "Wiki" so that it looks similar to the texts for the other buttons? 

### Expected Behavior

Change the "Wikipedia" button text in video info dialog to "Wiki".

### Steps To Reproduce

Go to the video info dialog and click left to view the buttons, including the "Wikipedia" one.

### Screenshots and Additional Info

![IMG20221106192052](https://user-images.githubusercontent.com/65297828/200175548-68ddb76f-2b3b-41b4-9941-d28f77b60b19.jpg)

![IMG20221106192045](https://user-images.githubusercontent.com/65297828/200175557-d3ebdad8-bb9d-4741-99d1-cd6684d75466.jpg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yeah I noticed this on my TV last night - will definitely be changing to "Wiki" 

It's weird because in 4k on my laptop it doesn't get cropped but on my TV in 1080p it does. I think it must be exactly one pixel too long!

**Comment by ShibajiCh** [comment]
Thank you @jurialmunkey !
