### ISSUE TITLE
[BUG] List of last played channels requires accessing it twice

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon.2#608]
### Skin section

PVR and Live TV

### Current Behavior

Whenever I access the list of last played channels (down arrow when on OSD menu), I need to access it twice for it to load. The first time I access it, I get an empty list.

### Expected Behavior

The list to load in first trh.

### Steps To Reproduce

1. Play a live channel.
2. Access OSD menu 
3. Click down arrow.
4. An empty list is shown.
5. Try again, this time the list shows up.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Are you sure you don't just need to wait a bit before pressing down? There's always going to be a bit of delay the first time you open the osd where you need to wait for it to load. If the list is empty then the bookmarks window is opened instead - which I'm guessing is what you're seeing in terms of an empty list. Does it have a "plus" button focused?

**Comment by jurialmunkey** [comment]
It's just a matter of waiting for the container to load first. I've adjusted the hint text to make it clearer when the channels are available. That's the best I can do. I can't make it load faster.

**Comment by juanma-cvega** [comment]
Hi, sorry for the late reply. Yes, I've been testing as well and it seems time related. How long I guess it also depends on whether the system is doing something else at the same time as sometimes I don't see this problem. I'm closing the issue as it seems there is nothing more to do here. Thanks.
