### ISSUE TITLE
[Feature] Dolby Vision flag

### ISSUE THREAD

**Issue by Eddage** [jurialmunkey/skin.arctic.horizon.2#610]
### Skin section

Library Views

### Feature description

A flag similar to the HDR flag, but for Dolby Vision. Could be based on filename if it isn't something Kodi can identify.

For example, my movies have DV in the filename if it is Dolby Vision. 

### Why is this feature needed? Please justify and explain.

Expands on the existing media info flags to add more clarity.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This would have to be based on filename. As far as I'm aware, Kodi doesn't have any specific infolabel for these additional layer formats like HDR10 and Dolby Vision and Atmos.

It would need to be based off more than just `DV` in the filename to avoid false positives with `DVD`

**Comment by piejanssens** [comment]
https://regex101.com/r/4YN4a2/1

**Comment by jurialmunkey** [comment]
> https://regex101.com/r/4YN4a2/1

Skins cant do regex.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

I wrote the below code to play DV files using an external player in Kodi. It covers all the DV parameters in a file name. You can use this for this request if that's possible. Just trying to help.

<playercorefactory>
<players>
<player name="Just Player" type="ExternalPlayer" audio="false" video="true">
<filename>com.brouken.player</filename>
<hidexbmc>true</hidexbmc> <playcountminimumtime>120</playcountminimumtime>
</player>
</players>
<rules action="prepend">
<rule internetstream="true">
<rule filename=".*[.]DV[.].*|.*\sDV\s.*|.*[.]Dv[.].*|.*\sDv\s.*|.*[.]dv[.].*|.*\sdv\s.*|.*D[/]VISION.*|.*\sDOVI\s.*|.*[.]DOVI[.].*|.*\sDoVi\s.*|.*[.]DoVi[.].*|.*\sDovi\s.*|.*[.]Dovi[.].*|.*\sdovi\s.*|.*[.]dovi[.].*|.*\sDOVi\s.*|.*[.]DOVi[.].*" player="Just Player"/>
</rule>
<rule video="true" player="dvdplayer"/>
</rules>
</playercorefactory>

**Comment by jurialmunkey** [comment]
@ShibajiCh - yeah that's regex so not possible in the skin.

I don't think workarounds based on filename are worthwhile considering there is a proper infolabel tag available in nexus. I'm going to be switching over to nexus very soon now that the beta is out.

**Comment by ShibajiCh** [comment]
> @ShibajiCh - yeah that's regex so not possible in the skin.
> 
> I don't think workarounds based on filename are worthwhile considering there is a proper infolabel tag available in nexus. I'm going to be switching over to nexus very soon now that the beta is out.

Fine @jurialmunkey. I'll also switch to Nexus as soon as Arctic Horizon 2 is compatible with it. 🙂👍🏻

Thanks and Regards,
ShibajiCh.

**Comment by Shawn9347** [comment]
Nexus now supports exactly this. But arctic horizon 2 doesn't yet.

**Comment by Weerasak1239** [comment]
"[\.\s]DV[\.\s]"gm

**Comment by Weerasak1239** [comment]
> ### Skin section
> 
> Library Views
> 
> ### Feature description
> 
> A flag similar to the HDR flag, but for Dolby Vision. Could be based on filename if it isn't something Kodi can identify.
> 
> For example, my movies have DV in the filename if it is Dolby Vision. 
> 
> ### Why is this feature needed? Please justify and explain.
> 
> Expands on the existing media info flags to add more clarity.
> 
> ### Screenshots and Additional Info
> 
> _No response_
> 
> ### Checklist
> 
> - [X] I have made a separate issue for each feature I am requesting.
> - [X] I have searched the issues and this feature has not been requested.
> - [X] I am using the most recent skin version.
