### ISSUE TITLE
[BUG] Lyrics overlaid over Music Info

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.horizon.2#611]
### Skin section

Music Info Dialog

### Current Behavior

Many thanks for fixing #592. I've tested and found one issue. If the Lyrics addon is configured to automatically display lyrics, selecting the play button causes lyrics to be overlaid on top of the Music Info.
![screenshot00001](https://user-images.githubusercontent.com/67786207/200266506-3ef39dff-fabc-4e30-851c-759bb7441b09.png)

### Expected Behavior

The Music Info should not still be displayed

### Steps To Reproduce

1 Select any album
2 Press I (info)
3 Press Play

NB ensure lyrics addon is configured to automatically display lyrics

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah, that's really annoying. That must be why in Estuary it closes the info dialog first before playing. Should be easy to fix.

Side note - Whenever I enable the automatic setting in the lyrics addon it has a huge impact on my system performance. Does it work okay for you? Maybe it's just a Windows thing but it is practically unusable for me on automatic.

**Comment by berkhornet** [comment]
My setup is on Windows, and the automatic setting doesn't seem to impact performance. I'm on Windows 10, running on an 8 year old i5 processor with 8gb memory
