### ISSUE TITLE
[BUG] Missing ui indications

### ISSUE THREAD

**Issue by Zurg-97** [jurialmunkey/skin.arctic.horizon.2#613]
### Skin section

Fullscreen Video OSD

### Current Behavior

Missing text in episodes's OSD "press down for bookmarks and chapters"
Missing text in all video files's OSD "Press down for movies and tv shows starring this actor"

### Expected Behavior

Showing text in episodes's OSD "press down for bookmarks and chapters"
Showing text in all video files's OSD "Press down for movies and tv shows starring this actor"

### Steps To Reproduce

1 Play an Episodes that has chapters
2 Open OSD and scroll down for playlist
3 In the playlist view you can scroll down for chapters but is missing the text that appears correcltly in movies

### Screenshots and Additional Info

![Screenshot (208)](https://user-images.githubusercontent.com/114401193/200312685-40ab2e3e-ac4f-4990-9936-4d47fd3a23ff.png)
![Screenshot (210)](https://user-images.githubusercontent.com/114401193/200312703-d3c0305b-4c08-41dd-9111-6126c7197ed9.png)
![Screenshot (211)](https://user-images.githubusercontent.com/114401193/200312719-c274d113-a221-422d-b74e-b623afddbde6.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
Same here noticed it when  @Zurg-97 pointed this out
