### ISSUE TITLE
Background fanart opacity

### ISSUE THREAD

**Issue by r95sguy** [jurialmunkey/skin.arctic.horizon.2#614]
### Skin section

Library Views

### Feature description

Add the ability to adjust background fanart (Library and PVR windows) opacity levels under settings.

### Why is this feature needed? Please justify and explain.

Different people would have different preferences, maybe some would like more or less opacity for the background fanart.

Thanks for the great work!

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry not going to happen. Transparency is determined in the texture to reduce the number of layers needed,so it is not possible to adjust.
