### ISSUE TITLE
[BUG] Expanded Information on Feature widgets not showing 

### ISSUE THREAD

**Issue by ewanw58385** [jurialmunkey/skin.arctic.horizon.2#617]
### Skin section

Home Widgets

### Current Behavior

When you enable expanded information (plot or full) on a feature widget (poster or landscape), the information on does not appear.  

### Expected Behavior

The information should be present when expanded information is enabled. 

### Steps To Reproduce

1. Create a feature widget (poster or landscape)
2. Turn on expanded information (plot or full)
3. Observe the widget on the page. Information is not present. 

### Screenshots and Additional Info

![Screenshot_20221108_050703](https://user-images.githubusercontent.com/72386462/200630698-1e278b2b-fa61-4e66-bc52-aa0172b55798.png)

![Screenshot_20221108_051113](https://user-images.githubusercontent.com/72386462/200630741-0b33b5b1-8da1-422b-928e-218a4e586547.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Intentional. You can only expand info on standard size widgets.

**Comment by ewanw58385** [comment]
Thank you!
