### ISSUE TITLE
[BUG] Watch progress icon not appearing

### ISSUE THREAD

**Issue by Logs22** [jurialmunkey/skin.arctic.horizon.2#62]
Here's an image on what I'm talking about, don't know the exact name of that item, but it's like when your 20 mins into a 45 minute episode and it shows that little logo.![](https://i.imgur.com/L10pNH5.jpg)

For reference the watched markers are appearing![](https://i.imgur.com/UcGXcj9.jpg) 

Thanks Jurial!

**Comment by derrgoo** [comment]
Scroll down we already have one open on this "% progress left blank" 👍

**Comment by Logs22** [comment]
@derrgoo I looked and completely missed that, my bad

**Comment by jurialmunkey** [comment]
Duplicate of https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/22

(just linking the issues)
