### ISSUE TITLE
[Feature] Context menu on full screen widgets/info screen

### ISSUE THREAD

**Issue by arcsur** [jurialmunkey/skin.arctic.horizon.2#620]
### Skin section

Home Widgets

### Feature description

Any chance of getting the ability to open a context menu on either full screen widgets or the info screen (or both :grin:)?

### Why is this feature needed? Please justify and explain.

Some addons provide options for list items via context menus and I can't find a way to access this from full screen widgets or info screen.

### Screenshots and Additional Info

For full screen widgets, just allowing a context menu to be opened would be good enough IMHO.  Personally I either use a kodi remote (yatse) or a keyboard to get context menu up.

If you decide to do for the info screen, adding options to the existing manage menu would also work I think.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by arcsur** [comment]
@jurialmunkey I am not sure I understand this response.  Context menu works on other widget types, just not the full screen menu.  As for the info screen, allowing it to work there would be menu items in the skin, would it not?

**Comment by jurialmunkey** [comment]
> @jurialmunkey I am not sure I understand this response. Context menu works on other widget types, just not the full screen widget. As for the info screen, allowing it to work there would be menu items in the skin, would it not?

Oh, you mean the fullscreen fanart widget with the "Play" / "More Information" buttons. I thought you were talking about the other types of fullscreen widget which are the same as the expanded widget.

I've thought about

**Comment by arcsur** [comment]
Yes I meant the fullscreen fanart widget.  Sorry if I used confusing terminology.

For the info screen, would it be possible to add the context menu items to the "Options" menu? The one you get by clicking the gear icon from the side bar in info.

**Comment by jurialmunkey** [comment]
> Yes I meant the fullscreen fanart widget. Sorry, I may have called it by the wrong name.

No, no - I simply misunderstood what you were asking.

Kodi determines what options the context menu displays and widget context menus will often be missing some options otherwise available from inside the library/plugin. I thought you were asking for a way to access the missing items (which is not possible).

> What about intercepting the onAction number related to the context menu? Is that feasible?

Like I said, there is no `<oncontext>` type of event available in the skinning engine. 

The skinning engine is defined using XML similar to how HTML might define a webpage layout. How the skin functions is limited to the controls and events available in the skinning engine. It cannot modify the engine itself or intercept button presses.

The button event triggers available are `<onclick>` `<onback>` `<oninfo>` and directional keys. Those are the only remote events that a skin can trigger an action for.

The only real solution is an option which replaces either "Play/Browse" or "More information" buttons with a "Context" one. I'm not sure if that'd be desireable to lose one of those?

**Comment by drinfernoo** [comment]
For what it's worth (maybe nothing, but this seemed as relevant a context as any), context menu items seem to be accessible through ListItem properties (in Matrix), as of https://github.com/xbmc/xbmc/pull/18106.

As an example, leveraging Devhelper Web:
```json
{"jsonrpc":"2.0","id":38,"method":"Files.GetDirectory","params":{"directory":"plugin://plugin.video.themoviedb.helper/?info=popular&tmdb_type=movie","media":"video","properties":["customproperties"]}}

{
    "id": 38,
    "jsonrpc": "2.0",
    "result": {
        "files": [
           {
                "customproperties": {
                    "available_releases": "Premiere / Theatrical",
                    "budget": "$250,000",
                    "cast": "Lauren LaVera / David Howard Thornton / Elliott Fullam / Sa…",
                    "contextmenuaction(0)": "RunPlugin(plugin://plugin.video.themoviedb.helper/?info=pla…",
                    "contextmenuaction(1)": "RunScript(plugin.video.themoviedb.helper,related_lists,tmdb…",
                    "contextmenuaction(2)": "RunScript(plugin.video.themoviedb.helper,sync_trakt,tmdb_ty…",
                    "contextmenuaction(3)": "RunScript(plugin.video.themoviedb.helper,manage_artwork,tmd…",
                    "contextmenuaction(4)": "RunScript(plugin.video.themoviedb.helper,refresh_details,tm…",
                    "contextmenuaction(5)": "RunScript(plugin.video.themoviedb.helper,add_to_library,tmd…",
                    "contextmenulabel(0)": "$ADDON[plugin.video.themoviedb.helper 32322]",
                    "contextmenulabel(1)": "$ADDON[plugin.video.themoviedb.helper 32235]",
                    "contextmenulabel(2)": "$ADDON[plugin.video.themoviedb.helper 32295]",
                    "contextmenulabel(3)": "$ADDON[plugin.video.themoviedb.helper 32222]",
                    "contextmenulabel(4)": "$ADDON[plugin.video.themoviedb.helper 32233]",
                    "contextmenulabel(5)": "$LOCALIZE[20444]",
                    "dbtype": "movie",
                    "imdb_id": "tt10403420",
                    "isplayable": "true",
                    "item.info": "play",
                    "item.tmdb_id": "663712",
                    "item.tmdb_type": "movie",
                    "item.type": "movie",
                    "param.info": "popular",
                    "param.tmdb_type": "movie",
                    "popularity": "3803.184",
                    "premiere_release": "2022-09-22",
                    "provider.link": "https://www.themoviedb.org/movie/663712-terrifier-2/watch?l…",
                    "providers": "Screambox Amazon Channel",
                    "revenue": "$5,325,078",
                    "set.fanart": "https://image.tmdb.org/t/p/original/xGl7uzt0JX8u2WCIKK4e9Sk…",
                    "set.name": "Terrifier Collection",
                    "set.poster": "https://image.tmdb.org/t/p/w500/fTDmbVPqUfeIMKM1ThLHSquwMsm…",
                    "set.tmdb_id": "727761",
                    "studio": "Bloody Disgusting",
                    "theatrical_release": "2022-10-06",
                    "tmdb_id": "663712",
                    "tmdb_rating": "7.0",
                    "tmdb_type": "movie",
                    "tmdb_votes": "563",
                    "total_pages": "11931",
                    "total_results": "238617",
                    "widget": "Popular Movies"
                },
                "file": "plugin://plugin.video.themoviedb.helper/?info=play&tmdb_typ…",
                "filetype": "file",
                "label": "Terrifier 2",
                "type": "movie"
            },
            ...,
           {
                "customproperties": {
                    "item.info": "popular",
                    "item.page": "2",
                    "item.tmdb_type": "movie",
                    "item.type": "movie",
                    "param.info": "popular",
                    "param.tmdb_type": "movie",
                    "widget": "Popular Movies"
                },
                "file": "plugin://plugin.video.themoviedb.helper/?info=popular&tmdb_…",
                "filetype": "directory",
                "label": "Next page",
                "type": "unknown"
            }
        ],
        "limits": {
            "end": 21,
            "start": 0,
            "total": 21
        }
    }
}
```

And the `contextmenuaction(x)` and `contextmenulabel(x)` properties are filled as described:
![image](https://user-images.githubusercontent.com/2319508/201568763-08eb70df-0ae5-4939-8ce6-a03de660fb9d.png)

Does this help?

**Comment by jurialmunkey** [comment]
@drinfernoo - Those will *only* be the custom entries for the plugin set via [addContextMenuItems](https://alwinesch.github.io/group__python__xbmcgui__listitem.html#ga14712acc2994196012036f43eb2135c4) method.

You won't be able to get any of the entries that come directly from Kodi or a Context Menu addon -- e.g. try it on a library item and you'll get nothing despite library items. Same goes for a plugin which defines the context menu entries in the addon.xml instead.

**Comment by jurialmunkey** [comment]
Added an option in most recent (0.7.5) - 
`Skin Settings > Navigation > Swap info button for options on fullscreen fanart widgets`

That will replace the "More information" button with an "Options" button that will open the context menu. When the "Options" button is enabled, you can also press info on the remote to open info directly instead.

And vice versa when the setting is disabled - i.e. press info on remote to open context when "More information" button is enabled.

**Comment by arcsur** [comment]
@jurialmunkey First of all thanks for looking at this and making the changes.

I just tested this and it works but it is a bit strange only using the info button, this kind of sucks from a remote where you have a dedicated context button.  Are you not able to intercept action id `117`?
