### ISSUE TITLE
[BUG] Widget metadata on submenu load very slowly. 

### ISSUE THREAD

**Issue by ewanw58385** [jurialmunkey/skin.arctic.horizon.2#621]
### Skin section

Library Views

### Current Behavior

When you create a submenu and add a list of widgets, the artwork does not load quickly, although the artwork on the home widgets loads fast. Sometimes only a few widget's metadata loads. 

### Expected Behavior

The submenu widget artwork/ metadata should load as soon as you open it. I'm assuming the priority is set to load all home widgets first, although if one wanted to use submenus as a main navigational tool, you have to wait 30 seconds/ reload the submenu a few times before the artwork appears. All widgets within the submenu should load together. 

### Steps To Reproduce

1. Create a submenu and add a list of widgets. Ensure there are home widgets as well, to compare with. 
2. Reload the skin and open the submenu. Home widgets may have already begun loading.  
3. Observe the lack artwork/ metadata in submenu widgets.
4. Wait 30 seconds to see if widgets appear. 
5. If not, reload skin and open submenu again. 
6. Instead of waiting, try backing out and reopening the submenu a few times. 
7. Artwork should eventually begin appearing in either case, but it is very slow. Sometimes only a few widgets load. 

![Screenshot_20221109_095845](https://user-images.githubusercontent.com/72386462/200950767-b310bf97-3cbf-435d-90ad-9c46d4f505d9.png)

![Screenshot_20221109_095102](https://user-images.githubusercontent.com/72386462/200950787-d2c7633a-5cf5-41ee-8b23-83ec9f72087b.png)

![Screenshot_20221109_100051](https://user-images.githubusercontent.com/72386462/200951372-e198328e-8dfe-4d05-aafe-86c0accf96fb.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This has nothing to do with the skin. The skin has no control over when or how kodi loads a directory, it has no control over when or how kodi downloads an image and no control over when or how kodi caches the image and then displays it.

All the skin defines is which content paths go into which container and how the elements in that container should be display on screen (eg display the poster at this coordinate and add this shadow texture etc) - it does not have anything to do with loading the content itself or how long that takes.

**Comment by ewanw58385** [comment]
Apologies. Thanks for letting me know.
