### ISSUE TITLE
[BUG] Rendering issues with the LoveFilm widget.

### ISSUE THREAD

**Issue by jbelew** [jurialmunkey/skin.arctic.horizon.2#623]
### Skin section

Home Widgets

### Current Behavior

When a "LoveFilm" widget isn't selected, it shows the ClearLogo and a rating. Once selected, the layout changes to the traditional "plot" display. Additionally, the "description" text shows in a faded state until the contents of the widget are redrawn. 

### Expected Behavior

The contents of the "LoveFilm" should be consistent. "Plot" text should render at the default opacity. 

### Steps To Reproduce

- Add a "LoveFilm" widget as the third or fourth item under "Movies".
- Scroll to the widget above the "LoveFilm" items and it renders as Screenshot 1.
- Navigate so that the "LoveFilm" widget is selected and see that it renders as Screenshot 2 with the plot text "dimmed" until another item is selected.

### Screenshots and Additional Info

Unselected - Displaying the ClearLogo (Screenshot 1)
![screenshot00014](https://user-images.githubusercontent.com/4211774/200961004-37fc838d-8c3d-45f7-b390-1f6edc6bee8e.png)

Selected - ClearLogo disappears and the "Plot" text is faded (Screenshot 2)
![screenshot00015](https://user-images.githubusercontent.com/4211774/200961028-45a50a8a-e93a-4f22-a087-c37c1a288253.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I cannot reproduce. 

This sounds like an issue with kodi rendering not the skin. Most likely a dirty regions or smartredraw setting is preventing rendering properly

**Comment by jbelew** [comment]
Good catch. I forgot I had this set --

```
  <gui>    
    <algorithmdirtyregions>1</algorithmdirtyregions>
    <!-- <smartredraw>true</smartredraw> -->
  </gui>
```
