### ISSUE TITLE
[Feature] Media Info Combined View Enhancements

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#628]
### Skin section

Library Views

### Feature description

Hi @jurialmunkey,

First of all thanks a lot for the new Media Info Combined View!
Few requests:
1) Is it possible to reduce the Seasons width so that the images can be made a bit larger?
2) Also, could you please add Episode Release date (instead of only year), Episode Runtime, Episode End time, Season/Episode Ratings, and Returning/Cancelled/Ended status on the top text area for the episodes/seasons like Big Landscape combined view?
3) Is it also possible to add the Season summary text somewhere in this view?

Please advise. Thanks again!

### Why is this feature needed? Please justify and explain.

These enhancements will make the Media Info Combined View even better.

### Screenshots and Additional Info

![IMG20221110225746](https://user-images.githubusercontent.com/65297828/201167115-c31b5b61-3bc6-42ae-a5cb-18c7c4611738.jpg)

![IMG20221110230208](https://user-images.githubusercontent.com/65297828/201167149-29ae5c16-ec50-42bc-93bc-a9f73cfce6b0.jpg)

![IMG20221110225404](https://user-images.githubusercontent.com/65297828/201167180-c5024bb0-57db-407a-b5d8-c7b480002c1f.jpg)

![IMG20221110225447](https://user-images.githubusercontent.com/65297828/201167223-9b977852-a531-4b35-a6a9-695dcee78b9b.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
> Is it possible to reduce the Seasons width so that the images can be made a bit larger?

Why would that make the images larger? The limiting factor is height.

>Also, could you please add Episode Release date (instead of only year), Episode Runtime, Episode End time, Season/Episode Ratings, and Returning/Cancelled/Ended status on the top text area for the episodes/seasons like Big Landscape combined view?

I did try this originally but it was confusing because the episode list is disconnected from the infoline. It works for Landscape combined because the rows are stacked on top of each other so that the episode list is aligned with the info.

It doesn't work for this view because the episodes are offset to the right and it forces your eyes to constantly scan the screen which is a massive UX design no-no.

> Is it also possible to add the Season summary text somewhere in this view?

I don't know where this would go. I think this would only cause unnecessary clutter, especially since a lot of tvshows don't have per season summaries.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Fine. Then I'll use the landscape combined view as it has more detailed info. Thank you!

Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

One small request, could you only add the Episode Runtime somewhere in the Media Info Combined View, may be beside the Rated text? That will be really helpful and then I can use this view. The other details are not that important. Only the episode runtime will be really really useful. Kindly consider if possible.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
> Hi @jurialmunkey,
> 
> One small request, could you only add the Episode Runtime in the Media Info Combined View, beside the Episode title, e.g. 1x01. Pilot | 43 mins ? You already have this in the Landscape Infolist view, so I guess it won't be that of a problem. This will be really helpful and then I can start using this new view. The other details are not that important. Only the episode runtime will be really really useful. Kindly consider if possible. I'll be really grateful to you.
> 
> Thanks and Regards, ShibajiCh.

Hi @jurialmunkey,

If this is possible then shall I create a separate ticket for this? Please advise.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Thank you so much for adding this feature in the latest update! The media info combined view is very useful for me now and looks very good too! Thanks again!

Regards,
ShibajiCh.
