### ISSUE TITLE
[BUG] feature poster widget section label

### ISSUE THREAD

**Issue by A3006B** [jurialmunkey/skin.arctic.horizon.2#632]
### Skin section

Home Widgets

### Current Behavior

With section labels turned on and a featured poster as first widget, clicking down onto the widget shows the name of the Home Screen item and then the widget name below. Other widget styles show only the name of their widget.

### Expected Behavior

Feature poster widget should only show its widget name and not the name of the home menu item above it

### Steps To Reproduce

Open feature poster widget. It then shows the name of the home menu item and then the widget name, other widget styles show only their widget name (see screenshots)

### Screenshots and Additional Info

![694F82F6-AB9D-4F25-89A9-E0CB7205FE71](https://user-images.githubusercontent.com/114344593/201361528-a9488a16-6e10-4437-afb5-715c3889ccd9.jpeg)
![D3AB5CB2-C9A5-4EDC-80B2-CB4AF605D661](https://user-images.githubusercontent.com/114344593/201361535-403253ba-2ba4-4a87-a9f9-d697856c92a6.jpeg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
That setting *only* applies to full expanded widgets. It does *not* (and should not) apply to any other widget type (not feature, not standard, not plot expanded). 

That option to move the title to the header for full expanded widgets only exists out of necessity to make room for the plot, otherwise I wouldn't do it there either.
