### ISSUE TITLE
[BUG] Random Crashing After v0.6.8.

### ISSUE THREAD

**Issue by jbelew** [jurialmunkey/skin.arctic.horizon.2#634]
### Skin section

Library Views

### Current Behavior

After extensive browsing through the library after v0.6.8. I've been getting skin crashes; Kodi will freeze for about 60s, then the skin will reload. 

### Expected Behavior

The skin should not crash?!?

### Steps To Reproduce

In my case ...

1. Running Nexus 20.3 (20.0b1-Nexus) on CoreElec (oDroid N2+), the skin crashes after extensive browsing, i.e. Looking around for new features or changes.
2. My installation is running with `<algorithmdirtyregions>1</algorithmdirtyregions>`, which appeared to improve performance with my GPU, but with no other changes. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jbelew** [comment]
I can post debug logs if they're helpful, but I'm currently running at <loglevel>0</loglevel> due to all the deprecation messages. Putting my "coding hat" on, could you be getting an unchecked "null" value from your hidden label width check?

**Comment by jbelew** [comment]
FYI, Nexus B1 just dropped for my distro, so upgrading to that. I'll see if I can reproduce it once that's done.

**Comment by jbelew** [comment]
Had one skin crash today while navigating into the TMDB Movie Hub. Unable to replicate though. 
[01_KODI_CRASH.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9995751/01_KODI_CRASH.log)

**Comment by naudski** [comment]
I too experience a lot of crashing lately. Was working flawlessly on my two nvidia shields, but also since 0.6.8 this issue came around on both shields.

**Comment by jurialmunkey** [comment]
Almost certainly related to title wrapping. Likely cause is divide by zero error in how Kodi calculates NumPages for textboxes when the height isn't tall enough to accomodate a full line of text.

I've been able to reproduce in Estuary reliably with a simply test case, so I've reported the issue here: https://github.com/xbmc/xbmc/issues/22136

In the meantime, if you are experiencing this crash please disable the title wrapping in experience settings (though fairly sure newer versions of the skin fixed it anyway, so please update the skin first).

**Comment by jurialmunkey** [comment]
I've added some extra margins to textbox height in the meantime in case different screen resolutions and os dependent font rendering are producing slightly different line heights

Please try 0.7.3 and see if that helps
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.7.3

**Comment by naudski** [comment]
Thanks! I will try that.

**Comment by jbelew** [comment]
I've found a repeatable pattern with 0.7.6. Attempting to select the video to the right, "Last To Take Hand Off Jet, Keeps It!" crashes the skin (please don't judge, the video just showed up in my feed ;) ). Could it be something in the YouTube API response strings? There's some "old school" ASCII art in the description field. 

![screenshot00017](https://user-images.githubusercontent.com/4211774/201731086-1f3c87bb-4f83-4119-b441-2975c945aaae.png)

[01_KODI_CRASH.zip](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/10005740/01_KODI_CRASH.zip)

**Comment by naudski** [comment]
I installed 0.7.6 and it is very stable. No more crashes.
I think the YouTube crash is caused by the youtube addon itself. I've experienced that for a long time already.

**Comment by jbelew** [comment]
> I installed 0.7.6 and it is very stable. No more crashes. I think the YouTube crash is caused by the youtube addon itself. I've experienced that for a long time already.

I've been using the YouTube Addon quite extensively over the past few months (no ads!) with no real stability issues. This is the first repeatable crash that I've been able to track down. It's definitely a problem related to "hydrating" the view. Could be related to other crashing issues with some untrapped exceptions related to the media item's payload.

**Comment by naudski** [comment]
You are right @jbelew. I tested it myself and kodi indeed crashes when scrolling through the video's in the youtube addon.

**Comment by jurialmunkey** [comment]
@jbelew - I can't reproduce on Matrix. Works fine for me. Did you test in Estuary to make sure it isn't skin specific? 

![screenshot00119](https://user-images.githubusercontent.com/4618719/201791594-86fe840c-3c87-4556-bb84-d1a0ba99a1a8.jpg)

**Comment by jbelew** [comment]
@jurialmunkey Works fine in Estuary. After more testing, it's not that specific video (the playlist has been updated). It's always crashing on the third video from the "Popular right now" feed. I played around with widget positioning and styles and it's isolated to the "Landscape" style.

**Comment by ddsarad** [comment]
Just wanted to say this is only a nexus issue, have been running the same build on both nexus and matrix, nexus crashes constantly, matrix is fine

**Comment by jbelew** [comment]
> Just wanted to say this is only a nexus issue, have been running the same build on both nexus and matrix, nexus crashes constantly, matrix is fine

I've been running Nexus since August, currently on the build tagged B1 and it's been very stable for me. This is a new issue with 7.6 and the first repeatable issue that I've found.

**Comment by jbelew** [comment]
And, of course, now it works. Must have been a defect with the API response from Youtube for about half a day.
