### ISSUE TITLE
[BUG] Fullscreen widget Browse button focus lost for TV Shows

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.horizon.2#638]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

If I click on the Fullscreen fanart widget Browse button for TV Shows (not Movies), go inside and then come back to the Fullscreen widget home screen the focus is lost from the Browse button. This happens only for the Browse button in TV Shows Fullscreen widget and not for the Play button in Movies Fullscreen widget. Could you please check and advise?

### Expected Behavior

The Browse button should stay focused on returning to the Fullscreen widget home screen.

### Steps To Reproduce

Go to TV Shows menu, click on Browse button in Fullscreen widget for TV Shows, then return back to the Fullscreen widget home screen. The focus on the Browse button is lost.

### Screenshots and Additional Info

Step 1:
![IMG20221114212438](https://user-images.githubusercontent.com/65297828/201707359-e1447e03-7f5c-48d2-87fb-465ed2ce77a0.jpg)

Step 2:
![IMG20221114212448](https://user-images.githubusercontent.com/65297828/201707399-db508f8f-143d-433b-bdc5-dcd6dc02aebf.jpg)

Step 3:
![IMG20221114212454](https://user-images.githubusercontent.com/65297828/201707426-72dbeb43-bc53-464a-a8e7-cfc230e4dfe9.jpg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce this issue

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

This was an old issue. It's not happening anymore after the last couple of updates. You can close this issue now. Thank you!
