### ISSUE TITLE
[BUG] error when backing up build. culprit... non-ascii characters in filename in a very specific sub-directory.

### ISSUE THREAD

**Issue by TheFather999** [jurialmunkey/skin.arctic.horizon.2#639]
### Skin section

Fonts and Languages

### Current Behavior

When trying to backup/archive my custom build I am presented with the error below and the whole process freezes Kodi. ctrl/alt/del and force terminating Kodi is necessary. However, if I manually delete the couple of image files in question, the build zips up just fine.
Here is where the images are located...
addons\skin.arctic.horizon.2\media\flags\color\mpaa\
España 7.png, España 12.png, etc.

Below is a screen capture of the error. It is obviously the tilde font character that is causing the error. Thank you in advance for any solution. EXH

### Expected Behavior

Build should ideally archive/zip without errors.

### Steps To Reproduce

Go to tools section in addon and select backup.

### Screenshots and Additional Info

![Untitled-1](https://user-images.githubusercontent.com/96840477/201718114-b8af689a-1410-49fd-9af3-07b3e5d3b663.jpg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Not a skin issue.

Report it to the author of whatever addon you're using to backup with.

These are legitimate filename characters. Filenames do not need to be ascii only
