### ISSUE TITLE
[Feature] Addition of the Lovefilm widget from Arctic Horizon 1

### ISSUE THREAD

**Issue by calebp744** [jurialmunkey/skin.arctic.horizon.2#640]
### Skin section

Home Widgets

### Feature description

I like the new lovefilm widget a lot for its own reasons, but I love lovefilm from AH1 and would be glad to see it return as an another widget alongside the new one in AH2.

The widget could be redone to have clearlogos for the shows/movies and have more information like the score, genre, etc.
![Screenshot_1 (9)](https://user-images.githubusercontent.com/118232057/201835093-b757152a-f246-4e6d-9838-f0c5f2b754e9.png)

### Why is this feature needed? Please justify and explain.

- It would provide a nice alternative to the current widget. It blends in nicely with other widgets like big landscape, yet catches your eye and provides a good focal point.
- It's a nice way to showcase fanart/artwork without it being obstructed by the logo or any text. 
- It's different enough to the new one to warrant using both widgets on your home screen.
- It's great in AH1 so I believe it could be even better in AH2.

I understand if this is not the look you're going for in AH2, thank you in advance.

### Screenshots and Additional Info

A few examples of how it could look.
![Screenshot_1 (2)](https://user-images.githubusercontent.com/118232057/201828750-ee5af3f9-f901-47e7-ac46-77485d2bb20f.png)
![Screenshot_1 (3)](https://user-images.githubusercontent.com/118232057/201827648-53aa9a0d-ed75-42b8-a318-4ec17f4ada88.png)
![Screenshot_1 (3) (1)](https://user-images.githubusercontent.com/118232057/201852747-ddbfb20b-7ee6-4a7e-8dcf-a049b96cb6d8.png)
![Screenshot_1 (5)](https://user-images.githubusercontent.com/118232057/201828488-72c0ea18-12af-4fab-bcb6-627011653913.png)

### Checklist

- [ ] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Next version will have "Feature Banner" which is a slightly different approach but will fulfill essentially the same requirements

Focused:

![screenshot00145](https://user-images.githubusercontent.com/4618719/204124661-845fe282-553f-4bf0-ab4e-8b82074eefc1.jpg)

Unfocused:

![screenshot00146](https://user-images.githubusercontent.com/4618719/204124665-18cc860a-c19b-4df2-afe2-a0bdd4ae3665.jpg)
