### ISSUE TITLE
having (custom/)pre defined fullscreen widget (*.xsp) also for music videos

### ISSUE THREAD

**Issue by AdamNo2** [jurialmunkey/skin.arctic.horizon.2#642]
### Skin section

Library Views

### Feature description

i have a modified movie scraper addon that scrapes concerts not under movies but into kodi's music videos section.
i created me a main menu item "musik videos" with library://video/musicvideos/.

further i took .kodi/addons/skin.arctic.horizont.2/extras/playlists/RandomTVShows.xsp
and modified it to .kodi/addons/skin.arctic.horizont.2/extras/playlists/custom/RandomMusicVideos.xsp (smartplaylist type="**musicvideos**")
`<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="musicvideos">
    <name>Random MuscVideos</name>
    <order direction="ascending">random</order>
</smartplaylist>`
and configured it as fullscreen-widget.

look at this beauty
![IMG_2157](https://user-images.githubusercontent.com/113284561/201997423-1b11ee0b-2d7f-4698-85fb-e66668563cbd.jpg)

unfortunately my ../custom/RandomMusicVideos.xsp is gone after every update of the skin (and you are pretty active releasing :)).

my request is keeping custom folder created under .kodi/addons/skin.arctic.horizont.2/extras/playlists/ untouched or having all xsp variants also for musicvideos as for TvShows, Movies, etc...

i favor a custom folder! 

### Why is this feature needed? Please justify and explain.

same functionality/appearance for music videos as tv shows or movies have it.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You shouldn't modify any files in Kodi's addon directory. Skins are addons. Everytime an addon updates, Kodi deletes the entire folder for the addon and then unzips the new version. The skin cannot control change this behaviour.

There's no need to modify the skin folder.

Goto `Videos > Playlists > New Smart Playlist...` and create your playlist rules then save it.
Now it will appear in the widget selector under `Videos > Video Playlist > `
