### ISSUE TITLE
[Feature] Stop playback button

### ISSUE THREAD

**Issue by dplim87** [jurialmunkey/skin.arctic.horizon.2#643]
### Skin section

Other

### Feature description

The OSD in AH2 looks great, but I noticed it does not have a stop button.

### Why is this feature needed? Please justify and explain.

My remote doesn't have a dedicated stop button, so this would simplify playback features

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skin Settings > Playback > Always display stop button.
