### ISSUE TITLE
[Feature] Display default fan art on full screen widgets when the item specific asset is missing. 

### ISSUE THREAD

**Issue by jbelew** [jurialmunkey/skin.arctic.horizon.2#647]
### Skin section

Home Widgets

### Feature description

When a specific item is displayed in a full-screen view that lacks fanart, the screen is black. IIRC, Kodi has a default or fallback fan art for movies and music for cases when the item-specific asset is missing. This could be further improved if genre-based fallback fan art can be sourced or added as a dependency.  

### Why is this feature needed? Please justify and explain.

Provides a more consistent, visual experience when using full-screen widgets. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jbelew** [comment]
This is a very rare occurrence in my library for movies (Neverwhere, I'm looking at you!), but much more common with music. I'm actually surprised at how strong the coverage is for classical music, but I still have about 15% of my library with missing assets.

**Comment by jurialmunkey** [comment]
Actually there's this resource for music which seems fairly decent
https://github.com/xbmc/repo-resources/tree/jarvis/resource.images.musicgenrefanart.coloured/resources

Some of the images are a bit strange though. The one for "Pop" has a person sitting listening to REM and Nirvana records...
https://github.com/xbmc/repo-resources/blob/jarvis/resource.images.musicgenrefanart.coloured/resources/Pop.jpg

And the "Gothic Metal" one is hilarious
https://github.com/xbmc/repo-resources/blob/jarvis/resource.images.musicgenrefanart.coloured/resources/Gothic%20Metal.jpg

But it seems like a decent option. I guess the question is what to use for the fallback when genre is not available.

**Comment by jurialmunkey** [comment]
Actually, no, that resource pack is too weird. I gave it a quick trial but the images don't really match the vibe of the artist at all. I guess the one for "Alternative Rock" is not too bad on The Cure - but the ones for Indie and Pop on Cocteau Twins and Michael Jackson really do not match the vibe of those artists at all...

![screenshot00128](https://user-images.githubusercontent.com/4618719/202374595-5c4ed324-10c2-4971-9af4-a206027d7f39.jpg)

![screenshot00126](https://user-images.githubusercontent.com/4618719/202374652-c4f56bb2-1d95-4f5e-97c6-e7febde6d6d5.jpg)

![screenshot00127](https://user-images.githubusercontent.com/4618719/202374617-79cea838-fdbe-4dba-a55e-2684180db049.jpg)

I think probably have to go with something much more generic

**Comment by jbelew** [comment]
If only I still had some Midjourney credits left ;).

**Comment by AdamNo2** [comment]
i am seeing the same for music videos.
there is no fan art and a blank background is displayed. 
![IMG_2164](https://user-images.githubusercontent.com/113284561/202455036-873b9da9-de51-46c3-98f7-def133459e8c.jpg)

if quality is sufficient, i propose to take the thumbnail as substitution for video types.
![IMG_2162](https://user-images.githubusercontent.com/113284561/202455456-35efcfa7-fada-49c6-9481-cee4a7ee7037.jpg)

no clue what to take for other media types like music :(

**Comment by jurialmunkey** [comment]
@AdamNo2 - unfortunately no way for the skin to check what the quality or resolution of a file is - usually autogenerated thumbs that kodi makes from videos are fairly low res so most likely wouldn't be a great option. I guess still might be better than a black screen though
