### ISSUE TITLE
[Feature] Disc number is redundant in album views

### ISSUE THREAD

**Issue by jbelew** [jurialmunkey/skin.arctic.horizon.2#649]
### Skin section

Library Views

### Feature description

Track listings in album views display disc numbers, taking up space that could be used for other items or longer title space.

### Why is this feature needed? Please justify and explain.

Albums with multiple discs only allow you to select one at a time. There's no view currently that lists all tracks and all discs in a single view. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I've got plenty of double disc albums that display as one entry. It's a matter of correct file metadata tags and scraper settings.

Two examples:

![screenshot00122](https://user-images.githubusercontent.com/4618719/202333123-8f282bc9-e28f-42d8-b65b-cd3bbc243558.jpg)

![screenshot00121](https://user-images.githubusercontent.com/4618719/202333130-b3367076-14f2-408e-9d78-2321231d20c3.jpg)

More importantly, however, is that the number field adapts based upon context and needs a wider column for other info. For example, in albums view it displays year:

![screenshot00123](https://user-images.githubusercontent.com/4618719/202333645-8d9218af-fa26-4329-be49-2092ac182f04.jpg)

**Comment by jbelew** [comment]
I found out what was happening, I had "Split albums into individual discs" turned on which always showed a "bumper" screen like this ... 

![screenshot00022](https://user-images.githubusercontent.com/4211774/202345245-dce35094-56df-46a5-ad41-9b33f3ea9eea.png)

I'll close this issue.
