### ISSUE TITLE
[Bug]Home Screen settings  Menu

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon.2#65]
Randomly the settings menu does not appear. Restarting Kodi works temporarily.

Loving the skin 😀

<img width="1446" alt="Screenshot 2022-06-06 at 03 14 16" src="https://user-images.githubusercontent.com/2873112/172083856-eb4a2bbe-b95c-4d41-b801-abddad775b23.png">

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8841423/kodi.log)
[kodi.old.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8841424/kodi.old.log)

Thanks

**Comment by jurialmunkey** [comment]
Can you get me your skinshortcuts-includes.xml file from addons/skin.arctic.horizon.2/1080i
?

Not sure why it's only shield users with this issue.

**Comment by krzysztofwinnik** [comment]
Not just shield users. I am on CoreElec and this happened to me several times yesterday. 
Sometimes it appears correctly when pressing RIGHT while last menu item is focused. Other times pressing RIGHT changes focus to first menu item and the only way to open settings menu is by pressing a button mapped to powermenu.
That bug seems to happen only on home screen.

**Comment by jurialmunkey** [comment]
@krzysztofwinnik - Do you have a mouse (or some form of pointer enabled e.g. one of the remote "air mouse" type of things)? I just had a bit of a lightbulb moment that it might be a mouse pointer stealing focus from the menu.

**Comment by krzysztofwinnik** [comment]
Nope. It is not that.

**Comment by krzysztofwinnik** [comment]
To be precise - I have mouse support enabled in Kodi settings and my remote has airmouse feature, but I am not a big fan of it and rarely use that feature.

**Comment by jurialmunkey** [comment]
If you move the pointer at all outside the menu, it will steal focus from the menu and the menu will close.

So if you have mouse enabled and the remote has an air mouse feature than even the slightest bump will cause it to de-focus.

**Comment by krzysztofwinnik** [comment]
@jurialmunkey sounds reasonable. I will turn it off later today and check if that is the problem.

**Comment by jurialmunkey** [comment]
@krzysztofwinnik @Blurayx - Can you test 0.1.7 and see if that solves the issue? 
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.7

**Comment by krzysztofwinnik** [comment]
@jurialmunkey - sure, I'll give it a try and report later.

**Comment by krzysztofwinnik** [comment]
happy to report the issue seems to be solved :-)
ty @jurialmunkey

**Comment by jurialmunkey** [comment]
> happy to report the issue seems to be solved :-) ty @jurialmunkey

Excellent! I'll leave this open until @Blurayx has a chance to test and confirm just to make sure he's having the same issue.

**Comment by Blurayx** [comment]
> > happy to report the issue seems to be solved :-) ty @jurialmunkey
> 
> Excellent! I'll leave this open until @Blurayx has a chance to test and confirm just to make sure he's having the same issue.

Working 😀
Thank You
