### ISSUE TITLE
[Feature] Add a format icon to song list view. 

### ISSUE THREAD

**Issue by jbelew** [jurialmunkey/skin.arctic.horizon.2#651]
### Skin section

Library Views

### Feature description

It'd be nice to get a format icon in the song list view; FLAC, MP3, AC3, etc. There used to be an icon displayed in the prior versions, but it was a little flashy and didn't seem to fit the style of the skin IMHO. 

### Why is this feature needed? Please justify and explain.

No way to know what format the songs are compressed in, especially if you prefer listening to FLAC content. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Ah I knew there was something I forgot to add back in!
