### ISSUE TITLE
[BUG] Sound and subtitle option on shield not working

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.horizon.2#652]
### Skin section

Fullscreen Video OSD

### Current Behavior

While a video is playing, when you highlight but not click the sound and subtitles buttons, you'll get a popup with options. On my mac, I can push up and select from the options and it works as intended, but on my shield, it does not switch. I have to click on the sound/subtitle buttons to pull up the full settings to change options.  

### Expected Behavior

Should behave on the shield the same way it does on my mac. 

### Steps To Reproduce

On the shield
1. play video with sound and subtitle options
2. on the OSD scroll to the sound/subtitle and a popup shows with options
3. select any of the options
4. does not switch to new selected options

### Screenshots and Additional Info

<img width="1235" alt="Screen Shot 2022-11-17 at 8 11 13 AM" src="https://user-images.githubusercontent.com/43726430/202472067-73730445-9161-4e5f-b142-dff301e1707c.png">
<img width="1237" alt="Screen Shot 2022-11-17 at 8 11 21 AM" src="https://user-images.githubusercontent.com/43726430/202472072-9ed77b8c-2ac2-433d-bd59-8f73ce15eeb8.png">
 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Debug log please. This is handled by the skinvariables script.

**Comment by Liquidrag** [comment]
> Debug log please. This is handled by the skinvariables script.

Sorry, must've been a fluke. It's running as it should now.

**Comment by jurialmunkey** [comment]
No worries.

When you click it runs a script to change the audio/sub. If there's a lot of things reloading (eg widgets) then sometimes kodi won't register the RunScript command properly (or kodi is massively delayed in responding ). Possibly was just something like that.

**Comment by Liquidrag** [comment]
Yea I think it was that.
