### ISSUE TITLE
[Feature] Make dimming of video when OSD is on optional

### ISSUE THREAD

**Issue by gn77b** [jurialmunkey/skin.arctic.horizon.2#653]
### Skin section

Fullscreen Video OSD

### Feature description

Currently when the OSD is on the picture is dimmed. It would be nice to add an option to disable dimming.

### Why is this feature needed? Please justify and explain.

Sometimes one pauses to take a better look at a scene and the dimming doesn't help.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jbelew** [comment]
Enable "Autohide seekbar after pausing" under "Playback" in the skin settings.

**Comment by jurialmunkey** [comment]
Solution as above
