### ISSUE TITLE
[Feature] Option to use imdb trailers instead of youtube

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.horizon.2#659]
### Skin section

Other

### Feature description

Would be nice if we could set the default trailer source to imdb trailers addon. I think its a much better source than youtube. 

### Why is this feature needed? Please justify and explain.

Better trailers than youtube

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This has nothing to do with the skin. The skin uses whatever is set in the trailer field for the item.
