### ISSUE TITLE
[Bug] [Fonts] CJK title font strokes are too thick

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/skin.arctic.horizon.2#66]
The CJK title font strokes are too thick (may be because the bold attribute), the space between strokes are too small, which makes the strokes tied up together for some complex characters (for example, "国", “端”, etc.). It's very hard to read them.

**Comment by jurialmunkey** [comment]
Can you get me a screenshot of the issue?

**Comment by Hawkedon** [comment]
![1](https://user-images.githubusercontent.com/46645337/172103576-0489fd2b-cf85-41fe-823f-58352ebec491.jpg)

The bottom right of both Chinese characters in red boxes are complex, and you can see from the picture, it's basically just a white block, all details are missing.

**Comment by jurialmunkey** [comment]
Have you tried switching to the "Light font" in appearance settings (Up to menu and then "Customise Appearance")? If the issue is only in the title, that should solve the issue.

**Comment by Hawkedon** [comment]
Thanks. It works! I chose the Clearlogo though. Does this mean there is no ClearLogo anymore because I choose "Light Font"? I like the "Heavy Font"/"Clearlogo", may be you can adjust the heavy font a little bit, so make it not that heavy? :)

**Comment by jurialmunkey** [comment]
If you choose Light Font and then Clearlogo, it will use Clearlogo but fallback to Light font.

**Comment by jurialmunkey** [comment]
> Hi @jurialmunkey, I checked the font in the skin and seems the problem is due to the bold style applied to the font RobotoCJKSC-Bold.ttf. This font is already bold by itself, with the bold style applied in the skin, it's a "double" bold, thus the rendering is bad. I removed the bold style applied to the font in Font.xml file, and the result font is still bold, but clearly enough to read.

Awesome - glad to hear that there is a suitable solution. I'll add this fix for the CJK fontset soon.
