### ISSUE TITLE
[Feature] preview every setting

### ISSUE THREAD

**Issue by Rootzpower** [jurialmunkey/skin.arctic.horizon.2#666]
### Skin section

Other

### Feature description

It's possible to preview inside kodi or wiki page, preview every single settings?
Sometimes it's difficulty to understand what do we really change on skin.

### Why is this feature needed? Please justify and explain.

Sometimes it's difficulty to understand what do we really change on skin.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What does this mean "preview every setting"? You'll need to be way more specific than that.
