### ISSUE TITLE
Conflict text widgets

### ISSUE THREAD

**Issue by bassemhelal18** [jurialmunkey/skin.arctic.horizon.2#668]
### Skin section

Home Widgets

### Current Behavior

When you add a text widgets and submenu images there is a conflict between both of them 

### Expected Behavior

I think they need to be separate 

### Steps To Reproduce

1-add text widget
2-add submenu  images
Last 2 raw 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I don't understand the issue you're reporting. Screenshots or a video would help.

**Comment by bassemhelal18** [comment]
https://user-images.githubusercontent.com/77381611/203778325-3c364fb7-4210-4dd3-8467-6c17aca9aeff.MOV

**Comment by jurialmunkey** [comment]
Turn off "expand information" for that text widget. The expand information option is not supported for that type of widget.
