### ISSUE TITLE
[BUG] Music Info

### ISSUE THREAD

**Issue by luckylukz02** [jurialmunkey/skin.arctic.horizon.2#672]
### Skin section

Music Info Dialog

### Current Behavior

![P_20221126_122357](https://user-images.githubusercontent.com/80491975/204088962-d771974c-858f-4890-bc36-574d7fe51b86.jpg)

### Expected Behavior

![P_20221126_122422](https://user-images.githubusercontent.com/80491975/204088968-ce90febd-723e-4444-9932-4bfa31505ad4.jpg)

### Steps To Reproduce

I installed Tidal2 music addon last week and added some widgets. When i used to play a song from a widget i would get a page which is displayed as the expected behavior. Instead now i get the current behavior. 

The expected behavior is reproduced from playing the same song within the Tidal2 music addon and local music files.

The addon is 3 months old so it has not been updated recently.

I reverted back to v0.7.6 from v0.7.8 which did not show the expected behavior.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't test with Tidal as I don't have an account but Music works completely fine for me.

There's no reason for it to not display artwork or title. It looks like something else going wrong here.

**Comment by luckylukz02** [comment]
I must have had the following setting on previously when it worked. Enabling again did the trick.

- Set placback informations for Web-Gui

![P_20221128_153500](https://user-images.githubusercontent.com/80491975/204318768-00816a3d-5b5b-41f8-90a4-62f692d65d49.jpg)

Can't recommend Tidal2 on Arctic Horizon 2 if you have Tidal.

Thanks
