### ISSUE TITLE
[BUG] Show Movies and TV Shows of Cast and Crew on Clicking their images in Video Info Screen or People Search

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#677]
### Skin section

Video Info Dialog

### Feature description

Hi @jurialmunkey,

Currently if I go to the video info screen of a movie or TV show and click on the image of any cast or crew then the info about that person opens, but on pressing down I'm not able to see the movies or TV shows in which they were present. I'm quite sure that earlier this used to work. Now this feature is available only if I press down while playing a video using the OSD. Could you please add this feature back?

Edit 1: This looks more like a bug than a new feature as the TV shows of cast are not even viewable from the people search.

Edit 2: This is definitely a bug and I found the cause of it on further investigation. This issue happens if I enable the option "Focus buttons when opening info dialog". I really like the buttons focused when opening the info dialog. So is there any way to rectify this issue? Kindly advise.

### Why is this feature needed? Please justify and explain.

This will help in seeing the movies or TV shows of the cast or crew in which they were present and will provide easier access than searching for them separately.

### Screenshots and Additional Info

![IMG20221129232321](https://user-images.githubusercontent.com/65297828/204607126-89250150-19cc-4c5b-98a4-99413bdc431b.jpg)

![IMG20221129232331](https://user-images.githubusercontent.com/65297828/204607158-3fde8cfd-32bb-45fb-bc4a-e111a0145133.jpg)

![IMG20221129233117](https://user-images.githubusercontent.com/65297828/204608457-28459210-a43e-4d66-bb8a-0a80bba7fdc5.jpg)

![IMG20221129233106](https://user-images.githubusercontent.com/65297828/204608587-15abc372-5dfd-46b4-bf02-edc8e6847e4e.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Can't you press right to unfocus the buttons and then down?

**Comment by ShibajiCh** [comment]
> Can't you press right to unfocus the buttons and then down?

Hi @jurialmunkey,

No, if the "Focus buttons when opening info dialog" option is turned on then the cast or crew info page opens with the buttons unfocused and the buttons menu is closed as well. Pressing right, left, up, down does nothing. Only if I turn off the "Focus buttons when opening info dialog" option then everything in the cast or crew info page starts working properly.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Works fine for me.
Info > Right > Down

https://user-images.githubusercontent.com/4618719/204703805-cbcd0f44-075b-459d-ba72-3af7b1fe370c.mp4

**Comment by jurialmunkey** [comment]
Nevermind, I see what you're saying. No play button exists for a person, which means the focus goes to a control that doesn't exist and you get stuck.

**Comment by ShibajiCh** [comment]
> Works fine for me. Info > Right > Down
> 
>  Kodi.2022-11-30.14-47-33.mp4

Hi @jurialmunkey,

You got me wrong. I'm not talking about that. I'm talking about when you go inside the cast or crew info by further clicking on any cast or crew image. Then that page doesn't respond to the right, left, up, down keys if the "Focus buttons when opening info" dialog is turned on. On clicking over any cast or crew image the cast or crew info dialog opens and the buttons should be focused which is not happening. There is some bug which is causing the buttons to remain unfocused on that page (see below screenshot).

![IMG20221129232331](https://user-images.githubusercontent.com/65297828/204704608-ac4feec9-66b1-4d99-938c-84a7c8e58240.jpg)

This is how it appears and the left, right, up, down buttons do nothing in this page if that above mentioned Focus buttons option is turned on. On turning that option off everything works fine. Kindly check and advise.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
> Nevermind, I see what you're saying. No play button exists for a person, which means the focus goes to a control that doesn't exist and you get stuck.

Hi @jurialmunkey,

Yes, that's correct.

**Comment by ShibajiCh** [comment]
Thank you @jurialmunkey !
