### ISSUE TITLE
[BUG] Plot not showing in full expanded info

### ISSUE THREAD

**Issue by brentsmith721** [jurialmunkey/skin.arctic.horizon.2#678]
### Skin section

Home Widgets

### Current Behavior

The plot is not showing on any of my widgets that have `Expand information` set to `Full`. It is showing correctly in fullscreen widgets and in addons. I can get it to show 2 lines by toggling `Expanded widgets move title to header for additional line of plot` to on, but when it is off it shows no plot at all.

I started using the skin over the weekend with a fresh install, I was almost certain when I first installed the plot was showing correctly, so I thought maybe I did something that caused it and wiped everything and started over fresh again when I noticed it missing, but the issue still appeared. It's possible I imagined it and was thinking of having seen it in an addon.

### Expected Behavior

The plot should show on widgets when `Expand information` is set to `Full`

### Steps To Reproduce

1. Create a widget containing movie or tv content and set `Expand information` to `Full`
2. Ensure `Skin Settings > Menus > Widgets > Expand widgets move title to header for additional line of plot` is toggled `off`
3. Navigate to the home menu where you created your widget
4. Focus an item in the widget you created
5. Notice the plot is not shown

### Screenshots and Additional Info

![Screenshot_20221130-003109](https://user-images.githubusercontent.com/42626892/204757253-13935dd3-b790-49e2-b66a-7bd5d38666b0.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is correct behaviour. You need to enable the option to move the title to header to see the plot.

I need to relabel the setting to make it clearer that it enables the plot for full expanded, not just provided an extra line.

**Comment by brentsmith721** [comment]
Ah okay. Yes I definitely mistook that setting to mean it would be an extra line added in addition to a default number of lines. Would you possibly consider a feature request for that functionality? Cause it does look like 1 line _would_ fit there and I did think it looked a bit off with that much whitespace. Maybe the options could be

- no plot
- 1 line of plot
- 2 lines of plot(moves title to header)

What do you think?
