### ISSUE TITLE
[Feature] Add subtitle color option [Nexus]

### ISSUE THREAD

**Issue by MauriceW67** [jurialmunkey/skin.arctic.horizon.2#681]
### Skin section

Other

### Feature description

The current version of the skin has almost all new subtitle options that were added / changed in Kodi Nexus. The only option missing is the subtitle color option (under Settings -> Player Settings -> Subtitles).

Now that Kodi Nexus is in beta, I hope you will consider adding this.

### Why is this feature needed? Please justify and explain.

I regularly switch between two shades of grey for subtitles, depending on if I'm watching SDR or HDR/DV content. This is because the shade I use for SDR is too bright for HDR and the shade that I use for HDR is too dim for SDR.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by saxoloman** [comment]
This would be awesome if possible.
I got a new TV yesterday and when watching HDR subtitles are stabbing my eyes.

**Comment by emiralem** [comment]
I know it is not exact solution you want, but you can change skin to default(estuary) and choose subtitle color you want from settings and than go back to AH2 as your skin.

**Comment by MauriceW67** [comment]
@emiralem I know this method, but it's not very efficient :)

Also, switching between skins means that AH2 reverts back to the default color scheme and I prefer to use the dark one.

So I hope @jurialmunkey will consider adding the subtitle color dialog sometime in the future...

**Comment by MoojMidge** [comment]
@jurialmunkey - Can you please add the following to DialogAddonSettings,xml as well, so that addon settings can use the colour picker button? Refer https://github.com/xbmc/xbmc/pull/20370
```
<include content="Dialog_Settings_Button">
    <param name="id" value="15" />
    <param name="control" value="colorbutton" />
    <description>Default Setting Button</description>
</include>
```
