### ISSUE TITLE
[Feature] Support more "new settings format" features

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon.2#685]
I've been in the process of updating a few add-ons to use the "new settings format", and have been really wanting to use settings levels and help text... but AH2 doesn't display them 😱

It seems like they're implemented for Kodi settings, but not add-on ones. Could we get this as well?

**Comment by jurialmunkey** [comment]
Are you sure? What's missing? Addons settings dialgo shows the help text for me at the bottom...

![screenshot00152](https://user-images.githubusercontent.com/4618719/206069893-e2fdb851-fdd4-47bb-9bc9-2f21fb2f7de7.jpg)

**Comment by drinfernoo** [comment]
Oh my goodness 🤦 It's the same as the labels, where they have to be localized 😅 I can't believe I didn't think of that.

**Comment by jurialmunkey** [comment]
> Hang on, what about settings levels?

Ugh, it's not documented so I didn't even know about it
https://kodi.wiki/view/List_of_Built_In_Controls#DialogAddonSettings.xml

Looking at Estuary, I'm guessing it is button id="20"
