### ISSUE TITLE
[BUG] PVR stream gets stuck when played in background

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#69]
It might seem to have nothing to do with the skin, but happens only with AH2, so I am pretty sure there must be some kind of skin-related reason for it.

**What exactly is happening?**
PVR stream is flawless when played fullscreen, but when I bring to front any other window during playback (like home screen), my stream gets stuck like each 3-4 seconds and then it stucks completeley.
When I switch to player window again, it looks like my stream is fast-forwarded and then it works flawlessly again.

I am pretty sure it has nothing to do with iptv stream quality / internet speed, hardware etc as nothing like this happens to me on AH1. The same bug happens on my CoreElec setup and Kodi for mac.
Also - nothing like this happens during movies / series playback when switching to background playback.

@jurialmunkey - I was wondering - perhapas this issue has something to do with that new preview window in EPG view that you have implemented in AH2? I am not sure how it works exactly, but isn’t it that the same stream needs to be rendered two times at the same time - for fullscreenplayback and then for EPG previerw and that couses this issue? If so - I’d love to see an option to turn off the preview just to ensure i can hear backgeround audio stream which won’t stuck. And perhaps sometime in the future an option for video playback in background (I know it’s on your to-do list).

**Comment by krzysztofwinnik** [comment]
I made a short movie to explain better what is this issue about. 
@jurialmunkey - watch it please with audio on. 
[Link to video](https://youtu.be/ui14LFOySuw)

**Comment by jurialmunkey** [comment]
Is this fixed now?

**Comment by krzysztofwinnik** [comment]
@jurialmunkey yup, thank you.
