### ISSUE TITLE
[Feature] Different view for episode groups

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon.2#691]
### Skin section

Library Views

### Feature description

Would it be possible to add a specific view for episode groups? Currently it's using posters by default. In the same note, would it be possible (I don't know if the API returns this) to show the number of groups for the episode group selected instead of the default number of seasons at the bottom left part of the screen? My reasoning here is that by selecting a different episode group, the official number of seasons loses its meaning and we are more interested here in the number of groups available.  This is specially true for anime, at least in my opinion. 

### Why is this feature needed? Please justify and explain.

The problem with the one used right now by default is that you don't see the name of the episode group so you get a bunch of posters with the same image and no description of what each one means. Meanwhile, if using squares instead of posters, you get the name of the episode group (and the same image again for all of them but I guess TMDB doesn't provide different posters for episode groups). 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by juanma-cvega** [comment]
From inside TMDbHelper. When you say Kodi's library you mean after syncing an addon list to the library, right? I'm not using the library at all now, I just use the addon through widgets.

**Comment by jurialmunkey** [comment]
Now possible to set separate views for TMDbHelper episode groupings.

Latest version of TMDbHelper fixes the season count issue.
