### ISSUE TITLE
[Feature] Choice between Landscape and Fanart in Media Info List

### ISSUE THREAD

**Issue by Rocknol** [jurialmunkey/skin.arctic.horizon.2#696]
### Skin section

Library Views

### Feature description

I really like the Media Info List view, but landscape art is used by default. Would it be possible to add an option to choose between landscape and fanart, like on these screenshots from Bello 8?

### Why is this feature needed? Please justify and explain.

This would allow more artwork choice in a library view that seems to be designed to showcase artwork.
I understand that I could just choose "No Art" in the landscape or fanart sections to have it revert to the other, but I'd have to do it for every library item. Having a general setting to switch between the two would imho make the process easier, as someone who usually prefers fanarts.

### Screenshots and Additional Info

![Kodi AH2](https://user-images.githubusercontent.com/120267328/206864101-547a52d4-2da7-417f-b370-866af136a245.PNG)

![Kodi AH2 2](https://user-images.githubusercontent.com/120267328/206864126-457ae547-6e64-43e2-9a18-0886df0daa41.PNG)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
In next release
Skin Settings > Appearance > Prefer landscape art

**Comment by NicolasBriE** [comment]
That's awesome, thank you.

**Comment by Rocknol** [comment]
That's awesome, thank you.
