### ISSUE TITLE
[Feature] [Viewtypes] Vertical combined list view

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#70]
Hi @jurialmunkey,

Is there any possibility of adding a view like the below image?
![images (51)](https://user-images.githubusercontent.com/65297828/172120342-128938fa-dc9c-4be7-bb3f-0d58fe38fdc5.jpeg)

**Comment by jurialmunkey** [comment]
Yeah I was thinking of adding a vertical "combined" view sort of similar (basically a mashup of the standard + info list). There's a few other viewtypes I also want to add (like lovefilm!!), so once I get through some of the more urgent issues / bugs I look at expanding the viewtypes a bit more.

**Comment by ShibajiCh** [comment]
Fine @jurialmunkey. Thank you for the update! I shall look forward to those new view types. In the meantime please take your time and resolve the urgent issues/bugs. No hurry! 🙂

**Comment by Goldenfreddy0703** [comment]
Hey @jurialmunkey , Sorry for the ping but in the future, were you thinking of having a Showcase Center Viewtype by anychance? It would be really cool having one for your skin and i would love to use that Viewtype. If you were thinking about adding that Viewtype, That would be really cool but if not then its totally fine. 
Thank you

![image](https://user-images.githubusercontent.com/62456796/172614187-fe0917bc-8506-4842-a82d-c16dfc04b3e9.png)

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Any updates on this vertical combined list view type? Just wanted to know if this is a work in progress.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
No updates yet, but definitely planned.

**Comment by ShibajiCh** [comment]
Fine @jurialmunkey. Thanks for letting me know!

**Comment by ShibajiCh** [comment]
Thank you so much @jurialmunkey !
