### ISSUE TITLE
[BUG] Short Description

### ISSUE THREAD

**Issue by docgoodygoods** [jurialmunkey/skin.arctic.horizon.2#703]
### Skin section

Other

### Current Behavior

After a clean install of KODI, the first thing I install is the repository and skin. Upon changing to the skin, I get a notification that Skinshortcuts had a problem. After this, I'm left with a blank screen (nothing but the background, search bar, and top right icon) and cannot do anything. I cannot access anything in KODI after this and have to completely reinstall afterwards. Running latest stable verson of KODI on Apple TV 4K.

### Expected Behavior

For the skin to change and be usable.

### Steps To Reproduce

1. Install repository
2. Install all requirements for skin
3. Install skin
4. Apply skin
5. Frozen

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by rapteev** [comment]
Hi
That is a problem with skinshortcuts on Apple TV . There’s nothing to do with the skin. You have to install previous version of skinshortcuts. I’m not sure but I think that is version 1.15

**Comment by jurialmunkey** [comment]
See solution above.
