### ISSUE TITLE
[BUG] Gap between Title and Plot when ratings are disabled

### ISSUE THREAD

**Issue by booyakafoo** [jurialmunkey/skin.arctic.horizon.2#707]
### Skin section

Home Widgets

### Current Behavior

Using TMDB helper widgets on Home. 
Expand information is set to Full. 

With ratings disabled.  Nothing is checked in skin settings, details, customize ratings.  
There is a space where the ratings should be.  The plot is only two lines.  Could you expand the plot to be 3 or 4 lines to fill up this space?  

Image to show the space. 
https://imgur.com/a/kgztNaF

### Expected Behavior

There is some wasted space and two lines of plot scrolling when there is space above looks off. 

### Steps To Reproduce

Create home widget with expand information set to full. 
Uncheck all options in skin settings, details, customize ratings. 

### Screenshots and Additional Info

Image to show the space. 
https://imgur.com/a/kgztNaF

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Next version (0.7.17) will add an option to disable all ratings and the plot will expand to fill the extra space.
