### ISSUE TITLE
[Feature] Seekbar for YouTube Trailers

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon.2#709]
### Skin section

Home Widgets

### Feature description

Hi mate, hope you are doing well.
In the skin settings > Behaviour > Under Playback I have disabled 'Trailer button plays windowed'....now when I watch the Trailer it is full screen which is fine as I would expect but I don't find the seek bar at the bottom.
Am I missing any settings?

### Why is this feature needed? Please justify and explain.

So that I can see the video quality being played just how I can see it for other videos when played via addons.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Not really possible. Playing a video full screen will force the video info dialog to close, so instead it is faked with a fullscreen overlay to avoid losing your place.

If you want to play a trailer in true fullscreen you'd need to play it from the context menu outside the info dialog.

**Comment by onlytanmoy** [comment]
Ah ok, no worries, thanks for sharing the work around :)
Happy holidays mate 🎉

**Comment by onlytanmoy** [comment]
[Quote]If you want to play a trailer in true fullscreen you'd need to play it from the context menu outside the info dialog.[/quote]
Unable to figure it, can you share a screenshot please?

**Comment by jurialmunkey** [comment]
@onlytanmoy - Sorry, you're right, there's no "play trailer" context menu item. I forgot that I used to have the Play Trailer context menu addon installed.

[BigNoid's version](https://github.com/BigNoid/context.trailer) in the official repo is for Leia but there's no reason the code can't work with Matrix. All that needs to happen is the python version needs to be bumped up to 3.0.0 in the addon.xml

There's a patched version in the [pull requests](https://github.com/BigNoid/context.trailer/pull/5) to allow installing on Matrix onwards: https://github.com/icegothic/context.trailer/tree/patch-1

Also not sure why it is limited to only Movies but you can make it work with TV Shows too by modifiying the addon.xml and removing the DBType check on this line: https://github.com/icegothic/context.trailer/blob/patch-1/addon.xml#L10

i.e. change
`<visible>String.IsEqual(ListItem.dbtype,movie) + !String.IsEmpty(ListItem.Trailer)</visible>`
to 
`<visible>!String.IsEmpty(ListItem.Trailer)</visible>`

**Comment by ShibajiCh** [comment]
> @onlytanmoy - Sorry, you're right, there's no "play trailer" context menu item. I forgot that I used to have the Play Trailer context menu addon installed.
> 
> [BigNoid's version](https://github.com/BigNoid/context.trailer) in the official repo is for Leia but there's no reason the code can't work with Matrix. All that needs to happen is the python version needs to be bumped up to 3.0.0 in the addon.xml
> 
> There's a patched version in the [pull requests](https://github.com/BigNoid/context.trailer/pull/5) to allow installing on Matrix onwards: https://github.com/icegothic/context.trailer/tree/patch-1
> 
> Also not sure why it is limited to only Movies but you can make it work with TV Shows too by modifiying the addon.xml and removing the DBType check on this line: https://github.com/icegothic/context.trailer/blob/patch-1/addon.xml#L10
> 
> i.e. change `<visible>String.IsEqual(ListItem.dbtype,movie) + !String.IsEmpty(ListItem.Trailer)</visible>` to `<visible>!String.IsEmpty(ListItem.Trailer)</visible>`

Thank you so much @jurialmunkey !

Regards,
ShibajiCh.

**Comment by onlytanmoy** [comment]
@jurialmunkey Many thanks mate, working like a charm, you are a super star🤘
Merry Christmas and a happy new year, cheers!
