### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TechXXX** [jurialmunkey/skin.arctic.horizon.2#710]
### Skin section

Home Widgets

### Current Behavior

If you go into search and search for Jack (this behaviour only manifests with TV shows, Movies are ok) then press info on Jack Ryan, play the trailer, back out of the trailer, back again, press info on Gentleman Jack and Jack Ryans source list pops up (don't have autoplay enabled). 

### Expected Behavior

Normally you'd see the info screen without source list popping up unwanted. 

### Steps To Reproduce

If you go into search and search for Jack (or anything) then press info on Jack Ryan, play the trailer, back out of the trailer, back again, press info on Gentleman Jack and Jack Ryans source list pops up (don't have autoplay enabled). 

****

### Screenshots and Additional Info

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/10297771/kodi.log)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce. I also don't know what you mean by "Source List".

**Comment by TechXXX** [comment]
Sorry source list as in the list Umbrella gives me for a specific title. Could be an umbrella issue, I don't know. Tried it on 2 systems (windows & android) both 19.4 with AH2 and Umbrella. Or maybe the new search strings are the problem? 

https://www.reddit.com/r/Addons4Kodi/comments/zpyrpr/replace_ah2_search_with_umbrella_or_fens_search/

**Comment by TechXXX** [comment]
Just tried it out in by opening TMDB helper & Umbrella from videoaddons (not from widget view) and both start playing upon hitting information (I).

**Comment by TechXXX** [comment]
Just tried it with FEN, inside FEN no issues (unlike Umbrella), when I use FEN as a player inside tmdb helper the problem persists. merry xmas

**Comment by krzysztofwinnik** [comment]
@TechXXX Here is what Fen dev says about its compatibility with TMDBHelper:

TMDbHelper and/or library playback issues are not supported. Fen does not support TMDbHelper. If I wanted to write an addon to purely search and play back results whilst another addon is used for everything else, that's what I would have written. The full breaking of TMDbHelper accessing Fen scraping & playback is close. Don't push that by opening an Issue related to it. Use a Fen fork if you want to use TMDbHelper.

**Comment by TechXXX** [comment]
which player are we supposed to use with TMDBhelper?

**Comment by jurialmunkey** [comment]
I cannot reproduce using the builtin tmdbhelper search lists. It sounds like you're double clicking or have a weird keymap or have added aweird search path. There's no reason for this behaviour to occur in the skin with the defaults.

**Comment by TechXXX** [comment]
some addon must have altered something on both my installs then, I just deleted my keymap and the custom search path for umbrella, now the source list doesn't pop up anymore (inside ah2 builtin search) but you can still see it trying via the message in the upper right corner, and on my trakt-trending widget (umbrella) the problem persists. Umbrella dev is looking into it as well, next step is a clean install. appreciate you looking into it.

**Comment by TechXXX** [comment]
ok I did a full clean install to 19.5, as soon as I enabled Umbrella autoplay is when the problem started, and disabling it apparently doesn't get rid of the problem.

**Comment by TechXXX** [comment]
Wrong github issue page, my apologies.

**Comment by TechXXX** [comment]
In case anyone else was having this issue the Umbrella dev is working toward a solution here (I hope;): 

https://www.reddit.com/r/Addons4Kodi/comments/zvu5lg/comment/j1u7i53/?context=3
