### ISSUE TITLE
[Feature] Add "Select Player" back to the main/primary context menu

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/skin.arctic.horizon.2#711]
### Skin section

Other

### Feature description

Would it be possible to move the "Select Player" item back to the main/primary context menu?  

### Why is this feature needed? Please justify and explain.

I'm pretty sure it was there early in the Alpha phase, but at some point it was moved to a second menu under TMDBH Options.  If others are at all like me, one of the primary benefits to using TMDBH is the ability to select different players without manually navigating within each separate addon.  That makes it one of the most used features of the context menu (at least for me).  So it's not as convenient to have to scroll down to TMDBH Options and click again to get to Select Player.  It would be really nice to have Select Player back on the primary context menu dialog for easier access.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by drinfernoo** [comment]
This would be an issue for https://github.com/jurialmunkey/plugin.video.themoviedb.helper.

**Comment by eengert** [comment]
Thanks, I wasn’t sure. I’ll move it.

-- 
Eric Engert

**Comment by jurialmunkey** [comment]
It is a Kodi issue which I reported back in September and the underlying issue has already been fixed for Nexus in this PR https://github.com/xbmc/xbmc/pull/21866
