### ISSUE TITLE
Cannot update to .19

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#714]
### Skin section

Other

### Current Behavior

I am still running Matrix, on a fresh install and it is not allowing me to install AH2, this is because TMDBh requires 5.0.40, and I turn requires Kodi 20 for python dependency 3.0.1.

### Expected Behavior

Able to install

### Steps To Reproduce

Try to install on fresh matrix on FireCube

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by alKODIque** [comment]
Yes, I am in the same situation ;)

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

I am facing the same issue. Unable to update to the latest version of Arctic Horizon 2 on Matrix v19.5 due to the unavailability of TMDB Helper v5.0.40 in the Repo. Kindly check and advise.

Thanks and Regards,
ShibajiCh.

**Comment by adamosborne83** [comment]
Until resolved, just grad a zip from previous version. 
I made sure I installed all dependencies first, then no issues.
I am sure Jurial will help us, as per 😀

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

I updated my Kodi to Nexus v20 RC2 and now everything is working fine.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
> Hi @jurialmunkey,
> 
> I updated my Kodi to Nexus v20 RC2 and now both the add-ons updated to their latest versions. However, I'm facing lots of crashes on my Nvidia Shield TV Pro 2019 with Nexus. It seems this is related to the TMDB Helper add-on as I can see in an ongoing issue thread. Hope to see the crashing issues resolved soon.
> 
> Thanks and Regards, ShibajiCh.

Python standard library ElementTree module is broken in Kodi using Python 3.11 (i.e. Nexus except for on Windows which still uses 3.8.15 of Python).

ElementTree parses XML metadata, so will need to remove your OMDb API key to avoid using ElementTree until it is fixed upstream.

**Comment by jurialmunkey** [comment]
@adamosborne83 @alKODIque - Version 5.0.41 of TMDbH for Matrix should be available on the repo now. 

New versions of TMDbH for Matrix will lag behind Nexus now. I've switched main branch of TMDbH to Nexus, so any new features need to be backported to Matrix.

I will continue to backport anything major to Matrix for the time being until these Python 3.11 issues are sorted but I'm pretty keen to stop Matrix dev as soon as reasonable.

**Comment by ShibajiCh** [comment]
> > Hi @jurialmunkey,
> > I updated my Kodi to Nexus v20 RC2 and now both the add-ons updated to their latest versions. However, I'm facing lots of crashes on my Nvidia Shield TV Pro 2019 with Nexus. It seems this is related to the TMDB Helper add-on as I can see in an ongoing issue thread. Hope to see the crashing issues resolved soon.
> > Thanks and Regards, ShibajiCh.
> 
> Python standard library ElementTree module is broken in Kodi using Python 3.11 (i.e. all Nexus platforms except for on Windows which still uses 3.8.15 of Python).
> 
> ElementTree parses XML metadata, so will need to remove your OMDb API key to avoid using ElementTree until it is fixed upstream.

Thank you @jurialmunkey !
I've already removed the OMDB API key and enabled the "Rebuild service listitems offscreen" as mentioned in the other issue thread for TMDB Helper. However, I miss those OMDB ratings a lot. Hope this issue will get resolved soon.

Regards,
ShibajiCh.
