### ISSUE TITLE
[BUG] Option Menu is empty

### ISSUE THREAD

**Issue by tmbt78** [jurialmunkey/skin.arctic.horizon.2#717]
### Skin section

Home Widgets

### Current Behavior

The option menu on the top right in the home screen is empty so i cannot enter in the settings menu or for example restart my device

### Expected Behavior

There should be some options to choose from

### Steps To Reproduce

Just switch on the device 

### Screenshots and Additional Info

![artist horizon 2](https://user-images.githubusercontent.com/48015052/210077422-20e737d7-4f5e-4a30-bf66-d95120e1f80d.jpg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Impossible for me to tell what the issue wis without a log but it will be either

- You didnt install skin shortcuts eventhough it is a skin dependency or you didn't install it properly (so reinstall it properly) 
- Your skinshortcuts setup is corrupt (so delete the script.skinshortcuts folder from userdata/addon_data and it will rebuild on restart) 
- You deleted all the items in the power menu (can't help you there if you're surprised that deleting things deletes things)

**Comment by tmbt78** [comment]
Hi, thanks for the answer.
To avoid every possible problem I can replicate the same problem on a new
install.
I just reinstalled a fresh new image on my Vero4k+ system. After that I
added only your repository and only your skin. I got no dependency error
but when I select your skin the power button on the top right is empty.
I can add that if I go in the movie section and select the top right option
button there i can see all the options to customize the selection. The
problem is only with the power button on the main menu. Does this make any
sense?
How can I give you logs to better understand this problem?

Thanks

Il Sab 31 Dic 2022, 01:13 jurialmunkey ***@***.***> ha
scritto:

**Comment by corus87** [comment]
I had the same issue, it happened after I updated the skin yesterday (also on a Vero 4k).

But I was able to solve the problem by renaming the script.skinshortcuts folder in userdata/addon_data, reloading the skin (kodi-send -a reloadskin), deleting the new generated script.skinshortcuts folder, renaming the original script.skinshortcuts folder back and reloading the skin again.
All my skin settings are still there and the menu is working again.

It does not sound like a corrupted skinshortcuts file, maybe it just cannot load it properly after the update?

**Comment by jurialmunkey** [comment]
Impossible to tell without a log file.

Highly unlikely to be a skin issue. Sounds like a problem specifically with OSMC as skinshortcuts functions properly on Kodi.

**Comment by RZR7332** [comment]
> I had the same issue, it happened after I updated the skin yesterday (also on a Vero 4k).
> 
> But I was able to solve the problem by renaming the script.skinshortcuts folder in userdata/addon_data, reloading the skin (kodi-send -a reloadskin), deleting the new generated script.skinshortcuts folder, renaming the original script.skinshortcuts folder back and reloading the skin again. All my skin settings are still there and the menu is working again.
> 
> It does not sound like a corrupted skinshortcuts file, maybe it just cannot load it properly after the update?

Thanks for your steps, had exactly the same problem - this resolved it.

**Comment by fraubush** [comment]
Hey @RZR7332 and @corus87 — I'm running into the same issue on my end. I've got OSMC installed on a Raspberry Pi 4 and got everything set up properly on my end until I applied the Arctic Horizon 2 skin. Now, when I boot up my Pi I'm stuck in the AH2 UI but when I move the cursor to the gear I get the same issue that is seen in tmbt78's image.

I understand the concept of your solve: rename the script.skinshortcuts folder; reloading the skin; rename back to original; reload skin again. But how do I rename the folder? I assume it's not through the Kodi/AH2 GUI but I can't find it there anyway if it is. I'm connected to the Pi from my mac via SSH but I'm still somewhat green in using command line prompts. Is there a way I can apply your fix via command line over SSH?

Thanks in advance!

**Comment by fraubush** [comment]
Ok, I'm getting closer. I figured out how to rename the folder using the mv command. Now, the folder in ~/.kodi/userdata/addon_data/ is called "script.skinshortcuts2." But anytime I reload the skin using "kodi-send -a reloadskin," the skin reloads but it does not generate a new script.skinshortcuts folder. There is still only my renamed version of the folder, script.skinshortcuts2. 

I'm attaching screenshot of my directory after the reloadskin command so you can see what I mean that the renamed folder is still there but there is no new folder generated. 
<img width="730" alt="Screen Shot 2023-01-16 at 7 34 05 PM" src="https://user-images.githubusercontent.com/25350771/212785069-023a3edd-3309-494a-a021-ccf7c7c01b14.png">

 
 Any idea what I'm doing wrong or how to resolve? Thanks!

**Comment by RZR7332** [comment]
@fraubush not sure why yours is not working. I can paste the terminal output from my attempts:

12:40:55.177 §root@osmc:/home/osmc/.kodi/userdata/addon_data# mv script.skinshortcuts/ script.skinshortcuts.orig/
12:40:55.654 §root@osmc:/home/osmc/.kodi/userdata/addon_data# 
12:40:55.754 §root@osmc:/home/osmc/.kodi/userdata/addon_data# 
12:40:59.245 §root@osmc:/home/osmc/.kodi/userdata/addon_data# ls -la
12:40:59.257 §total 152
12:40:59.257 §drwxr-xr-x 38 osmc osmc 4096 Jan  3 12:40 .
12:40:59.257 §drwxr-xr-x 11 osmc osmc 4096 Dec 26 18:34 ..
12:40:59.257 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.themoviedb.org
12:40:59.257 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.themoviedb.org.python
12:40:59.257 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.tvdb.com.python
12:40:59.257 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.tvshows.themoviedb.org.python
12:40:59.257 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.universal
12:40:59.257 §drwxr-xr-x  3 osmc osmc 4096 Sep 18 21:14 peripheral.joystick
12:40:59.257 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 plugin.audio.soundcloud
12:40:59.257 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 plugin.program.autocompletion
12:40:59.258 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 plugin.video.specialfeatures
12:40:59.258 §drwxr-xr-x  4 osmc osmc 4096 Sep 23 12:43 plugin.video.themoviedb.helper
12:40:59.258 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 plugin.video.youtube
12:40:59.258 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.artwork.beef
12:40:59.258 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.colorbox
12:40:59.258 §drwxr-xr-x  6 osmc osmc 4096 Sep 23 12:43 script.extendedinfo
12:40:59.258 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.grab.fanart
12:40:59.258 §drwxr-xr-x  3 osmc osmc 4096 Jan  2 19:58 script.module.autocompletion
12:40:59.258 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.metadatautils
12:40:59.258 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.osmcsetting.apfstore
12:40:59.258 §drwxr-xr-x  2 osmc osmc 4096 Sep 18 21:14 script.module.osmcsetting.pi
12:40:59.258 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.osmcsetting.updates
12:40:59.258 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.simplecache
12:40:59.260 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.thetvdb
12:40:59.260 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 script.module.youtube.dl
12:40:59.260 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 script.skin.helper.backgrounds
12:40:59.260 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 script.skinshortcuts.orig
12:40:59.260 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 script.skinvariables
12:40:59.261 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 script.texturemaker
12:40:59.261 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 script.tv.show.next.aired
12:40:59.261 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 service.thoradia
12:40:59.261 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 skin.arctic.horizon
12:40:59.261 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 skin.arctic.horizon.2
12:40:59.261 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 skin.arctic.zephyr.2
12:40:59.261 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 skin.estuary
12:40:59.261 §drwxr-xr-x  2 osmc osmc 4096 Sep 18 21:14 skin.osmc
12:40:59.261 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 skin.quartz
12:40:59.261 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 weather.gismeteo
12:41:19.048 §root@osmc:/home/osmc/.kodi/userdata/addon_data# kodi-send -a reloadskin
12:41:19.209 §Sending: {'type': 'action', 'content': 'reloadskin'}
12:46:16.030 §root@osmc:/home/osmc/.kodi/userdata/addon_data# ls -la
12:46:16.035 §total 156
12:46:16.037 §drwxr-xr-x 39 osmc osmc 4096 Jan  3 12:41 .
12:46:16.037 §drwxr-xr-x 11 osmc osmc 4096 Dec 26 18:34 ..
12:46:16.037 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.themoviedb.org
12:46:16.037 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.themoviedb.org.python
12:46:16.037 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.tvdb.com.python
12:46:16.037 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.tvshows.themoviedb.org.python
12:46:16.037 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.universal
12:46:16.037 §drwxr-xr-x  3 osmc osmc 4096 Sep 18 21:14 peripheral.joystick
12:46:16.037 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 plugin.audio.soundcloud
12:46:16.037 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 plugin.program.autocompletion
12:46:16.037 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 plugin.video.specialfeatures
12:46:16.037 §drwxr-xr-x  4 osmc osmc 4096 Sep 23 12:43 plugin.video.themoviedb.helper
12:46:16.038 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 plugin.video.youtube
12:46:16.038 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.artwork.beef
12:46:16.038 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.colorbox
12:46:16.038 §drwxr-xr-x  6 osmc osmc 4096 Sep 23 12:43 script.extendedinfo
12:46:16.038 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.grab.fanart
12:46:16.038 §drwxr-xr-x  3 osmc osmc 4096 Jan  2 19:58 script.module.autocompletion
12:46:16.038 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.metadatautils
12:46:16.038 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.osmcsetting.apfstore
12:46:16.038 §drwxr-xr-x  2 osmc osmc 4096 Sep 18 21:14 script.module.osmcsetting.pi
12:46:16.038 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.osmcsetting.updates
12:46:16.038 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.simplecache
12:46:16.038 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.thetvdb
12:46:16.038 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 script.module.youtube.dl
12:46:16.038 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 script.skin.helper.backgrounds
12:46:16.039 §drwxr-xr-x  2 osmc osmc 4096 Jan  3 12:41 script.skinshortcuts
12:46:16.039 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 script.skinshortcuts.orig
12:46:16.039 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 script.skinvariables
12:46:16.039 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 script.texturemaker
12:46:16.039 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 script.tv.show.next.aired
12:46:16.039 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 service.thoradia
12:46:16.039 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 skin.arctic.horizon
12:46:16.039 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 skin.arctic.horizon.2
12:46:16.039 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 skin.arctic.zephyr.2
12:46:16.039 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 skin.estuary
12:46:16.039 §drwxr-xr-x  2 osmc osmc 4096 Sep 18 21:14 skin.osmc
12:46:16.039 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 skin.quartz
12:46:16.039 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 weather.gismeteo
12:46:28.603 §root@osmc:/home/osmc/.kodi/userdata/addon_data# rm -rf script.skinshortcuts
12:46:28.967 §root@osmc:/home/osmc/.kodi/userdata/addon_data# 
12:46:52.234 §root@osmc:/home/osmc/.kodi/userdata/addon_data# cp -r script.skinshortcuts.orig/ script.skinshortcuts/
12:46:52.708 §root@osmc:/home/osmc/.kodi/userdata/addon_data# 
12:46:54.104 §root@osmc:/home/osmc/.kodi/userdata/addon_data# ls -la
12:46:54.111 §total 156
12:46:54.111 §drwxr-xr-x 39 osmc osmc 4096 Jan  3 12:46 .
12:46:54.111 §drwxr-xr-x 11 osmc osmc 4096 Dec 26 18:34 ..
12:46:54.111 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.themoviedb.org
12:46:54.111 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.themoviedb.org.python
12:46:54.111 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.tvdb.com.python
12:46:54.111 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.tvshows.themoviedb.org.python
12:46:54.111 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 metadata.universal
12:46:54.111 §drwxr-xr-x  3 osmc osmc 4096 Sep 18 21:14 peripheral.joystick
12:46:54.112 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 plugin.audio.soundcloud
12:46:54.112 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 plugin.program.autocompletion
12:46:54.112 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 plugin.video.specialfeatures
12:46:54.112 §drwxr-xr-x  4 osmc osmc 4096 Sep 23 12:43 plugin.video.themoviedb.helper
12:46:54.112 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 plugin.video.youtube
12:46:54.112 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.artwork.beef
12:46:54.112 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.colorbox
12:46:54.112 §drwxr-xr-x  6 osmc osmc 4096 Sep 23 12:43 script.extendedinfo
12:46:54.112 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.grab.fanart
12:46:54.112 §drwxr-xr-x  3 osmc osmc 4096 Jan  2 19:58 script.module.autocompletion
12:46:54.112 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.metadatautils
12:46:54.112 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.osmcsetting.apfstore
12:46:54.112 §drwxr-xr-x  2 osmc osmc 4096 Sep 18 21:14 script.module.osmcsetting.pi
12:46:54.112 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.osmcsetting.updates
12:46:54.112 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.simplecache
12:46:54.112 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:43 script.module.thetvdb
12:46:54.113 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 script.module.youtube.dl
12:46:54.113 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:43 script.skin.helper.backgrounds
12:46:54.113 §drwxr-xr-x  2 root root 4096 Jan  3 12:46 script.skinshortcuts
12:46:54.113 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 script.skinshortcuts.orig
12:46:54.113 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 script.skinvariables
12:46:54.113 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 script.texturemaker
12:46:54.113 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 script.tv.show.next.aired
12:46:54.113 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 service.thoradia
12:46:54.113 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 skin.arctic.horizon
12:46:54.113 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 skin.arctic.horizon.2
12:46:54.113 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 skin.arctic.zephyr.2
12:46:54.113 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 skin.estuary
12:46:54.113 §drwxr-xr-x  2 osmc osmc 4096 Sep 18 21:14 skin.osmc
12:46:54.114 §drwxr-xr-x  2 osmc osmc 4096 Sep 23 12:44 skin.quartz
12:46:54.114 §drwxr-xr-x  3 osmc osmc 4096 Sep 23 12:44 weather.gismeteo
12:46:57.002 §root@osmc:/home/osmc/.kodi/userdata/addon_data# kodi-send -a reloadskin
12:46:57.079 §Sending: {'type': 'action', 'content': 'reloadskin'}

Maybe try restarting Kodi itself then running the reloadskin command again? You can do it from the CLI - systemctl restart mediacenter.service

**Comment by fraubush** [comment]
Thanks @RZR7332! After I posted my messages, I was able to mess around a little more and was able to get things working! Here's what I believe was able to solve for me. I'm still pretty new to this stuff so I hope this makes sense and can be helpful for anyone else in the future. I was accessing the OSMC pi 4 over SSH.

- Last we left off I had renamed script.skinshortcuts and ran reloadskin but, for some reason, i would see the screen flash and the skin reload but it was not generating a new script.skinshortcuts folder. It just kept my renamed version
- So, I tried deleting the file altogether with 'rm -r script.skinshortcuts2' (since I had already renamed script.skinshortcuts)
- I reloaded the skin again and AH2 was still active with the same problem, no settings listed under the top-right gear icon. And all of this now without script.skinshortcuts existing at all
- So then I wanted to reinstall Skin Shortcuts. I thought it would be an easy install since the repository said it could be installed by the Kodi official addons. That wasn't the case for me. Unless I'm mistaken, it should be in the context menu addons but it wasn't listed as an option for me.
- I did some Googling and ended up using rm to delete guisettings.xml inside the /home/osmc/.kodi/userdata/ directory. This removed the active AH2 skin and brought me back to the default OSMC/Kodi skin. 
- Then, still in the default skin, I went into the settings to 'configure skin' _that_ gave me a prompt that I didn't have Skin Shortcuts and it would need to be installed. I let that do its thing and was able to open the 'configure skin' in the default skin.
- Then I set the skin back to AH2 and, voila! Now I have access to the full settings list from the top-right gear icon. 

Hope this makes sense and can help someone out in the future. If any of this doesn't make sense let me know. Thanks  to everyone in this thread for getting me going.

**Comment by jurialmunkey** [comment]
The above commit provides a workaround to ensure a settings option is available if skinshortcuts fails to build. It doesn't fix the underlying issue (that needs to be fixed either OSMC or skinshortcuts) but it will prevent you from getting stuck.
