### ISSUE TITLE
[Feature] Short Description

### ISSUE THREAD

**Issue by cremonies** [jurialmunkey/skin.arctic.horizon.2#718]
### Skin section

Other

### Feature description

Ability to customize the new Video Hubs so not have all genres or network/providers

### Why is this feature needed? Please justify and explain.

The list of providers is very long. I would like to be able to only have the ones I care about visible.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Closed by https://github.com/jurialmunkey/skin.arctic.horizon.2/commit/043aa8ad133099d3e087cfdda1108781b9a66667
