### ISSUE TITLE
[Request] Remember settings for Colours.

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.arctic.horizon.2#72]
@Jurialmunkey Skin Default or Dark. If I change skins and come back I have to reset this each time. Can it be set to choose your default?

![image](https://user-images.githubusercontent.com/63697905/172130232-c8dcdacb-a2ce-4e1b-bd7c-b536582a53a1.jpeg)

**Comment by jurialmunkey** [comment]
Unfortunately not possible. Kodi handles theme settings and it will reset back to default when you switch skins (I think it might also revert font settings too).
