### ISSUE TITLE
[Feature] Show Unwatched Episode Count for Episode Lists

### ISSUE THREAD

**Issue by Jcloak** [jurialmunkey/skin.arctic.horizon.2#726]
### Skin section

Home Widgets

### Feature description

If the number of unwatched episodes is greater than 1, please display the number of unwatched episodes for the list. If the unwatched episode count is less than or equal to 1 then it should continue to hide the indicator as it serves no purpose.

### Why is this feature needed? Please justify and explain.

This is useful for addons that report the unwatched episode count for the Next Up Trakt list. If I am 3 episodes behind, it would be nice to see that so I know how many episodes I have remaining.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It already does...

![screenshot00159](https://user-images.githubusercontent.com/4618719/210298246-57023d25-5e5e-4857-98a7-c4001cd99c58.jpg)

**Comment by Jcloak** [comment]
I'm referring to a list that contains individual episodes for several shows. In your screenshot it would have

- Brooklyn Nine-Nine (Old School) S1:E8 (11)
- The Handmaid's Tale (God Bless the Child) S3:E4 (10)
- etc.

It looks like your screenshot is a list of shows instead of episodes.

**Comment by jurialmunkey** [comment]
Kodi does not provide this information for individual episodes.

**Comment by Jcloak** [comment]
Seren is one addon that sets the Unwatched Episodes count for lists like this. Other addons might as well, so that is why I requested the feature.

**Comment by jurialmunkey** [comment]
It doesn't make sense to show unwatched counts instead on episodes because then there is no way to tell whether an episode has been watched or if it is inprogress.

**Comment by Jcloak** [comment]
I have seen this functionality in other skins before. I think the progress indicator might take priority over the unwatched episode count indicator. This would also only impact skins that are passing the unwatched episode count for lists like this. If the addon passes 0 or 1 for unwatched, this feature would not do anything. For Seren it is a configurable setting and probably works the same way for other addons as well.
