### ISSUE TITLE
Greek not showing up in Regional>Language

### ISSUE THREAD

**Issue by ViewAfterReview** [jurialmunkey/skin.arctic.horizon.2#73]
![screenshot00000](https://user-images.githubusercontent.com/86300945/172130557-33f92fc8-80f7-4131-8c25-122d8b7ab7b9.png)

There is no option to switch to Greek language

**Comment by jurialmunkey** [comment]
Language selection is handled by Kodi, not the skin. Greek shows up fine as an option for me. Make sure that you haven't disabled the Greek language addon

`Add-ons > My Add-ons > Look and Feel > Languages > Greek`
