### ISSUE TITLE
[Feature] "Play Trailer" on down option

### ISSUE THREAD

**Issue by JayDee696969** [jurialmunkey/skin.arctic.horizon.2#730]
### Skin section

Library Views

### Feature description

In skin settings/Navigation/Press Down from row view scrollbar opens. It would be great to have a "Play Trailer" option to choose from. Just throwing it out there. I dont see any views that have a trailer button in the skin, so this would be a great alternative.

### Why is this feature needed? Please justify and explain.

Not "needed", but would be a useful way to quickly watch a trailer while browsing your media in row views.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
How do you use this feature or activate it is there a new setting
