### ISSUE TITLE
Submenu Integration with Custom Hubs

### ISSUE THREAD

**Issue by jollyhiggler** [jurialmunkey/skin.arctic.horizon.2#731]
### Skin section

Other

### Feature description

I'd like to be able to use the section submenu as the Hub Submenu Node in custom hubs. It's currently possible to select it in the same way as on the home screen, but the result is the "Submenu" header with a blank space underneath.

If the above is possible, I'd then like the additional option to access the hub by pressing up from the home menu: either as a global skin navigation setting or as a selectable option for each individual home menu item. 

### Why is this feature needed? Please justify and explain.

The ability to effectively combine submenu with custom hub and further streamline the navigation of the skin. It would also provide a straightforward means of customising the hub submenu node items in custom hubs.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Should now be able to set individual actions for Menu row onup like you can with Widget end row. Also expanded widget end row action to allow setting any action rather than just hubs.
