### ISSUE TITLE
Question - Curious about changing some asset sizes in views in personal version.

### ISSUE THREAD

**Issue by severtjoseph6** [jurialmunkey/skin.arctic.horizon.2#732]
### Skin section

Library Views

### Feature description

I personally prefer certain logos and other fields larger to take up room for ones I've turned off, ie Clear logo has plenty of room in my view with everything above it turned off so I want to make it bigger. I wanted to know if I could be pointed in the right directions or any specific documentation on these variables to experiment with it on my own. Below is my example, I would want the clear logo variable to span across the screen and maybe be higher.

### Why is this feature needed? Please justify and explain.

This is based on my personal preference and I am only hoping for some direction on where to start, otherwise feel free to close.

### Screenshots and Additional Info

![PXL_20230106_025602523](https://user-images.githubusercontent.com/70487148/210920983-58492a08-0a56-4032-b025-5cf247d58040.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The short answer is that the widget positioning and info panel code is complex. You will struggle to get decent consistent results if you don't have a lot of skinning experience. 

The places you'll want to look in are (but not limited to) -
Includes_Info.xml contains the definition of the info panel components
Includes_Widgets.xml defines widget repositioning
Includes_Constants.xml defines several constants used for coordinates
