### ISSUE TITLE
Spot light trailers[Feature] Short Description

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.horizon.2#733]
### Skin section

Home Widgets

### Feature description

While the farnart is scrolling at what ever time the user has pre set. Would it be possible for the full screen widget at the top of all widgets run a random trailer for the movie or TV show that is being portrayed to its end and once the trailer has finished the fanarts start to scroll again until a random trailer is then picked and starts the trailer run cycle once again.

### Why is this feature needed? Please justify and explain.

Just to enhance the look of the skin and the way it works. It would be great to have the trailers run without having to select information and to then press the trailer button. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The problem with auto playing trailers is that kodi forces all widgets to refresh after a video stops playing. So all your widgets will be constantly reloading and if you have something like random sort then you'd lose your place.

There's no way for the skin to suppress this behaviour.

**Comment by DROIDshield** [comment]
Thanks for taking the time to respond. I think then for the sake of keeping skin tip top we close this comment and enjoy what we have... it's truly a great skin kills TBM hands down. Keep doing what you do. Thanks again for your time. I believe you have a donate tab on your Kodi thread, so I'll drop you a drink or two.

**Comment by DROIDshield** [comment]
Admin has said this is a no go within this skin.
