### ISSUE TITLE
Clear logo on Full Screen Widget

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#734]
### Skin section

Home Widgets

### Feature description

Just a little request, if possible....
So on fullscreen widget would it be possible to Customise it so you can have clear logo?

I use thin font on my widgets, but just think clear logo adds a certain style on full screen. 

### Why is this feature needed? Please justify and explain.

Looks gorgeous 

### Screenshots and Additional Info

![20230106_211042](https://user-images.githubusercontent.com/78307374/211101064-dd8a9c50-20da-41ea-a439-cc25841161f1.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by drinfernoo** [comment]
Your screenshot clearly shows the `clearlogo` for The Shannara Chronicles being displayed there 🤔

**Comment by adamosborne83** [comment]
> Your screenshot clearly shows the `clearlogo` for The Shannara Chronicles being displayed there 🤔

You are correct, Mr Observant...... so want clearlogo on full screen, but on all my widgets beneath the option to have THIN FONT

**Comment by adamosborne83** [comment]
> > Your screenshot clearly shows the `clearlogo` for The Shannara Chronicles being displayed there 🤔
> 
> You are correct, Mr Observant. Haha..... so would like clearlogo on full screen, but on all my widgets beneath the option to have THIN FONT

**Comment by adamosborne83** [comment]
Great idea

**Comment by jurialmunkey** [comment]
Sorry I don't have plans for this level of fine grain control. Either clearlogos are on or off. It's tied to a TMDbHelper setting which needs to be either on or off to serve the cropped logos. It's not really suitable to being flipped continually.

**Comment by adamosborne83** [comment]
No worries, thank you for the reply, only reason I don't leave clear logo on like it was in Auramod, is that it kills my ocd that it can sometimes take a moment to load, or that it resizes itself.

Anyway, thanks again.
