### ISSUE TITLE
[Feature] Vocal search

### ISSUE THREAD

**Issue by fana13** [jurialmunkey/skin.arctic.horizon.2#736]
### Skin section

Home Widgets

### Feature description

Vocal search on keyboard for example, when clic on search field

### Why is this feature needed? Please justify and explain.

It will be great to have a vocal option for search 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is not something a skin can do. Voice recognition needs to be supported by kodi

**Comment by swazen** [comment]
+1
Have juste create issue for roadmap in [xbmc git](https://github.com/xbmc/xbmc/issues/22661)

**Comment by swazen** [comment]
Solved!!!
You must long press ok button in the search field for voice dictation work's !!!!

**Comment by fana13** [comment]
Unfortunatly it's not working on Nvidia Shield.
A message appear, not enough permission...
