### ISSUE TITLE
Kodi 20 Crash

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#737]
### Skin section

Home Widgets

### Current Behavior

Hi Jurial,  I trust you're well.

I have sporadic crashes on K20.
I am using a FC 3rd Gen. 
Just so you know I have also given both kodi logs to the Umbrella Dev too, as I know he recently removed all element tree from the addon.
So i am not saying this is a 'YOU' issue, just it might give you some info that could be relevant?

I have resolver disabled too.

### Expected Behavior

Not to crash on selecting movies

### Steps To Reproduce

Movies with widgets on AH2

### Screenshots and Additional Info

https://paste.kodi.tv/afosarotus

Https://paste.kodi.tv/eturotumub

Https://paste.kodi.tv/ladukejagi

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Do you have crash logs with stacktraces? 

Standard logs wont give much information about a crash and it could be for any variety of reasons. Need a stacktrace (sometimes called backtrace) from the CRASH log to have any chance of determining the cause of a crash.

I'm not familiar enough with android to know if it generates those or how to get them on that platform but that's the only thing that's going to give useful info in the case of a crash.

**Comment by jurialmunkey** [comment]
Also tell those addon authors they can easily get their addons compatible with nexus infotag requirements using script.module.infotagger

It's made by me but is available on official repo. Simplifies the conversion process and will get rid of a lot of that log spam
https://github.com/jurialmunkey/script.module.infotagger

**Comment by adamosborne83** [comment]
Going to close for now, as I will download nightly kodi to see if that fixes.
If I am still having significant errors I will do as requested. 

Dev said thanks for the above link too.
