### ISSUE TITLE
[Feature] Episode scroller controlled by native addon

### ISSUE THREAD

**Issue by TechXXX** [jurialmunkey/skin.arctic.horizon.2#739]
### Skin section

Home Widgets

### Feature description

Hi, not sure if this is possible or easily achievable but could the episode scroller be tied to our main addon in the same fashion the AH2 search can be tied to our main addon? (see reddit post below): 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/211279184-41e03650-20fb-4adf-9a24-096f290d39a6.png">

https://www.reddit.com/r/Addons4Kodi/comments/zpyrpr/replace_ah2_search_with_umbrella_or_fens_search/

### Why is this feature needed? Please justify and explain.

Couple reasons for this. First and foremost reason being speed/time, the tmdb helpers' 'building player dialogue' considerably slows down starting the next episode especially on low spec devices. It also seems to break a4ksubs autosearch feature. 

p.s. I would have mentioned the context menu but that seems to have disappeared in episode view (umbrella-widget), i.e. in episode view I can't access any context menu anymore. Unrelated bug...or feature?

### Screenshots and Additional Info

can't access context menu here: 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/211284249-fc1185ae-390f-464d-aad8-cb1e820f26c8.png">

19.4 - all addons latest version.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The current playlist queue is displayed first.

The tmdbhelper based playlist is only displayed as a fallback if there is no queued items

Ask the addon author to queue the up next episodes on playback.

**Comment by TechXXX** [comment]
ok, I'll see what the addon dev has to say about this, thanks for the feedback, appreciate it.

**Comment by TechXXX** [comment]
Got this response from Umbrella's dev, I think what he's saying is that there's no queuing when autoplay isn't enabled...but when autoplay is enabled I wouldn't need to use the episode selector. 

https://github.com/umbrellaplug/umbrellaplug.github.io/issues/190

**Comment by umbrellaplug** [comment]
Just wanted to pop in and let you know I'm watching this issue from my side as well. If there's something I can be doing on my side to help please let me know, but it seems the user is trying to avoid using tmdbhelper when launching from a tmdbhelper widget, which I do not know a way around.

**Comment by jurialmunkey** [comment]
The widget always uses the current queued playlist. 

It is only filled from tmdbhelper if the queue is empty.

If your addon queues items then that queue from your addon will be displayed there

From the sounds of things he wants the queued items from your addon to provide a source select rather than auto playing.

That's an option that the addon would need to provide.

**Comment by umbrellaplug** [comment]
I only queue up playlist if they have a setting turned on for continuous playback.

"If your addon queues items then that queue from your addon will be displayed there" That's the info I was missing. Thanks

Obviously this user wants that playlist built either way.

I will need to think on this, because I would need to stop kodi from auto playing the next item on the playlist in this scenario.

**Comment by jurialmunkey** [comment]
I think you can still autoplay if you use setresolvedurl() - just route your playback to whatever method allows selecting a source and then pass the source selected to setresolvedurl and it should work.

That's the point of setresolvedurl - to do some other work to decide (resolve) the url to be used for playback before giving it to kodi
