### ISSUE TITLE
Bug - black screen

### ISSUE THREAD

**Issue by alKODIque** [jurialmunkey/skin.arctic.horizon.2#74]
@jurialmunkey  🙃

I haven't seen a reported issue on this, hope I don't double post :P
I have a bug when playing trailers: I have to switch to full screen mode otherwise I have a black screen in the windowed view.
Here is a video of what it looks like.
(I also attach my log, in case it can help)
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8843365/kodi.log)

https://vimeo.com/717445723

**Comment by jurialmunkey** [comment]
Not sure what the cause is yet but see thread linked above
