### ISSUE TITLE
[BUG] fanart not respecting blur and not changing to correct library item

### ISSUE THREAD

**Issue by reitenth** [jurialmunkey/skin.arctic.horizon.2#740]
### Skin section

Home Widgets

### Current Behavior

im stuck on the same fanart for every series unless i go into the seasons where it correctly shows series fanart. it also has a black background instead of using the blur setting enabled.

### Expected Behavior

change fanart to correct series and use blur.

### Steps To Reproduce

using jellycon, matrix 19.5, and wifi. started happening a week ago on both matrix and nexus and multiple reinstalls.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Debug log?

**Comment by reitenth** [comment]
https://paste.kodi.tv/celanixiju.kodi

**Comment by jurialmunkey** [comment]
You've got a ton of jellycon errors that log. They all relate to a method called `serve_image` so I'd expect that is the cause of your artwork not working.

You'll need to speak to the jellycon author about these errors. They aren't skin errors.
