### ISSUE TITLE
[BUG] overlap with multiple widgets on home screen

### ISSUE THREAD

**Issue by reitenth** [jurialmunkey/skin.arctic.horizon.2#742]
### Skin section

Home Widgets

### Current Behavior

there is currently a overlap on the bottom of the home screen with multiple widgets. 

also the arrow gradient is still there if u have only one widget which looks quite bad. 

### Expected Behavior

no overlap and ability to remove the gradient arrow at the bottom of the home screen. 

### Steps To Reproduce

have multiple home screen widgets

### Screenshots and Additional Info

![205563961-f7cbaffd-04ca-49f8-9f7b-4f8e0e3eb3d0](https://user-images.githubusercontent.com/94771708/211556584-f36a7cc3-1ff4-41d8-b317-089f46524d3e.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is intentional. It shows that you have more items to scroll down to.

**Comment by reitenth** [comment]
i dont have more items to scroll down though. it looks bad in general, but at least, shouldnt be there if you only have one widget.

**Comment by jurialmunkey** [comment]
I can literally see another widget below in your screenshot.

**Comment by reitenth** [comment]
second line of my text, "also the arrow gradient is still there if u have only one widget which looks quite bad."

do u need me to get a screenshot with only one widget so you can see?

also appears others dont particulary like the gradient.

https://www.reddit.com/r/Addons4Kodi/comments/109bg9o/ah2_customization_removing_black_shadow_at_bottom/
