### ISSUE TITLE
[BUG] Scrolling Issue in Information Dialog

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon.2#744]
### Skin section

Video Info Dialog

### Current Behavior

I'm seeing a strange issue when scrolling through the widgets at the bottom of the information dialog.

If you try to scroll down, in order to focus a widget which is loaded, it seems that if the _next_ widget hasn't loaded yet, there is a hitch in the scrolling, and the widgets get "unaligned". This seems to happen for both movies and TV shows.

### Expected Behavior

Smooth scrolling, even on widgets which aren't loaded, but especially on widgets which are.

### Steps To Reproduce

1. Open the Information dialog on any item.
2. Scroll down to open the "recommendations" widgets.
3. Continue scrolling, trying to scroll down faster than widgets can load.
4. This should occur if you scroll down to a loaded widget, which does not have another loaded below:
```
Focused widget  <-- shift focus downward _from_ this one
Loaded widget   <-- _to_ this one
Loading widget
```

### Screenshots and Additional Info

I made a short screen capture: https://youtu.be/S_wNl46EnB8

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Can you disable YouTube from Recommendations
`Skin Settings > Details > Customise Recommendations > Youtube`

I think that's stealing focus when you move down because you don't have it installed.

**Comment by jurialmunkey** [comment]
Closing as there's not much I can do about this unfortunately. My only option would be to prevent navigation entirely until all the lists load, which I doubt is desirable.
