### ISSUE TITLE
[Feature] Full Info on search results

### ISSUE THREAD

**Issue by hobbit200** [jurialmunkey/skin.arctic.horizon.2#745]
### Skin section

Other

### Feature description

I have enabled the Expanded Information option in search menu, but I only see plot information in the results. 
It whould be very usefull to be able to choose between plot and full information, like we can choose in widgets.

### Why is this feature needed? Please justify and explain.

To be able to have a similar appearance in every part of the skin.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Not possible due to limitations of how the search window works. Results in unusual behaviour

**Comment by hobbit200** [comment]
Thank you for your answer and for the wonderfull skin you created.
