### ISSUE TITLE
[BUG] Sporadic crashes while navigating through and selecting items in custom hubs

### ISSUE THREAD

**Issue by iampritesh** [jurialmunkey/skin.arctic.horizon.2#749]
### Skin section

Other

### Current Behavior

Hi Jurial,

I've been experiencing a few crashes, this is one I've been able to reproduce successfully.  I open the Fen info screen of a movie in a custom hub, select a trailer to watch, and when I stop the trailer, Kodi will crash 50% of the time.

### Expected Behavior

To return to the Fen info screen after stopping the trailer.

### Steps To Reproduce

1. Set up a custom hub with nodes pointing to Fen folders
2. Open Fen's information screen on a movie in the custom hub
3. Watch a trailer for a few seconds
4. Stop the trailer
5. If no crash then try again with another trailer

### Screenshots and Additional Info

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/10415300/kodi.log)
Using Kodi 20 RC2 on an Nvidia Shield Pro TV (2019)

Thanks so much for creating this skin!

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Need a debug CRASH log with stacktrace to be able to determine anything about a crash. 

Sounds like a plugin issue rather than a skin issue though. Do you still get a crash with that plugin disabled?

**Comment by iampritesh** [comment]
Thank you very much.  Disabled reuselanguageinvoker and don't seem to be getting those crashes any more.  Thanks again!
