### ISSUE TITLE
[REQUEST] bring back an option to disable UP for SUBMENU on homescreen

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#75]
It's rather a small thing, but I found that particular option very useful in AH1.
I am not a fan of non-intuitive shortcuts, such as the one that requires user to press UP to open submenu BELOW the menu item.
For me a much better solution is to set SetFocus(302,0,absolute) action for menu items.
Still, I know some other people like it the way it is. 
An option in skin-settings would please everyone, I guess.

**Comment by ShibajiCh** [comment]
Thank you!
