### ISSUE TITLE
[BUG] Poster-style Fullscreen widget label doesn't get cleared when scrolling down

### ISSUE THREAD

**Issue by OneAngryMan** [jurialmunkey/skin.arctic.horizon.2#750]
### Skin section

Home Widgets

### Current Behavior

Hi,
I've got my widgets set up as follows:
1. Poster-style Fullscreen widget
2. Text-style widget ("Expand info" not available for that style)
3. Poster-style widget with "Expand info" set to full

"Expanded widget style" is set to Fullscreen. Widgets 1 + 3 display their label in the top left corner when focused, which is the way it's supposed to be. However, when scrolling down from widget 1 to widget 2, the label from widget 1 does not get cleared. It should be replaced by the category name, as it happens when scrolling up from widget 3 to widget 2. The attached screenshots should clarify the issue. It's a minor thing, but once you see it, you can't stop noticing it. Related to #445.

### Expected Behavior

Clear Fullscreen widget label when focusing widget (not expanded) below.

### Steps To Reproduce

1. Set poster-style Fullscreen widget
2. Create text-style widget below Fullscreen widget
3. Scroll down

### Screenshots and Additional Info

![Screenshot (453)](https://user-images.githubusercontent.com/83606678/212440672-832bfa07-3ec5-4064-bdba-e2f31dfb2c6e.png)
![Screenshot (454)](https://user-images.githubusercontent.com/83606678/212440673-312a871b-1a7a-4765-a8ae-0f8167a4f50d.png)
![Screenshot (455)](https://user-images.githubusercontent.com/83606678/212440667-47fc92c0-ef2d-4334-a9b4-56aba893e03b.png)
![Screenshot (456)](https://user-images.githubusercontent.com/83606678/212440668-9ef3c030-dd27-4ff6-a160-b532bd5d6fbb.png)
![Screenshot (457)](https://user-images.githubusercontent.com/83606678/212440670-4f9c2e70-da26-47f2-ab60-a0319a48f1cf.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah yep, it's not clearing the property properly. Easy fix.
