### ISSUE TITLE
[Feature] Fanart as background image & show more

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon.2#751]
### Skin section

Home Widgets

### Feature description

Hi mate, hope you are doing well.
1. Is it possible to have Fanart of a movie poster that I will select in my home widget appear as the current background image?
2. I am unable to find the 'Show More' option against my widgets, where in settings it is available?

### Why is this feature needed? Please justify and explain.

1. Will be nice to have fanart appear as background image depending on my current selection.
2. I can scroll to the very right and click on 'Show More' to view all movies added to my list added as widget, else I would have no option to see all the movies that are part of my list and play it.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
1. Disable simple background to see fanart (assuming you have background setup to use Fanart or Flixart of course!)
`Skin Settings > Appearance > Customise Appearance > Simple background` 

2. `Skin Settings > Menus > Limited widgets have "more items" object`

**Comment by onlytanmoy** [comment]
Thanks for the steps mate.
1 is all good now.
2 is still not working, can't see that 'Show more' options at the end, please see screen capture https://streamable.com/obk2k9

**Comment by jurialmunkey** [comment]
It only shows the item if you set an artificial item limit on the widget -- for example, you have 100 items in your library and you show a widget of all items sorted randomly but set the widget item limit to be 20. Then you'll get a "show more" item which will take you to the full list.

It won't do anything for a plugin where there's a "next page" (which seems to be what you're trying to do here considering it is a watchlist). That's up to the plugin to determine if the "next page" item shows.

If you're using TMDbHelper, then it has its own setting to determine if next page items are shown for widgets. For other plugins I can't do anything.
