### ISSUE TITLE
[Feature] More genres in infoline

### ISSUE THREAD

**Issue by SirRickie** [jurialmunkey/skin.arctic.horizon.2#752]
### Skin section

Video Info Dialog

### Feature description

I wonder if the following is possible in your wonderful skin : in the infoline, there is only 1 genre displayed (see screenshot, as an example, there is only the genre "mystery", while for this movie there are also other genres).  Is it not possible to display all the genres in the infoline (as in Aura) ? I don't think there is a view which displays all the genres. Tnx.

### Why is this feature needed? Please justify and explain.

When browsing through a movie section (let's say a Trakt list in TMDBH) and I want to add some movies to my watchlist, I always look at the genres as I don't like, let's say, comedy or documentary. When I browse I skip then the comedy ones. But as there is only 1 genre displayed, all the comedy ones are not visible to me.

### Screenshots and Additional Info

![PXL_20230115_101544760 MP](https://user-images.githubusercontent.com/60318531/212535972-556caf01-2e7c-4676-9c00-409e4ddb2665.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Unfortunately there really isn't enough room for more than one rating.

If you use Landscape viewtypes you can see the full genre as the subline.
