### ISSUE TITLE
[Rating] Portugal Rating

### ISSUE THREAD

**Issue by Rootzpower** [jurialmunkey/skin.arctic.horizon.2#753]
### Skin section

Other

### Feature description

Hello

It's possible to add rating from Portugal?

If help to implement is the info for age rating of Portugal:
https://en.wikipedia.org/wiki/Inspec%C3%A7%C3%A3o_Geral_das_Actividades_Culturais

### Why is this feature needed? Please justify and explain.

I see there are several ratings from others countries but not Portugal

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I use the classification pack by wyrm and unfortunately there aren't any icons for Portugal
https://github.com/wyrm65/resource.images.classificationicons.colour/tree/master/resources

**Comment by Rootzpower** [comment]
I made a request for him.
Maybe he replies
Thanks

**Comment by Rootzpower** [comment]
Talked with him and files are already upload 👍

**Comment by jurialmunkey** [comment]
Closed by #771
