### ISSUE TITLE
Watched items

### ISSUE THREAD

**Issue by cslogg** [jurialmunkey/skin.arctic.horizon.2#755]
### Skin section

Home Widgets

### Feature description

In widgets  the ability to hide “watched items”

### Why is this feature needed? Please justify and explain.

Makes widgets using much more pleasureable.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skins cannot control this behaviour.

Use a smart playlist with the rules you want for your library.

For plugins you need to ask the plugin author.
