### ISSUE TITLE
[BUG] Can't play videos with comma in path when using combined view

### ISSUE THREAD

**Issue by Kantana** [jurialmunkey/skin.arctic.horizon.2#756]
### Skin section

Library Views

### Current Behavior

When using a combined view, in this case "Landscape Combined", and trying to play an episode where there is a comma in the path, I get the error "One or more items failed to play." This only happens on shows where the title includes a comma, for example "Ijiranaide, Nagatoro-san".

### Expected Behavior

Episode plays.

### Steps To Reproduce

1. Go to a TV show with a comma in the file paths
2. Select a combined view, in this case "Landscape Combined"
3. Select an episode and try to play it
4. Episode does not play, but instead triggers an error saying "One or more items failed to play."
5. Select a non-combined view, e.g. "Landscape List", and the same episode plays just fine.

### Screenshots and Additional Info

Relevant lines in log from when the issue occurs. As you can see, the path cuts at the first comma in "Ijiranaide, Nagatoro-san".
The path should be "smb://10.0.0.20/Media/Anime/TV Series/Ijiranaide, Nagatoro-san/Season 2/Ijiranaide, Nagatoro-san - S02E03.mkv"

2023-01-16 19:17:26.061 T:15228    INFO <general>: VideoPlayer::OpenFile: smb://10.0.0.20/Media/Anime/TV Series/Ijiranaide
2023-01-16 19:17:26.063 T:34740    INFO <general>: Creating InputStream
2023-01-16 19:17:26.065 T:34740   ERROR <general>: CFileCache::XFILE::CFileCache::Open - <smb://10.0.0.20/Media/Anime/TV Series/Ijiranaide> failed to open
2023-01-16 19:17:26.065 T:34740   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [smb://10.0.0.20/Media/Anime/TV Series/Ijiranaide]

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Can you test latest version (v0.7.29)?

I think it should be fixed by this commit: 85d6243453ab3d62d808a8bc88d6f21d2e2a13a0

**Comment by Kantana** [comment]
I can confirm the issue is fixed. Both shows I tested with a comma in their names are playing just fine with combined view.
Thank you so much!
