### ISSUE TITLE
[Feature] Bigger Video Player Buttons 

### ISSUE THREAD

**Issue by rowel07** [jurialmunkey/skin.arctic.horizon.2#758]
### Skin section

Fullscreen Video OSD

### Feature description

Can you make an option where we can change the video player buttons bigger? Just like in expanded widget where can set it to simple or fullscreen.

### Why is this feature needed? Please justify and explain.

Sometimes I watch TV Shows using my phone. But when I'm trying to pause the video, i accidentally touch the progress bar. AH2 to support all devices is great and a little UI optimization for touchscreen devices would be AMAZING!

### Screenshots and Additional Info

![IMG_20230117_223739](https://user-images.githubusercontent.com/30220813/212932512-d4e1f769-2859-4cf4-9f64-59c681010c43.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Rootzpower** [comment]
Yeah sometimes it's a bit confuse.
Bigger buttons, other layer color or central icons may help, i think.

**Comment by heimdall47** [comment]
The option to change the control buttons would be great. Really liked the ones in Aura

**Comment by jurialmunkey** [comment]
Sorry an option for this is too difficult to manage and adds too much complexity to OSD code.

Primary focus of the skin is as a 10ft interface and touch concerns are secondary.
