### ISSUE TITLE
[BUG] The Plot is missing some letters with RTL languages in Kodi 20

### ISSUE THREAD

**Issue by psp2111-ADSLGATE** [jurialmunkey/skin.arctic.horizon.2#765]
### Skin section

Home Widgets

### Current Behavior

After Updating to Kodi 20 I notice some Plot is starting out of window frame.
it is affecting the plot in both Widgets and Info Dialog, but you can find it more often in this widget view "Pictures"
and it happening only with Arabic language, most likely other RTL languages is also affected

Kodi 20

![Screenshot_53](https://user-images.githubusercontent.com/80945174/213878382-8e2ecf13-f3a2-40ec-8920-afd7a964f583.png)

Kodi 19

![Screenshot_55](https://user-images.githubusercontent.com/80945174/213878403-0200ed70-03f0-4c5d-9aa3-a65306b2442b.png)

### Expected Behavior

The Plot text should show up like Kodi 19

### Steps To Reproduce

Change the skin font to NotoRoboto Arabic / Hebrew
Change the Widget view like the pictures
Change the region to Arabic Saudi Arabia within TMDb Helper settings.
Clear TMDb Helper Cache.
look for the bug.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I'm sorry I don't really understand the issue. Are you saying the text box is wider in nexus?

Note that depending on background settings plot will be wider (shorter for flixart)

Double check that you have same appearance background settings in both versions.

**Comment by jurialmunkey** [comment]
Oh I see now - a few characters are chopped off the edge. That'd be a kodi rendering problem with bolded characters - not much the skin can do about it.

My guess is the changes to tightly pack the font texture atlas in nexus mean that kodi is not properly calculating width for bolded rtl text.

**Comment by jurialmunkey** [comment]
I can reproduce in Estuary so it is definitely a Kodi bug rather than a skin bug. Not much else I can do about it directly, so I'll close this issue and progress can be tracked in the issue I reported above on xbmc github.
