### ISSUE TITLE
Constant widget scrolling for OLED screens. 

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.horizon.2#768]
### Skin section

Home Widgets

### Feature description

Screen burnin is a major factor on oled tv's. AH2 focuses the widgets ie screen that is being displayed at the time. I have a family that do not understand the damage this can do to a £2k plus tv screen and they constantly leave the screen showing a full screen of what ever movie or program widget they where looking at before leaving the tv to do what ever else. The last skin I came from TBM had this feature which really helps to solve this issue. 

But to have the AH2 focus all the time instead of when an item is clicked really hurts especially when I'm not around to police the users.

### Why is this feature needed? Please justify and explain.

This a focus or not button should definitely be added to cope with screen burnin on OLED tv panels. A constant image is not at all good for these panels and should be moving at all times to stop pixel damage. 

See a shot of a previous TV i have now sitting in the garage because of to much daytime TV my Mrs and the kids just leave the TV and move onto other things. This was done in lock down. Yellow screen highlights the burnin. I love AH2 but don't want to go back to buying another TV since I've not long replaced this damaged unit.
![20200802_032513](https://user-images.githubusercontent.com/97023369/214222181-f25019b1-fd0d-42c6-a33b-3ec274d45bc3.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Isn't this exactly what a screensaver is for?
Interface Settings > Screensaver

I personally use drinfernoo's "Arctic Mirage" screensaver (on my repo) which allows displaying a widget fanart slideshow as a screensaver.

I've deliberately skinned it for AH2 with avoiding burn-in in mind. It uses a pan-and-scan Ken Burns style effect for the fanart background and the info overlay alternates sides with each item in the slideshow.

![Screenshot 2023-01-24 173900](https://user-images.githubusercontent.com/4618719/214227393-b8bb8e7c-4400-4cb8-bb63-a260345bb148.jpg)

**Comment by DROIDshield** [comment]
Never really liked the screensavet idea and the last time I tried having a Xmas saver Kodi wouldn't pickup the file in its addon. 

I will look into yours after work and see how it fares against seeing scrolling widgets that could be clicked on at any moment to watch. Maybe im being a bit greedy but the alternative may be just as good if not better than my idea.

**Comment by jurialmunkey** [comment]
You can already set autoscrolling widgets. The problem is that all the other content will still be in the same spot (e.g. menus, info, clock etc) - so you'll get burn in there. The only real solution is a screensaver (or display auto power off).

I'm fairly confident that Arctic Mirage allows clicking the items (at least it did last time I tried to click it).

**Comment by DROIDshield** [comment]
Yes I already use the scrolling but as you said the screen that is showing is static.. but if the screensaver host click to play wow.. that will definitely do the job. I'll be on it soon as this working day is done.

**Comment by DROIDshield** [comment]
I've now added the screen saver pointed to TMDB trending movies and it does look good. It definitely doe's not suck up the system resources while running on the shield so this is great to mitigate any burn-in from static images. Have to say though I do have say I'm  not a fan of the pan effect but I guess I'll get used to it. Thanks again for the input.
