### ISSUE TITLE
[BUG] Constant crashes on MacOS 13.1/Kodi 20

### ISSUE THREAD

**Issue by CamilleHbp** [jurialmunkey/skin.arctic.horizon.2#769]
### Skin section

Home Widgets

### Current Behavior

I recently did a full clean install of Kodi 20 after the update got my setup to crash constantly. I use Kodi 20 on a MacOS 13.1 silicon.

The clean update works but is unstable. I think most crashes happen when exiting the settings and returning to the main menu.

It seems to be caused by your skin, as far as I could understand. Estuary does not seem to have that problem. I have joined one crash log, I can post more when it happens if you want.

Steps I did for the clean install:
1. Delete `~/Library/Application Support/Kodi` and complete remove Kodi with AppCleaner
2. Reinstall Kodi 20
3. Add the repositories (https://jurialmunkey.github.io/repository.jurialmunkey/ and another one for my player)
4. Install the last versions for all dependencies and add-ons
5. Set up my menus (only for stream players)
6. Exit the settings and admire a beautiful crash to desktop 😝 

The following error seems to come back a lot in the `kodi.log`, could it be any help to you?

```
2023-01-24 16:20:29.748 T:290483    info <general>: Loading skin file: /Users/camille/Library/Application Support/Kodi/addons/skin.arctic.horizon.2/1080i/script-skinshortcuts.xml, load type: LOAD_ON_GUI_INIT
2023-01-24 16:20:29.813 T:291669   error <general>: EXCEPTION: Non-Existent Control 111
2023-01-24 16:20:29.814 T:291669   error <general>: EXCEPTION: Non-Existent Control 309
2023-01-24 16:20:29.814 T:291669   error <general>: EXCEPTION: Non-Existent Control 310
2023-01-24 16:20:29.840 T:291671   error <general>: GetDirectory - Error getting /Users/camille/Library/Application Support/Kodi/userdata/library/video
2023-01-24 16:20:29.843 T:291671   error <general>: GetDirectory - Error getting /Users/camille/Library/Application Support/Kodi/userdata/library/music
2023-01-24 16:20:29.851 T:291671   error <general>: GetDirectory - Error getting upnp://
```

### Expected Behavior

I would like it not to crash so much. 😄 

### Steps To Reproduce

1. Use the skin
2. Edit a setting and come back to main menu
3. See a beautiful crash to desktop after a few minutes

### Screenshots and Additional Info

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/10491458/kodi.log)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Need a CRASH log with stacktrace to have any chance of telling you the cause of the crash.

Standard log won't tell you anything because when a crash happens the application is already exited so it can't log what it is doing.

Error messages in log can be ignored. They do not cause crashes.

Almost certainly this is an elementtree crash but I cant tell you without a stack trace.

**Comment by rowel07** [comment]
I also experienced this on Android. When changing view type, adding widget/submenu, etc. 

When I changing something I immediately go back to home before it crash to save it. Then open again doing the same thing until I finish customizing the skin.

I'm glad that I have access in android/data folder in my phone that makes it easier to customize this skin in my Android TV.

**Comment by CamilleHbp** [comment]
I will close the issue. I'm not using Kodi on anything else than computers so I've decided to switch to Stremio. It is far more stable because of its limited set of features, and works for my needs.
