### ISSUE TITLE
[Feature] Short Description

### ISSUE THREAD

**Issue by girkers** [jurialmunkey/skin.arctic.horizon.2#773]
### Skin section

PVR and Live TV

### Feature description

When looking through the TV Guide when viewing the information on the show, I would like to simply press the button to go to the show.

### Why is this feature needed? Please justify and explain.

Currently what you have to do is press the left arrow and then select switch to go to the TV program.

### Screenshots and Additional Info

![PXL_20230125_212502272 MP](https://user-images.githubusercontent.com/66195700/214695940-3d85dee8-4ca6-4d93-a96a-f8383b3b3a2a.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
https://kodi.wiki/view/Settings/Live_TV/Guide#Default_select_action
