### ISSUE TITLE
[Feature] Add IMDB Rating to the posters in widgets

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.horizon.2#776]
### Skin section

Home Widgets

### Feature description

The feature I am requesting is similar to this implementation
![image](https://user-images.githubusercontent.com/9439671/214787496-1c987074-5e2d-459b-b12a-8f9b398b300b.png)

Basically, showing a listitem property on the posters to easily detect the movies features, ratings, certificate, genre. 

### Why is this feature needed? Please justify and explain.

I understand the  Funiture in AH2 provide it all when you select the listitem, but having it shown would be nice especially in Wall view.

I proposing this as an option for the users, they can opt-in or opt-out anytime.

If you can direct me, I will try to do it. I added some details to AH2 furniture before, so I think I can try. Just point me to the right direct. Where to edit the views content, and how to add a toggle to the settings.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skin Settings > Details > Indicators > Ratings

**Comment by xyzfre** [comment]
This new feature looks AMAZING💯💯 thank you @jurialmunkey

**Comment by Mr-7mdan** [comment]
> Skin Settings > Details > Indicators > Ratings
@jurialmunkey 
Perfect as always. Thank you

**Comment by luckylukz02** [comment]
Been hoping for this for some time. How do you change the rating from TMDB to IMDB.

**Comment by jurialmunkey** [comment]
It uses whatever is set to listitem.rating

You need to change your library scraper to add imdb instead of tmdb ratings.

For plugins it is whatever the plugin sets. The skin cannot control what plugins or the library do.

**Comment by georgew21** [comment]
I wonder if it could possible to use metacritic from the themoviedbhelper?

**Comment by jurialmunkey** [comment]
> I wonder if it could possible to use metacritic from the themoviedbhelper?

No. It is not possible to modify the metadata of listitems. That is why all TMDbHelper metadata is *outisde* the listitem and only for the focused item.

**Comment by Mr-7mdan** [comment]
@jurialmunkey, Could point me out to a method of creating custom properties per item ? (I know it is almost not doable for listitem). 
I tried to understand TMDBHelper code but unfortunately couldn’t quite understand. I think you are using something called Json RPC. 
i just want to set a custom property via python script and then display it using XML window. 
Currently, I do it by setting window properties and $INFO tags in XML. It is a sluggish solution, I want something bound to the item itself. Your help is appreciated

**Comment by jurialmunkey** [comment]
@Mr-7mdan - Sorry I don't understand what you're attempting to do.

**Comment by Mr-7mdan** [comment]
@jurialmunkey, I was able to do the following :
1- Get the listitem Title and IMDB ID. `xbmc.getInfoLabel("ListItem.Title/IMDBNumber/TVShowTitle")`
2- Load some data (1st from cache, if not available from an API then add to cache)
3- Display the data in the furniture section of the VideoInfoDialog
  3.1- Set this data as a Window Properties using 
  `WindowID= xbmcgui.getCurrentWindowId()
  WID = xbmcgui.Window(WindowID)
  WID.setProperty('XYZ', " ABC")
  `
  3.2- Display this property in the XML using
  `$INFO[Window(home).Property(XYZ)]`
  
  3.3 Clear this property in the XML when unloading the XML 
`<onunload>ClearProperty(XYZ,Home)</onunload>`

The results achieved :
![image](https://user-images.githubusercontent.com/9439671/222947659-002f4823-536d-46b5-82b9-9183481bc1fd.png)

Now, this poses some issues:
1- The window property persists when loading another window from the VideoInfoDialog. Like recommendations for example;
![image](https://user-images.githubusercontent.com/9439671/222948154-4d77f288-f850-448d-b662-1f3cb97a9864.png)

![image](https://user-images.githubusercontent.com/9439671/222948170-27590628-180d-47ba-a95f-91b1d8089694.png)

Which results,, in displaying wrong information.
2- Cannot display this property in the Home screen (where the widgets are).
3- Sometimes, the clearproperty on the unload just doesn't work.

I am looking for a way to attach this data to the list item itself, so it can be displayed separately from the window. Like the furniture items you've added "Metacritic, EmmyAwards etc"

What I tried and failed :
1- I was able to set a property to the listitem and then recall it via getProperty. and it works in the python script and I find the result in the log as expected.
`    name = xbmc.getInfoLabel("ListItem.Title")
    li = xbmcgui.ListItem(name)
    li.setProperty("PG","hi")
    logger.info(li.getProperty("PG"))`
2- When I use the property in XML, I get an empty string.
`$INFO[ListItem.Property(PG)`

Sorry about my English and my mediocre programing, I am just trying to make something in my free time. Appreciate your help

**Comment by jurialmunkey** [comment]
> I am looking for a way to attach this data to the list item itself

You cannot do this. Kodi does not allow you to modify listitems already on screen.

**Comment by Maiskolf** [comment]
> You need to change your library scraper to add imdb instead of tmdb ratings.

@jurialmunkey Could you provide a bit more detail on how to do this? Under Skin settings > Details > Customise ratings, I have selected multiple rating sources. When enabling "Ratings" under Customize indicators, the rating shown is always the default "Kodi Star" rating. Is there any way to change this to IMDB?

Thanks in advance for all your efforts.

**Comment by jurialmunkey** [comment]
You'd need to ask the addon author. It has nothing to do with the skin or tmdbhelper. It is whatever rating the addon sets internally.
