### ISSUE TITLE
[Feature] Possible PVR OSD improvements

### ISSUE THREAD

**Issue by chcore** [jurialmunkey/skin.arctic.horizon.2#778]
### Skin section

Fullscreen Video OSD

### Feature description

I would like to raise a couple of issues with the PVR OSD:

1. The main title is truncated too early. In my screenshot there is enough room for perhaps another word and a half
2. The title, channel, channel number and channel name are displayed twice in different places. I think it would be great to remove the circled elements in the screenshot below to slim it down a little (or maybe an option to remove them)
3. The OSD currently shows up to 2 lines of plot info. When there are exactly 2 lines of plot info, the text scrolls for no reason. It should not scroll, as there is enough room to display it all at once

### Why is this feature needed? Please justify and explain.

Hopefully to make the PVR OSD a little nicer to use.

### Screenshots and Additional Info

![image](https://user-images.githubusercontent.com/83099052/214818712-847fa3d0-41ac-4ac1-972b-877052b6e350.png)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Outdated by a7bafc3
