### ISSUE TITLE
[BUG] episode context menu poster

### ISSUE THREAD

**Issue by A3006B** [jurialmunkey/skin.arctic.horizon.2#779]
### Skin section

Library Views

### Current Behavior

When opening an episodes context menu, the season poster in the foreground pulls from tmdb instead of local season poster artwork

### Expected Behavior

The season poster in the episode menu should use local artwork if available

### Steps To Reproduce

Go to episode, open context menu, season poster in foreground pulls from tmdb instead of showing local artwork

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
TMDbHelper issue. Fixed in next release of TMDbHelper.
