### ISSUE TITLE
[BUG] "Focus buttons when opening info dialog" doesn't work for all addon info dialogs

### ISSUE THREAD

**Issue by OneAngryMan** [jurialmunkey/skin.arctic.horizon.2#780]
### Skin section

Video Info Dialog

### Current Behavior

Hi,
I've turned on the "Focus buttons when opening info dialog" setting. This works very well and reliably for video info dialogs, but not for addon info dialogs. When opening addon info dialogs from the addon browser, the menu buttons get focused by default for some specific addons, like for example all my repository addons, but for some other addons the buttons never get focused automatically (e.g. TMDb Helper, Gismeteo, Fen, Version Check [the default Kodi one]). The behavior for each addon also seems to be fixed, so it never works for TMDb Helper but always for the jurialmunkey repo. 
After a lengthy investigation, I eventually figured out that changing the "5000" value in [line 126 of the the DialogAddonInfo.xml](https://github.com/jurialmunkey/skin.arctic.horizon.2/blob/main/1080i/DialogAddonInfo.xml#L126) file to "4000" seems to fix the issue. Somehow. Would be great if you could look into this. 

### Expected Behavior

Always focus the buttons in addon info dialogs when "Focus buttons when opening info dialog" is turned on. 

### Steps To Reproduce

turn "Focus buttons when opening info dialog" on - navigate to addon browser - open info dialogs of random addons

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yeah there's an override hardcoded into kodi which forces focus to particular controls in addon info regardless of what the skin does.

I'll have a look soon as there are a couple of tricks to workaround it that I think should work.
