### ISSUE TITLE
[Feature] Include <news> changelog tag in addon.xml

### ISSUE THREAD

**Issue by francis-robert** [jurialmunkey/skin.arctic.horizon.2#781]
### Skin section

Other

### Feature description

Been reading about addon development and came across the [<news> tag](https://kodi.wiki/view/Addon.xml#%3Cnews%3E). It seems to be used to display the changelog of the incoming update by the addon system.

Here's the excerpt from the linked page:

```
<news>
Note: Used in Kodi v17 Krypton and later only. Older versions are forward compatible.

The <news> element should contains a simple description of the major changes made to the add-on (new functionality, big fixes, etc). This is displayed in the Kodi addon installation/update system. (In the author's opinion, too many add-ons skip this piece of information, making it difficult for users to determine whether a particular problem that they may have been having has been fixed or not.) Please keep it short (it's limited to 1500 characters); you might want to only include the changes for the last version here.

Here is an example:

<news>v0.1.2  (2014-01-15)
- Added notification for Ubuntu users checking through apt command</news>
```

### Why is this feature needed? Please justify and explain.

I believe that this would be helpful for users to quickly glean what may be included in a particular update.

Often times, new features can be released such as #358, #271, etc. but there are no existing means for a user to identify that these are included in a release without either navigating the skin settings and doing the mental diff yourself of every single setting and option, or, by looking through the changeset of the releases in the GitHub releases.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It's too much extra work to constantly be updating the news tag. I'd rather just push commits with appropriate messages and spend my time adding features / fixing bugs than worrying about whether the news tag is up to date - that's something for official stable releases where updates might be months apart, not alpha where I'm often updating daily.
