### ISSUE TITLE
[Feature] Extra Infos

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon.2#782]
### Skin section

Home Widgets

### Feature description

Happy Sunday mate @jurialmunkey 
The inclusion of Reviews / Comments is a nice touch.
In the same line can you please also include the below extra info from IMDb?
- Trivia
- Blunders
- Parental Guidance

Please see screen record using Fen as a widget https://imgur.com/sBRZmDd

### Why is this feature needed? Please justify and explain.

I prefer having my widgets created from TMDb Helper so will be great to have this feature built into my favourite AH2 skin.

### Screenshots and Additional Info

Will be good to have a button named 'Extras' and placed on the left panel as seen in this screenshot
https://imgur.com/MYeFC07
Clicking that Extras button will reveal all 4 sections:
- Reviews / Comments
- Trivia
- Blunders
- Parental Guidance

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
IMDB api costs $400000 a year for nonpersonal access to that data. I'm not exaggerating - see marketplace https://aws.amazon.com/marketplace/pp/prodview-nzspap6vaousm?sr=0-4&ref_=beagle&applicationId=AWSMPContessa#offers 

Scraping it off their website is against their terms of use and is a violation of the copyright.

**Comment by onlytanmoy** [comment]
Ok got it, thanks for the clarification @jurialmunkey 

On a diff note, is there a setting currently in the skin to switch off the label names in the Home menu and instead just have the icons displayed alone?

**Comment by jurialmunkey** [comment]
Yeah "menu style" set to "iconic" in skin settings.

**Comment by onlytanmoy** [comment]
Smashing! thanks mate.
