### ISSUE TITLE
[Feature] Genres in expanded info

### ISSUE THREAD

**Issue by Dragoopai** [jurialmunkey/skin.arctic.horizon.2#784]
### Skin section

Home Widgets

### Feature description

When I configure a widget which sets "Expand information" to "full" I would like to also see the genres above the widget (maybe underneath the plot).

### Why is this feature needed? Please justify and explain.

I use the widget on the homescreen to explore my library. Without the genre info it is hard to know if it's the worth to take a deeper look. Without this feature I always need to go into the information of the show/movie, then get the detailed info. That is at least for me a bit cumbersome.

### Screenshots and Additional Info

I would also appreciate if the genres could be enabled for the Poster Row view.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Dragoopai** [comment]
@OneAngryMan Yes I have.

**Comment by Dragoopai** [comment]
Maybe it is also good to mention that when I go into the information view of a tvshow the genre will be displayed there.

**Comment by Liquidrag** [comment]
Mine shows up under the title.

**Comment by Dragoopai** [comment]
![20230130_153318](https://user-images.githubusercontent.com/123862271/215506816-170d36c9-7772-4da7-9d4e-d8798ab32d53.jpg)

Hope that is good enough. I would like to have the genres somewhere left to the plot.

**Comment by jurialmunkey** [comment]
TMDb API blocks adult items from search results so it is not possible to lookup genres from TMDb for your hentai.

Genres work perfectly fine for non-adult items.

![Screenshot 2023-02-01 013746](https://user-images.githubusercontent.com/4618719/215790285-5e9c9d3d-42a7-4c91-b7cb-840029132ee9.jpg)

**Comment by Dragoopai** [comment]
I've scrapped them on my own. (In the nfo files). In the information section of the TVShow is see the genres. Is it maybe because there are to many?... around 6 or something.

**Comment by jurialmunkey** [comment]
Kodi does not have a way to split genres so it needs tmdbhelper. If tmdbhelper cannot lookup the item online then it never gets to the point of splitting the genre.

There's not enough room to display more than one genre in the infoline which is why tmdbhelper is required.

**Comment by Dragoopai** [comment]
@jurialmunkey Thanks for the reply. Sorry for asking silly questions but how are my genres in my nfo-files related to the tmdbhelper? My assumption was I put genres in my nfo-files, then I import everything into Kodi and the skin will then just show the genres.

**Comment by jurialmunkey** [comment]
The space for the genre in the infoline (like my screenshot) is only big enough to accomodate a single genre.

Kodi often has multiple genres together e.g. "Action / Adventure / Comedy / Sci-Fi". That will be too long. Kodi has no way to split the genres into individual genres and there is no way for the skin to determine how long the genre line is.

That means some other solution needs to be used. In this case TMDbHelper does some additional work to split the genres into single items e.g. "Action" "Adventure" "Comedy" "Sci-Fi".

That allows the skin to display the first genre "Action" which will fit.

Problem is that if TMDbHelper cannot find the item on TMDb then it will never reach the stage of manipulating the genre and splitting it. It just provides a blank.

**Comment by Dragoopai** [comment]
Is it maybe possible to implement an option which puts *all* genres underneath the info line? I saw that on Aeon Nox Silvo.

**Comment by jurialmunkey** [comment]
No there is not enough room. All I'll get then is complaints that the plot is only one line high.

**Comment by Dragoopai** [comment]
Totally understandable! What about an option "show all genres" and dump them out like they are? I mean I have so much space left on the right. I think it would still fit.
