### ISSUE TITLE
[Feature] Set Genres Images Folder

### ISSUE THREAD

**Issue by Dragoopai** [jurialmunkey/skin.arctic.horizon.2#788]
### Skin section

Other

### Feature description

It would be nice to be able to select folder (smb would be nice) where the images for the genres are stored.

### Why is this feature needed? Please justify and explain.

As an Android user it is hard so manipulate internal Kodi file. With this solution I would be able to have my own genre images.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
In next release
Skin Settings > Appearance > Custom genre icon folder

Must be png that match genre label.
