### ISSUE TITLE
[BUG] Search Not Working 

### ISSUE THREAD

**Issue by redvegas** [jurialmunkey/skin.arctic.horizon.2#789]
### Skin section

Home Widgets

### Current Behavior

The search bar just keeps loading infinitely 

### Expected Behavior

The search bar should show what I typed in from my library 

### Steps To Reproduce

Go to search bar
Search anything 
Nothing shows up 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Works fine for me. I can't reproduce this issue
