### ISSUE TITLE
[Feature] changeable submenu widget style

### ISSUE THREAD

**Issue by peat80** [jurialmunkey/skin.arctic.horizon.2#790]
### Skin section

Home Widgets

### Feature description

It would be nice if we could change the style of the submenu when it is used as homescreen widget.

At the moment when you add a submenu as home widget it always shows in the button style no matter what you set as style for the entry.

### Why is this feature needed? Please justify and explain.

More customizing options. At least it should be changeable to text only like when you use it as normal submenu.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Okay should allow setting as Text or Apps in addition to the standard Button now. Other styles like Poster or Lovefilm not possible for obvious reasons. I did think about Square but it was too much of a pain to manage without it being a breaking change.
