### ISSUE TITLE
[Feature] Show hint of next widgets

### ISSUE THREAD

**Issue by jweinr** [jurialmunkey/skin.arctic.horizon.2#792]
### Skin section

Home Widgets

### Feature description

A suggestion.

I believe this used to be the case earlier but it's not anymore.
Having a faded out sneak peak of whatever is below of your current widget/menu is super intuitive for navigation. Just like apple tv or Netflix do it.
Same for whatever is above.
It is more informative and intuitive than the small arrows currently used.

![PXL_20230125_015226558~2](https://user-images.githubusercontent.com/6373803/215654146-26c72fff-ab68-45d8-82bf-f9988e98686b.jpg)

### Why is this feature needed? Please justify and explain.

Make the skin more intuitive.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jweinr** [comment]
> Set expanded style to simple and you will see the next widget.

I see now, expanded view let's you see the footer in widget home screen, with the trade off of loosing the next widget preview.

Here's my humble take:
Any chance you'd consider settling for just one style for expanded widgets, simplifying your work and enabling the best of both worlds, applying some visual economy?

- keep widget name on top, and hide the menu name, as in current expanded view: no need to keep reminding users they're on movies or series menu once they already saw the name of the menu when they navigated into it, and the content of the menu explains by itself.
- next comes media name/clear art, year, PG rating etc, then comes awards: this is all relevant info for a person who's looking for something to watch (what's the name of the movie, what year is it, how long does it last, what kind of genre, can kids watch it, is the movie good based on awards ratings).
- next strip of movie boxes, no need to explain this one.
- next a sneak peak of the next widget to make navigation intuitive.
- get rid of the up and down arrows: the skin is vertical navigation, no need to remind it permanently with arrows. Having a sneak peak tells you two things: something is below (the function of the down arrow) and what's below has a name. The up arrow is redundant too, since you already had to be coming from top to bottom to begin with, and as a failsafe you can always press "back button" and be teleported to the top.
- get rid of the footer from the home screen: all the information presented to you in the footer is technical details which have no place on a home screen and only clutter, and belong to the movie/series/media detailed view once you click on it.

Think of this: imagine yourself shuffling through your physical collection of books/movies/games/concerts that are neatly stored on your bookshelf:
What do you wanna glance first and easily, what do you not need to see upfront, and what do you wanna see in more detail once you pull one of the movies off the shelf.

**Comment by jurialmunkey** [comment]
The options are already the simplest they can be - I personally dislike full expansion. I far prefer simple as consistent positioning of widget name is more important to me.

Simple retains a widget style view that allows adding additional title / plot / info above.

Full mimics the library view on the homescreen.

I wouldn't want to compromise either of these as I think they both have use cases that many users appreciate. The compromises you suggest would annoy several users and then I'm back to square one of having complicated fine grained options.
