### ISSUE TITLE
[BUG] Lovefilm shows KeyArt twice

### ISSUE THREAD

**Issue by PizzaPino** [jurialmunkey/skin.arctic.horizon.2#794]
### Skin section

Home Widgets

### Current Behavior

When simple background for widgets is not selected, you will see the artwork twice when using lovefilm. One time inside lovefilm and one time behinde lovefilm which looks a bit buggy. 

### Expected Behavior

I would suggest to enable simple background or blurred background art just for lovefilm. 

### Steps To Reproduce

1. Select lovefilm
2. Deselect simple background for widgets

### Screenshots and Additional Info

![image](https://user-images.githubusercontent.com/10676597/215774444-f4e77c6f-ff8a-4dc9-9612-0029f2c7ee03.jpg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Bindou01** [comment]
I don't know if it's possible.  But if it is, I'm voting for Live Wallpaper to be totally blurry, but only with the Lovefilm Widget.  It would just be ethnically beautiful.  It would really highlight this Widget, and make it rank as the most beautiful.  :D

**Comment by jurialmunkey** [comment]
> I don't know if it's possible. But if it is, I'm voting for a Wallpaper (dinamic/Keyart) totally blurry, but only with the Lovefilm Widget. It would just be beautiful. It would really highlight this Widget, and make it rank as the most beautiful. :D

Yeah I think that would make the most sense for this widget style and was my original intention - I think there's just a condition somewhere not working correctly.

**Comment by Bindou01** [comment]
> It would be great if you could.  We believe in you. :)

**Comment by Bindou01** [comment]
Has there been any progress on this display issue ?

**Comment by Bindou01** [comment]
> ### Skin section
> Home Widgets
> 
> ### Current Behavior
> When simple background for widgets is not selected, you will see the artwork twice when using lovefilm. One time inside lovefilm and one time behinde lovefilm which looks a bit buggy.
> 
> ### Expected Behavior
> I would suggest to enable simple background or blurred background art just for lovefilm.
> 
> ### Steps To Reproduce
> 1. Select lovefilm
> 2. Deselect simple background for widgets
> 
> ### Screenshots and Additional Info
> ![image](https://user-images.githubusercontent.com/10676597/215774444-f4e77c6f-ff8a-4dc9-9612-0029f2c7ee03.jpg)
> 
> ### Checklist
> * [x]  I have made a separate issue for each bug that I am reporting.
> * [x]  I have searched the issues and this bug has not been reported.
> * [x]  I am using the most recent skin version.
> * [x]  I have confirmed that this bug does not occur in the default skin.

Has there been any progress on this display issue ?
