### ISSUE TITLE
[BUG] Settings level change button sets wrong focus when pressing down if too many settings categories present

### ISSUE THREAD

**Issue by OneAngryMan** [jurialmunkey/skin.arctic.horizon.2#797]
### Skin section

Other

### Current Behavior

Hi,
when focusing the settings level change button in an addon settings dialog, where the settings categories column contains more items than can be displayed at once, the upmost setting category doesn't get focused properly upon pressing down on the settings level change button. The video should speak for itself. Related to #685. The complete removal of the button wouldn't do much harm either. Next to no addons make use of it and the idea of different settings categories for addons is sort of a joke by itself. Also it makes navigation more cumbersome in general.

### Expected Behavior

Always focus upmost settings category after pressing down on settings level change button.

### Steps To Reproduce

Install addon which has lots of settings categories (e.g. Umbrella, TMDb Helper) - open settings dialog - focus settings level change button - press down

### Screenshots and Additional Info

https://user-images.githubusercontent.com/83606678/215887156-366a5f7b-481e-4b10-b4ee-fb92366a2886.mp4

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah I remember why I didn't put it on the other side. Not actually enough room for four buttons with proper spacing when the addon icon is visible.

Anyway, pretty sure I've managed to fix it.

**Comment by jurialmunkey** [comment]
> Yup, works, though I don't really get how using SetFocus() makes a difference here. Weird Kodi things.

Yeah no idea, it's weird but it works. My guess is that builtins like SetFocus() go on a stack, so SetFocus(3) and SetFocus(-100) always execute in order one after the other; whereas specifying the ID directly goes via different process and ends up in a race against the SetFocus(-100)

Complete assumption though. Anyway, if it works, it works.
