### ISSUE TITLE
The candidates and entered text are overlapped when inputing Chinese

### ISSUE THREAD

**Issue by Hawkedon** [jurialmunkey/skin.arctic.horizon.2#8]
Thanks @jurialmunkey for the great new skin! It seems the controls 312/313/314 in DialogKeyboard.xml
 are overlapped when inputing Chinese characters.

**Comment by Hawkedon** [comment]
![2](https://user-images.githubusercontent.com/46645337/172104532-53f64f60-cacc-409b-a4d5-99aad7736e02.jpg)

@jurialmunkey A screenshot of the problem, you can see the overlap in the red box I highlighted, which I inputed the character "g" and "e", and the candidate Chinese characters just overlapped.

**Comment by jurialmunkey** [comment]
@Hawkedon - I'm assuming it is a Pinyin typing system where the candidate characters appear in a top row and "sounds like" characters appear in the bottom row?

**Comment by Hawkedon** [comment]
Thanks @jurialmunkey. Your assumption is correct. It works now!
