### ISSUE TITLE
[Feature] Add Loading spinner for Fullscreen widgets

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/skin.arctic.horizon.2#802]
### Skin section

Home Widgets

### Feature description

Please add a "Loading..." spinner for fullscreen widgets like the one displayed while regular widgets are loading.

### Why is this feature needed? Please justify and explain.

On some installations, the only widget on the main screen is a fullscreen widget.  In those cases, there is no indication that anything is happening while the widget is loading - it's just a blank page.  Some slower devices can take 10+ seconds to load the widget, so it would be nice to have the same "Loading..." spinner for fullscreen widgets that is displayed for regular widgets.

If you're concerned about having multiple "Loading..." spinners on a screen (when there are multiple widgets), maybe you could only display it for the first widget (which would always be the fullscreen widget, if present).

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by eengert** [comment]
I've updated to v0.8.15 on my Apple TV, Mac and Nvidia Shield but I still don't see a loading spinner for my fullscreen widgets. 

Here is an example of a fullscreen widget configuration:
![Screenshot 2023-03-06 at 11 51 25 AM](https://user-images.githubusercontent.com/33561812/223177419-ab017d9c-695f-461f-bc40-71898c8fe368.png)


And here is how it is displayed:
![Screenshot 2023-03-06 at 11 52 43 AM](https://user-images.githubusercontent.com/33561812/223177531-5337ba31-f96f-4af3-92cf-578838b37a45.png)


When it is loading, there is no spinner displayed for the fullscreen widget, whether it is the only widget or if there are other widgets below it.  Am I missing something?

**Comment by jurialmunkey** [comment]
Oh I thought you meant fullscreen fanart widgets.

Didn't realise the indicator is nor working for the other styles. That's strange because those should be same definition as normal widgets
