### ISSUE TITLE
Voice Search. Will this be added anytime soon?

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.horizon.2#805]
### Skin section

Other

### Feature description

Will it be possible for me to pickup my remote and do a voice self a movie or TV show?

### Why is this feature needed? Please justify and explain.

This really would make like easier than having to type out the program or film name in the search bar.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is not a skin matter.

Kodi already has voice recognition for keyboard on android. Long press OK on text field allows you to speak.
