### ISSUE TITLE
[BUG] Otaku add-on Playing Next Dialog issue and autoplay next episode issue in Arctic Horizon 2 skin

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#806]
### Skin section

Fullscreen Video OSD

### Current Behavior

Hi @jurialmunkey,

Hope you're doing well. The Otaku add-on developer asked me to report this issue here to you. The Playing Next Dialog in the add-on is not appearing. Also, the autoplay next episode function is not working due to this issue as well. This issue is not happening in Kodi Matrix and is  specific only to Kodi Nexus and upward versions. I'm using an Nvidia Shield TV Pro. I've tested with Kodi official Matrix, Kodinerds Maven Matrix build, Kodi Official Nexus, Kodinerds Maven Nexus, Kodi official Omega - Alpha 1, and Kodinerds Maven Omega - Alpha 1 versions.

You can check my tickets here as well which I reported to the Otaku add-on developer:

https://github.com/Goldenfreddy0703/Otaku/issues/63

https://github.com/Goldenfreddy0703/Otaku/issues/67

Here's my Kodi log:

https://paste.kodi.tv/xiholuveyi

### Expected Behavior

The Playing Next Dialog should appear at the end of every episode in Kodi Nexus and should autoplay the next episode as well. The issue is only happening in Arctic Horizon 2 skin and not in the default Estuary skin.

### Steps To Reproduce

What I did was first use the Otaku add-on in the default Estuary skin and the Playing Next Dialog appeared fine and also played the next episode correctly. Next I switched back to the Arctic Horizon 2 skin and the Playing Next Dialog appeared fine there too and the next episode played fine too. After this I exited Kodi and opened it again. This is when the issue started happening. The Playing Next Dialog didn't appear in the Arctic Horizon 2 skin this time and the next episode also didn't play. I then switched back to the default Estuary skin again, exited Kodi and opened it again. The Playing Next Dialog appeared fine in the Estuary skin again. So my guess is that when I'm switching to Arctic Horizon 2 skin and exiting Kodi something is happening which is causing the Playing Next Dialog to fail.

### Screenshots and Additional Info

Screenshot in Estuary:

![IMG20230206204755](https://user-images.githubusercontent.com/65297828/217464456-4bf4229a-e261-471c-8444-a988c736d4b6.jpg)

Screenshot in Arctic Horizon 2 when it worked without exiting Kodi Nexus:

![IMG20230206210542](https://user-images.githubusercontent.com/65297828/217464568-50080901-12bb-4534-95c2-d1ca22cf70c0.jpg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I dont see how this can be a skin issue. This is not a dialog in the skin. If it comes from the addon then the skin doesn't have any control over it.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Fine. I'll let the Otaku developer know about your above comment. However, as per all my tests this issue is only happening in Arctic Horizon 2 and not in Estuary. Not sure why.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
Hey @jurialmunkey we are really sorry for bothering you, this guy has had so many errors if you look at his log and it could possibly be related to a connection issues or something. Thank you for the response and the great skin and I hope you have great day. Thank you

**Comment by Goldenfreddy0703** [comment]
Oh this maybe unrelated but do you by anychance know why this guy cannot load some things in tmdb helper. That would be great if you can tell me about that. Thank you

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey and @Goldenfreddy0703,

Thank you both! I'm not very sure if it's a connection issue. If you have followed my earlier replies in the Otaku GithHub thread then you can see this is Nexus and upward Kodi versions specific and not related to Kodi Matrix. Also, the issue is only happening in the Arctic Horizon 2 skin with only the Otaku addon. All other add-ons like Seren and Fen have perfectly working Playing Next Dialog with Autoplay next episode.

For me more or less whatever I see is loading is TMDB Helper. I'm not sure what those specific errors are for. I'm using @jurialmunkey's skins since a long time along with TMDB Helper and have been testing issues and reporting him from time to time. So as far as I can guess that those issues are related with Nexus/Omega, Arctic Horizon 2 skin, and Otaku add-on.

Thanks to everyone for looking into this!

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
> Hey @jurialmunkey we are really sorry for bothering you, this guy has had so many errors if you look at his log and it could possibly be related to a connection issues or something. Thank you for the response and the great skin and I hope you have great day. Thank you

What errors are you talking about?

The only error I see is a trace back for Otaku plugin related to its use of ast.literal_eval starting at this timestamp 
`2023-02-05 22:02:07.119 T:22298   error <general>: Traceback (most recent call last):`

Theres a lot of depreciation messages but those aren't coming from TMDbhelper and won't really affect anything anyway (just log spam). 

There's a couple of fanart TV image errors but that's just fanart TV not having an image and also won't affect anything. 

Other than that I can't really see any errors. The only real error I see is the traceback from Otaku...

**Comment by Goldenfreddy0703** [comment]
Yeah i have noticed that too, there has been alot going on with Otaku, Real Debrid, Nord Vpn, Playlist, Ect. Me and my team are trying to look into it and recently i started encountering issues. 

Thank you very much for pointing this stuff out and you can close this issue if you like to.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

We found what was causing this issue. The Play button in the video info screen is linked to TMDB Helper and TMDB Helper is linked to Trakt, whereas Otaku addon is linked to Anilist and not Trakt. Therefore, playing any Otaku addon video using the Play button in the video info screen plays it through the TMDB Helper. Now if we disable TMDB Helper in the Arctic Horizon 2 skin then the Play button in the video info screen stops functioning entirely. Now if we set Default Select Action as "Play" instead of "Show Information" under the Media Settings -> Videos in Kodi then the video info screen is over-ridden and I guess the video plays using Play from here (which is also present in the context menu). So, is there any way that we can somehow change the functionality of the Play button in the video info screen so that it doesn't override the Play functions of Otaku. The Play button in the video info screen works perfectly for all other video add-ons like Fen, Seren, etc. I guess because they use Trakt. The problem is only with Otaku because I guess it uses Anilist instead of Trakt. Your advise regarding this matter will be extremely beneficial for many users of Otaku addon.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
>We found what was causing this issue. The Play button in the video info screen is linked to TMDB Helper and TMDB Helper is linked to Trakt, whereas Otaku addon is linked to Anilist and not Trakt.

This assumption is incorrect. The play button does NOT play anything using TMDbHelper.

All the RunScript command does is close out the recommendations dialog window manager (the extended info style browsing in the info dialog). Playback is handled by the standard Kodi builtin command `PlayMedia()`


> Therefore, is there any way that we can somehow change the functionality of the Play button in the video info screen so that it doesn't override the Play function of Otaku?

The play button doesn't override anything.

It calls `PlayMedia($INFO[ListItem.FileNameAndPath])` which is a standard Kodi builtin.


> The problem is only with Otaku because I guess it uses Anilist instead of Trakt. 

Nope. Entirely unrelated. 


> . I tried changing different settings in TMDB Helper addon to modify the Play button functionality in the video info screen, but none of them worked as the Play button is completely linked to TMDB Helper

Changing TMDbHelper "play button functionality" won't make any difference because TMDbHelper is NOT playing anything. You would see a log message about TMDbHelper attempting playback if it was.

Playback is done entirely through a standard Kodi builtin PlayMedia() If the Otaku addon is incompatible with PlayMedia then they need to fix it.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Thank you for the detailed explanation!

@Goldenfreddy0703 might be able to look into this.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

One question, if the Play button in the video info screen is calling PlayMedia(), then what function is being called to play the video when I'm changing the default select action to Play instead of Show Information, because that works perfectly with the Playing Next Dialog in Otaku? Is it "Play from here"? I'm asking this because if PlayMedia() is failing to obtain the playlist then how is the video playing on click when I'm changing the default select action to Play instead of Show Information. Your expert opinion will be extremely useful for us.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
> If this is the problem, there were some changes in Nexus to the PlayMedia builtin to try and provide something of a workaround for similar plugin problems:

@MoojMidge - I could be misunderstanding but I thought that parameter was for physical playlist files like `.m3u` or `.strm` because there's no way to determine the content type before playback. 

It shouldn't matter for PlayMedia() on a single item from a plugin because that's playing the item direcltly and the playlist is constructed afterwards. Otherwise everything would play though the music playlist and the video playlist would never be used. I could be mistaken though.

**Comment by jurialmunkey** [comment]
@ShibajiCh - Try 0.8.4 -- that will force playlist hint to video

Note that if this works it is just a workaround. The Otaku plugin is going to run into this same problem with any skin that uses PlayMedia() not just AH2 because the default behaviour set in Kodi is to use a music playlist if the playlist type cannot be determined.

It's a bad approach in general that Kodi has two different playlist types. Definitely shouldn't be up to the skin to determine playlist type which is why this is only a workaround and not a proper fix.

**Comment by Liquidrag** [comment]
@ShibajiCh it has to be something to do with your setup. I'm using nexus, AH2, and otaku on a mac and shield and I get the popup and when I click play, it plays. Maybe you need to start from scratch?
<img width="2560" alt="Screen Shot 2023-02-09 at 7 06 16 AM" src="https://user-images.githubusercontent.com/43726430/217821685-9cae9d78-ba5a-452c-a638-5edc3ebe8071.png">

**Comment by Goldenfreddy0703** [comment]
@Liquidrag hey, last time we called and discussed what widget stuff was having problems then we tested it and yeah, I noticed something odd. Playlist stuff will be fixed one day. It will just take some time to do.

**Comment by Liquidrag** [comment]
@Goldenfreddy0703 ok, I hope you figure it out.

**Comment by ShibajiCh** [comment]
Hi @jurialmunkey,

Thank you! However, the Arctic Horizon 2 skin version 0.8.4 didn't resolve the issue with Otaku. The Playing Next Dialog still didn't appear when played using the Play button in video info dialog. Only Play from here is working. Else I need to change the Default Select Action in Kodi to Play, then clicking on the video makes the Playing Next Dialog appear fine. I guess even that defaults to Play from here. Correct me if I'm wrong. Other Play options like Source Select, etc. in Otaku's context menu doesn't make the Playing Next Dialog appear as well. The error getting the playlist still remains if played using the Play button in video info screen.

Here's my updated Kodi log in case you want to refer to it:

https://paste.kodi.tv/docebilogo

@Liquidrag: Like @Goldenfreddy0703 said, we had a call sometime back today and he too faced the same issues as me. So it's not a problem with my setup. The issue with the Playing Next dialog only happens in Otaku when played using the Play button in Arctic Horizon 2's video info screen or if played using the source select option in Otaku. If you use Play from here or change the default select action in Kodi to Play then the video plays fine along with the Playing Next Dialog.

Hope @Goldenfreddy0703 can resolve this issue with the Otaku playlist soon.

@jurialmunkey: Any valuable suggestions from you will help us a lot too.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment]
Hey @ShibajiCh I will be working on the playlist soon so that it can work with watchlist, @jurialmunkey can provide a workaround in the future. Will happen very soon, u just gotta wait and we all should be good. 

Big thanks to @jurialmunkey for helping us and contributing in this and for the skin. 
Thank you and you can close this issue if you like.

**Comment by MoojMidge** [comment]
@ShibajiCh - I'm pretty sure the recent changes made in AH2 have worked because your last log had the following line:
```
2023-02-09 19:52:57.279 T:24831 error <general>: Playlist Player: skipping unplayable item: 1, path [plugin://plugin.video.otaku/play/151806/2/]
```
Granted this is not terribly useful because the plugin is still failing for whatever reason, but that is the limit of what impact a skin can possibly have in trying to workaround these problems.

As @jurialmunkey stated, this is something that should be fixed by the plugin.

**Comment by jurialmunkey** [comment]
Closing this because, as @MoojMidge mentioned above, not much else I can do from the skin side.

**Comment by Goldenfreddy0703** [comment]
> Closing this because, as @MoojMidge mentioned above, not much else I can do from the skin side.

Hey that's totally fine, huge thank you for helping us and thank you very much,.

**Comment by ShibajiCh** [comment]
Thank you all @jurialmunkey @Goldenfreddy0703 and @MoojMidge !
