### ISSUE TITLE
[Feature] Option to select first unwatched Episode of currently watching Season in TV Shows under library list/combined view for add-ons

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.horizon.2#809]
### Skin section

Library Views

### Feature description

Hi @jurialmunkey,

I'm not sure whether to add this request here under Arctic Horizon 2 skin or under TMDB Helper addon. Similar to Kodi library settings is it possible to add an option to always select the first unwatched Episode of currently watching Season in TV Shows under library list/combined view for add-ons?

### Why is this feature needed? Please justify and explain.

This feature will save us a lot of time and will provide an OTT (Netflix) kind of experience, where we don't need to search the first unwatched Episode of a currently watching TV Show Season in library view. Whenever a library list/combined view is opened for a TV Show the first unwatched Episode of the currently watching season will be automatically selected.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I don't think this is actually possible. Definitely would be a good feature but I can't think of any way to do it from the skin side, and everything from the plugin side would be a hack.

TMDbHelper does have the "Up Next" season which will display the next episodes to watch.

**Comment by AakashC2020** [comment]
> I don't think this is actually possible. Definitely would be a good feature but I can't think of any way to do it from the skin side, and everything from the plugin side would be a hack.
> 
> TMDbHelper does have the "Up Next" season which will display the next episodes to watch.

Hi @jurialmunkey,

No problem. Just wanted to know if this was possible. Thank you for letting me know in details!
