### ISSUE TITLE
[BUG] some strings are not mapped in strings.po

### ISSUE THREAD

**Issue by krzysztofwinnik** [jurialmunkey/skin.arctic.horizon.2#81]
I've ran through all possible views and found some strings that are not mapped in string.po and therefore imposible to be translated. 

Here is what I've found:

- all views - options pop-up title ("options")
- home - submenu - "options" caption
- infoview - "search" button
- ratings - "released" caption
- weather - "provided by" title

Not many... but it would be nice to have those strings mapped as well for translation purposes.

Also, there is one string that do not make much sense in my language (Polish) - probably beacuse it is mapped to kodi language strings.po instead of skins' file. That would be:
- Settings > Menus > Customise home screen >    "label" caption translated as "studios"
Not sure if it makes sense in other languages or is it just wrong mapping.

**Comment by krzysztofwinnik** [comment]
many thanks for that!

**Comment by krzysztofwinnik** [comment]
Ok, so I found one more minor bug related to localizations, so i re-open this issue.
Please look at those two screenshots. 
In pop-up opitons menu viewtype names get localized correctly, but in a dialogue window the names remain in English.
Also, the title of the dialogue window need to be translated, but I think it is a skinvariables thing, right? 

PS. I am really gettig excited with how this skin already looks like and how consistent it is. Great job! Please keep it that way and do not get tempted to please everyone with unnecessary features! :-
<img width="1440" alt="Zrzut ekranu 2022-06-8 o 09 12 49" src="https://user-images.githubusercontent.com/679205/172558394-4a60849b-39cb-410f-90b1-feec1023c6b9.png">
<img width="1440" alt="Zrzut ekranu 2022-06-8 o 09 16 13" src="https://user-images.githubusercontent.com/679205/172558405-2b9656ae-8b27-413c-8189-4e4872019c7d.png">
)

**Comment by jurialmunkey** [comment]
Ah yep, forgot about those ones. Should be working now.

And yes, you're correct - the heading is localized in skinvariables not the skin itself. It's only possible to localize the "Choose viewtype" part, because the "(episodes)" part refers to the Kodi library dbtype so it is a strict name.

**Comment by krzysztofwinnik** [comment]
Yup, it works now for videos window viewtypes, but not for customise menu items widget aspects in settings.
 <img width="1440" alt="Zrzut ekranu 2022-06-8 o 12 19 57" src="https://user-images.githubusercontent.com/679205/172593596-9616269a-383c-4dcb-b7cb-ca84116c5663.png">

**Comment by jurialmunkey** [comment]
Aspect can't be localised because it is a setting for the widget template. If it is localised then the string won't match the setting in the template and the wrong one will be built.
