### ISSUE TITLE
[BUG] Favourites dialog is broken

### ISSUE THREAD

**Issue by CruxH** [jurialmunkey/skin.arctic.horizon.2#813]
### Skin section

Other

### Current Behavior

Clicking on items in the 'Favourites' dialog does not produce any results.

### Expected Behavior

In the 'Favourites' dialog, clicking on items navigates to their location.

### Steps To Reproduce

1. Add any item to favourites
2. Click on the newly added item in the 'Favourites' dialog

### Screenshots and Additional Info

1. In other skins, both existing items in the 'Favourites' dialog and newly added ones in Horizon 2 function as intended
2. The previous version of the skin 0.8.4 worked as intended
3. 'Favourites Browser' works as intended

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The dialog has been depreciated in Kodi Nexus and will be removed in Omega.

You must use favourites browser now.

The "new" dialog is a fake custom dialog with a favourites widget to try to retain existing functionality but so far not working great.

Personally I prefer the dialog and think in some ways the window is a regression but it wasn't my decision.
