### ISSUE TITLE
[Feature] Make bakup for skin settings

### ISSUE THREAD

**Issue by fatshotty** [jurialmunkey/skin.arctic.horizon.2#815]
### Skin section

Other

### Feature description

Is it possibile to make a full backup for skin settings in order to have the same settings on other kodi installation?

### Why is this feature needed? Please justify and explain.

make a full-backup for all widget and submenu settings

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This isn't a skin issue.

You can copy your userdata/profile folders and addon_data to another install to retain settings. Skin settings are addon settings just like any other addon

**Comment by Liquidrag** [comment]
> This isn't a skin issue.
> 
> You can copy your userdata/profile folders and addon_data to another install to retain settings. Skin settings are addon settings just like any other addon

Sorry to bother you but I'm trying to restore just the skin from my old build onto a fresh build. I've copied over addons>skin.arctic.horizon.2, userdata>profiles.xml, userdata>guisettings.xml, userdata>addon_data>skin.arctic.horizon.2 and nothing other than the switch to dark theme seemed to work. I was hoping all of my tabs, hubs, and settings would switch over. Am I missing a file?

**Comment by jurialmunkey** [comment]
Need to copy addon_data for dependencies, in particular these ones:

Menus:
addon_data/script.skinshortcuts

Views:
addon_data/script.skinvariables

Color:
addon_data/script.texturemaker

**Comment by Liquidrag** [comment]
Perfect! Thank you! I still think a backup/restore skin settings would be helpful though.

**Comment by Omarscomin** [comment]
> Perfect! Thank you! I still think a backup/restore skin settings would be helpful though. 

What process/program are you using to perform your backups and restores? I've literally never run into the issue of my skin settings not carrying over to a restore. I've got widgets/hubs/customization galore!

**Comment by Liquidrag** [comment]
> What process/program are you using to perform your backups and restores? I've literally never run into the issue of my skin settings not carrying over to a restore. I've got widgets/hubs/customization galore!

OpenWizard. I have 0 problems with backup/restore but just wanted to start fresh with just the skin and its settings moved over without having to uninstall all of my addons besides the skin and then backup/restore. I'm just suggesting it would be convenient for a backup/restore option just for the skin where I could do a fresh install, install AH2, and point to a restored file, but understand if JurialMunkey doesn't want that feature. At the end of the day, I am thankful he responded and told me the dependencies I needed to move also.
