### ISSUE TITLE
[Feature] Hide watched items in widget views

### ISSUE THREAD

**Issue by xologram** [jurialmunkey/skin.arctic.horizon.2#817]
### Skin section

Home Widgets

### Feature description

Add an option to hide watched items in home widget views. 

### Why is this feature needed? Please justify and explain.

If I have Seren or FEN Watchlist as a widget - it would be great to hide the watched items. For a more netflixy experience.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skin can't control this behaviour. Ask the addon author.

**Comment by xologram** [comment]
thanks for the answer. addons usually rely on kodi's "hide watched items" context menu inside lists. even if I enable this in the addon - the widget does not honor it. would it be possible to make widget honor this and use kodi's native "hide watched items" filter?

**Comment by jurialmunkey** [comment]
As I said, skins cannot control this behaviour.

The setting inside the media window views is controlled by Kodi.

For widgets there is no option so the only way to achieve what you want is if the addon author adds an option to hide watched items on widgets.
