### ISSUE TITLE
[Feature] Auto load more in a widget

### ISSUE THREAD

**Issue by xologram** [jurialmunkey/skin.arctic.horizon.2#818]
### Skin section

Home Widgets

### Feature description

When using a list as a widget many plugins have "Next page" button which once clicked will open up the addon and continue browse there. It would be great if the widget could load the next page in the widget itself once hovered over "Next page" button. That way no need to open the addon.

### Why is this feature needed? Please justify and explain.

For a better UI experience. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It would be nice but unfortunately not possible. Kodi has no method of rolling load of content.
