### ISSUE TITLE
[Question] How to call program information window in pvr

### ISSUE THREAD

**Issue by notoco** [jurialmunkey/skin.arctic.horizon.2#819]
### Skin section

PVR and Live TV

### Feature description

This is not a request for new functionality - but a question - I love the look of this window - how do I bring it up using a shortcut?

### Why is this feature needed? Please justify and explain.

I would like to replace the default channel info with this

### Screenshots and Additional Info

![screenshot00002](https://user-images.githubusercontent.com/36659110/218760156-1875b448-38cf-41c9-8977-87e90e53266a.png)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Yep that was the plan to replace the bottom bar info with this view for pvr. Should be working in next release oninfo press.
