### ISSUE TITLE
Add open Wall View on pressing down feature

### ISSUE THREAD

**Issue by ShibajiCh** [jurialmunkey/skin.arctic.horizon.2#82]
Hi @jurialmunkey,

Could you please add the "Pressing down opens wall view (replaces scrollbar)" feature to this skin as well which you currently have in Arctic Horizon 1? It's really very useful for long lists.

**Comment by jurialmunkey** [comment]
See todo list

**Comment by ShibajiCh** [comment]
Okay. Thank you!
