### ISSUE TITLE
[Feature] 4KMovies.xsp in playlist

### ISSUE THREAD

**Issue by aseanic** [jurialmunkey/skin.arctic.horizon.2#824]
### Skin section

Home Widgets

### Feature description

Please put back 4KMovies.xsp and HDMovies.Xsp files in playlist folder

### Why is this feature needed? Please justify and explain.

Please include **4KMovies.xsp** & **HDMovies.xsp** in the playlist folder, (i had to take these two files from Arctic Zephyr) currently tag function doesnt have the feature to separate these type of files. My library has a mixture of movies in a resolution range of 4K to SD. Some have similar title so when run add to library both movies will be widgeted side by side redundantly ugly. I still need the low res movies for low tier device. Widgetizing video source folder will not form movie poster view widgets but file instead. It can only widgetize them if it's clicked from button or link. That's the reason i need 4KMovies.xsp as playlist cause it will definitely be widgetized as a movie.  

### Screenshots and Additional Info

https://user-images.githubusercontent.com/79122869/219045790-7fbf3c59-17cd-48ce-ba7f-351dec93fbd3.mp4

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can already set any smart playlist you like. These do not need to be in the skin folder to use

Save them in your userdata/playlists folder and they will be available:
https://kodi.wiki/view/Smart_playlists/XSP_Method#Location_of_XSP_Files

To set them:
Choose widget > Videos > Video playlists


Any smart playlist you make via Videos > Smart Playlists will also be displayed there.
