### ISSUE TITLE
[Feature] Video Thumbnail as fullscreen widget

### ISSUE THREAD

**Issue by aseanic** [jurialmunkey/skin.arctic.horizon.2#826]
### Skin section

Home Widgets

### Feature description

Personal video collection will have thumbnail that will be widgetized in fullscreen just like EPG images. 

### Why is this feature needed? Please justify and explain.

Currently personal video collection can only be widgetized as landscape/poster / square etc but not fullscreen. Any attempt to opt for fullscreen, the widget will come up empty,

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can set custom metadata for home movies by using .nfo files
https://kodi.wiki/view/NFO_files

All you need to do is set artwork as fanart.
