### ISSUE TITLE
[Feature] Animated Discart & Videolyrics

### ISSUE THREAD

**Issue by aseanic** [jurialmunkey/skin.arctic.horizon.2#827]
### Skin section

Music Visualisation OSD

### Feature description

Please bring back Animated Discart & Videolyrics

### Why is this feature needed? Please justify and explain.

Should have the option to enable and disable discart and videolyrics because they're just unique, beautiful and fun especially for young people.

### Screenshots and Additional Info

https://user-images.githubusercontent.com/79122869/219066049-0a52b616-5fb7-4f12-b409-375b4baae562.mp4

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
> Please bring back Animated Discart & Videolyrics

These were never in the skin. Video lyrics will not be added as it does not suit the style of skin. There are other skins if you want a less minimalist interface.

Discart I may consider.
