### ISSUE TITLE
Fullscreen Widget Limit

### ISSUE THREAD

**Issue by rmdcf1967** [jurialmunkey/skin.arctic.horizon.2#828]
### Skin section

Home Widgets

### Feature description

On Android with KodiNerds 20, when I setup a fullscreen widget based on a Trakt list with more than 600 items, everthing seemed to work flawlessly. But to my surprise, when I scroll (or on autoscroll) when it reaches 20 items, it shows Nest Page, but it doesn't have any button to load the next page as it happens on a normal widget . I forgot to mention that on the fullscreen wiget configurations I've set it up to " No-limt (9999)".

Is this normal or should I do something else? Many thanks in advance

### Why is this feature needed? Please justify and explain.

For people who have big tratk lists

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Xiqnez** [comment]
Trakt limitation. Had nothing to do with the skin.

Per Trakt Update Blog (2022, May 24):

Pagination — All lists are now paginated, this allows larger lists to actually load and be useable. All sorting and filtering options are still available.

**Comment by jurialmunkey** [comment]
See above for pagination reason. 

For next page, you can click the next page item by using the Browse button as long as the addon you're using is coded properly and sets the is folder flag on the item.
