### ISSUE TITLE
Dependency TMDb 5.0.52 could not be satisfied

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#830]
### Skin section

Other

### Current Behavior

When trying to update to AH2 0.8.7 I get a error pop up ,Dependency TMDb 5.0.52 could not be satisfied ,, I’m already updated to TMDb 5.0.52 on Windows 11 v20

### Expected Behavior

//

### Steps To Reproduce

//

### Screenshots and Additional Info

//

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by RayvChan** [comment]
android also
