### ISSUE TITLE
[Feature] Submenu 

### ISSUE THREAD

**Issue by heimdall47** [jurialmunkey/skin.arctic.horizon.2#831]
### Skin section

Home Widgets

### Feature description

I have setup a submenu for Actors in my movie library. The submenu cannot be sorted alphabetically as it appears there is only one option i.e. date. Currently actors show all jumbled whereas it is easier to search alphabetically. Similarly if I setup Genres - Action in the Submenu there should be option to sort them by year 

### Why is this feature needed? Please justify and explain.

It would make sense to view actors alphabetically rather than jumbled up. Similarly Action genre should have the ability to sort by year or rating.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I don't know what you mean by "submenu" -- I'm assuming you're talking about a shortcut which takes you to either a library node or plugin directory. Either way, skins do not control which sort methods are available.

If this is a library node, then the sorting methods are determined by Kodi.
If this is a library smart playlist, then the sorting method is determined by the method you choose in the playlist.
If this is a plugin path, then the available sorting methods are determined by the plugin.
