### ISSUE TITLE
PVR fanart is rendered behind background image.

### ISSUE THREAD

**Issue by woodside007** [jurialmunkey/skin.arctic.horizon.2#832]
### Skin section

PVR and Live TV

### Current Behavior

 With look-ups for PVR windows setting enabled, PVR fanart shows for a split second while navigating the guide and then fades back behind the skin's background image. The only way to view is to set background to none in appearance settings. Maybe a z-order issue?

Also, what is the "EPGEventIcon for PVR fanart" setting for? I've enabled and disabled but see no changes anywhere and was just curious as to what purpose it has enabled or disabled. Thanks.

### Expected Behavior

PVR fanart to be rendered in front of background image.

### Steps To Reproduce

Go to PVR channels guide while PVR look-ups are enabled and navigate channels. When a guide item has fanart it flashes for an instant and then fades behind.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [x] I have confirmed that this bug does not occur in the default skin.

**Comment by pakraider** [comment]
+1, choosing 'Blur' and then any of Clearart, FlixArt, or Keyart has this behavior.

Choosing 'Fanart' does show the fanart though as the background, in case that helps in tracking this down.

**Comment by jurialmunkey** [comment]
TMDbHelper issue.
