### ISSUE TITLE
getting a lot of  ConnectionError : TMDb timeout Suppression retries for 30 seconds 

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.horizon.2#833]
### Skin section

Other

### Current Behavior

After updating to the latest version of AH2 and TMDb I’m getting a lot of ConnectionError : TMDb timeout Suppression retries for 30 seconds ,the pop up shows up more  for information on TV Shows and Movies ,Actors and recommendations etc.. when it does happen the information screen struggles or shows up blank ,I tried on two different PCs and both give the same  pop up ,, Windows 11 Pro v20 , AH2 v0.8.8 ,TMDb v5.0.52

### Expected Behavior

//

### Steps To Reproduce

//

### Screenshots and Additional Info

//

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Coincidence

TMDb api intermittently struggling to serve all requests yesterday.

**Comment by xyzfre** [comment]
Ok👍🏼 My apologies I thought it had something to do with the update ,glad to hear it's api issues because AH2 has been working flawlessly Thank you @jurialmunkey for all your AMAZING work💯💯
