### ISSUE TITLE
[BUG] No clearlogo in fullscreen video OSD

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/skin.arctic.horizon.2#835]
### Skin section

Fullscreen Video OSD

### Current Behavior

No clearlogo in fullscreen video OSD. This happens since the last updates, I have not changed anything in my settings.

### Expected Behavior

Clearlogo in fullscreen video OSD :)

### Steps To Reproduce

Fullscreen video.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Kayzels** [comment]
I've noticed the same. I thought it might be due to the TMDb issues yesterday, but it is still occurring today after that.

Will upload a log later, if needed.

**Comment by jurialmunkey** [comment]
Yes, log please. I can't recreate, logos working fine for me.

I bet either your library or the addon you're using is setting the wrong value in a `UniqueID(tmdb)` -- probably putting an imdb or tvdb ID instead and lookup is failing.

**Comment by Kayzels** [comment]
[Kodi Log](https://paste.kodi.tv/uyoyiqijob.kodi)

Seems to be something to do with `getUniqueID`.

`xbmc.InfoTagVideo' object has no attribute 'getUniqueID'` appears multiple times. Possibly a difference between Matrix, and Nexus? I haven't updated yet.

**Comment by jurialmunkey** [comment]
Yep that's be it. Didn't realise you were on Matrix. My mistake, didn't check the docs close enough when backporting. Fairly sure there's another method I can use to get uniqueid here which is Matrix compatible.
