### ISSUE TITLE
Skin does not start

### ISSUE THREAD

**Issue by Hallo951** [jurialmunkey/skin.arctic.horizon.2#84]
Hello,

I can't get your skin to start. I use a Zidoo Z9x as a media player. Kodi runs on this as a fork in the app ZDMC in version 19.4. This corresponds to the Kodi in version 19.4 only with the difference that for playing the movies not the Kodi own player is used but the native zidoo own player is used. Currently I use the skins Aeon Nox Silvo and l Artic Zephyr - Reloaded with ZDMC. Both work without any problems. 

I have successfully installed your skin with all dependencies, but I can't get it to start. When I want to start your skin, the whole settings menu changes briefly to your skin, but then jumps back to the previous old skin. I don't get a window where I can confirm the use of your skin, like it usually is with the other skins.

Do you have any idea why I can't start your skin? The other skins work as well.

**Comment by jurialmunkey** [comment]
No idea. Impossible to tell without a debug log.

**Comment by Hallo951** [comment]
All right, here's the Kodi log file when I try to launch your skin:

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8850875/kodi.log)

**Comment by Hallo951** [comment]
And here is a Kodi log file when I switch from Aeon Nox Silvo to the "Artic Zephyr - Reloaded" skin, which is based on your old skin. This runs without any problems for me.

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/8850929/kodi.log)

**Comment by jurialmunkey** [comment]
Logs says that DialogConfirm loads correctly so I'm not sure why it wouldn't display.

A couple of things to try:
Disable mouse support temporarily 
`Settings > System > Input > Enable mouse and touch screen support`

Act like the confirm dialog is visible i.e. press left then enter after the skin is visible just like you would normally to choose Yes.

If neither of those work, are you able to get me a short video or at least a screenshot of the confirm dialog not being visible? Might give me a better sense of what is happening if I can see it.

**Comment by Hallo951** [comment]
For me, the mouse support was deactivated. I activated it once as a test, but it made no difference. Confirming the new skin without a confirmation screen via the key combinations "Press left and then enter" unfortunately did nothing either.

I once read the following note in another forum in connection with ZDMC and another skin that did not start:

"I went through the same hassle, you need stop ZMDC, then activate the skin in the config file, I think it was guisettings.xml."

Maybe that will help you. Unfortunately, it doesn't mean too much to me.

Can you perhaps determine the problem from a comparison between the two log files?

Here is the video you are looking for:


https://user-images.githubusercontent.com/40667862/172388780-4aa2bd48-435e-46a8-a948-942c6ae942b5.mp4

**Comment by jurialmunkey** [comment]
> "I went through the same hassle, you need stop ZMDC, then activate the skin in the config file, I think it was guisettings.xml."
> Maybe that will help you. Unfortunately, it doesn't mean too much to me.

That's something you need to do. They are saying to change the skin manually by editing the guisettings file which contains your Kodi settings.

You can find guisettings.xml in your `kodi/userdata` folder
https://kodi.wiki/view/Userdata#Location

With Kodi closed, you edit the file in a text edit. Look for a line like this:
`<setting id="lookandfeel.skin">skin.your.current.skin.name</setting>`

And change to this
`<setting id="lookandfeel.skin">skin.arctic.horizon.2</setting>`

Then open Kodi and AH2 will be set as the skin.

**Comment by jurialmunkey** [comment]
> But that still doesn't explain why one skin works automatically and the other one doesn't. 

Yeah I'm not sure what the cause is. It sounds like a bug specific to this platform rather than the skin because otherwise I would've heard from other people with the same problem

>Is there any rotine missing that changes this guidatei accordingly?

guisettings.xml is just a textfile that Kodi stores its settings in. When you change skins, Kodi updates the settings file.

The specific issue that you're having is that there is some bug in ZDMC preventing the Confirm dialog from displaying for some reason. 

When you change skins the confirm dialog pop-ups and you need to select "Yes" to confirm the skin otherwise Kodi reverts back to your previous settings after a short delay. If something is preventing the dialog from displaying, then you can't confirm the setting change so Kodi reverts back to the previous settings (i.e. the previous skin).

**Comment by Hallo951** [comment]
So I tried it out last night according to your instructions. It works! Your skin is running now. Very nice skin! Changing from your skin to another is only possible with the procedure you described. It doesn't work in Kodi itself. I just wonder why that is?

**Comment by jurialmunkey** [comment]
> So I tried it out last night according to your instructions. It works! Your skin is running now. Very nice skin! Changing from your skin to another is only possible with the procedure you described. It doesn't work in Kodi itself. I just wonder why that is?

No idea. It works in normal Kodi, so it must be a bug in ZDMC

**Comment by Hallo951** [comment]
Just a short info. With the latest version, starting the skin in ZDMC is now possible without problems. I don't know what you changed but it works now. The only thing that doesn't work now is switching to another skin. Currently you can only switch to another skin by deleting the entire skin folder of your skin.

Any idea what this could be?
