### ISSUE TITLE
[BUG] Arctic Waves causing screen flickering

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.horizon.2#841]
### Skin section

Other

### Current Behavior

Hi @jurialmunkey,

After the recent changes to the flix view blur effects in the latest update I've noticed that Arctic Waves is causing severe screen flickering when used in combination with Flix and Blur view. This is happening usually when I click on the Next page item, and Arctic Waves appears on screen for a few seconds while switching to the next page. I've currently disabled Arctic Waves and screen flickering has stopped. Please check and advise.

### Expected Behavior

Arctic Waves shouldn't cause screen flickering.

### Steps To Reproduce

Enable Arctic Waves. Enable Flix view with Blur. Go to any addon's next page item including that of the TMDB Helper addon. Click on the next page item from any widget or from within any addon. Screen will start to flicker severely.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce.

The recent changes shouldn't affect this much at all -- it was only a texture swap, it didn't change any code. The textures being changed shouldn't make much difference to how the skin runs, it only changes the appearance of the background overlay.

**Comment by AakashC2020** [comment]
> I can't reproduce.
> 
> The recent changes shouldn't affect this much at all -- it was only a texture swap, it didn't change any code. The textures being changed shouldn't make much difference to how the skin runs, it only changes the appearance of the background overlay.

Hi @jurialmunkey,

The flickering issue is happening whenever Arctic Waves appears on the screen. Please check the attached image for my appearance settings and also check the attached video links to see the flickering issue. I'm using an Nvidia Shield TV Pro (2019) with Kodi Nexus v20.

![IMG20230226103814](https://user-images.githubusercontent.com/65297828/221393535-549805d7-ae11-4a59-bb1a-9f21d6709f6f.jpg)

https://drive.google.com/file/d/1snjgdg35d4nWdwDtuO7qyRmtLTpFeVgd/view?usp=share_link

https://drive.google.com/file/d/1aAa1fAOhNEzaLuzVJWE4yBwj8M7UdGXn/view?usp=share_link

https://drive.google.com/file/d/1rBv99qiU-15I16s9iexIxOmYrQSetdzn/view?usp=share_link

**Comment by AakashC2020** [comment]
Here is my Kodi log file as well in case you need it:

https://paste.kodi.tv/hipusifiva

**Comment by jurialmunkey** [comment]
Can you rollback to the previous version (0.8.10) and confirm that it isn't happening on that version
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.8.10

I cannot see any real reason as to why the changes in 0.8.11 would cause this issue so I want to make absolutely certain that it is that change and not some other change on your system.

**Comment by AakashC2020** [comment]
> Can you rollback to the previous version (0.8.10) and confirm that it isn't happening on that version https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.8.10
> 
> I cannot see any real reason as to why the changes in 0.8.11 would cause this issue so I want to make absolutely certain that it is that change and not some other change on your system.

Hi @jurialmunkey,

I rolled back to v0.8.10 and also to v0.8.4, but the issue is still happening, so I guess it's not related to yesterday's update. Not sure what might be causing this, but the issue is happening only when Arctic Waves appear on the screen. The more duration Arctic Waves stay on the screen the more severely the flickering happens. If I disable Arctic Waves then everything seems to be well and good. 🙁

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

This issue is happening only with the recent updates from Kodinerds Maven build of Nexus v20. I installed original Nexus v20 from Kodi website and the issue is not there in that version.
