### ISSUE TITLE
Info text scrolling too fast?

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.horizon.2#846]
### Skin section

Home Widgets

### Feature description

Just wondering is it possible to slow down  the rate that the text scrolls at? By the time I'm half way thouthe first line it's scrolled up past the viewing area and so have to wait for the whole lot to start over to read the info showing.

Skin and addin all upto date. Can see anywhere in settings that might control the text scroll rate.
![20230301_020131](https://user-images.githubusercontent.com/97023369/222026104-a7f9588c-e963-4956-a37d-751dc6fe36ee.jpg)

### Why is this feature needed? Please justify and explain.

I guess for me and those that aren't speed readers.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Now linked to autoscroll time interval setting.

**Comment by DROIDshield** [comment]
Thats great, I can see the difference... thanks for your time and efforts.
