### ISSUE TITLE
[Request] Display video metadata info when information icon is selected

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.arctic.horizon.2#85]
Is it possible to instead of displaying the video metadata when pausing the content, display it along side cast and episode plot when the Information icon is selected that way we can quickly take a peak without having to completely pause the content being watched. I'll leave two screenshots below so you can have a better clue of what I mean.

![image](https://user-images.githubusercontent.com/76958541/172258472-31ff5bff-346a-4327-be9a-e44b225a6049.jpeg)

![image](https://user-images.githubusercontent.com/76958541/172258484-46401041-6d62-4450-a385-a85a1c011062.jpeg)

**Comment by jurialmunkey** [comment]
No it would be too cluttered.

You can view seekbar with codecs by pressing info
