### ISSUE TITLE
Full screen widget will not auto scroll.

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.horizon.2#851]
### Skin section

Home Widgets

### Current Behavior

The gone screen widget does not auto scroll since the last update. 

### Expected Behavior

When main menu icon is highlighted the full screen should scroll.
![20230304_184318](https://user-images.githubusercontent.com/97023369/222923362-97eb12ee-1800-4761-818f-3c0a21352fde.jpg)

### Steps To Reproduce

Select main window icon, this should trigger the auto scroll after the set seconds.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Yes, I've noticed the same issue too after the latest update.

**Comment by adamosborne83** [comment]
I mentioned this earlier, Jurial has fixed it for the next update, look at closed issues.

**Comment by AakashC2020** [comment]
> I mentioned this earlier, Jurial has fixed it for the next update, look at closed issues.

Hi @adamosborne83,

Yes, I noticed it now under closed issues. Thanks to you and @jurialmunkey!
