### ISSUE TITLE
[BUG] links dont play when selected and no play option in context menu

### ISSUE THREAD

**Issue by Mahava** [jurialmunkey/skin.arctic.horizon.2#853]
### Skin section

Video Info Dialog

### Current Behavior

In addon, links to media do not play when selected or clicked and theres no play option in the context menu for the link.

I asked the addon developer and he told me to use another skin.  Could this be a skin issue?

Fyi, they do play in another skin.. Estuary mod v2

Im on windows and am using latest version of everything.

### Expected Behavior

I expect links to play when clicked/ selected

### Steps To Reproduce

Click on a link in releasehub or release bb

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Skin doesn't control context menu.

You probably set the wrong content type. Make sure content type is videos.

**Comment by Mahava** [comment]
do they play for you?  IF SO WHAT SETTING DO YOU USE.   I DONT KNOW WHAT YOU MEAN BY SETTING CONTENT AS VIDEO?  DO YOU MEAN VIEW MODE?  TRIED IN SKIN SETTINGS BUT NOTHING WORKS.   THIS ISNT A WIDGET, BTW.

TRIED EVERY VIEWTYPE LISTED.  ADDON HAS VIEWTYPE SETTING THAT ASKS FOR NUMBER, EG 500.  WHAT NUMBER DO I PUT THERE FOR VIDEOS?  I PRESUME ITS ASKING FOR SKIN VIEWTYPE NUMBER.

**Comment by jurialmunkey** [comment]
Man calm down with the all caps.

I don't use this addon but skins do not control playback. 

Check your menu configuration. You likely setup a widget or shortcut to use programs content when it should be videos. If you send content to programs then Kodi will treat it like a program and it won't play. 

If that's not the problem then you're going to have to be clearer about how to reproduce it. Screenshots help.

**Comment by Mahava** [comment]
IM NOT A MAN.  CAPS ARENT AN INDICATION OF MY MOOD IM TRYING TO TPE ON A PHONE WHICH IS STUCK ON CAPS.  IS IT OFFENSIVE?  MY APOLOGIES.

I CHECKED THE ADDON SHORTCUT PER YOUR HINT,  IT WAS SET AS SQUARES AND ADDONS.  CHANGED TO VIDEOS AND IT WORKED!    I WASNT AWARE THAT THIS SETTING WOULD HAVE AN EFFECT ONCE I WAS INSIDE THE ADDON ITSELF.

THANKS JURIALMUNKEY!
