### ISSUE TITLE
[BUG] Clearlogos on episode images in Media Info List view still appearing after latest update

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.horizon.2#854]
### Skin section

Library Views

### Current Behavior

Hi @jurialmunkey,

This is regarding my issue #791. I noticed that you closed it as completed, but the clearlogos are still appearing on the episode images in the Media Info List View. Do I need to change any "new" setting to make them disappear? Please see attached screenshots and kindly advise.

### Expected Behavior

Clearlogos shouldn't appear on the episode images after the latest update.

### Steps To Reproduce

Go to TV Shows -> Library Views of Episodes -> Change to Media Info List View. The images of the episodes beside the Poster will have large clearlogos on them.

### Screenshots and Additional Info

![IMG20230305005845](https://user-images.githubusercontent.com/65297828/222934233-beac943b-5366-49ca-9217-f0f0a0ba5a94.jpg)

![IMG20230305005821](https://user-images.githubusercontent.com/65297828/222934238-8716f1f7-3d51-46fb-987f-b0951334f411.jpg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah, I forgot that Media Info List has a separate media info panel definition from Media Info *Play*List. Meant to change both.

**Comment by AakashC2020** [comment]
Thank you @jurialmunkey !
