### ISSUE TITLE
[Feature] Allow EPGEventIcon to be fallback artwork in the EPG

### ISSUE THREAD

**Issue by pakraider** [jurialmunkey/skin.arctic.horizon.2#855]
### Skin section

PVR and Live TV

### Feature description

If the "EPGEventIcon for PVR fanart" option is enabled, EPGEventIcon should be available as a fallback for artwork in the EPG.

### Why is this feature needed? Please justify and explain.

Many of my PVR programs do not have any online artwork available, but nearly all have an EPGEventIcon from the PVR backend which would do great as a fallback. Online artwork is higher quality, so I would still want that as the top priority when it's available.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
v0.8.21 of the skin + v5.1.11 of TMDbHelper will enable use of EPGEventIcon for blur/flixart if no online fanart found (and EPGEventIcon is enabled).
