### ISSUE TITLE
[BUG] Short Description

### ISSUE THREAD

**Issue by Foze11** [jurialmunkey/skin.arctic.horizon.2#856]
### Skin section

Fullscreen Video OSD

### Current Behavior

Was watching Hunter X hunter first season. And when i pause the show the anime logo displays just fine. Finished season 1 and when i started watching season 2 i noticed that there is no anime logo just the title name, i am using Plex Kodi connect addon. But some people on the forums reported they have this bug without PKC 

### Expected Behavior

Display of the anime logo

### Steps To Reproduce

1. Start season 1 
2. Logo there
3. Start season 2
4. No logo (just title)

### Screenshots and Additional Info

![A4752EBC-A177-4F7A-BBD0-EAD4174F9E49](https://user-images.githubusercontent.com/127034392/222966536-7e755504-3eac-4534-bc38-45df4f0c4b7e.jpeg)
![C595A31A-8CF4-4AC7-BAB4-5A3E9DE0515C](https://user-images.githubusercontent.com/127034392/222966542-025434cc-234d-4da1-8224-74d2595f4ed8.jpeg)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Kayzels** [comment]
I can report something similar happening regarding clearlogos. Most likely related to something in TMDbHelper. 

Playing directly from the addon shows the clearlogo correctly. Playing from the TMDbHelper player shows the show title for a few seconds. Instead of then showing the clearlogo, the show title then disappears, and just the episode name is shown.

**Comment by Foze11** [comment]
Is there a chance this will get fixed ?

**Comment by jurialmunkey** [comment]
Episode numbering does not match TMDb for Season 2:
https://www.themoviedb.org/tv/46298-hunter-x-hunter/season/2

There is no such episode 2x02 on TMDb. 
TMDbHelper will not be able to find this episode because it does not exist on TMDb

If you want TMDbHelper to lookup artwork for you then you need to make sure the details supplied match what is on the the TMDb website. 

Alternatively, you need to setup PKC to supply its own artwork.

**Comment by Foze11** [comment]
> Episode numbering does not match TMDb for Season 2: https://www.themoviedb.org/tv/46298-hunter-x-hunter/season/2
> 
> There is no such episode 2x02 on TMDb. TMDbHelper will not be able to find this episode because it does not exist on TMDb
> 
> If you want TMDbHelper to lookup artwork for you then you need to make sure the details supplied match what is on the the TMDb website.
> 
> Alternatively, you need to setup PKC to supply its own artwork.

Oh right. When using sonarr for renaming it was following tvdb for episode numbering not tmdb 

can you just point me to how i can get PKC to supply its own artwork ? Sorry if asking too much

**Comment by jurialmunkey** [comment]
> can you just point me to how i can get PKC to supply its own artwork ? Sorry if asking too much

I don't use PKC so I don't know.

Point is that if the addon/library etc. supplies its own artwork then TMDbHelper will use that artwork first, so even if it doesn't match you should still get artwork.

**Comment by Foze11** [comment]
> > can you just point me to how i can get PKC to supply its own artwork ? Sorry if asking too much
> 
> I don't use PKC so I don't know.
> 
> Point is that if the addon/library etc. supplies its own artwork then TMDbHelper will use that artwork first, so even if it doesn't match you should still get artwork.

Alright dude tysm i appreciate all the help. The artworks and everything is there its just the logo, i think my problem comes from using normal episode numbering like s02e01 unlike how tmdb uses its episode numbering it continues the number. So like season 1 finale episode 55 season 2 starts with 56 :(

**Comment by jurialmunkey** [comment]
@Foze11 - Make sure that you're using most recent version of TMDbHelper (v5.1.6 on Nexus). If you've got the artwork for the logo in PKC then that version should make sure you still get artwork properties in the video player even if the lookup fails because of the numbering mismatch.

**Comment by Foze11** [comment]
> @Foze11 - Make sure that you're using most recent version of TMDbHelper (v5.1.6 on Nexus). If you've got the artwork for the logo in PKC then that version should make sure you still get artwork properties in the video player even if the lookup fails because of the numbering mismatch.

Lets goooo. New update did it, tysm man
