### ISSUE TITLE
[BUG] TV Show status date not displaying day and month

### ISSUE THREAD

**Issue by 0x464e** [jurialmunkey/skin.arctic.horizon.2#860]
### Skin section

Library Views

### Current Behavior

The ended/cancelled/returning etc date for tv shows or tv show episodes only always shows -d.-m.year, where year is the correct year, but day and month don't work. Weirdly enough, for movies there doesn't seem to be any problem however.

![Kodinerds_20230309_024806](https://user-images.githubusercontent.com/36742501/223886718-fe2d0ac5-41b6-41b8-8d31-f12f7e5b2656.png)

### Expected Behavior

It should properly show day and month, as it does for movies.

### Steps To Reproduce

Have some TV shows and try to see the date.

### Screenshots and Additional Info

I'm on Nvidia Shield using PlexKodiConnect, if that could somehow affect this.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Some regional short date formats in Kodi are incompatible with python date time module on some OSes

Change your Region short format date settings
`Interface Settings > Regional > Short date format`

Then delete TMDb API cache in TMDbHelper
`TMDbHelper Settings > Expert > Delete cache > Delete TMDb cache`

As long as you use a "normal" regional short format like dd/mm/yyyy or dd-mm-yy etc. then it should work.

**Comment by jurialmunkey** [comment]
"dd.mm.yyyy"  should work fine. The dots aren't the problem. It's just something in your regional formatting has a weird "-d" which is not something supported by the python datetime module on your OS. 

I'm not even quite sure what that "-d" is meant to do compared to "d". It obviously has some special function but not sure what. By "normal" I just mean it uses normal date formatting characters and not special ones like that.

**Comment by 0x464e** [comment]
There are three different short date formats in Kodi regional settings that use dots and none of them work for TV shows.
