### ISSUE TITLE
[Feature] show number items in a view list

### ISSUE THREAD

**Issue by haivu87** [jurialmunkey/skin.arctic.horizon.2#861]
### Skin section

Library Views

### Feature description

would you could add an option to show number of total media items ( for example : all movies, all animation movies, all tv show, all music albums ...) in a media playlist view ?

### Why is this feature needed? Please justify and explain.

i think its a basic feature

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
focus the scrollbar and the number of items in the list displays with the clock.
