### ISSUE TITLE
BLUE LINE WHEN STREAMING 4K CONTENT WITH DXVA 

### ISSUE THREAD

**Issue by Gnreux** [jurialmunkey/skin.arctic.horizon.2#862]
### Skin section

Fullscreen Video OSD

### Current Behavior

- When watching 4k HDR content with DXVA as the render method, a blue line, either horizontal or vertical, appears on bottom or right edge of video;

- 1080p and 4k non-HDR content is unaffected;

- Choosing "pixel shader" as the player's video render method fixes the issue;

- Using the same add-ons to scrap and stream with Estuary as a skin fixes the issue;

- Local videos are affected as well when using AH2.

### Expected Behavior

Being able to stream 4K HDR content with "Auto detect" or DXVA as the render method and without any visual glitch. 

### Steps To Reproduce

1. Pick any HDR 4k video, either through a local library or through a scrapping add-on like Fen, Seren or Umbrella;
2. Have it played in the internal player with default settings for display and player;
3. Observe a blue line on the edge of the video when watching on internal display. 

### Screenshots and Additional Info

[Log when playing 4k HDR video through TMDB helper, Trakt and Fen with DXVA as the render method and AH2 as a skin](https://paste.kodi.tv/iduvuzasuf.kodi)

[Screenshots of blue line (zoom in)](https://imgur.com/a/bQPul0L)

############################################################

[Log when playing 4k HDR video through TMDB helper, Trakt and Fen with DXVA as the render method and Estuary as a skin](https://paste.kodi.tv/cicequpago.kodi)

[Screenshots of normal behavior](https://imgur.com/a/sRMOKjt)

#############################################################

[More blue line examples](https://imgur.com/a/aTFmTzQ)

#############################################################

**Setup :**
LENOVO YOGA 9I 14IAP7 [82LU0047US]
Processor    12th Gen Intel® Core™ i7-1260P   2.10 GHz
Installed RAM    16,0 GB (15,7 GB usable)
System type    64-bit operating system, x64-based processor

NO EXTERNAL DISPLAY
[See display/gpu information](https://imgur.com/5wsgIge)

Windows 11 Home
Version    22H2
Installed on    ‎2023-‎02-‎25
OS build    22621.1344
Serial number    PF474L4D
Experience    Windows Feature Experience Pack 1000.22639.1000.0

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't see the issue you're talking about. I can't see any blue line...

**Comment by jurialmunkey** [comment]
Ah I can see it in your second set of screenshots but not the first set.

This looks like a rendering issue, not a skin issue per se. I don't doubt that something in this skin which is not in Estuary is triggering the issue but the problem itself is not the skin.

> Choosing "pixel shader" as the player's video render method fixes the issue;

Why not use pixel shaders then? They produce better quality images than DXVA.
