### ISSUE TITLE
[Feature] tv sort by newest episode airdate

### ISSUE THREAD

**Issue by A3006B** [jurialmunkey/skin.arctic.horizon.2#863]
### Skin section

Home Widgets

### Feature description

Is it possible to add an option to sort tv widgets by the newest episode airdate?

### Why is this feature needed? Please justify and explain.

Would be really useful to see tv shows by which ones are currently airing new episodes.

there is an option to sort by date added, but if whole tv shows are added after they air it throws the ordering off.
There is also already an option for year, but it means long running tv shows that are still airing are at the bottom of the list.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
All available sort methods are provided already, so no not possible
https://kodi.wiki/view/List_of_built-in_functions#List_of_sort_methods

The skin doesn't (and is unable to) sort anything. It only tells Kodi which sort method to use. If you can't sort the way you want using the available methods then it's not possible without writing your own plugin.
