### ISSUE TITLE
[Feature] Enhanced Stacked Widgets

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.horizon.2#864]
### Skin section

Home Widgets

### Feature description

The newly introduced stacked widgets (content based on the above selected item) works flawlessly. This feature is unique to AH2 and sets it apart from other skins.

I would like to propose a feature/improvement that will take the stacked widgets to the next level.

> My proposal is to have 2 types of widgets:
1- Master widgets : This widget would behave as if it was a filter for the Child Widgets underneath it. 
2- Child widgets : This type is the stacked widget that will use the selected item in the above “Master Widget” to be used in filtering out the child/stacked widget data.

By having it as a type, we can have **multiple** stacked widgets, that loads up based on **one** Master widget selection. 

###  Current Implementation ; 
1. Stacked Widget is populated based on the widget above.
2. The stacked widget displays the exact content of the selected item in widget above it.

### Proposed Implementation : 
1. Stacked Widgets are populated based on the preceding master widget.
2. The stacked widgets display filtered lists based on the selection in the master widget and not its content.

If this feature to be implemented, some modifications to TMDB helper are needed in order to achieve the full potential. The discover functionality needs to be flexible enough to adopt the new input from the master widget.

First use case,
-   Imagine having “Movie Genres” master widget.
-   Having 3 child widgets underneath it:
1. Trending (where genre={master widget selection})
2. Most watched (where genre={master widget selection})
3. Custom Widget from Discover functionality. To filter movies. For example; movies with lang=en, rating>6, mpa=PG,PG-13, year>1990, and genre={Master widget selected item}
D

Second use case,
1. Imagine having “TV Shows Genres” master widget.
2. Studios - Child widget (where genre={master widget selection}
3. Lets say you selected "Action" in point 1, and "Netflix" in point 2
4. Now add a third child widget, that loads up TV shows with Action, and Netflix as filters in the Genre, and Studio sections. 

> The whole idea is to enable the user to navigate his way to find the movie/tv show his looking for. 

The same logic can be applied if you create a “Years” master widget, or a “Studio” master widget, etc

By doing this, the user will have (Tabs) like behavior, where the content of the rest of the page (Child widgets) will respond to the selection from the master widget (filters widget)

Finally, i think this would enable a 2 dimensional way of navigating the home screen instead of the current 1 dimensional and linear browsing experience. Currently if you click on a genre, you see a full list of the genre’s movies, after this proposal, you can filter out these results by adding filters widgets (Master widgets); 

You can have:
Most watched horror movies
Top rated horror movies
Recently added horror movies
etc. 

and when the user selects Action genre, 
Most watched action movies
Top rated action movies
Recently added action movies

After-all, I think the experience is determined by how easy the user can find a movie to watch and this is a step in the right direction.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Mr-7mdan** [comment]
@jurialmunkey any hope for this?

**Comment by Mr-7mdan** [comment]
@jurialmunkey, In Arctic Fuse, similar functionality is available via the discover feature. I hope it is not difficult to port this feature to AH2

**Comment by jurialmunkey** [comment]
It is quite complicated and only really possible in Fuse because I planned for it from the start.

**Comment by Mr-7mdan** [comment]
> It is quite complicated and only really possible in Fuse because I planned for it from the start.

Thanks
