### ISSUE TITLE
PVR Landscape style view

### ISSUE THREAD

**Issue by r95sguy** [jurialmunkey/skin.arctic.horizon.2#871]
### Skin section

PVR and Live TV

### Feature description

Currently, PVR landscape widgets displays EPGEventicon which is great, but it's left blank in case EPGEventicon is not available. Would it be possible to make it show channel logo in case EPGEventicon is not available (e.g. sports, news)?

### Why is this feature needed? Please justify and explain.

Widgets would look better

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Already displays channel icons for me if epgeventicon is empty. Check your pvr settings.

**Comment by r95sguy** [comment]
I have just checked the XML files, and I think you are right, it should display channel icon if epgeventicon is empty according to "Image_Landscape" variable settings, but I have no idea why this is not working. It would display channel icon in square and poster styles, but not in landscape. The same issue is also under PVR OSD.

**Comment by jurialmunkey** [comment]
> It would display channel icon in square and poster styles, but not in landscape. 

Either your PVR backend, PVR client, or Kodi PVR settings are adding a filename for ListItem.Art(thumb) but the actual file doesn't exist (same is also possible for fanart/landscape but most likely I expect thumb). 

Skins cannot check if a file exists. It can only check if the metadata listing a filepath or url for that artwork type is empty or not. The reason it works for Square or Poster is because those only use Icon and never Art(thumb).

**Comment by r95sguy** [comment]
That makes sense, it must be related to PVR backend/ client, but is there a way to prioritize icon over art(thumb)? Guidance would be appreciated. Thanks!

**Comment by jurialmunkey** [comment]
> That makes sense, it must be related to PVR backend/ client, but is there a way to prioritize icon over art(thumb)? Guidance would be appreciated. Thanks!

Landscape prioritises thumb over icon because thumbs are meant to be 16:9 and icons are not. 

This needs to be fixed in the PVR client, not the skin.
