### ISSUE TITLE
[BUG] Scaling seekbar wrong

### ISSUE THREAD

**Issue by Skiedl** [jurialmunkey/skin.arctic.horizon.2#872]
### Skin section

Fullscreen Video OSD

### Current Behavior

When displaying any kind of content and using the seekbar to skip ahead or go backward near the beginning or the end of the displayed content it behaves like the seekbar should be shorter compared to the dot that seeks as seen in the pictures attached. 

This behaviour started since the version 0.7.28 and I tested it on Windows 10 running Kodi 20.1 and a Nvidia Shield running Kodi 19.5.

### Expected Behavior

The dot on the seekbar to scale better compared to the seekbar itself.

### Steps To Reproduce

Watch any kind of content from any kind of device, let it be usb, nas or local storage.

### Screenshots and Additional Info

![Schermafbeelding 2023-03-15 223751](https://user-images.githubusercontent.com/98761422/225450225-65c3996b-5b80-4cb3-af28-24d6fcf2446d.png)
![Schermafbeelding 2023-03-15 223915](https://user-images.githubusercontent.com/98761422/225450244-4790995f-6a24-452c-8fb1-72c261241a02.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Been meaning to fix this for ages. Should be much better now. Will be added to next release (v0.8.17)
