### ISSUE TITLE
[BUG] ActivateWindow(setting) not working

### ISSUE THREAD

**Issue by Jeanaimarre** [jurialmunkey/skin.arctic.horizon.2#875]
### Skin section

Other

### Current Behavior

Good morning

 I had artic1 before and I need to access the librelec settings (in order to go to the system menu to connect the bluetooth) but impossible from artic2 to access it. Indeed, in the artic2 there is a bug the ActivateWindow(setting) is the same as the ActivateWindow(interfacesetting) which means that I cannot access the real librelec settings

### Expected Behavior

Nothing happenn

### Steps To Reproduce

ActivateWindow(setting) is the same as the ActivateWindow(interfacesetting) 

### Screenshots and Additional Info

I have librelec Kodi 19.3 on RI4

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Programs > LibreELEC Settings.
