### ISSUE TITLE
[Feature] Glass / Transparent menu & dialog

### ISSUE THREAD

**Issue by aseanic** [jurialmunkey/skin.arctic.horizon.2#878]
### Skin section

Other

### Feature description

I see the last update v.0.8.17, the top menu has been changed to transparent which look very nice. i wonder if all the dialog and scroll down menu will be transparent or glass too?

### Why is this feature needed? Please justify and explain.

The whole AH2 skin is based on dark theme, but the dialog and menu are in light theme like in Arctic Zephyr on light theme. Kinda ummatch.

### Screenshots and Additional Info

![Presentation1](https://user-images.githubusercontent.com/79122869/226509570-f054dd1a-d4eb-4c7f-9ed9-d64c14ab3f9f.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can change the colour scheme for dialogs to dark in interface settings.

There are no plans for transparent dialogs as the readability will be poor and Kodi doesn't have a dynamic blur ability.
