### ISSUE TITLE
[Feature] 4 Thumbnails for Chapter / Bookmark / Channel / EPG instead of 3  

### ISSUE THREAD

**Issue by aseanic** [jurialmunkey/skin.arctic.horizon.2#879]
### Skin section

Other

### Feature description

The Chapter/ Bookmark / Channel / EPG thumbnail which appear below the control when we press up looks weird and unbalanced with only 3 tiles. The empty space can fit for another tile and make it look more appealing.

### Why is this feature needed? Please justify and explain.

To symmetrically balanced look for the tiles else it looks like a missing thumbnail.

### Screenshots and Additional Info

![2](https://user-images.githubusercontent.com/79122869/226512896-e41e1813-d13c-46e5-974b-7decab4fd3cc.jpg)
![1](https://user-images.githubusercontent.com/79122869/226512899-b5d5c4c7-bf09-44d9-bab6-1a77303d16e5.jpg)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Mr-7mdan** [comment]
It is funny since I never had thumbnails in the Chapters section. It is always empty (transparent). Maybe it is another bug on my system. 
I am using Kodi 19.3 for tvOS (Apple TV 4K 2021 / tvOS 16.3.1)

**Comment by jurialmunkey** [comment]
Not possible without significantly altering the skin design or breaking important elements.

The sizing of the episode thumbs is necessary to maintain consistent spacing of the seekbar. Changing the width of the items will also change their height which will then not fit correctly in the space. If the height of the seekbar slide is changed to accomodate it will then impact other parts of the seekbar such as cast list.
