### ISSUE TITLE
[Feature] Animated Discart & ClearArt Placement

### ISSUE THREAD

**Issue by aseanic** [jurialmunkey/skin.arctic.horizon.2#880]
### Skin section

Music Visualisation OSD

### Feature description

Could you implement the Animated Discart and ClearArt on the lyric nowplaying display with placement as per below pictures

### Why is this feature needed? Please justify and explain.

It will look more elegant and classy. Currently no animated discart and no clearArt on the lyric nowplaying display.

### Screenshots and Additional Info

**Example Placement 1**
![Slide1](https://user-images.githubusercontent.com/79122869/226885903-50d5fee8-e2a5-4321-9e6c-a8e4b0366a4f.PNG)
**Example Placement 2**
![Slide2](https://user-images.githubusercontent.com/79122869/226885941-9c34b718-7009-44ba-94d1-d6aaca31da24.PNG)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry not planning to add clearart to OSD.

The discart is not possible due to the way the zoom animation works to transition the cover from small to large.
