### ISSUE TITLE
[BUG] RSS Feeds do not show on skin even if item is enabled

### ISSUE THREAD

**Issue by beanbaganalytica** [jurialmunkey/skin.arctic.horizon.2#882]
### Skin section

Home Widgets

### Current Behavior

No RSS Feeds showing

### Expected Behavior

RSS Feeds should scroll somewhere

### Steps To Reproduce

1. Enable RSS Feeds

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Sorry RSS feeds are not supported in this skin and don't plan on including them.
