### ISSUE TITLE
[Feature] Add an average rating

### ISSUE THREAD

**Issue by daviddia5** [jurialmunkey/skin.arctic.horizon.2#885]
### Skin section

Video Info Dialog

### Feature description

Add an average rating for a movie or tv series

### Why is this feature needed? Please justify and explain.

We can see an average rating of all available. This way we get a more precise idea at a single glance.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skins can't do any math, so this is unfortunately not possible.
