### ISSUE TITLE
Details/ customise ratings

### ISSUE THREAD

**Issue by SirRickie** [jurialmunkey/skin.arctic.horizon.2#889]
### Skin section

Home Widgets

### Feature description

In skinsettings/details/customise ratings, I have enabled the ratings : Metacritic TV shows/RT user TV shows/RT critic TV shows. But these ratings don't show up in the infoline of the items in my library (the icon of these three shows up in the infoline, but rating is displayed as %). And the shows have indeed ratings on RT and Meta websites. Do I miss a certain setting somewhere ? Or can they not be displayed ? Tnx.

### Why is this feature needed? Please justify and explain.

Is always great to have as much ratings possible.

### Screenshots and Additional Info

![Schermopname (81)](https://user-images.githubusercontent.com/60318531/227789454-273381de-8ffb-42ae-ab11-435c8e897126.png)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by adamosborne83** [comment]
That means that OMDB api does not have any information for those, yet. If you do not like it there, in the option to disable and enable ratings, at the top, I believe its called place holder ratings, or something to that effect, I'm not at TV at the moment. Then if I does not gace the rating the place holder will not show up.

**Comment by xyzfre** [comment]
There's a new API feature in TMDb H to get extra TV show ratings and Movie Letterboxd ratings but you must enter your mdblist API key in settings

**Comment by SirRickie** [comment]
> That means that OMDB api does not have any information for those, yet. If you do not like it there, in the option to disable and enable ratings, at the top, I believe its called place holder ratings, or something to that effect, I'm not at TV at the moment. Then if I does not gace the rating the place holder will not show up.

Tnx.

**Comment by SirRickie** [comment]
> There's a new API feature in TMDb H to get extra TV show ratings and Movie Letterboxd ratings but you must enter your mdblist API key in settings

Tnx. I will try this.

**Comment by xyzfre** [comment]
Just keep in mind on my end after adding the mdblist API Key it took about 24 hours to generate all the ratings ,the next day is when I started getting all ratings for TV shows and the extra Letterboxd for Movies but it's worth waiting they look AMAZING I love seeing ratings myself ,, this is a really GREAT feature jurialmunkey added AH2 is the best skin💯

**Comment by jurialmunkey** [comment]
Yes these need mdblist. Please see first page of AH2 thread on kodi forum.
