### ISSUE TITLE
The settings made in the "customize appearance" menu are not saved.

### ISSUE THREAD

**Issue by OCHSPB** [jurialmunkey/skin.arctic.horizon.2#89]
The settings made in the "customize appearance" menu are not saved. After restarting the application or changing the skin, they are reset to standard. In other menus, the settings are saved correctly.
Kodi 19.4 on NVIDIA Shield and Windows 8

**Comment by jurialmunkey** [comment]
Did you Quit Kodi properly? If you force quit or restart then skin settings are not saved. That skin can't do anything about this as Kodi manages when settings are saved.

**Comment by OCHSPB** [comment]
Of course, I close KODI by selecting "Quit".
Skin settings are not saved only in this submenu. The rest are saved as usual. After closing KODI, the skin settings file contains all the selected items, but after initialization it returns to some default form.

**Comment by jurialmunkey** [comment]
Could you try v0.1.14 and see if that fixes it?
https://github.com/jurialmunkey/skin.arctic.horizon.2/releases/tag/v0.1.14
