### ISSUE TITLE
[Feature] Option to revert back to frame advance functionality on paused Fullscreen Video OSD

### ISSUE THREAD

**Issue by admiral-aqua** [jurialmunkey/skin.arctic.horizon.2#891]
### Skin section

Fullscreen Video OSD

### Feature description

I hope I do this correctly, I just made this account. 
First of all, great project, best skin I've used so far, thanks for the hard work! 
One thing that would be great though would be an option to revert back to the behavior of the OSD the way the original Estuary skin handles pressing up on it. So instead of opening the Payback Speed menu, accessing the frame advance functionality.

**Here is what happens in Estuary:**
![signal-2023-03-27-222448](https://user-images.githubusercontent.com/129110225/228061500-9d53a220-c8c2-4954-9f77-45c359466e1f.jpeg)

**Here is what happens in AH2:**
![signal-2023-03-27-222522_002](https://user-images.githubusercontent.com/129110225/228061594-8ae4d905-e2fc-45c7-85cb-063234432cb9.jpeg)

### Why is this feature needed? Please justify and explain.

To have greater control over the playback and not miss details, although I currently have a second profile set up with the standard skin to switch to while paused, so it's definitely not a super pressing issue, but if it would be possible and not too much of a hassle to implement this I and I'm sure some other users would greatly appreciate it. There very well may be a good reason for why it's not included, if so I apologize in advance and also if there is an easier way I can do it myself I apologize I was not able to find anything on it. I'll be the first to admit that I can get a a bit overwhelmed with all the menus and addon menus within kodi.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can already do this. Move to one of the 10 second frame skip buttons and press up.

Also you don't even need to open osd to frame skip. Pressing left/right on remote without osd active should do adaptive seek (though I understand seekbar gives a bit more finer control)

**Comment by admiral-aqua** [comment]
I just looked and I can't find the single frame advance function

**Comment by jurialmunkey** [comment]
Oh I see, so this is a feature which is only enabled when the video is paused correct?
