### ISSUE TITLE
Critic Ratings Showing as “- -“ for most rating agencies.

### ISSUE THREAD

**Issue by beanbaganalytica** [jurialmunkey/skin.arctic.horizon.2#895]
### Skin section

Video Info Dialog

### Current Behavior

Currently all Rotten Tomatoes/ IMDB critic ratings have no value. I am unsure if this is the skin, or would I need to get a different addon to pull this info.

### Expected Behavior

Show Movie/ TV Shows rotten tomatoes and IMDB ratings.

### Steps To Reproduce

1. Look at item
2. Rotten Tomatoes/ IMDB rating is NULL

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
![image](https://user-images.githubusercontent.com/49699869/229373636-22c96531-fc10-45b2-8173-f136c77572ad.jpeg)

**Comment by xyzfre** [comment]
Arctic Horizon 2 Kodi Forum tells you all the instructions you need to know

**Comment by xyzfre** [comment]
In TMDb Helper settings you need to enter all your APIs to get these ratings

**Comment by beanbaganalytica** [comment]
Thank you!
