### ISSUE TITLE
[Feature] Show library statistics in title

### ISSUE THREAD

**Issue by Gorge-1** [jurialmunkey/skin.arctic.horizon.2#900]
### Skin section

Library Views

### Feature description

Add statistics to the title of the different views.
Something like **Total Movies: xxx / Watched: xxx / Unwatched: xxx**
Same for TV Shows and Music.

### Why is this feature needed? Please justify and explain.

Now the title of views just says "Titles" with no more information. Would be cool to add some useful information to this unused screenspace.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can already see the total number of items in the view by focusing the scrollbar. The date field in the clock will change to display the number of items and number of pages.

Above commit will add unwatched/watched counts to the button toggling whether watched items are visible.
