### ISSUE TITLE
[Feature] Submenu Search

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon.2#904]
### Skin section

Home Widgets

### Feature description

The submenu search is not working properly I reckon. Please see the screen record.
https://streamable.com/5d6a0u

### Why is this feature needed? Please justify and explain.

When I trigger search for the 2nd time it brings me to search result from the 1st time. I would expect the search keyboard to reappear so that I can initiate a new search.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Kodi caches the last opened directory in MyVideoNav, so if you reopen the MyVideoNav window to the same directory it will not refresh the path.

If this is for TMDbHelper, see this comment for a solution:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/523#issuecomment-1454925240

If this is another plugin, speak to the plugin author about a solution. However, the above will probably work for other plugins using a kwargs style url path (e.g. ?key=value&key=value style path) and they don't use the reload= param for something else.

**Comment by onlytanmoy** [comment]
Thanks for the solution mate, I am using TMDbHelper so all good now :)

If you watch this screen record https://streamable.com/b10h6b at around 0:50 you will notice after entering the search string when I press Done, the Keyboard pops up again and I need to press Done one more time before the results get displayed.
I have noticed this earlier too so nothing to do with the reload param.
Have you observed this before too? Any fix if so?
