### ISSUE TITLE
Nexus required?

### ISSUE THREAD

**Issue by C-O-D** [jurialmunkey/skin.arctic.horizon.2#907]
### Skin section

Other

### Feature description

(Sorry for posting this here but the forum doesn't work atm)
So we have to upgrade to Nexus to continue installing AH2 updates because TMDB Helper requires it?
That would be a pity, because Nexus is not (yet) running correctly on my RockPi 4B and I have to wait until this is fixed...

### Why is this feature needed? Please justify and explain.

Nexus is not (yet) running correctly on my RockPi 4B and I have to wait until this is fixed...

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Yes, Nexus is now required. It is too difficult for me to maintain independent versions of the skin.

I already stopped skin support for Matrix and stopped backporting changes for TMDbHelper to the Matrix version several weeks ago, it just wasn't enforced as a strict requirement until I needed to bump the depedency requirement to fix an issue.

Likely you can still get away with running on Matrix if you modify the addon.xml to allow a lower version of TMDbHelper but I can't offer support or bugfixes for Matrix any longer as it has reached a point where backporting isn't really feasible anymore.

**Comment by C-O-D** [comment]
Thanks for clarifying!
