### ISSUE TITLE
[Feature] Viewtype for only text addon

### ISSUE THREAD

**Issue by rbb91** [jurialmunkey/skin.arctic.horizon.2#908]
### Skin section

Addon Views

### Feature description

Hello! I'm making my skin and it gives me a problem with one addon. When I start it gives me an error and I think it comes from not having images in the menus and only having a list, since when I try to modify the viewtype it comes out empty, I change to another skin and if it works. How could I fix it? When I put a list-only widget, it loads me, but when I enter I have the same error again. Thank you

### Why is this feature needed? Please justify and explain.

I need an option to see an addon that only contains text

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What error?

**Comment by rbb91** [comment]
> ¿Qué error?

Good evening, first of all forgive me for my English. I use translator. 

It's not really a bug, the addon in question is "Torque lite". It is an addon that has phrases without image, such as "F1 races". So when you open the addon there is no way to access it, since the skin does not know how to display it. 

The Viewtype space in that add-on is empty and cannot be modified. This "bug" disappears when used in a widget with only text, but once you access anywhere in the menu, it appears blank again. 

I do not know if I could put the name of the Addon but I have seen that it was necessary. You can edit my message once you try it if you wish. Thank you! I look forward to your reply

**Comment by jurialmunkey** [comment]
I can't even install this addon. It is broken in every skin I try.

**Comment by rbb91** [comment]
> Ni siquiera puedo instalar este complemento. Se rompe en cada piel que intento.

Try in zephyr reloaded

**Comment by jurialmunkey** [comment]
Installing on Nexus via that repo. The addon will not open in any skin. The addon is broken.

**Comment by rbb91** [comment]
> Instalación en Nexus a través de ese repositorio. El complemento no se abrirá en ninguna piel. El complemento está roto.

Are you tried in zephyr reloaded?
![Screenshot_2023-04-15-09-03-43-12_e18329511ee9ae4541720d804dbbeba9](https://user-images.githubusercontent.com/4742651/232194165-ed63503a-01ab-4a8a-84ab-f933885c8309.jpg)

**Comment by jurialmunkey** [comment]
Yes.

The addon doesn't work at all. It doesn't matter which skin.
