### ISSUE TITLE
[BUG] Matrix Dependency issue between AH2 and TMDB helper

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.horizon.2#909]
### Skin section

Other

### Current Behavior

The latest version defines TMDB Helper 5.1.11 as a dependency. While people on Matrix cannot download it. Therefore, people on Mattix cannot update AH2 to the latest version because they cannot fulfill the dependency.

    <import addon="plugin.video.themoviedb.helper" version="5.0.52~nexus" />
    <import addon="plugin.video.themoviedb.helper" version="5.1.11~nexus" />

### Expected Behavior

To update normally 

### Steps To Reproduce

Try to update AH2 on Matrix.
max TMDB helper version available for Matrix is 5.05 i think

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/907
