### ISSUE TITLE
Reset reume point 

### ISSUE THREAD

**Issue by Dappakid13** [jurialmunkey/skin.arctic.horizon.2#911]
### Skin section

Home Widgets

### Current Behavior

Hello @jurialmunkey 

I have noticed for a few days whenever I try to reset the resume point from the homescreen or within trakt in tmdbhelper, nothing happens. I have the same issue on more than one device. I have tried logging out and authenticating trakt again, deleting cache in tmdb helper settings. I have to reset it in one of the addons.

### Expected Behavior

If I have a show in my in progress that I completed and I reset the resume point, that episode or movie progress is back at 0%.

### Steps To Reproduce

On homescreen or in the trakt section of tmdb helper widget go to your in progress widget.

Pull up the menu on that item (look for reset resume point).
It load and nothing happens.

### Screenshots and Additional Info

[download.txt](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/11242934/download.txt)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
What's this got to do with the skin?
