### ISSUE TITLE
[Feature] Season and Episode info on home screen widget

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.horizon.2#916]
### Skin section

Home Widgets

### Feature description

I'm just wondering if it would be possible to add some sort of info that shows the season and Episode when using homescreen landscape widgets for when we use next episodes, auramod used to have a similar thing 
![received_107951884470578](https://user-images.githubusercontent.com/76907836/233976902-9103ea22-86dc-4035-a6af-14f5f35eebfb.jpeg)
Similar to how this looks within the addon itself

Many thanks 

### Why is this feature needed? Please justify and explain.

Would be nice for this feature to be added instead of using other info views 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It already does show season and episode info...

![screenshot00314](https://user-images.githubusercontent.com/4618719/233998247-f333f246-69d5-408a-84e1-cd6d2a86c59e.jpg)

**Comment by JFG1000** [comment]
Could you please tell me what setting/widget type that is, as mine only tells me the name of the episode and not the season and number

**Comment by JFG1000** [comment]
Not to worry I've sorted it many thanks
