### ISSUE TITLE
[Usability] New adding sources setup is un-intuitive

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.horizon.2#92]
Took me five minutes to even figure out how to modify a video source. 

This is how it was in AH (And pretty much all kodi skins). Buttons for Browse etc to the right. 

![screenshot00026](https://user-images.githubusercontent.com/25871666/172383352-945b45fd-9deb-4efb-9eef-93a80c207b10.png)

In AH2 its now icons merged into the source text entry, which is ok I guess, but when you click on the source (as you do) it immediately brings up a text entry box.. 

![screenshot00027](https://user-images.githubusercontent.com/25871666/172383725-1645d631-df34-4949-a882-4a51fca0d1bf.png)

And the trouble is, with long source names (which is pretty common, for example my external drive is labelled HGST-HTS545050A7 lol), the icons are obscured

![screenshot00028](https://user-images.githubusercontent.com/25871666/172383974-aa95ec1c-2e5b-46c7-b3e6-ff845739fc06.png)

For this would suggest either the tried and tested approach from AH, or make browse the default action?

**Comment by jurialmunkey** [comment]
Ah this reminds me that I was meaning to change the layout of that dialog. I don't add new sources very often, so I forgot about it a bit.

Can you try 0.1.15 and see if you find the new layout more intuitive? I think it is much better now

**Comment by dm2912** [comment]
> 

yup, thats better. Especially with browse as default which for most will be the expected behaviour.
