### ISSUE TITLE
[Feature] Short Description

### ISSUE THREAD

**Issue by xXHexaKillXx** [jurialmunkey/skin.arctic.horizon.2#923]
### Skin section

Fonts and Languages

### Feature description

I would love to get speech to text working for non native language other than english. i would like to add vietnamese text to the speech to text feature support if possible.

### Why is this feature needed? Please justify and explain.

Would be helpful for user using a remote that has microphone support such as chromecast TV, and firestick and so on. The pain typing non native by pressing button and convert it to english. Would like a helping hand to enable it else if there is an existing request you can delete this request.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is outside the domain of the skin. Skins only control how Kodi looks and navigates. 

You would need to ask on the kodi forums about speech to text and the supported languages.
