### ISSUE TITLE
Allow Config of Custom Hub as a Sub menu Item

### ISSUE THREAD

**Issue by JSAKelley** [jurialmunkey/skin.arctic.horizon.2#925]
### Skin section

Other

### Feature description

Currently you can select Custom Hub as a path for a Submenu Item but you have no way of configuring it. 

### Why is this feature needed? Please justify and explain.

It would be nice to have a button on the submenu widget to be able to open a Custom Hub

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Unfortunately not possible. 

Widget configurations are essentially separate submenus configured with a different layout, so they must be tied to the mainmenu item. 

Skinshortcuts does not allow submenu items to have their own nested submenus.
