### ISSUE TITLE
[BUG] Local info recommendations: Movie Set navigation not working

### ISSUE THREAD

**Issue by TheTyrius** [jurialmunkey/skin.arctic.horizon.2#926]
### Skin section

Video Info Dialog

### Current Behavior

When selecting a movie from the list of movies from the same set, I get thrown to the top level "Video Library" screen instead of opening the movie info (my selected default action).

### Expected Behavior

Movie info opens.

### Steps To Reproduce

1. Select the behavior setting "use local library info for recommendations"
2. Go to a movie that is part of a set
3. Press "down" to get to the recommendations
4. Select a movie from the same set

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by TheTyrius** [comment]
I reproduced on a clean setup on a second PC, so I really hope it's not just me making a mistake. Logs are clean apart from `error <general>: XFILE::CDirectory::GetDirectory - Error getting videodb://movies/sets/X/Y?setid=X`

**Comment by jurialmunkey** [comment]
Pressing `Action(Info)` inside the video info dialog is hardcoded in Kodi to close the info dialog.

Changing default select action simply means pressing OK now does `Action(Info)` instead of `Action(Play)` so whenever you click an item in a list in the info dialog then Kodi will close the window.

**Comment by TheTyrius** [comment]
Just had time to apply your fix, working perfectly. Thanks for taking the time :)
It seems like the fanart (I use flixart) isn't loaded when browsing via (local) recommendations. Is this inherent with the method used, or could you have a look?

**Comment by TheTyrius** [comment]
@jurialmunkey can you check why fanart doesn't load when using the action you implemented in 7f21412b00bc727f9cfd3e6671496dab73feb948 ? If you can't just yet, maybe kindly reopen the issue so it doesn't get lost? :)
