### ISSUE TITLE
[BUG] Fullscreen widget not longer showing up in custom Hubs

### ISSUE THREAD

**Issue by JacopoV** [jurialmunkey/skin.arctic.horizon.2#932]
### Skin section

Home Widgets

### Current Behavior

Recently noticed the fullscreen widget in custom Hubs no longer shows the content. I tried also changing the content itself to be shown but it didn't help.

### Expected Behavior

As in previous release, the widget content should be shown as expected.

### Steps To Reproduce

1 create a custom hub
2 set a Fullscreen widget
3 navigate and enter the custom hub and see the widget not being displayed 

### Screenshots and Additional Info

Currently affecting version 0.8.23

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Was already fixed on main branch.
https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/931

**Comment by JacopoV** [comment]
@jurialmunkey oh apologies. when i looked thru the open tickets i didn't see that one. Thanks again
