### ISSUE TITLE
incorrect episode runtimes

### ISSUE THREAD

**Issue by rizreflects** [jurialmunkey/skin.arctic.horizon.2#933]
### Skin section

Other

### Current Behavior

Hey jurialmunkey, I hope you're doing well. I recently noticed that the episode run time for many shows are incorrect. If you take a look at a new show that recently came out called 'love & death', Arctic horizon displays the episode runtime as 30 mins. When checking on mdblist however, the episode runtime is actually 42 mins. Is this something you could possibly look into? I've noticed this problem with quite a few other shows aswell.

### Expected Behavior

 The episode runtimes to be correct. 

### Steps To Reproduce

View a show like love & death from the homescreen.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I don't understand what this has to do with the skin?

The runtime is whatever is listed in your library (or addon) for that item.
