### ISSUE TITLE
[Feature] Background image for each main menu item

### ISSUE THREAD

**Issue by satelly1** [jurialmunkey/skin.arctic.horizon.2#936]
### Skin section

Other

### Feature description

Request the option of being able to select a different background image/jpeg for each main menu item. This is separate to the current "customise background image" which is only a single image used for all purposes. This is a feature of previous skins by jurialmunkey, including the original AH1.

### Why is this feature needed? Please justify and explain.

For those who prefer a simple and minimalist home screen, the different background images helps quickly navigating between the different menu options.

### Screenshots and Additional Info

<img width="1041" alt="Background Option" src="https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/69080264/fe5aaa86-7c5b-42f8-9849-70d5f20d7847">

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can already set a background. Set a fullscreen widget with no other widgets and you will have a fanart background with nothing else onscreen except the menu bar.

The above commit fixes the fullscreen widget not displaying images for picture sources.

**Comment by satelly1** [comment]
Thank you for looking into this so quickly. I am now using the updated [Includes_Images.xml] file and it shows the full background picture as desired. I set up a new picture subfolder for each main menu item with only 1 picture stored as I want to keep a static picture. The only problem isthe picture "updates" every 5-10 seconds. the picture "slides" to the right and is replaced by the same picture. This would be good if there were multiple pictures, however I only have 1. Compared to the "background" option on AH1, the picture there stays and doesn't move.

**Comment by jurialmunkey** [comment]
Was a bug in the fullscreen background widget not honouring the autoscroll setting. Should be fixed now (assuming you disable autoscroll for the fullscreen widget).

**Comment by Arokhaerr** [comment]
I am sorry to necro this issue, but where do I select the image or folder source inside the fullscreen widget?
satelly1 got it working but it seems im missing something.. as conte t type I can set "picture" but I cannot select any paths or folders he mentioned. :(
