### ISSUE TITLE
black background "none" not as good looking as litebox

### ISSUE THREAD

**Issue by reitenth** [jurialmunkey/skin.arctic.horizon.2#939]
### Skin section

Library Views

### Feature description

i think the black background for "none" under appearance with netlfix corner fanart could use some work. i see the left edge of a lot of fanart whereas that doesnt exist with arctic zephyr reloaded using litebox blur. i think the gradient needs to go a bit further right and be more of a ( shape instead of the | it is now. 

### Why is this feature needed? Please justify and explain.

black backrond does not look at good as litebox in arctic zephyr reloaded.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Screenshots? Resolution? Steps to reproduce? I don't see the problem that you say there is.

Also I have no idea what litebox has to do with anything? If you want blur choose blur

**Comment by reitenth** [comment]
there is not a problem, the black background on 'none' just doesnt look as good as running a black background with litebox because it has a stronger gradient from background to fanart. litebox uses a black blur if you want a black background, i wouldnt even think of it as a blur. 

could u just point me to where the 'none' black background is in the code? i will change it fit my preferences myself. i think i can do that.

**Comment by jurialmunkey** [comment]
I still don't understand what litebox has to do with anything since it is used to do blur and you're talking about it being disabled.

Shows me screenshots of the issue so that I can understand the problem. Also your screen resolution is important because dimensions can change how kodi scales diffuse textures.

**Comment by reitenth** [comment]
![Kodi_20230616_200840](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/94771708/fd036c01-95cf-448b-a999-d04fa788bb2d)
![Kodi_20230616_200749](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/94771708/a6f4d046-35de-439d-9292-96739505ee44)
![Kodi_20230616_200616](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/94771708/366fb3d2-09cc-4cd8-b5ef-0a2dadf9641a)

**Comment by reitenth** [comment]
it has more of a curve ( as to not look like a sharp line. honestly, blur settings like litebox would an idea if possible.

**Comment by jurialmunkey** [comment]
Again... Litebox does not do diffuses. A diffuse texture is what is used to blend background and foreground. This has nothing to do with litebox.

**Comment by jurialmunkey** [comment]
What colour scheme do you have enabled? It looks like high contrast which will make the effect look worse. Use default if you want to blend to grey.
