### ISSUE TITLE
[BUG] Désactivation imprévu

### ISSUE THREAD

**Issue by Lucas67159** [jurialmunkey/skin.arctic.horizon.2#942]
### Skin section

Home Widgets

### Current Behavior

Le skin se désactive sans reson et plusieurs fois dans la journée quand je lance Kodi je suis obligé de le remettre à chaque fois

### Expected Behavior

Le skin se désactive

### Steps To Reproduce

Pas d'étapes

### Screenshots and Additional Info

Pas de capture pour le moment

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I cannot speak French. English only please.

**Comment by Lucas67159** [comment]
The skin deactivates without reson and several times during the day when I launch Kodi I have to put it back each time

**Comment by jurialmunkey** [comment]
Debug log?

Unlikely to be a skin issue. Sounds like a problem with your Kodi settings.

**Comment by Lucas67159** [comment]
My Kodi settings?Can you enlighten me on this, I don't see if you can help me at all.

**Comment by jurialmunkey** [comment]
I can't know anything without a debug log of the issue.

Most likely it sounds like your kodi gui settings are not saving correctly and so kodi is reverting to your previous setup. This can happen if you do not exit kodi correctly and force quit instead. It also happens on some kodi forks like osmc or on some devices/os where certain parts of the system disk are protected.

**Comment by Lucas67159** [comment]
Ah yes I see and how can I do for this problem

**Comment by Rocknol** [comment]
> Ah yes I see and how can I do for this problem

C'est sûrement un bug dû à ta config comme dit plus haut donc le skin n'y est pour rien, tu devrais essayer de poster ton problème(en anglais) sur le forum officiel de Kodi ( https://forum.kodi.tv/forumdisplay.php?fid=59 ) en créant un fichier debug log.
Ici ils t'expliquent comment faire --> https://forum.kodi.tv/showthread.php?tid=42708

**Comment by Lucas67159** [comment]
But how can I make a report I can't find a button to write a report
