### ISSUE TITLE
[BUG] Does not find results when searching in the Hebrew language

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/skin.arctic.horizon.2#943]
### Skin section

Other

### Current Behavior

Hello,

I am writing to report a problem with the search function in the skin.arctic.horizon.2 interface. When I search for titles of movies or series in Hebrew, no results are returned, while when I search in English, results are found.

I suspect that this may be due to a problem that the search algorithm is not adapted to queries in the Hebrew language, or that the database does not contain enough data in Hebrew to return accurate results. However, there may also be a bug or technical issue with the search function that causes it to misbehave.

Could you please look into this issue and help? I would greatly appreciate any help or insight you can provide.

Thank you for your time and attention.

### Expected Behavior

Should find results in the Hebrew language
It used to work and then stopped

### Steps To Reproduce

in the search above

### Screenshots and Additional Info

This is how it looks in English
![image](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/102416233/e1db1a06-b6cf-4dc8-8a70-684b2d62a425)
וככה זה נראה בעברית
![image](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/102416233/06c37ba1-a456-4676-8f5c-1cfdc91abd66)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Did you check that the search query works from inside TMDbHelper itself?

If it works in TMDbHelper and not the search page then it is a likely duplciate of this issue with RTL languages https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/355

Not much I can do about it either way. Either it's an issue with the TMDb api not return results or it is the above issue with RTL languages which requires a Kodi skinning engine fix and cannot be addressed by the skin.

**Comment by The-cpu-max** [comment]
It does not work
The only thing I found out that in reversed writing he manages to find in Hebrew for example fast and nervous should be written like this
מהיר ועצבני 
And the only problem is it works
Only if you write it the other way around
So it's probably related to RTL
ינבצעו ריהמ

**Comment by The-cpu-max** [comment]
Now that I remember, when you started the skin the words in the search were always reversed
Not any more
And that causes a problem

**Comment by The-cpu-max** [comment]
> Did you check that the search query works from inside TMDbHelper itself?
> 
> If it works in TMDbHelper and not the search page then it is a likely duplciate of this issue with RTL languages #355
> 
> Not much I can do about it either way. Either it's an issue with the TMDb api not return results or it is the above issue with RTL languages which requires a Kodi skinning engine fix and cannot be addressed by the skin.

the link its not work for me 
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/fix_search_rtl.zip
can you give me new link with that fix?

**Comment by jurialmunkey** [comment]
That will not fix the issue. It was a test but it didn't work.

**Comment by The-cpu-max** [comment]
> That will not fix the issue. It was a test but it didn't work.

But, in your first updates at the very beginning it worked
I would write down the name in Hebrew and he would reverse the words by himself
Which file is responsible for this? I will try to download and update you

**Comment by The-cpu-max** [comment]
> That will not fix the issue. It was a test but it didn't work.

So can you write me which file is responsible for this?

**Comment by jurialmunkey** [comment]
No skin file is responsible for the issue. The issue relates to how Kodi deals with RTL languages inside the edit control.

**Comment by The-cpu-max** [comment]
> No skin file is responsible for the issue. The issue relates to how Kodi deals with RTL languages inside the edit control.
Ok, so can we open an issue about it in Kodi?
