### ISSUE TITLE
Full Screen Widget

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.horizon.2#945]
### Skin section

Home Widgets

### Current Behavior

Movies on Full Scrren, seem to be no longer automatically scrolling. 

### Expected Behavior

Scrolls

### Steps To Reproduce

Use full screen widget

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Have you enabled autoscroll in the fullscreen widget's settings?

**Comment by adamosborne83** [comment]
Goodness sake, I'm an idiot..... I need to pay closer attention to new additions. 

Sorry for wasting your time.

**Comment by jurialmunkey** [comment]
No worries! It's only because I fixed a bug a few weeks back where the setting was being ignored completely. You probably had it disabled the entire time but it still would have "worked" because of that bug.
