### ISSUE TITLE
[BUG] A blank page

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/skin.arctic.horizon.2#948]
### Skin section

Other

### Current Behavior

When you get to an add-on that doesn't work properly.
You just see a blank screen

### Expected Behavior

A back button appears
or a text that says there is a problem
When the screen is blank it is not clear what the source of the problem is
And if we are waiting for the ADD-ON to come up

### Steps To Reproduce

Enter any plugin that doesn't work properly and you'll see a blank screen

### Screenshots and Additional Info

![image](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/102416233/eaa1ae45-0499-4143-827c-3e31f9b37254)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Like I said, I need exact steps to recreate the issue and understand what the problem is. There shouldn't be a blank page.

**Comment by The-cpu-max** [comment]
> Like I said, I need exact steps to recreate the issue and understand what the problem is. There shouldn't be a blank page.

Got it, what do you need from me?

**Comment by jurialmunkey** [comment]
Name of the addon and how to reproduce the issue

**Comment by The-cpu-max** [comment]
> 

I have no way for you to see it, since I have a certain block that prevents the ADD-ON from working on the computer
If you download it, it will work normally
But that's not the point, it happens in every expansion that has one error or another

**Comment by The-cpu-max** [comment]
> > 
> 
> I have no way for you to see it, since I have a certain block that prevents the ADD-ON from working on the computer If you download it, it will work normally But that's not the point, it happens in every expansion that has one error or another

You still have to press another button and enter another screen
It's ineffective

**Comment by The-cpu-max** [comment]
It's the same principle, I think
that you are looking for something in the search and he did not find it
He does not write. No results were found

**Comment by jurialmunkey** [comment]
Without a way to reproduce the issue I cannot investigate the problem.
