### ISSUE TITLE
[Feature] Tap & Double Tap Home Menu Action

### ISSUE THREAD

**Issue by rowel07** [jurialmunkey/skin.arctic.horizon.2#949]
### Skin section

Home Widgets

### Feature description

Is it possible to add  tap & double tap action in home menu? I think it will improved navigation on touchscreen screen devices. Just like when single tap the movie menu it will do nothing...you can easily jump the menu you created in your homescreen. But when you double tap it, it will show the submenu.

### Why is this feature needed? Please justify and explain.

Improve navigation for touchscreen devices.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Double tap is not possible to configure. Only actions skins can define are onclick, onback, and oninfo (and back/info aren't always configurable either).

Single tap already works as long as you use Classic or Icons menu and you have a fullscreen widget configured. I tested on Windows using my touch screen and it works fine. Possibly other widget styles will block the click area but with a fullscreen widget it definitely works for me.
