### ISSUE TITLE
Watched recommendations in The Moviedb Helper

### ISSUE THREAD

**Issue by Romik2505** [jurialmunkey/skin.arctic.horizon.2#951]
### Skin section

Home Widgets

### Feature description

You would need a feature that would easily redirect a specific movie or TV series from being watched in Themoviedbhelper to a specific application and playing that video. I don't know how the players in Themoviedbhelper work, but it would be better to redirect the video to the android application, which is installed anyway.

### Why is this feature needed? Please justify and explain.

Facilitating video playback

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I don't understand what you're asking for here.

**Comment by Romik2505** [comment]
There are video players in TheMovieDB Helper. Only it doesn't work for me. I have installed Disneyplus, Netflix, HBO MAX, Viaplay and there is only Netflix player. So can you play in other addon players as well. How to do it.
I have a favorite video I'm watching in Trakt and I wanted to play it right away from Kodi, but I don't know how?
Maybe my English is not good because I use a translator

**Comment by jurialmunkey** [comment]
That has nothing to do with the skin...

You can find information about players on the TMDbHelper wiki
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function

There are options in the configure player dialog to build players from templates. There are also several places you can find online to download players for 3rd party plugins.

**Comment by Romik2505** [comment]
Thanks

Roman Czarnecki

śr., 28 cze 2023, 18:09 użytkownik jurialmunkey ***@***.***>
napisał:
