### ISSUE TITLE
[BUG] TV Show menu missing

### ISSUE THREAD

**Issue by aicynide** [jurialmunkey/skin.arctic.horizon.2#953]
### Skin section

Home Widgets

### Current Behavior

I enabled TV Show menu but its missing

### Expected Behavior

Tv show menu beside Movies

### Steps To Reproduce

1. Fresh install this add-on
2. Check TV Show menu

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You can customise the home menu from skin settings.

If you added the TV Shows shortcut and it is not displaying then you likely do not have TV Shows in your library. You need to add a different action than the tvshow library.
