### ISSUE TITLE
[BUG] The dependency on script.skinvariables version 1.0.0 could not be satisfied

### ISSUE THREAD

**Issue by rahaaatul** [jurialmunkey/skin.arctic.horizon.2#957]
I was trying to install it from your repo and I face this issue:

https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/86149861/3d09081d-d9e3-4d75-898a-15c1b56480b0

I'm on Kodi Nexus 20.1 on Windows 11.

_Originally posted by @rahaaatul in https://github.com/jurialmunkey/skin.arctic.horizon.2/discussions/956_

**Comment by rahaaatul** [comment]
Okay, so I uninstalled skin variable addon manually and reinstalled it manually from your repo. Now it started downloading.

**Comment by theMonk3y** [comment]
Same problem, uninstalling dosent help

**Comment by jurialmunkey** [comment]
Enable kodi setting to allow updates from any repo.
