### ISSUE TITLE
[Feature] information screen of Live TV Program

### ISSUE THREAD

**Issue by AdamNo2** [jurialmunkey/skin.arctic.horizon.2#958]
### Skin section

PVR and Live TV

### Feature description

i am using Webgrab+ to gather EPG data for live TV.
i am in Germany where the Program Title has often an appendix to the original title like:
>Event Horizon - Am Rande des Universums; instead of just Event Horizon
>Clueless - Was sonst!; instead of just Clueless

For these Programs when i go to Information Screen no additional info like Poster/Director/etc. are displayed.
![Screenshot from 2023-07-14 17-18-30](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/113284561/010ea77c-0eab-4ca0-a9db-7187f754ad25)

this is my epg.xml for Program Event Horizon:

```
  <programme start="20230714040000 +0000" stop="20230714054000 +0000" channel="Sky Cinema Best Of">
    <title lang="de">Event Horizon <E2><80><93> Am Rande des Universums</title>
    <title lang="en">Event Horizon</title>
    <title lang="xx">Event Horizon</title>
    <sub-title lang="de"><E2><80><9E>Solaris<E2><80><9C> trifft auf <E2><80><9E>Hellraiser<E2><80><9C>: G<C3><A4>nsehaut und tolle Optik!, US/GB (1997)</sub-title>
    <desc lang="de">Sam Neill als besessener Wissenschaftler ...</desc>
    <credits>
      <director>Paul W. S. Anderson</director>
      <actor>Laurence Fishburne</actor>
      <actor>Sam Neill</actor>
      <actor>Joely Richardson</actor>
      <actor>Kathleen Quinlan</actor>
      <actor>Richard T. Jones</actor>
      <actor>Jack Noseworthy</actor>
      <writer>Philip Eisner</writer>
      <producer>Jeremy Bolt</producer>
      <producer>Lawrence Gordon</producer>
      <composer>Michael Kamen</composer>
      <composer>Orbital</composer>
    </credits>
    <date>1997</date>
    <category lang="de">Science fiction / Fantasy / Horror</category>
    <icon src="https://images.tvtoday.de/itv/2023-07-14/5460b2a4e4b08cb8014aa804_780.jpg" />
    <country lang="de">USA/GB</country>
  </programme>
```

to what i had before
`    <title lang="de">Event Horizon <E2><80><93> Am Rande des Universums</title>`
i also added the original title
`    <title lang="en">Event Horizon</title>`
`    <title lang="xx">Event Horizon</title>`
but still no details in info page!

i suggest to iterate through all "<title lang" tags till a hit was found in external/details database.

### Why is this feature needed? Please justify and explain.

all languages having a variant program title will show full details in Live TV Information.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
> i suggest to iterate through all "<title lang" tags till a hit was found in external/details database.

This is not possible.

TMDbHelper does not have access to your PVR epg. It can only access the metadata Kodi provides via the ListItem that your PVR client generates.

That means it needs to try to make a match based upon the title that your PVR client adds. If it has extra words then it wont be able to match anything.

> For these Programs when i go to Information Screen no additional info like Poster/Director/etc. are displayed.

I don't see any artwork information in that EPG extract. If TMDbHelper can't match for an online lookup and your PVR doesn't supply it's own artwork then there's nothing to display.

Director will display if the ListItem has a ListItem.Director field. If it isn't displaying then that means your PVR is not putting this information in.

**Comment by AdamNo2** [comment]
i am using tvheadend and checked for epg format it's using internally:
https://tvheadend.org/projects/tvheadend/wiki/Epgdb

i also checked for Kodi's internal epg database:
https://kodi.wiki/view/Databases/Epg

as it turned out, tvh sends only it's internal maintained epg data. no original title, director, etc..
as consequence, it makes no sense to feed tvh with epg tags it will not send to the client.

i will open a feature request for tvheadend server & client to get all the xml tags/data that kodi is capable of.

Thank you for your help!

**Comment by AdamNo2** [comment]
Ups! 
tvh has in EPG grabber module an extra option 
_Scrape credits and extra information:_
that needs to be checked!

**Comment by AdamNo2** [comment]
sorry for bothering you!
