### ISSUE TITLE
[BUG] Tmdb helper

### ISSUE THREAD

**Issue by Lucas67159** [jurialmunkey/skin.arctic.horizon.2#961]
### Skin section

Other

### Current Behavior

When I launch Kodi there is a notification from TMDB Helper every time that says trakt authorized.2086.01sec

### Expected Behavior

no behavior

### Steps To Reproduce

No steps just launch kodi

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Then disable the notification in the addon. This has nothing to do with the skin.

**Comment by Lucas67159** [comment]
And how do I turn off the notification please? It may sound stupid but I couldn't find it.
