### ISSUE TITLE
Wallpaper problem the images remain fixed..

### ISSUE THREAD

**Issue by kris06** [jurialmunkey/skin.arctic.horizon.2#963]
### Skin section

Other

### Current Behavior

arctic horizon 2 . For a few days, the dynamic images in the background no longer work, this remains fixed..

### Expected Behavior

wallpapers usually scroll

### Steps To Reproduce

wallpapers usually scroll

### Screenshots and Additional Info

   arctic horizon 2 . For a few days, the dynamic images in the background no longer work, this remains fixed..

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Have you enabled autoscroll for the widget?

**Comment by kris06** [comment]
Yes, scrolling is enabled, I haven't changed anything.  I even like reinstalling artic horizon 2 but it doesn't change anythingEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : jurialmunkey ***@***.***> Date : 22/07/2023  12:25  (GMT+01:00) À : "jurialmunkey/skin.arctic.horizon.2" ***@***.***> Cc : kris06 ***@***.***>, Author ***@***.***> Objet : Re: [jurialmunkey/skin.arctic.horizon.2] Wallpaper problem the images remain fixed.. (Issue #963) 
Have you enabled autoscroll for the widget?

**Comment by kris06** [comment]
Indeed, it was the automatic scrolling that disabled itself, I don't understand.  thank you for your replyEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : jurialmunkey ***@***.***> Date : 22/07/2023  12:25  (GMT+01:00) À : "jurialmunkey/skin.arctic.horizon.2" ***@***.***> Cc : kris06 ***@***.***>, Author ***@***.***> Objet : Re: [jurialmunkey/skin.arctic.horizon.2] Wallpaper problem the images remain fixed.. (Issue #963) 
Have you enabled autoscroll for the widget?
