### ISSUE TITLE
[Feature] I would like to be able to see the widgets above and below

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.horizon.2#964]
### Skin section

Home Widgets

### Feature description

I would like to see widgets that are above or below. I watched a video on YouTube and the guy was using your skin. I see he has settings so the above and below widgets are visible. I have attached photos. Has this been removed or is there a setting I need to change? Any help is much appreciated.

### Why is this feature needed? Please justify and explain.

So I can tell if there is more context below or above 

### Screenshots and Additional Info

![20230729_212126](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/121204283/36e7f1a2-f5d6-449b-a091-7ac960ccb7bc)
![Screenshot_20230729_211847_Chrome](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/121204283/3f382f04-1ac9-4b02-afb9-937c7653bf0a)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
That looks like an old version of the skin in the second shot. 

However if you disable the fullscreen expanded option to turn off the footer, you'll be able to see the next widget.
