### ISSUE TITLE
Next Episode button is Video OSD

### ISSUE THREAD

**Issue by Roy416** [jurialmunkey/skin.arctic.horizon.2#969]
### Skin section

Fullscreen Video OSD

### Feature description

There being a button so it goes to the next episode. It would appear after the pause button.

### Why is this feature needed? Please justify and explain.

Currently there is no easy/convenient way to go to the next episode in the playlist. You can go to the playlist by pressing down when the video osd is active, but sometimes it starts at the incorrect episode, so you have to scroll through the episodes and find the corresponding next episode. Tried nextup addon but it can be inconsistent at showing up. Also tried keymapper and the "play next" doesn't work. 

So having a button where you can brainlessly click and it goes to the next episode would be very convinient. 

### Screenshots and Additional Info

<img width="1280" alt="Untitled" src="https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/19165926/89c0a69a-2703-4293-8ed3-f1a8ad8f290c">

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
There is a next button by default. 

If you aren't seeing it then either there is no next item in your playlist, or you have deliberately disabled it in the skin settings by choosing to always show the stop button instead.

**Comment by Roy416** [comment]
Hm, I turned that option off just now and restarted kodi, and I'm still only getting the pause button.

**Comment by Roy416** [comment]
I wonder if its not showing up on my laptop, because I'm using it through a windows smb

**Comment by Roy416** [comment]
Nevermind, it isn't an issue with AH2. It is the fork of the UpNext Addon I'm using. If I play the video through its widget, it only displays the stop button. Guess I'll bug their github, ty for replying

**Comment by jurialmunkey** [comment]
Yeah if you're playing via an add-on, it will be up to the add-on to create a playlist queue. The next button will display if there's a next item in the queue, otherwise it displays stop.

The reason why you might still see episodes when you press down is because if the queue is empty then the skin will fallback to displaying the Library or TMDbHelper entry for all episodes in the season instead. There's no point showing the "next" button in that scenario because the next command only plays next item in the queue (which is empty so will cause playback to stop anyway).

**Comment by Roy416** [comment]
> Yeah if you're playing via an add-on, it will be up to the add-on to create a playlist queue. The next button will display if there's a next item in the queue, otherwise it displays stop.

Not sure If I should create another issue but, If I were to create a widget under Default Widget > Episodes > In-Progress, it still shows the stop button. I'm presuming these widgets are apart of AH2 and not another addon that came with the skin?But if I were to click on show through the library, the next episode button appears. Would it be possible for that widget to create a playlist queue?
