### ISSUE TITLE
[BUG] Updating

### ISSUE THREAD

**Issue by Wolfy0222** [jurialmunkey/skin.arctic.horizon.2#972]
### Skin section

Other

### Current Behavior

Tmdb will not update nor will script variables both looking for script.jurial v 0.15 but the script that is here is script v0.17 maybe a typo? trying to update on xbox again so i cant manually install proper script manually

### Expected Behavior

it should auto update like it did before

### Steps To Reproduce

install skin,
failed to install a dependency

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Wolfy0222** [comment]
also same for fuse

**Comment by jurialmunkey** [comment]
Follow all the instructions...

Installation
The skin and its required dependencies are available on my 3rd party alpha repository.
Requires Kodi Nexus or higher.

Kodi File Manager Source:
https://jurialmunkey.github.io/repository.jurialmunkey/

Direct ZIP Install:
[https://jurialmunkey.github.io/repositor...ey-3.3.zip](https://jurialmunkey.github.io/repository.jurialmunkey/repository.jurialmunkey-3.3.zip)

Instructions:
1. Enable "Unknown Sources" in Kodi Settings > System > Add-ons
2. Enable "Update official add-ons from: Any repositories" in Kodi Settings > System > Add-ons
3. Install my repository using either the zip or file manager source linked above
