### ISSUE TITLE
could we have a scrolling title here. THANKS

### ISSUE THREAD

**Issue by kris06** [jurialmunkey/skin.arctic.horizon.2#974]
### Skin section

Home Widgets

### Feature description

could we have a scrolling title here. THANKS

### Why is this feature needed? Please justify and explain.

could we have a scrolling title here. THANKS

### Screenshots and Additional Info

![mous](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/31409100/a8f1ab48-7eea-41c1-86e6-b60102214643)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Omarscomin** [comment]
> It is already implemented.
> 
> Kodi settings -> Skin -> Behavior -> Enable "Autoscroll Lables"
> 
> 
> 
> Anyway I highly recommend to do as @Omarscomin said because it way cleaner and easier to read, or Activate "Clearlogo" instead. 

Clear logo for the win!!!!

**Comment by kris06** [comment]
Merci beaucoups


----- Mail original -----
De: "psp2111-ADSLGATE" ***@***.***>
À: "jurialmunkey/skin.arctic.horizon.2" ***@***.***>
Cc: "kris06" ***@***.***>, "Author" ***@***.***>
Envoyé: Lundi 21 Août 2023 21:57:53
Objet: Re: [jurialmunkey/skin.arctic.horizon.2] could we have a scrolling title here. THANKS (Issue #974)





It is already implemented. 
Kodi settings -> Skin -> Behavior -> Enable "Autoscroll Lables" 

Anyway I highly recommend to do as @Omarscomin said because it way cleaner and easier to read, or Activate "Clearlogo" instead.

**Comment by kris06** [comment]
Merci beaucoups

----- Mail original -----
De: "Omarscomin" ***@***.***>
À: "jurialmunkey/skin.arctic.horizon.2" ***@***.***>
Cc: "kris06" ***@***.***>, "Author" ***@***.***>
Envoyé: Lundi 21 Août 2023 17:17:09
Objet: Re: [jurialmunkey/skin.arctic.horizon.2] could we have a scrolling title here. THANKS (Issue #974)





Not technically the exact same thing that you're requesting, but enabling the following setting would display the entire movie title: 

Kodi settings > Skin > Appearance > Customise appearance > Enable "Wrap long titles"
