### ISSUE TITLE
[BUG] Can't Install Dependencys Needed to Add Skin

### ISSUE THREAD

**Issue by M0NKE3MAN** [jurialmunkey/skin.arctic.horizon.2#987]
### Skin section

Other

### Current Behavior

Trying to download TMDB Helper and Skin Variables but I'm getting an error saying the dependencys versions could not be satisfied. I've installed Arctic Horizon 2 on 4 of my other devices so I know you need those 2 dependencies to be added first to make the Skin download correctly.  

### Expected Behavior

Skin Variables installs
TMDB Helper installs
Arctic Horizon 2 installs

### Steps To Reproduce

1. Goto TMDB Helper Repo
2. Click install 
3. Get error message that the version cannot be satisfied

1. Goto Skin Variables Repo
2. Click install
3. Get error message that the version can't be satisfied

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Follow all instructions properly on the forum about allowing uodates from any repositories.
