### ISSUE TITLE
Font size problem in the add-on

### ISSUE THREAD

**Issue by akunh121** [jurialmunkey/skin.arctic.horizon.2#989]
### Skin section

Home Widgets

### Current Behavior

Hey
There is a problem with the size of the font, in the name of the movie
Movies with long names - appear with dots
It happens that you are inside one of the FEN add-ons for example
And this happens in the Hebrew and English
In Hebrew it cuts off the first letters
can you fix?

### Expected Behavior

To see the full name of the movie in Hebrew

### Steps To Reproduce

1.go to addon
2.go to a title of movie with long name that the metadata in Hebrew and you will see the first letters cuts off

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by akunh121** [comment]
![IMG_20231026_145039_222](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/85361952/a3deec70-6ec6-4380-aad0-70004516cf73)
![IMG-20231026-WA0005](https://github.com/jurialmunkey/skin.arctic.horizon.2/assets/85361952/324070c6-155a-4373-9405-497e57b4931e)

**Comment by ChocOranger** [comment]
It's unlikely it will change even though it's huge.

However you can change it yourself easily.

Edit the file addons\skin.arctic.horizon.2\1080i\fonts.xml in your local data folder (location depends on operating system https://kodi.wiki/view/Kodi_data_folder)

Search the file for "font_info_black" and change the 'size' - save and restart Kodi

        <font>
            <name>font_info_black</name>
            <filename>RobotoCondensed-bold.ttf</filename>
            <size>112</size>
            <style>uppercase</style>
        </font>

**Comment by jurialmunkey** [comment]
There is already an option in appearance settings to wrap long titles.

**Comment by ChocOranger** [comment]
The wrapping setting is bugged. Small fonts are wrapped where they shouldn't. Large fonts spread out massively.
Probably to do with the bug on line spacing.
