### ISSUE TITLE
[Question] Reload Skin

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon.2#99]
Will you be implementing Reload Skin?

<img width="371" alt="Screenshot 2022-06-07 at 22 25 51" src="https://user-images.githubusercontent.com/2873112/172486028-9fb11664-026e-48e8-b65e-c5bc9d727afe.png">

Thanks

**Comment by Hawkedon** [comment]
@Blurayx, you can add a new item for power menu and customize the action as "ReloadSkin()".

**Comment by Blurayx** [comment]
> @Blurayx, you can add a new item for power menu and customize the action as "ReloadSkin()".

Thanks. unfortunately, it didn't work.

**Comment by Hawkedon** [comment]
Weird. I did the same and it works very well. Though I think @jurialmunkey should add that to the skin by default.

**Comment by jurialmunkey** [comment]
Added. Will be in 0.1.18
`Choose shortcut > Kodi Commands > Reload Skin`

**Comment by Blurayx** [comment]
> Added. Will be in 0.1.18
> 
> `Choose shortcut > Kodi Commands > Reload Skin`

Thank you 😃

**Comment by Blurayx** [comment]
> Added. Will be in 0.1.18
> `Choose shortcut > Kodi Commands > Reload Skin`

Not sure if Reload Skin is working correctly. when I click on Reload skin it defaults to my Next Aired Libary.



https://user-images.githubusercontent.com/2873112/172551020-e2f3c747-f836-494b-b8dc-e4c6cc9d6856.mov

**Comment by jurialmunkey** [comment]
> > Added. Will be in 0.1.18
> > `Choose shortcut > Kodi Commands > Reload Skin`
> 
> Not sure if Reload Skin is working correctly. when I click on Reload skin it defaults to my Next Aired Libary. AH defaults back to the Home screen.
> AH2.mov

Ah yep, you're right. I accidentally pasted the next aired library command over the reload one! Should be fixed _now_ in 0.1.24 (you might need to delete and re-add the shortcut).
